{
 "title": "Kubernetes",
 "description": "Monitors Kubernetes cluster using Prometheus. Shows overall cluster CPU / Memory / Filesystem usage as well as individual pod, containers, systemd services statistics.",
 "tags": [
  "topic:kubernetes",
  "topic:management-cluster",
  "topic:workload-cluster",
  "owner:team-honeybadger"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(container_memory_working_set_bytes, cluster_id)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(container_fs_limit_bytes{cluster_id=\"$cluster\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cluster Memory Usage",
   "type": "gauge",
   "description": "Memory used by containers, in comparision to the memory available on machines",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster_id=\"$cluster\"}) / sum(kube_node_status_capacity_memory_bytes{cluster_id=\"$cluster\"}) * 100"
    }
   ]
  },
  {
   "title": "Cluster CPU Usage",
   "type": "gauge",
   "description": "CPU used by containers in comparison to the amount of CPU cores available in machines",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (irate (container_cpu_usage_seconds_total{cluster_id='$cluster'}[3m])) / sum (kube_node_status_capacity_cpu_cores{cluster_id='$cluster'}) * 100"
    }
   ]
  },
  {
   "title": "Cluster Filesystem Usage",
   "type": "gauge",
   "description": "Disk space used by containers as a share of all avalable disk space",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/[x]*[sv]d[a-z][1-9]$\",id=\"/\",cluster_id='$cluster',instance=~\"$instance\"}) / sum (container_fs_limit_bytes{device=~\"^/dev/[x]*[sv]d[a-z][1-9]$\",id=\"/\",cluster_id='$cluster',instance=~\"$instance\"}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{cluster_id='$cluster'})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kube_node_status_capacity_memory_bytes{cluster_id='$cluster'})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_user_seconds_total{cluster_id='$cluster'}[5m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kube_node_status_capacity_cpu_cores{cluster_id='$cluster'})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/[x]*[sv]d[a-z][1-9]$\",id=\"/\",instance=~\"$instance\", cluster_id='$cluster'})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_fs_limit_bytes{device=~\"^/dev/[x]*[sv]d[a-z][1-9]$\",id=\"/\",instance=~\"$instance\", cluster_id='$cluster'})"
    }
   ]
  },
  {
   "title": "Pod CPU Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pod CPU Usage",
   "type": "timeseries",
   "description": "The CPU usage of individual pods, in percentage  of 1 core",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",instance=~\"$instance\", cluster_id='$cluster'}[3m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "System Services CPU Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "System Services CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (irate (container_cpu_usage_seconds_total{id=~\"/system.slice/.*\",instance=~\"$instance\", cluster_id='$cluster'}[3m])) by (id)",
     "legendFormat": "{{ id }}"
    }
   ]
  },
  {
   "title": "Container CPU Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Container CPU usage",
   "type": "timeseries",
   "description": "CPU usage on a container level",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",container!=\"POD\",instance=~\"$instance\", cluster_id='$cluster'}[5m])) by (container, pod)",
     "legendFormat": "pod: {{ pod }} | {{ container }}"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name!~\"^k8s_.*\",instance=~\"$instance\", cluster_id='$cluster'}[5m])) by (instance, name, image)",
     "legendFormat": "docker: {{ kubernetes_io_hostname }} | {{ image }} ({{ name }})"
    }
   ]
  },
  {
   "title": "All Processes CPU Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {}
   ]
  },
  {
   "title": "All Processes CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{cluster_id=\"$cluster\",instance=~\"$instance\"}[3m])) by (id)",
     "legendFormat": "{{ id }}"
    }
   ]
  },
  {
   "title": "Pod Memory Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pod Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",cluster_id=\"$cluster\",instance=~\"$instance\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "System Services Memory Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {}
   ]
  },
  {
   "title": "System Services Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=~\"/system.slice/.*\",cluster_id=\"$cluster\",instance=~\"$instance\"}) by (id)",
     "legendFormat": "{{ id }}"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",container!=\"POD\",cluster_id=\"$cluster\",instance=~\"$instance\"}) by (instance, container)",
     "legendFormat": "pod: {{ pod }} | {{ container }}"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name!~\"^k8s_.*\",cluster_id=\"$cluster\",instance=~\"$instance\"}) by (instance, name, image)",
     "legendFormat": "docker: {{ instance }} | {{ image }} ({{ name }})"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{rkt_container_name!=\"\",cluster_id=\"$cluster\",instance=~\"$instance\"}) by (instance, rkt_container_name)",
     "legendFormat": "rkt: {{ instance }} | {{ rkt_container_name }}"
    }
   ]
  },
  {
   "title": "All Processes Memory Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 },
   "targets": [
    {}
   ]
  },
  {
   "title": "All Processes Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{cluster_id=\"$cluster\",instance=~\"$instance\"}) by (id)",
     "legendFormat": "{{ id }}"
    }
   ]
  },
  {
   "title": "Network Transfer Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Network Transfer",
   "type": "timeseries",
   "description": "Sum of all network transfer from and to containers",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{cluster_id='$cluster',instance=~\"$instance\"}[3m]))",
     "legendFormat": "Incoming"
    },
    {
     "expr": "- sum(irate(container_network_transmit_bytes_total{cluster_id='$cluster',instance=~\"$instance\"}[3m]))",
     "legendFormat": "Outgoing"
    }
   ]
  },
  {
   "title": "Pod Network Transfer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pod Network Transfer",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",cluster_id=\"$cluster\",instance=~\"$instance\"}[3m])) by (pod)",
     "legendFormat": "-> {{ pod }}"
    },
    {
     "expr": "- sum(irate(container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",cluster_id=\"$cluster\",instance=~\"$instance\"}[3m])) by (pod)",
     "legendFormat": "<- {{ pod }}"
    }
   ]
  },
  {
   "title": "Container Network Transfer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Container Network Transfer",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",cluster_id=\"$cluster\",instance=~\"$instance\"}[3m])) by (container, pod)",
     "legendFormat": "-> pod: {{ pod }} | {{ container }}"
    },
    {
     "expr": "- sum(irate(container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",cluster_id=\"$cluster\",instance=~\"$instance\"}[3m])) by (container, pod)",
     "legendFormat": "<- pod: {{ pod }} | {{ container }}"
    },
    {
     "expr": "sum(irate(container_network_receive_bytes_total{image!=\"\",name!~\"^k8s_.*\",cluster_id=\"$cluster\",instance=~\"$instance\"}[3m])) by (instance, name, image)",
     "legendFormat": "-> docker: {{ kubernetes_io_hostname }} | {{ image }} ({{ name }})"
    },
    {
     "expr": "- sum(irate(container_network_transmit_bytes_total{image!=\"\",name!~\"^k8s_.*\",cluster_id=\"$cluster\",instance=~\"$instance\"}[3m])) by (instance, name, image)",
     "legendFormat": "<- docker: {{ kubernetes_io_hostname }} | {{ image }} ({{ name }})"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{rkt_container_name!=\"\",cluster_id=\"$cluster\",instance=~\"$instance\"}[3m])) by (instance, rkt_container_name)",
     "legendFormat": "-> rkt: {{ kubernetes_io_hostname }} | {{ rkt_container_name }}"
    },
    {
     "expr": "- sum(irate(container_network_transmit_bytes_total{rkt_container_name!=\"\",cluster_id=\"$cluster\",instance=~\"$instance\"}[3m])) by (instance, rkt_container_name)",
     "legendFormat": "<- rkt: {{ kubernetes_io_hostname }} | {{ rkt_container_name }}"
    }
   ]
  },
  {
   "title": "All Processes Network Transfer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 },
   "targets": [
    {}
   ]
  },
  {
   "title": "All Processes Network Transfer",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum (irate (container_network_receive_bytes_total{cluster_id=\"$cluster\",instance=~\"$instance\"}[3m])) by (id)",
     "legendFormat": "-> {{ id }}"
    },
    {
     "expr": "- sum (irate (container_network_transmit_bytes_total{cluster_id=\"$cluster\",instance=~\"$instance\"}[3m])) by (id)",
     "legendFormat": "<- {{ id }}"
    }
   ]
  }
 ]
}