{
 "title": "Konfigure Operator",
 "tags": [
  "owner:team-honeybadger",
  "konfigure-operator"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "konfigure_operator_reconcile_condition"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster Reconcilers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(konfigure_operator_reconcile_condition{resource_namespace=~\"$namespace\",condition_type=\"Ready\",condition_status=\"True\"})"
    }
   ]
  },
  {
   "title": "Ready configurations",
   "type": "table",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "konfigure_operator_reconcile_condition{namespace=~\"$namespace\",condition_type=\"Ready\", condition_status=\"True\"} == 1",
     "legendFormat": "{{config_name}}"
    }
   ]
  },
  {
   "title": "Failing Reconcilers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(konfigure_operator_reconcile_condition{resource_namespace=~\"$namespace\",condition_type=\"Ready\",condition_status=\"False\"})"
    }
   ]
  },
  {
   "title": "Failed configurations",
   "type": "table",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 5 },
   "targets": [
    {
     "expr": "konfigure_operator_reconcile_condition{namespace=~\"$namespace\",condition_type=\"Ready\", condition_status=\"False\"} == 1",
     "legendFormat": "{{config_name}}"
    }
   ]
  },
  {
   "title": "Reconciler ops avg. duration",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "  sum(rate(konfigure_operator_reconcile_duration_seconds_sum{namespace=~\"$namespace\"}[5m])) by (kind)\n/\n  sum(rate(konfigure_operator_reconcile_duration_seconds_count{namespace=~\"$namespace\"}[5m])) by (kind)",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  { "title": "Timing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Cluster reconciliation duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "  sum(rate(konfigure_operator_reconcile_duration_seconds_sum{namespace=~\"$namespace\"}[5m])) by (resource_kind, resource_name, resource_namespace)\n/\n  sum(rate(konfigure_operator_reconcile_duration_seconds_count{namespace=~\"$namespace\"}[5m])) by (resource_kind, resource_name, resource_namespace)",
     "legendFormat": "{{resource_kind}}/{{resource_namespace}}/{{resource_name}}"
    }
   ]
  }
 ]
}