{
 "title": "Teleport",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(up{app=\"kube-state-metrics\"},cluster_id)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{app=\"kube-state-metrics\", cluster_id=\"$cluster\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Teleport Process State",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "state" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_state{cluster_id=\"$cluster\"}",
     "legendFormat": "{{app_kubernetes_io_component}}"
    }
   ]
  },
  {
   "title": "User Logins",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(user_login_total{cluster_id=\"$cluster\"})",
     "legendFormat": "Successful"
    },
    {
     "expr": "sum(failed_login_attempts_total{cluster_id=\"$cluster\"})",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Connected Resources",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (type)(teleport_connected_resources{cluster_id=\"$cluster\"})",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Registered Servers by version",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (version)(teleport_registered_servers{cluster_id=\"$cluster\"})",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Proxy Session Metrics",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (proxy_ssh_sessions_total{cluster_id=\"$cluster\"})\n",
     "legendFormat": "Total Sessions"
    },
    {
     "expr": "sum (proxy_connection_limit_exceeded_total{cluster_id=\"$cluster\"})",
     "legendFormat": "Limit Exceeded Sessions"
    }
   ]
  },
  {
   "title": "Cache Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by(cache_component)(teleport_cache_events{cluster_id=\"$cluster\"})",
     "legendFormat": "{{cache_component}}"
    }
   ]
  },
  {
   "title": "DynamoDB Successful operations ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(operation)(dynamo_requests{cluster_id=\"$cluster\",result=\"success\"})",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "DynamoDB Error operations",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(operation)(dynamo_requests{cluster_id=\"$cluster\",result=\"error\"})",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "S3 Successful operations",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (operation)(s3_requests{cluster_id=\"$cluster\",result=\"success\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "S3 Error operations",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (operation)(s3_requests{cluster_id=\"$cluster\",result=\"error\"})",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Proxy Service Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connection and Login Failures - Failed SSH Connection Attempts",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(failed_connect_to_node_attempts_total{cluster_id=\"$cluster\"}[5m]))\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Connection and Login Failures - Failed Login Attempts",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(failed_login_attempts_total{cluster_id=\"$cluster\"}[5m]))\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Proxy Connection Metrics - Connection Limit Exceedance",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(proxy_connection_limit_exceeded_total{cluster_id=\"$cluster\"}[5m]))\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Proxy Connection Metrics - Active Sessions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "proxy_ssh_sessions_total{cluster_id=\"$cluster\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Teleport SSH Service Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "User Max Concurrent Sessions Hit",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(user_max_concurrent_sessions_hit_total{cluster_id=\"$cluster\"}[5m]))\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total SSH data transfer for \"$cluster\"",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "targets": [
      {
       "expr": "sum(rate(rx{cluster_id=\"$cluster\"}[5m]) + rate(tx{cluster_id=\"$cluster\"}[5m])) by (node)",
       "legendFormat": "{{mb}}"
      }
     ]
    },
    {
     "title": "SSH Connection Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by(app_kubernetes_io_component)(rx{cluster_id=\"$cluster\"})",
       "legendFormat": "{{app_kubernetes_io_component}} - rx"
      },
      {
       "expr": "sum by(app_kubernetes_io_component)(tx{cluster_id=\"$cluster\"})",
       "legendFormat": "{{app_kubernetes_io_component}} - tx"
      }
     ]
    }
   ]
  },
  {
   "title": "Auth Service and backends",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Number of Throttled Auth Generate Requests",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(auth_generate_requests_throttled_total{cluster_id=\"$cluster\"}[1h]))\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Number of Failed Disk Monitoring Attempts",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(audit_failed_disk_monitoring{cluster_id=\"$cluster\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Current Disk Space Usage Percentage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "targets": [
      {
       "expr": "audit_percentage_disk_space_used{cluster_id=\"$cluster\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Error Rate for Emitting Audit Events",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(audit_failed_emit_events{cluster_id=\"$cluster\"}[1h])) / sum(rate(audit_failed_emit_events{cluster_id=\"$cluster\"}[1h]) + rate(teleport_audit_emit_events{cluster_id=\"$cluster\"}[1h]))\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Latency for Backend Read Operations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, rate(backend_read_seconds_bucket{cluster_id=\"$cluster\"}[5m]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Number of Current Generate Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
     "targets": [
      {
       "expr": "auth_generate_requests{cluster_id=\"$cluster\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Total Number of Backend Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
     "targets": [
      {
       "expr": "sum(rate(backend_read_requests_total{cluster_id=\"$cluster\"}[5m]))+ sum(rate(backend_write_requests_total{cluster_id=\"$cluster\"}[5m]))\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Latency for Generate Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(auth_generate_seconds_bucket{cluster_id=\"$cluster\"}[10m])) by (le))\n",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Incomplete Session Uploads",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(teleport_incomplete_session_uploads_total{cluster_id=\"$cluster\"})",
       "legendFormat": "Sessions"
      }
     ]
    }
   ]
  },
  {
   "title": "Kubernetes Access - Client Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "In-Flight Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "targets": [
      {
       "expr": "teleport_kubernetes_client_in_flight_requests{cluster_id=\"$cluster\"}\n",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Total Requests to Upstream",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "targets": [
      {
       "expr": "sum(increase(teleport_kubernetes_client_requests_total{cluster_id=\"$cluster\"}[5m]))\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "TLS Handshake Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(teleport_kubernetes_client_tls_duration_seconds_bucket{cluster_id=\"$cluster\"}[10m])) by (le))\n",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "Time to Dial Upstream Server",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(teleport_kubernetes_client_got_conn_duration_seconds_bucket{cluster_id=\"$cluster\"}[10m])) by (le))\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Time to First Byte from Upstream",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(teleport_kubernetes_client_first_byte_response_duration_seconds_bucket{cluster_id=\"$cluster\"}[10m])) by (le))\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Upstream Request Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(teleport_kubernetes_client_request_duration_seconds_bucket{cluster_id=\"$cluster\"}[10m])) by (le))\n",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Kubernetes Access - Server Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server In-Flight Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "targets": [
      {
       "expr": "teleport_kubernetes_server_in_flight_requests{cluster_id=\"$cluster\"}\n",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Total API Requests Handled",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "targets": [
      {
       "expr": "sum(increase(teleport_kubernetes_server_api_requests_total{cluster_id=\"$cluster\"}[5m]))\n",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "Total Request Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(teleport_kubernetes_server_request_duration_seconds_bucket{cluster_id=\"$cluster\"}[10m])) by (le))\n",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "Response Size Distribution",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(teleport_kubernetes_server_response_size_bytes_bucket{cluster_id=\"$cluster\"}[10m])) by (le))\n",
       "legendFormat": "{{label_name}}"
      }
     ]
    }
   ]
  }
 ]
}