{
 "title": "Loki / Slow queries",
 "tags": [
  "owner:team-atlas",
  "topic:observability",
  "component:loki"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(loki_build_info,cluster_id)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(loki_build_info{cluster_id=~\"$cluster\"},namespace)"
    }
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" },
   { "name": "min_duration", "label": "Min duration", "query": "5ms" },
   { "name": "component", "label": "Component", "query": "querier, frontend, ruler" }
  ]
 },
 "panels": [
  {
   "title": "Across tenants",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile_over_time(0.99, {cluster_id=~\"$cluster\",namespace=~\"$namespace\"} |= \"metrics.go\" | logfmt | component_extracted=~\"$component.*\" | duration > ${min_duration} | unwrap duration_seconds(duration) [$__auto]) by ()",
     "legendFormat": "p99"
    },
    {
     "expr": "quantile_over_time(0.5, {cluster_id=~\"$cluster\",namespace=~\"$namespace\"} |= \"metrics.go\" | logfmt | component_extracted=~\"$component.*\" | duration > ${min_duration} | unwrap duration_seconds(duration) [$__auto]) by ()",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Fetched lines",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "quantile_over_time(0.99, {cluster_id=~\"$cluster\",namespace=~\"$namespace\"} |= \"metrics.go\" | logfmt | component_extracted=~\"$component.*\" | duration > ${min_duration} | unwrap total_lines[$__auto]) by ()",
     "legendFormat": "p99"
    },
    {
     "expr": "quantile_over_time(0.5, {cluster_id=~\"$cluster\",namespace=~\"$namespace\"} |= \"metrics.go\" | logfmt | component_extracted=~\"$component.*\" | duration > ${min_duration} | unwrap total_lines[$__auto]) by ()",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Fetched bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "quantile_over_time(0.99, {cluster_id=~\"$cluster\",namespace=~\"$namespace\"} |= \"metrics.go\" | logfmt | component_extracted=~\"$component.*\" | duration > ${min_duration} | unwrap bytes(total_bytes)[$__auto]) by ()",
     "legendFormat": "p99"
    },
    {
     "expr": "quantile_over_time(0.5, {cluster_id=~\"$cluster\",namespace=~\"$namespace\"} |= \"metrics.go\" | logfmt | component_extracted=~\"$component.*\" | duration > ${min_duration} | unwrap bytes(total_bytes)[$__auto]) by ()",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Time span",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile_over_time(0.99, {cluster_id=~\"$cluster\",namespace=~\"$namespace\"} |= \"metrics.go\" | logfmt | component_extracted=~\"$component.*\" | duration > ${min_duration} | unwrap duration_seconds(length)[$__auto]) by ()",
     "legendFormat": "p99"
    },
    {
     "expr": "quantile_over_time(0.5, {cluster_id=~\"$cluster\",namespace=~\"$namespace\"} |= \"metrics.go\" | logfmt | component_extracted=~\"$component.*\" | duration > ${min_duration} | unwrap duration_seconds(length)[$__auto]) by ()",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Slow queries",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{cluster_id=~\"$cluster\",namespace=~\"$namespace\"} |= \"metrics.go\"| logfmt | component_extracted=~\"$component\" | duration > ${min_duration} | label_format response_time_seconds=\"{{ if .duration }} {{ duration .duration }} {{ end }}\",param_step_seconds=\"{{ if .step }} {{ div .step 1000 }} {{ end }}\",length_seconds=\"{{ if .length }} {{ duration .length }} {{ end }}\""
    }
   ]
  }
 ]
}