{
 "title": "Loki log volume",
 "tags": [ "owner:team-atlas" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "custom_interval", "label": "Interval", "query": "1m,5m,10m,20m,30m,1h" },
   { "name": "k", "label": "top", "query": "1,2,3,5,10,20" },
   { "name": "event_group", "label": "Kubernetes events group by", "query": "kind, name" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard shows the log volume for each scrape job with different grouping for each panel.        Note that the queries used are intensive in terms of performance which might result in slow response time."
   }
  },
  {
   "title": "Kubernetes Pods",
   "type": "timeseries",
   "description": "Log volume per Kubernetes pod",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk($k, sum by(cluster_id, namespace, pod) (count_over_time({scrape_job=\"kubernetes-pods\"} |~ `` [$custom_interval])))",
     "legendFormat": "{{cluster_id}} - {{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Kubernetes Events",
   "type": "timeseries",
   "description": "Log volume per Kubernetes events namespace and selected group by label",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk($k, sum by(cluster_id, namespace, $event_group) (count_over_time({scrape_job=\"kubernetes-events\"} | logfmt |~ `` [$custom_interval])))",
     "legendFormat": "{{cluster_id}} - {{namespace}} - {{$event_group}}"
    }
   ]
  },
  {
   "title": "System logs",
   "type": "timeseries",
   "description": "Log volume per systemd unit",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk ($k, sum by (cluster_id, systemd_unit) (count_over_time({scrape_job=\"system-logs\"} |~ \"\" [$custom_interval])) > 10)",
     "legendFormat": "{{cluster_id}} - {{systemd_unit}}"
    }
   ]
  },
  {
   "title": "Audit logs",
   "type": "timeseries",
   "description": "Log volume per Audit log username",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk ($k, sum by(cluster_id, user_username) (count_over_time({scrape_job=\"audit-logs\"} | json |~ \"\" [$custom_interval])))",
     "legendFormat": "{{cluster_id}} - {{user_username}}"
    }
   ]
  }
 ]
}