{
 "title": "KVM Resource Usage",
 "tags": [
  "provider:kvm",
  "owner:team-rocket",
  "topic:management-cluster",
  "topic:workload-cluster"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kube_pod_container_resource_requests{cluster_type=~\"management_cluster\",container=\"k8s-kvm\",unit=\"core\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "  ", "type": "macropower-analytics-panel", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "At a glance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Physical machines",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(up{app=\"kubelet\", cluster_type=\"management_cluster\"})"
    }
   ]
  },
  {
   "title": "Physical machines as control plane nodes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(up{app=\"kubelet\", cluster_type=\"management_cluster\",role=\"master\"})"
    }
   ]
  },
  {
   "title": "Physical machines as workers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(up{app=\"kubelet\", cluster_type=\"management_cluster\",role=\"worker\"})"
    }
   ]
  },
  {
   "title": "Workload clusters",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(sum(kube_pod_container_info{cluster_type=~\"management_cluster\",container=\"k8s-kvm\"}) by (namespace))"
    }
   ]
  },
  {
   "title": "Unscheduled CPU requests",
   "type": "stat",
   "description": "If you see a number here, the installation doesn't have enough resources to schedule this workload cluster.",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aggregation:node:cpu_cores_total{cluster_type=\"management_cluster\"}"
    }
   ]
  },
  {
   "title": "Unscheduled Memory requests",
   "type": "stat",
   "description": "If you see a number here, the installation doesn't have enough resources to schedule this workload cluster.",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aggregation:node:memory_memtotal_bytes_total{cluster_type=\"management_cluster\"}"
    }
   ]
  },
  {
   "title": "Free resources in the installation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }
  },
  {
   "title": "CPU resources left (vCores)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:node:cpu_cores_total{cluster_type=~\"management_cluster\"}) - sum(kube_pod_container_resource_requests{cluster_type=\"management_cluster\", unit=\"core\"})"
    }
   ]
  },
  {
   "title": "CPU resources left",
   "type": "timeseries",
   "description": "CPU (v)Cores installed minus the CPU requests from CPU requests, as a percentage",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum(aggregation:node:cpu_cores_total{cluster_type=\"management_cluster\"}) - sum(kube_pod_container_resource_requests{cluster_type=\"management_cluster\", unit=\"core\"})) / sum(aggregation:node:cpu_cores_total{cluster_type=\"management_cluster\"})",
     "legendFormat": "vCores left"
    }
   ]
  },
  {
   "title": "Memory resources left",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:node:memory_memtotal_bytes_total{cluster_type=\"management_cluster\"}) - sum(kube_pod_container_resource_requests{cluster_type=\"management_cluster\", unit=\"byte\"})"
    }
   ]
  },
  {
   "title": "Memory resources left",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum(aggregation:node:memory_memtotal_bytes_total{cluster_type=\"management_cluster\"}) - sum(kube_pod_container_resource_requests{cluster_type=\"management_cluster\", unit=\"byte\"})) / sum(aggregation:node:memory_memtotal_bytes_total{cluster_type=\"management_cluster\"})",
     "legendFormat": "Memory left"
    }
   ]
  },
  { "title": "Machine Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "CPU (v)Cores per Machine",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_node_status_capacity{cluster_type=\"management_cluster\", resource=\"cpu\"}",
     "legendFormat": "{{ node }} ({{ role }})"
    }
   ]
  },
  {
   "title": "RAM per Machine",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "kube_node_status_capacity{cluster_type=~\"management_cluster\", resource=\"memory\"}",
     "legendFormat": "{{ node }} ({{ role }})"
    }
   ]
  },
  {
   "title": "CPU requests for workload clusters (timeline)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 }
  },
  {
   "title": "CPU resources reserved by workload cluster workers per machine",
   "type": "timeseries",
   "description": "only worker nodes",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster_type=~\"management_cluster\",pod=~\"worker.*\",node!=\"\",unit=\"core\"}) by (node)",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "CPU resources reserved by workload cluster workers per cluster",
   "type": "timeseries",
   "description": "requests on worker nodes",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster_type=~\"management_cluster\",pod=~\"worker.*\",node!=\"\",unit=\"core\"}) by (namespace)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "CPU requests for workload clusters (current)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 }
  },
  {
   "title": "CPU resources reserved for workload cluster worker nodes",
   "type": "graph",
   "description": "Only worker nodes",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "vCores" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster_type=~\"management_cluster\",pod=~\"worker.*\",node!=\"\",unit=\"core\"}) by (node)",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "CPU resources reserved by workload cluster workers per cluster",
   "type": "graph",
   "description": "requests on worker nodes",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "vCores" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster_type=~\"management_cluster\",pod=~\"worker.*\",node!=\"\",unit=\"core\"}) by (namespace)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Memory requests for workload clusters (current)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 }
  },
  {
   "title": "Memory requests for workload cluster worker nodes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster_type=~\"management_cluster\",pod=~\"worker.*\",node!=\"\",unit=\"byte\"}) by (node)",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Memory requests by workload cluster workers, per cluster",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster_type=~\"management_cluster\",pod=~\"worker.*\",node!=\"\",unit=\"byte\"}) by (namespace)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "CPU Requests for Operational Workloads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 }
  },
  {
   "title": "CPU resources reserved for overhead by node",
   "type": "graph",
   "description": "only worker nodes",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short", "label": "vCores" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster_type=~\"management_cluster\",container!=\"k8s-kvm\",unit=\"core\"}) by (node)",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "CPU resources reserved for overhead by type",
   "type": "graph",
   "description": "only worker nodes",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short", "label": "vCores" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster_type=~\"management_cluster\",container!=\"k8s-kvm\",unit=\"core\"}) by (namespace)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Memory Requests for Operational Workloads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 }
  },
  {
   "title": "Memory reserved for overhead, by node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster_type=~\"management_cluster\",container!=\"k8s-kvm\",unit=\"byte\"}) by (node)",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Memory reserved for overhead, by node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster_type=~\"management_cluster\",container!=\"k8s-kvm\",unit=\"byte\"}) by (namespace)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  { "title": "Overall CPU Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "CPU requests in total, by node",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster_type=~\"management_cluster\",node!=\"\",unit=\"core\"}) by (node)",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Memory requests in total, by node",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster_type=~\"management_cluster\",node!=\"\",unit=\"byte\"}) by (node)",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Details for workload cluster $cluster (Only when workload cluster is selected)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "repeat": "cluster_id",
   "collapsed": true,
   "panels": [
    {
     "title": "Control plane",
     "type": "stat",
     "gridPos": { "h": 6, "w": 2, "x": 0, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(up{app=\"kubelet\", cluster_type=\"workload_cluster\",role=\"master\",cluster_id=\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Workers",
     "type": "stat",
     "gridPos": { "h": 6, "w": 2, "x": 2, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(up{app=\"kubelet\", cluster_type=\"workload_cluster\",role=\"worker\",cluster_id=\"$cluster\"})"
      }
     ]
    },
    {
     "title": "CPU reserved by workers per machine",
     "type": "graph",
     "description": "only worker nodes",
     "gridPos": { "h": 6, "w": 6, "x": 4, "y": 73 },
     "yaxes": [
      { "format": "none", "label": "vCores" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{cluster_type=~\"management_cluster\",pod=~\"worker.*\",node!=\"\",unit=\"core\",namespace=\"$cluster\"}) by (node)",
       "legendFormat": "{{ node }}"
      }
     ]
    },
    {
     "title": "Memory reserved by workers per machine",
     "type": "graph",
     "description": "only worker nodes",
     "gridPos": { "h": 6, "w": 6, "x": 10, "y": 73 },
     "yaxes": [
      { "format": "decbytes", "label": "vCores" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{cluster_type=~\"management_cluster\",pod=~\"worker.*\",node!=\"\",unit=\"byte\",namespace=\"$cluster\"}) by (node)",
       "legendFormat": "{{ node }}"
      }
     ]
    },
    {
     "title": "Unscheduled CPU requests",
     "type": "stat",
     "description": "If you see a number here, the installation doesn't have enough resources to schedule this workload cluster.",
     "gridPos": { "h": 6, "w": 4, "x": 16, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{cluster_type=~\"management_cluster\",node=\"\",namespace=\"$cluster\",unit=\"core\"})"
      }
     ]
    },
    {
     "title": "Unscheduled Memory requests",
     "type": "stat",
     "description": "If you see a number here, the installation doesn't have enough resources to schedule this workload cluster.",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes{cluster_type=~\"management_cluster\",node=\"\",namespace=\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Worker memory usage in regards to pod limit in percent.",
     "type": "graph",
     "description": "This dashboard show percentage of kvm pod memory consumption in regards to pod limit.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 79 },
     "yaxes": [
      { "format": "percent", "label": "memory usage" }
     ],
     "targets": [
      {
       "expr": "100 *  sum by (pod) (label_replace(node_memory_Active_bytes{cluster_id=\"$cluster\", cluster_type=\"workload_cluster\"}, \"pod\", \"$1\", \"node\", \"(.*)\")) / on (pod) sum by (pod) (kube_pod_container_resource_limits{cluster_type=\"management_cluster\",unit=\"byte\",namespace=\"$cluster\",pod=~\"worker.*\"})",
       "legendFormat": "{{ pod }}"
      }
     ]
    }
   ]
  }
 ]
}