{
 "title": "Mimir / Rate Control",
 "description": "Help understanding MImir rate control behaviour",
 "tags": [
  "topic:observability",
  "owner:team-atlas",
  "component:mimir"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(cortex_build_info,cluster_id)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(cortex_build_info{cluster_id=\"$cluster\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Mimir Rate Control",
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "options": {
    "content": "Mimir Rate Control is managed by multiple Mimir solutions:\n- [Ingesters Circuit Breakers](https://grafana.com/docs/mimir/latest/configure/about-ingester-circuit-breakers)\n- [Reactive Limiters](https://grafana.com/docs/mimir/latest/configure/about-reactive-limiters/)\n\nThis dashboard will help you detect if Rate Control did discard some metrics, and why."
   }
  },
  {
   "title": "Circuit Breaker Discards",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(cortex_ingester_circuit_breaker_results_total{cluster_id=\"$cluster\", namespace=\"$namespace\", result!=\"success\"}[24h]))",
     "legendFormat": "24H Non-success"
    },
    {
     "expr": "sum(delta(cortex_ingester_circuit_breaker_request_timeouts_total{cluster_id=\"$cluster\", namespace=\"$namespace\"}[24h]))",
     "legendFormat": "24H Timeouts"
    }
   ]
  },
  {
   "title": "24H Reactive Limiter Discards",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(cortex_ingester_rejection_rate{cluster_id=\"$cluster\", namespace=\"$namespace\"}[24h]))",
     "legendFormat": "Rejected"
    }
   ]
  },
  { "title": "Mimir Circuit Breakers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Circuit Breaker requests",
   "type": "timeseries",
   "description": "Total requests executed via a circuit breaker. ",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(cortex_ingester_circuit_breaker_results_total{cluster_id=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) by (pod, request_type, result) != 0",
     "legendFormat": "{{pod}} / {{request_type}} / {{result}}"
    }
   ]
  },
  {
   "title": "Circuit Breaker timeouts",
   "type": "timeseries",
   "description": "Number of times the circuit breaker records a request that reaches timeout.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(cortex_ingester_circuit_breaker_request_timeouts_total{cluster_id=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) by (pod, request_type) != 0",
     "legendFormat": "{{pod}} / {{request_type}}"
    }
   ]
  },
  {
   "title": "Non-closed circuit breakers",
   "type": "timeseries",
   "description": "Shows number of circuit breakers that are not in a `closed` state, ie `open` or `half-open`.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(cortex_ingester_circuit_breaker_current_state{cluster_id=\"$cluster\", namespace=\"$namespace\", state!=\"closed\"}) by (pod, request_type) != 0",
     "legendFormat": "{{pod}} / {{request_type}}"
    }
   ]
  },
  {
   "title": "State transitions",
   "type": "timeseries",
   "description": "Shows the number of times a circuit breaker enters a state.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(cortex_ingester_circuit_breaker_transitions_total{cluster_id=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) by (pod, state, request_type) != 0",
     "legendFormat": "{{pod}} / {{request_type}} / {{state}}"
    }
   ]
  },
  { "title": "Mimir Reactive Limiter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Reactive Limiter rejected requests",
   "type": "timeseries",
   "description": "Current rate of new requests rejection.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(cortex_ingester_rejection_rate{cluster_id=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) by (pod) != 0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Reactive Limiter blocked requests",
   "type": "timeseries",
   "description": "Current number of requests that are queued waiting on the limiter.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(cortex_ingester_reactive_limiter_blocked_requests{cluster_id=\"$cluster\", namespace=\"$namespace\"}) by (pod, request_type) != 0",
     "legendFormat": "{{pod}} / {{request_type}}"
    }
   ]
  },
  {
   "title": "Requests and Limits",
   "type": "timeseries",
   "description": "Limits are constantly adjusted, so you here can compare limits (filled) with inflight requests (lines) and see how far they are from the limits.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(cortex_ingester_reactive_limiter_inflight_limit{cluster_id=\"$cluster\", namespace=\"$namespace\"}) by (pod, request_type)",
     "legendFormat": "limit for {{pod}} / {{request_type}}"
    },
    {
     "expr": "sum(cortex_ingester_reactive_limiter_inflight_requests{cluster_id=\"$cluster\", namespace=\"$namespace\"}) by (pod, request_type)",
     "legendFormat": "requests for {{pod}} / {{request_type}}"
    }
   ]
  }
 ]
}