---
- id: editorconfig-checker
  name: 'Check .editorconfig rules'
  description: '`editorconfig-checker` is a tool to check if your files consider your .editorconfig-rules.'
  entry: ec
  language: python
  types:
    - json
    - yaml
  require_serial: true
