{
 "title": "Deprecated APIs in workload clusters",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "About this dashboard",
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "options": {
    "content": "All data shown here is based on the `apiserver_requested_deprecated_apis` metric, introduced with Kubernetes 1.19. Check the `Removed in release` column below to find out which API is to be removed when.\n\nNote that this metric does not imply that a resource is _stored_ in a deprecated API. Instead it counts a _request_ in the outdated form."
   }
  },
  {
   "title": "Deprecated APIs",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(apiserver_requested_deprecated_apis{cluster_type=\"workload_cluster\"})"
    }
   ]
  },
  {
   "title": "Deprecated APIs by cluster",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "sum(apiserver_requested_deprecated_apis{cluster_type=\"workload_cluster\"}) by (cluster_id)",
     "legendFormat": "{{ cluster_id }}"
    }
   ]
  },
  {
   "title": "Deprecated APIs by group",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(apiserver_requested_deprecated_apis{cluster_type=\"workload_cluster\"}) by (group)",
     "legendFormat": "{{ group }}"
    }
   ]
  },
  {
   "title": "Deprecated APIs by resource and version",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 7 },
   "targets": [
    {
     "expr": "sum(apiserver_requested_deprecated_apis{cluster_type=\"workload_cluster\"}) by (group, resource, version)",
     "legendFormat": "{{ resource }} . {{ group }} / {{ version }}"
    }
   ]
  },
  {
   "title": "Full list",
   "type": "table",
   "description": "Note: Some entries might affect subresources.",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(apiserver_requested_deprecated_apis{cluster_type=\"workload_cluster\"}) without (app, cluster_type, installation, instance, job, role, subresource, provider)"
    }
   ]
  }
 ]
}