{
 "title": "Draughtsman",
 "tags": [
  "topic:management-cluster",
  "owner:team-biscuit"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "Latency and Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Helm Installer Duration",
   "type": "graph",
   "description": "Time taken to perform Helm actions.\nLogging into Quay, pulling charts, and installing charts.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(draughtsman_helm_installer_helm_command_duration_milliseconds) by (name)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "GitHub API Rate Limit Usage",
   "type": "graph",
   "description": "Percentage of our limit we are using. We should get worried when values approach 100%.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "((sum(draughtsman_github_eventer_rate_limit_limit) - sum(draughtsman_github_eventer_rate_limit_remaining)) / sum(draughtsman_github_eventer_rate_limit_limit)) * 100",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Deployment Status Fetch Duration",
   "type": "graph",
   "description": "Time taken (on average) to fetch GitHub Deployment Statuses.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(draughtsman_github_eventer_github_deployment_status_duration_milliseconds)",
     "legendFormat": "Average duration"
    }
   ]
  },
  {
   "title": "Deployment Fetch Duration",
   "type": "graph",
   "description": "Average time taken to fetch GitHub deployment events. 200 is returned if new Deployments are returned, 304 if the cache has been hit.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(draughtsman_github_eventer_github_deployment_duration_milliseconds{code=\"200\"})",
     "legendFormat": "Status 200 (events found)"
    },
    {
     "expr": "avg(draughtsman_github_eventer_github_deployment_duration_milliseconds{code=\"304\"})",
     "legendFormat": "Status 304 (no events found)"
    }
   ]
  },
  {
   "title": "Secret Request Duration",
   "type": "graph",
   "description": "Time taken to request draughtsman-values-secret.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(draughtsman_secret_configurer_request_duration_milliseconds)",
     "legendFormat": "Duration"
    }
   ]
  },
  {
   "title": "ConfigMap Request Duration",
   "type": "graph",
   "description": "Time taken to request draughtsman-values.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(draughtsman_configmap_configurer_request_duration_milliseconds)",
     "legendFormat": "Duration"
    }
   ]
  },
  {
   "title": "Slack Notification Duration",
   "type": "graph",
   "description": "TIme taken to post notifications to Slack",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(draughtsman_slack_notifier_request_duration_milliseconds)",
     "legendFormat": "Duration"
    }
   ]
  }
 ]
}