{
 "title": "Network Anomaly Detection",
 "tags": [
  "topic:workload-cluster",
  "topic:management-cluster"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(node_network_transmit_bytes_total, cluster_id)"
   },
   {
    "name": "device",
    "label": "Network Device",
    "query": "label_values(node_network_receive_bytes_total, device)"
   },
   {
    "name": "metric",
    "label": "Receive / Transmit",
    "query": "node_network_receive_bytes_total,node_network_transmit_bytes_total"
   },
   { "name": "threshold", "label": "Threshold", "query": "1,1.5,2,2.5,3" },
   { "name": "duration", "label": "Duration", "query": "2m,5m,10m,15m" }
  ]
 },
 "panels": [
  { "title": "$metric", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "metric" },
  {
   "title": "Rate of Bytes ($duration)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate($metric{cluster_id=\"$cluster\", device=\"$device\"}[$duration])",
     "legendFormat": "{{ instance }} - {{ device }}"
    }
   ]
  },
  {
   "title": "Average Rate of Bytes ($duration)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(rate($metric{cluster_id=\"$cluster\", device=\"$device\"}[$duration]))",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Standard Deviation of Rate of Bytes ($duration)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "stddev (rate($metric{cluster_id=\"$cluster\", device=\"$device\"}[$duration]))",
     "legendFormat": "stddev"
    }
   ]
  },
  {
   "title": "Rate of Bytes ($duration) Less Than $threshold * Standard Deviation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate($metric{cluster_id=\"$cluster\", device=\"$device\"}[$duration]) < scalar(avg(rate($metric{cluster_id=\"$cluster\", device=\"$device\"}[$duration])) - $threshold*stddev (rate($metric{cluster_id=\"$cluster\", device=\"$device\"}[$duration])))",
     "legendFormat": "{{ instance }} - {{ device }}"
    }
   ]
  },
  {
   "title": "Rate of Bytes ($duration) Greater Than $threshold * Standard Deviation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate($metric{cluster_id=\"$cluster\", device=\"$device\"}[$duration]) > scalar(avg(rate($metric{cluster_id=\"$cluster\", device=\"$device\"}[$duration])) + $threshold*stddev (rate($metric{cluster_id=\"$cluster\", device=\"$device\"}[$duration])))",
     "legendFormat": "{{ instance }} - {{ device }}"
    }
   ]
  },
  { "title": "$metric", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Rate of Bytes ($duration)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate($metric{cluster_id=\"$cluster\", device=\"$device\"}[$duration])",
     "legendFormat": "{{ instance }} - {{ device }}"
    }
   ]
  },
  {
   "title": "Average Rate of Bytes ($duration)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(rate($metric{cluster_id=\"$cluster\", device=\"$device\"}[$duration]))",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Standard Deviation of Rate of Bytes ($duration)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "stddev (rate($metric{cluster_id=\"$cluster\", device=\"$device\"}[$duration]))",
     "legendFormat": "stddev"
    }
   ]
  },
  {
   "title": "Rate of Bytes ($duration) Less Than $threshold * Standard Deviation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate($metric{cluster_id=\"$cluster\", device=\"$device\"}[$duration]) < scalar(avg(rate($metric{cluster_id=\"$cluster\", device=\"$device\"}[$duration])) - $threshold*stddev (rate($metric{cluster_id=\"$cluster\", device=\"$device\"}[$duration])))",
     "legendFormat": "{{ instance }} - {{ device }}"
    }
   ]
  },
  {
   "title": "Rate of Bytes ($duration) Greater Than $threshold * Standard Deviation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate($metric{cluster_id=\"$cluster\", device=\"$device\"}[$duration]) > scalar(avg(rate($metric{cluster_id=\"$cluster\", device=\"$device\"}[$duration])) + $threshold*stddev (rate($metric{cluster_id=\"$cluster\", device=\"$device\"}[$duration])))",
     "legendFormat": "{{ instance }} - {{ device }}"
    }
   ]
  }
 ]
}