{
 "title": "Nodes Overview",
 "tags": [
  "owner:team-ludacris",
  "topic:management-cluster",
  "topic:workload-cluster"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(up{app=\"node-exporter\"}, cluster_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "  ", "type": "macropower-analytics-panel", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Worker nodes",
   "type": "stat",
   "description": "Last number of worker nodes in the selected time interval",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kube_node_role{cluster_id=\"$cluster\",role=\"worker\"})"
    }
   ]
  },
  {
   "title": "Control plane nodes",
   "type": "stat",
   "description": "Last number of control plane nodes in the selected time interval",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kube_node_role{cluster_id=\"$cluster\",role=\"master\"})"
    }
   ]
  },
  {
   "title": "Number of nodes",
   "type": "timeseries",
   "description": "Worker and control plane nodes over time",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(kube_node_role{cluster_id=\"$cluster\",role=\"master\"})",
     "legendFormat": "Control plane nodes"
    },
    {
     "expr": "count(kube_node_role{cluster_id=\"$cluster\",role=\"worker\"})",
     "legendFormat": "Worker nodes"
    }
   ]
  },
  { "title": "CPU usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Overall average",
   "type": "stat",
   "description": "Average CPU usage over all nodes, including worker nodes and control plane, for the selected time frame",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1 - avg(irate(node_cpu_seconds_total{mode=\"idle\",cluster_id=\"$cluster\",node!=\"\"}[5m]))"
    }
   ]
  },
  {
   "title": "Per node",
   "type": "timeseries",
   "description": "CPU time time usage per node",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - avg(irate(node_cpu_seconds_total{mode=\"idle\",cluster_id=\"$cluster\",node!=\"\"}[5m])) by (node))",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  { "title": "Load", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Load over 1 minute",
   "type": "timeseries",
   "description": "Load as reported by node_exporter via the node_load1 metric",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(node_load1{cluster_id=\"$cluster\",node!=\"\"}) by (node)",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Load over 5 minutes",
   "type": "timeseries",
   "description": "Load as reported by node_exporter via the node_load5 metric",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(node_load5{cluster_id=\"$cluster\",node!=\"\"}) by (node)",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Load over 15 minutes",
   "type": "timeseries",
   "description": "Load as reported by node_exporter via the node_load15 metric",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(node_load15{cluster_id=\"$cluster\",node!=\"\"}) by (node)",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Total memory",
   "type": "stat",
   "description": "RAM in all nodes, including worker nodes and control plane",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{cluster_id=\"$cluster\",node!=\"\"})"
    }
   ]
  },
  {
   "title": "Used memory",
   "type": "stat",
   "description": "RAM used in all nodes, including worker nodes and control plane",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1 - sum(node_memory_MemFree_bytes{cluster_id=\"$cluster\",node!=\"\"}) / sum(node_memory_MemTotal_bytes{cluster_id=\"$cluster\",node!=\"\"})"
    }
   ]
  },
  {
   "title": "Used memory per node",
   "type": "timeseries",
   "description": "As reported by node-exporter via the node_memory_MemFree_bytes and node_memory_MemTotal_bytes metrics",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - sum(node_memory_MemFree_bytes{cluster_id=\"$cluster\",node!=\"\"}) by (node) / sum(node_memory_MemTotal_bytes{cluster_id=\"$cluster\",node!=\"\"}) by (node)",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Received per node and device",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{cluster_id=\"$cluster\",node!=\"\"}[5m])) by (node, device)",
     "legendFormat": "{{ node }} {{ device }}"
    }
   ]
  },
  {
   "title": "Transmitted per node and device",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{cluster_id=\"$cluster\",node!=\"\"}[5m])) by (node, device)",
     "legendFormat": "{{ node }} {{ device }}"
    }
   ]
  },
  { "title": "Disks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Total disk size",
   "type": "stat",
   "description": "Total of disk storage available in all nodes",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{cluster_id=\"$cluster\",node!=\"\"})"
    }
   ]
  },
  {
   "title": "Total disk usage",
   "type": "stat",
   "description": "Total of disk usage in all nodes",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1 - sum(node_filesystem_free_bytes{cluster_id=\"$cluster\",node!=\"\"}) / sum(node_filesystem_size_bytes{cluster_id=\"$cluster\",node!=\"\"})"
    }
   ]
  },
  {
   "title": "Usage for selected disks",
   "type": "timeseries",
   "description": "Only showing disks with usage above 10 percent. Not including persistent volumes.",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - sum(node_filesystem_free_bytes{cluster_id=\"$cluster\",node!=\"\"} / node_filesystem_size_bytes{cluster_id=\"$cluster\",node!=\"\"}) by (node, device, mountpoint) > 0.1",
     "legendFormat": "{{ node }} - {{device}} - {{ mountpoint }} "
    }
   ]
  }
 ]
}