{
 "title": "Pod request vs usage",
 "tags": [ "owner:team-atlas" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(process_cpu_seconds_total, cluster_id)"
   },
   {
    "name": "container",
    "label": "Container",
    "query": "label_values(process_cpu_seconds_total{cluster_id=\"$cluster\"},app)"
   }
  ]
 },
 "panels": [
  {
   "title": "Top10 lowest % requested CPU over real usage",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sort(bottomk(10,sum(label_replace(rate(process_cpu_seconds_total{cluster_id=\"$cluster\"}[2h]),\"container\",\"$1\",\"app\",\"(.*)\"))by(container)/ on(container)avg(avg_over_time(kube_pod_container_resource_requests_cpu_cores{cluster_id=\"$cluster\"}[1d]))by(container)*100))",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Top10 lowest % requested memory over real usage",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sort(bottomk(10,avg(label_replace(avg_over_time(process_resident_memory_bytes{cluster_id=\"$cluster\"}[1w]),\"container\",\"$1\",\"app\",\"(.*)\"))by(container)/ on(container)avg(avg_over_time(kube_pod_container_resource_requests_memory_bytes{cluster_id=\"$cluster\"}[1w]))by(container)*100))",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "CPU request vs usage (Y-axis: log2 scale)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_requests_cpu_cores{cluster_id=\"$cluster\",container=\"$container\"})",
     "legendFormat": "request"
    },
    {
     "expr": "avg(rate(process_cpu_seconds_total{cluster_id=\"$cluster\",app=\"$container\"}[2h]))",
     "legendFormat": "usage"
    }
   ]
  },
  {
   "title": "Memory request vs usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_requests_memory_bytes{cluster_id=\"$cluster\",container=\"$container\"})",
     "legendFormat": "request"
    },
    {
     "expr": "avg(avg_over_time(process_resident_memory_bytes{cluster_id=\"$cluster\",app=\"$container\"}[2h]))",
     "legendFormat": "usage"
    }
   ]
  }
 ]
}