{
 "title": "Service Level",
 "tags": [ "atlas" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(slo_requests{}, service)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(slo_requests{}, cluster_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Currently Alerting Services",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(\n        slo_errors_per_request:ratio_rate1h{service=~\"$service\", cluster_id=~\"$cluster\"} > on (service, cluster_id) group_left (cluster_type, class) slo_threshold_high\n        and\n        slo_errors_per_request:ratio_rate5m{service=~\"$service\", cluster_id=~\"$cluster\"} > on (service, cluster_id) group_left (cluster_type, class) slo_threshold_high\n        or\n        slo_errors_per_request:ratio_rate6h{service=~\"$service\", cluster_id=~\"$cluster\"} > on (service, cluster_id) group_left (cluster_type, class) slo_threshold_low\n        and\n        slo_errors_per_request:ratio_rate30m{service=~\"$service\", cluster_id=~\"$cluster\"} > on (service, cluster_id) group_left (cluster_type, class) slo_threshold_low\n      ) by (service, cluster_id)"
    }
   ]
  },
  {
   "title": "Alert",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(\n      slo_errors_per_request:ratio_rate1h{service=~\"$service\", cluster_id=~\"$cluster\"} > on (service, cluster_id) group_left (cluster_type, class) slo_threshold_high\n      and\n      slo_errors_per_request:ratio_rate5m{service=~\"$service\", cluster_id=~\"$cluster\"} > on (service, cluster_id) group_left (cluster_type, class) slo_threshold_high\n      or\n      slo_errors_per_request:ratio_rate6h{service=~\"$service\", cluster_id=~\"$cluster\"} > on (service, cluster_id) group_left (cluster_type, class) slo_threshold_low\n      and\n      slo_errors_per_request:ratio_rate30m{service=~\"$service\", cluster_id=~\"$cluster\"} > on (service, cluster_id) group_left (cluster_type, class) slo_threshold_low\n    ) by (service, cluster_id)",
     "legendFormat": "{{service}} / {{cluster}}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "slo_requests{service=~\"$service\", cluster_id=~\"$cluster\"}",
     "legendFormat": "{{service}} / {{cluster}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "slo_errors{service=~\"$service\", cluster_id=~\"$cluster\"}",
     "legendFormat": "{{service}} / {{cluster}}"
    }
   ]
  },
  {
   "title": "High Burn Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "slo_errors_per_request:ratio_rate5m{service=~\"$service\", cluster_id=~\"$cluster\"}",
     "legendFormat": "{{service}} / {{cluster}} (5m)"
    },
    {
     "expr": "slo_errors_per_request:ratio_rate1h{service=~\"$service\", cluster_id=~\"$cluster\"}",
     "legendFormat": "{{service}} / {{cluster}} (1h)"
    },
    {
     "expr": "min(slo_threshold_high{service=~\"$service\", cluster_id=~\"$cluster\"}) by (service)",
     "legendFormat": "SLO High Threshold - {{service}}"
    }
   ]
  },
  {
   "title": "Low Burn Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "slo_errors_per_request:ratio_rate30m{service=~\"$service\", cluster_id=~\"$cluster\"}",
     "legendFormat": "{{service}} / {{cluster}} (30m)"
    },
    {
     "expr": "slo_errors_per_request:ratio_rate6h{service=~\"$service\", cluster_id=~\"$cluster\"}",
     "legendFormat": "{{service}} / {{cluster}} (6h)"
    },
    {
     "expr": "min(slo_threshold_low{service=~\"$service\", cluster_id=~\"$cluster\"}) by (service)",
     "legendFormat": "SLO Low Threshold - {{service}}"
    }
   ]
  },
  {
   "title": "SLO targets",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1- min(slo_target{service=~\"$service\", cluster_id=~\"$cluster\"}) by (service)"
    }
   ]
  }
 ]
}