{
 "title": "AWS CNI",
 "tags": [
  "provider:aws",
  "topic:workload-cluster",
  "owner:team-phoenix"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(kubernetes_build_info, cluster_id)"
   }
  ]
 },
 "panels": [
  {
   "title": "Kubernetes nodes",
   "type": "singlestat",
   "description": "Number of Kubernetes nodes according to the kube_node_info metric",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_info{cluster_id=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "aws-node instances",
   "type": "singlestat",
   "description": "Number of aws-node instances, including both worker and control plane nodes. There should be one for each node.",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(awscni_eni_max{cluster_id=\"$cluster\"}) by (pod_name))"
    }
   ]
  },
  {
   "title": "Maximum ENI capacity",
   "type": "singlestat",
   "description": "The theoretical limit of Elastic Network Interface that could be available to nodes in this cluster.",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(awscni_eni_max{cluster_id=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Maximum IP addr. capacity",
   "type": "singlestat",
   "description": "The theoretical number of IP addresses available in this cluster if all nodes had all possible ENIs allocated",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(awscni_ip_max{cluster_id=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "ENIs allocated",
   "type": "singlestat",
   "description": "The number of ENIs currently allocated to nodes",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(awscni_eni_allocated{cluster_id=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Current IP capacity based on ENI",
   "type": "singlestat",
   "description": "The capacity of IP addresses in the cluster, based on the number of ENIs currently allocated.",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(awscni_total_ip_addresses{cluster_id=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "IP addresses in use",
   "type": "singlestat",
   "description": "IP addresses currently assigned to pods",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(awscni_assigned_ip_addresses{cluster_id=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Free IP addresses",
   "type": "singlestat",
   "description": "IP addresses available per ENIs, but currently not assigned to pods",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(awscni_total_ip_addresses{cluster_id=\"$cluster\"}) - sum(awscni_assigned_ip_addresses{cluster_id=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Assigned IP addresses per node",
   "type": "bargauge",
   "description": "For each aws-node instance, the number of IP addresses assigned currently",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "awscni_assigned_ip_addresses{cluster_id=\"$cluster\"}",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "IP addresses in the workload cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "IP capacity",
     "type": "graph",
     "description": "This graph compares over time: (a) theoretical capacity based on ENI capacity, (b) actual capacity based on current ENIs, (c) actual IP addresses in use.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(awscni_ip_max{cluster_id=\"$cluster\"})",
       "legendFormat": "Theoretical maximum"
      },
      {
       "expr": "sum(awscni_total_ip_addresses{cluster_id=\"$cluster\"})",
       "legendFormat": "Capacity based on ENIs available"
      },
      {
       "expr": "sum(awscni_assigned_ip_addresses{cluster_id=\"$cluster\"})",
       "legendFormat": "In use"
      }
     ]
    },
    {
     "title": "IP capacity by node (awscni_ip_max)",
     "type": "graph",
     "description": "awscni_ip_max is set on start of the ipamD daemon to the value of NumENIs * NumIPsPerENI. The number of IPs per ENI and the number of ENIs is dependent on the instance type.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(awscni_ip_max{cluster_id=\"$cluster\"}) by (pod_name)",
       "legendFormat": "{{ pod_name }}"
      }
     ]
    },
    {
     "title": "IP capacity per node (awscni_total_ip_addresses)",
     "type": "graph",
     "description": "This is an actual metric/gauge whose value is incremented for each IP address that can be assigned to an ENI when an ENI is added to the set of ENIs managed by the ipamD daemon. This happens on start of the CNI plugin's ipamD daemon.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "awscni_total_ip_addresses{cluster_id=\"$cluster\"}",
       "legendFormat": "{{ pod_name }}"
      }
     ]
    },
    {
     "title": "IP addresses in use per node (awscni_assigned_ip_addresses)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "awscni_assigned_ip_addresses{cluster_id=\"$cluster\"}",
       "legendFormat": "{{ pod_name }}"
      }
     ]
    },
    {
     "title": "Requests to add an IP address per node (awscni_add_ip_req_count)",
     "type": "graph",
     "description": "Requests to add an IP address to a node, in number of operations per hour",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(awscni_add_ip_req_count{cluster_id=\"$cluster\"}[60m])",
       "legendFormat": "{{ pod_name }}"
      }
     ]
    },
    {
     "title": "Force-removed IP addresses per node (awscni_force_removed_ips)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "awscni_force_removed_ips{cluster_id=\"$cluster\"}",
       "legendFormat": "{{ pod_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Elastic Network Interfaces (ENI) in the workload cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "ENI capacity per node (awscni_eni_max)",
     "type": "graph",
     "description": "Maximum number of ENIs available per node. This is dependent on the instance type.",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "awscni_eni_max{cluster_id=\"$cluster\"}",
       "legendFormat": "{{ pod_name }}"
      }
     ]
    },
    {
     "title": "ENI allocated per node (awscni_eni_allocated)",
     "type": "graph",
     "description": "Number of network interfaces allocated at the given moment.",
     "gridPos": { "h": 7, "w": 9, "x": 9, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "awscni_eni_allocated{cluster_id=\"$cluster\"}",
       "legendFormat": "{{ pod_name }}"
      }
     ]
    },
    {
     "title": "Force-removed ENI per node (awscni_force_removed_enis)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "awscni_force_removed_enis{cluster_id=\"$cluster\"}",
       "legendFormat": "{{ pod_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Activity in the workload cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "AWS API latency - .99 quantile (awscni_aws_api_latency_ms)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "awscni_aws_api_latency_ms{quantile=\"0.99\",cluster_id=\"$cluster\"}",
       "legendFormat": "{{ pod_name }} / {{ api }}"
      }
     ]
    },
    {
     "title": "AWS API errors (awscni_aws_api_latency_ms_sum)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(awscni_aws_api_latency_ms_sum{error=\"true\",cluster_id=\"$cluster\"}) by (cluster_id, pod_name, api)",
       "legendFormat": "{{ pod_name }} / {{ api }}"
      }
     ]
    },
    {
     "title": "ipamd actions in progress (awscni_ipamd_action_inprogress)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "awscni_ipamd_action_inprogress{cluster_id=\"$cluster\"}",
       "legendFormat": "{{ pod_name }} / {{ fn }}"
      }
     ]
    }
   ]
  }
 ]
}