{
 "title": "K8s API performance",
 "tags": [
  "owner:team-turtles",
  "topic:performance",
  "component:kube-apiserver"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   { "name": "cluster_id", "label": "Cluster ID", "query": { "query": "label_values(up, cluster_id)" } },
   {
    "name": "etcd_operation",
    "query": {
     "query": "label_values(etcd_request_duration_seconds_bucket, operation)"
    }
   },
   {
    "name": "priority_level",
    "query": {
     "query": "label_values(apiserver_flowcontrol_dispatched_requests_total, priority_level)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "API Server metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 1 },
   "options": {
    "content": "The number of requests that hit the API server."
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 1 },
   "options": {
    "content": "Count of watch requests by resource"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate of API requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "sum by (instance) (rate(apiserver_request_total{cluster_id=\"$cluster_id\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Watch Events Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "sum(rate(apiserver_watch_events_total{cluster_id=\"$cluster_id\"}[$__rate_interval])) by (kind)",
     "legendFormat": "{{ kind }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 11 },
   "options": {
    "content": "Response times distribution (excluding WATCH requests)"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "API Server Request Duration",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(increase(apiserver_request_duration_seconds_bucket{cluster_id=\"$cluster_id\",verb!=\"WATCH\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "API Server Fariness and Priority",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 21 },
   "options": {
    "content": "See https://kubernetes.io/docs/concepts/cluster-administration/flow-control/ and https://itnext.io/kubernetes-api-priority-and-fairness-b1ef2b8a26a2"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "API Requests for priority level $priority_level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
   "repeat": "priority_level",
   "targets": [
    {
     "expr": "sum(irate(apiserver_flowcontrol_dispatched_requests_total{cluster_id=\"$cluster_id\",priority_level=\"$priority_level\"}[$__rate_interval]))",
     "legendFormat": "Rate"
    },
    {
     "expr": "min(apiserver_flowcontrol_request_concurrency_limit{cluster_id=\"$cluster_id\",priority_level=\"$priority_level\"})",
     "legendFormat": "Limit"
    },
    {
     "expr": "sum(irate(apiserver_flowcontrol_current_inqueue_requests{cluster_id=\"$cluster_id\",priority_level=\"$priority_level\"}[$__rate_interval]))",
     "legendFormat": "Queued"
    },
    {
     "expr": "sum(irate(apiserver_flowcontrol_rejected_requests_total{cluster_id=\"$cluster_id\",priority_level=\"$priority_level\"}[$__rate_interval]))",
     "legendFormat": "Rejected"
    }
   ]
  },
  {
   "title": "ETCD Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Number of etcd actions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sum(rate(etcd_mvcc_put_total{cluster_id=\"$cluster_id\"}[$__rate_interval]))",
     "legendFormat": "PUT"
    },
    {
     "expr": "sum(rate(etcd_mvcc_delete_total{cluster_id=\"$cluster_id\"}[$__rate_interval]))",
     "legendFormat": "DELETE"
    },
    {
     "expr": "sum(rate(etcd_mvcc_range_total{cluster_id=\"$cluster_id\"}[$__rate_interval]))",
     "legendFormat": "RANGE"
    },
    {
     "expr": "sum(rate(etcd_mvcc_txn_total{cluster_id=\"$cluster_id\"}[$__rate_interval]))",
     "legendFormat": "TXN"
    }
   ]
  },
  {
   "title": "Number of keys in ETCD by member",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "avg(etcd_debugging_mvcc_keys_total{cluster_id=\"$cluster_id\"}) by (ip)",
     "legendFormat": "{{ ip }}"
    }
   ]
  },
  {
   "title": "Commit write duration distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sum(increase(etcd_debugging_disk_backend_commit_write_duration_seconds_bucket{cluster_id=\"$cluster_id\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Total etcd DB size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "etcd_db_total_size_in_bytes{cluster_id=\"$cluster_id\"}",
     "legendFormat": "Real size on disk"
    },
    {
     "expr": "etcd_mvcc_db_total_size_in_use_in_bytes{cluster_id=\"$cluster_id\"}",
     "legendFormat": "Used size (excludes fragmentation) {{ip}}"
    }
   ]
  },
  {
   "title": "etcd $etcd_operation request duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "repeat": "etcd_operation",
   "targets": [
    {
     "expr": "sum(increase(etcd_request_duration_seconds_bucket{cluster_id=\"$cluster_id\", operation=\"$etcd_operation\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "ETCD Keyspace usage (in percentage)",
   "type": "timeseries",
   "description": "The set of all keys in an ETCD cluster. If the percentage is too high, ETDC will stop working.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 88 },
   "targets": [
    {
     "expr": "etcd_mvcc_db_total_size_in_bytes{cluster_id=\"$cluster_id\"} / etcd_server_quota_backend_bytes{cluster_id=\"$cluster_id\"} * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node (VM) Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Node CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - avg(irate(node_cpu_seconds_total{mode=\"idle\",cluster_id=\"$cluster_id\",node!=\"\"}[$__rate_interval])) by (node)) and on (node) kube_node_role{cluster_id=\"$cluster_id\",role=~\"control-plane|master\"}",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Node memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(1 - sum(node_memory_MemAvailable_bytes{cluster_id=\"$cluster_id\",node!=\"\"}) by (node) / sum(node_memory_MemTotal_bytes{cluster_id=\"$cluster_id\",node!=\"\"}) by (node)) and on (node) kube_node_role{cluster_id=\"$cluster_id\",role=~\"control-plane|master\"}",
     "legendFormat": "{{ node }}"
    }
   ]
  }
 ]
}