{
 "title": "Cilium Agent logs",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kubernetes_build_info,cluster_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Errors & Warnings",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (level) (count_over_time({service_name=\"cilium-agent\", cluster_id=\"$cluster\"} | logfmt | level =~ `error|warning`[$__auto]))",
     "legendFormat": "{{ level }}"
    }
   ]
  },
  {
   "title": "Errors & Warnings",
   "type": "logs",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 5 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"cilium-agent\", cluster_id=\"$cluster\"} | logfmt | level =~ `error|warning` | line_format \"pod={{.pod}} msg={{.msg}} error={{.error}} endpoint={{.ciliumEndpointName}}\""
    }
   ]
  },
  {
   "title": "Top 10 Errors",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (msg) (count_over_time({service_name=\"cilium-agent\", cluster_id=\"$cluster\"} | logfmt | level = `error`[$__auto]))",
     "legendFormat": "{{ msg }}"
    }
   ]
  },
  {
   "title": "Top 10 Warnings",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (msg) (count_over_time({service_name=\"cilium-agent\", cluster_id=\"$cluster\"} | logfmt | level = `warning`[$__auto]))",
     "legendFormat": "{{ msg }}"
    }
   ]
  },
  {
   "title": "Failing Cilium Network Policies ",
   "type": "table",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 23 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (k8sNamespace, ciliumNetworkPolicyName) (rate({service_name=\"cilium-agent\", cluster_id=\"$cluster\"} | logfmt | level =~ `error|warning` | msg =~ `Unable to add CiliumNetworkPolicy`[1m]))"
    }
   ]
  }
 ]
}