{
 "title": "Kubernetes Events & Resources Count",
 "tags": [ "owner:team-phoenix" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster ID",
    "query": {
     "query": "label_values(etcd_kubernetes_resources_count, cluster_id)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(etcd_kubernetes_resources_count, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$cluster - Kubernetes objects by Kind",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum (etcd_kubernetes_resources_count{cluster_id=\"$cluster\", namespace=~\"$namespace\"}) by (kind)",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "$cluster - Kubernetes objects by Namespace",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum (etcd_kubernetes_resources_count{cluster_id=\"$cluster\", namespace=~\"$namespace\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "title": "Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "$cluster -  Current Number of Events",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(etcd_kubernetes_resources_count{cluster_id=\"$cluster\", kind=\"events\",namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "$cluster -  Rate of Events every 5m in 1m buckets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(etcd_kubernetes_events_count{cluster_id=\"$cluster\", namespace=~\"$namespace\"}[1h])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "$cluster -  Events by Kind of the involved object",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(etcd_kubernetes_events_count{cluster_id=\"$cluster\",namespace=~\"$namespace\"}) by (kind)",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "$cluster - Events by reason",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 24 },
   "targets": [
    {
     "expr": "sum(etcd_kubernetes_events_count{cluster_id=\"$cluster\",namespace=~\"$namespace\"}) by (reason)",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "$cluster - Events by namespace",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 24 },
   "targets": [
    {
     "expr": "sum(etcd_kubernetes_events_count{cluster_id=\"$cluster\",namespace=~\"$namespace\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  }
 ]
}