{
 "title": "ETCD Backup",
 "tags": [
  "owner:team-phoenix",
  "component:etcd"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(etcd_backup_latest_attempt, tenant_cluster_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Backup metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Backup file size",
   "type": "graph",
   "description": "Size of the etcd snapshot archive.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg by (tenant_cluster_id) (etcd_backup_size_bytes)",
     "legendFormat": "{{tenant_cluster_id}}"
    }
   ]
  },
  {
   "title": "Backup Creation Time",
   "type": "graph",
   "description": "The time it took to take the etcd snapshot.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg by (tenant_cluster_id) (etcd_backup_creation_time_ms)",
     "legendFormat": "{{tenant_cluster_id}}"
    }
   ]
  },
  {
   "title": "Encryption Time",
   "type": "graph",
   "description": "The time it took to encrypt the backup, if encryption is enabled.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg by (tenant_cluster_id) (etcd_backup_encryption_time_ms)",
     "legendFormat": "{{tenant_cluster_id}}"
    }
   ]
  },
  {
   "title": "Upload Time",
   "type": "graph",
   "description": "The time it took to upload the backup archive to the S3 bucket. ",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg by (tenant_cluster_id) (etcd_backup_upload_time_ms)",
     "legendFormat": "{{tenant_cluster_id}}"
    }
   ]
  },
  {
   "title": "Management cluster (Vintage only)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Number of Workload Clusters",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count(sum(max_over_time(cluster_service_cluster_info{}[$__range])) by (cluster_id)) OR on() vector(0)) + (count(count(max_over_time(cluster_operator_cluster_status{}[$__range])) by (cluster_id)) OR on() vector(0)) - (count(count(max_over_time(cluster_operator_cluster_status{status=\"Deleting\"}[$__range]) == 1) by (cluster_id)) OR on() vector(0))"
    }
   ]
  },
  {
   "title": "Count of TC ETCD Backups",
   "type": "stat",
   "description": "The count of non-management cluster etcd backups.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count (etcd_backup_latest_success{tenant_cluster_id != \"ManagementCluster\"}) by (tenant_cluster_id))"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 0, "y": 14 },
   "options": { "content": "# V2\n\n\n\n" },
   "targets": [
    {}
   ]
  },
  {
   "title": "Latest backup schedule",
   "type": "stat",
   "description": "The last time a backup was scheduled, whether successful or not.",
   "gridPos": { "h": 2, "w": 5, "x": 1, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(etcd_backup_latest_attempt{tenant_cluster_id=\"ManagementCluster\",etcd_version=\"V2\"}*1000)"
    }
   ]
  },
  {
   "title": "Latest successful backup",
   "type": "stat",
   "description": "Date of the latest backup completed successfully. This is the time the backup was taken, not when it finished uploading.",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(etcd_backup_latest_success{tenant_cluster_id=\"ManagementCluster\",etcd_version=\"V2\"}*1000)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 0, "y": 16 },
   "options": { "content": "# V3\n\n\n\n" },
   "targets": [
    {}
   ]
  },
  {
   "title": "Latest backup schedule",
   "type": "stat",
   "description": "The last time a backup was scheduled, whether successful or not.",
   "gridPos": { "h": 2, "w": 5, "x": 1, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(etcd_backup_latest_attempt{tenant_cluster_id=\"ManagementCluster\",etcd_version=\"V3\"}*1000)"
    }
   ]
  },
  {
   "title": "Latest successful backup",
   "type": "stat",
   "description": "Date of the latest backup completed successfully. This is the time the backup was taken, not when it finished uploading.",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(etcd_backup_latest_success{tenant_cluster_id=\"ManagementCluster\",etcd_version=\"V3\"}*1000)"
    }
   ]
  },
  {
   "type": "text",
   "description": "These include the Management Cluster in CAPI clusters.",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 18 },
   "options": { "content": "# Workload Clusters" },
   "targets": [
    {}
   ]
  },
  {
   "title": "$cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "repeat": "cluster",
   "targets": [
    {}
   ]
  },
  {
   "title": "Latest backup schedule",
   "type": "stat",
   "description": "The last time a backup was scheduled, whether successful or not.",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(etcd_backup_latest_attempt{tenant_cluster_id=\"$cluster\",etcd_version=\"V3\"}*1000)"
    }
   ]
  },
  {
   "title": "Latest successful backup",
   "type": "stat",
   "description": "Date of the latest backup completed successfully. This is the time the backup was taken, not when it finished uploading.",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(etcd_backup_latest_success{tenant_cluster_id=\"$cluster\",etcd_version=\"V3\"}*1000)"
    }
   ]
  }
 ]
}