{
 "title": "External Secrets",
 "description": "Monitoring External Secrets and related components",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "rate_interval",
    "label": "Rate Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "namespace", "label": "Namespace", "query": "external-secrets" }
  ]
 },
 "panels": [
  { "title": "Reconciliation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Managed Resources",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "etcd_kubernetes_resources_count{namespace=\"$namespace\", kind=~\".*external-secrets.*\"}",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Workqueue Depth by Controller",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by (name) (workqueue_depth{job=~\"$namespace/.+\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Webhooks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Validation Webhook Requests (total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by(webhook) (controller_runtime_webhook_requests_total{namespace=\"$namespace\", webhook=~\"/validate.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validation Webhook Latency (sum)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(webhook) (controller_runtime_webhook_latency_seconds_sum{namespace=\"$namespace\", webhook=~\"/validate.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Conversion Webhook Requests (total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by(webhook) (controller_runtime_webhook_requests_total{namespace=\"$namespace\", webhook=~\"/convert.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Conversion Webhook Latency (sum)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(webhook) (controller_runtime_webhook_latency_seconds_sum{namespace=\"$namespace\", webhook=~\"/convert.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Webhook requests (in-flight)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum by(webhook) (controller_runtime_webhook_requests_in_flight{namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Certificates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Cert watcher read certificates (total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum by(app) (certwatcher_read_certificate_total{namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cert watcher read certificates (errors)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "sum by(app) (certwatcher_read_certificate_errors_total{namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}