{
 "title": "Grafana",
 "description": "The meta-dashboard about Grafana health and usage",
 "tags": [
  "owner:team-atlas",
  "topic:observability",
  "component:grafana"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "At  a Glance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Restarts",
   "type": "stat",
   "description": "Pod restarts",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{pod=~\"grafana-.*\"})"
    }
   ]
  },
  {
   "title": "Users Logged In",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(grafana_stat_active_users)" }
   ]
  },
  {
   "title": "Dashboards",
   "type": "stat",
   "description": "The number of dashboards existing",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(grafana_stat_totals_dashboard)"
    }
   ]
  },
  {
   "title": "API Error Rate",
   "type": "stat",
   "description": "As a percentage of Grafana API requests on selected range.",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(increase(grafana_api_response_status_total{code!=\"200\"}[$__range])) / sum(increase(grafana_api_response_status_total[$__range]))",
     "legendFormat": "error ratio"
    }
   ]
  },
  {
   "title": "Proxy Error Rate",
   "type": "stat",
   "description": "As a percentage of proxy requests (Prom, Elasticsearch, ...) on selected range.",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(increase(grafana_proxy_response_status_total{code!=\"200\"}[$__range])) / sum(increase(grafana_proxy_response_status_total[$__range]))"
    }
   ]
  },
  {
   "title": "Average Requests per Second",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(grafana_api_response_status_total[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "CPU Requests",
   "type": "stat",
   "description": "Number of CPU cores reserved",
   "gridPos": { "h": 5, "w": 2, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster_type=~\"management_cluster\",pod=~\"grafana.*\", resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "Memory Request",
   "type": "stat",
   "description": "Amount of memory reserved",
   "gridPos": { "h": 5, "w": 3, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster_type=~\"management_cluster\",pod=~\"grafana.*\", resource=\"memory\"})"
    }
   ]
  },
  { "title": "User Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Users Logins (beta)",
   "type": "timeseries",
   "description": "This is supposed to display the number of logins over time.",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(grafana_api_login_post_total)"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "description": "Current users logged in",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "sum(grafana_stat_active_users)" }
   ]
  },
  {
   "title": "Proxy Requests",
   "type": "timeseries",
   "description": "Number of proxy requests processed over time",
   "gridPos": { "h": 7, "w": 8, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(grafana_api_dataproxy_request_all_milliseconds_sum) / sum(grafana_api_dataproxy_request_all_milliseconds_count)",
     "legendFormat": "Requests"
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Proxy Request Latency",
   "type": "timeseries",
   "description": "Time it takes to fulfill a query via the proxy",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(grafana_api_dataproxy_request_all_milliseconds) by (quantile)",
     "legendFormat": "{{ quantile }} quantile"
    }
   ]
  },
  {
   "title": "Dashboard Load Latency",
   "type": "timeseries",
   "description": "Time it takes to fetch a dashboard (the main resource)",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(grafana_api_dashboard_get_milliseconds) by (quantile)",
     "legendFormat": "{{ quantile }} Quantile"
    }
   ]
  },
  {
   "title": "API Errors",
   "type": "timeseries",
   "description": "Errors in requests to the Grafana API",
   "gridPos": { "h": 7, "w": 5, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(grafana_api_response_status_total{code!=\"200\"}[$__rate_interval]))",
     "legendFormat": "Errors per second"
    }
   ]
  },
  {
   "title": "Proxy Error Rate",
   "type": "timeseries",
   "description": "Errors in requests to the datasource proxy",
   "gridPos": { "h": 7, "w": 5, "x": 17, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(grafana_proxy_response_status_total{code!=\"200\"}[$__rate_interval]))"
    }
   ]
  }
 ]
}