{
 "title": "Kube-Builder Operators",
 "description": "Show data for any kube-builder-based operator",
 "tags": [ "operator" ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   { "name": "LogsDS", "label": "Logs datasource", "query": "loki" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(controller_runtime_reconcile_total,cluster_id)"
    }
   },
   {
    "name": "operator",
    "query": {
     "query": "label_values(controller_runtime_reconcile_total{cluster_id=~\"$cluster\"},app)"
    }
   },
   {
    "name": "controller",
    "query": {
     "query": "label_values(controller_runtime_reconcile_total{cluster_id=~\"$cluster\", app=~\"$operator\"},controller)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Documentation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kube-Builder operators metrics",
     "type": "text",
     "gridPos": { "h": 17, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "## Intro\n\nAll operators written in go and based on `kube-builder` will expose common metrics.\nThis dashboard exploits these to show useful data about how well your operators work.\n\n## Durations\n\nYou can see here if one or multiple operators are taking longer than usual for resources reconciliations.\n\n👉 useful to spot long-hanging reconciliations.\n\n## Status\n\nHere, you see the amount of reconciliations, and their status.\nYou can also see the error ratio, meaning how often a reconciliation fails.\n\n👉 useful to spot failing reconciliations.\n\n## Controller Runtime Reconciliation total & errors\n\nInspired from kubebuilder [dashboards generator](https://master.book.kubebuilder.io/plugins/grafana-v1-alpha.html#controller-cpu--memory-usage).\n\nAnother way to see `Status` data.\n\n## Controller CPU & Memory Usage\n\nInspired from kubebuilder [dashboards generator](https://master.book.kubebuilder.io/plugins/grafana-v1-alpha.html#controller-cpu--memory-usage).\n\nAlways useful to see resource usage!\n\n## Work Queue\n\nInspired from kubebuilder [dashboards generator](https://master.book.kubebuilder.io/plugins/grafana-v1-alpha.html#controller-cpu--memory-usage)."
     }
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{cluster_id=\"$cluster\", scrape_job=\"kubernetes-pods\", pod=~\".*$operator.*\"}"
    }
   ]
  },
  { "title": "Durations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "workqueue_queue_duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(increase(workqueue_queue_duration_seconds_bucket{cluster_id=~\"$cluster\", app=~\"$operator\", name=~\"$controller\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "workqueue_work_duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "sum(increase(workqueue_work_duration_seconds_bucket{cluster_id=~\"$cluster\", app=~\"$operator\", name=~\"$controller\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "workqueue_queue_duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(workqueue_queue_duration_seconds_sum{cluster_id=~\"$cluster\", app=~\"$operator\", name=~\"$controller\"}[$__rate_interval])) by (cluster_id,app,name)",
     "legendFormat": "{{cluster_id}}: {{app}}/{{name}}"
    }
   ]
  },
  {
   "title": "workqueue_work_duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(workqueue_work_duration_seconds_sum{cluster_id=~\"$cluster\", app=~\"$operator\", name=~\"$controller\"}[$__rate_interval])) by (cluster_id,app,name)",
     "legendFormat": "{{cluster_id}}: {{app}}/{{name}}"
    }
   ]
  },
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Rates",
   "type": "timeseries",
   "description": "Shows how often operators reconciliate some resources.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_total{cluster_id=~\"$cluster\", app=~\"$operator\", controller=~\"$controller\"}[$__rate_interval])) by (cluster_id, app, controller, result)",
     "legendFormat": "{{cluster_id}}: {{app}}/{{controller}} - {{result}}"
    }
   ]
  },
  {
   "title": "Error ratio",
   "type": "timeseries",
   "description": "0% = all reconciliations work ❤️ |\n100% = no reconciliation works 💔 |\nno data = there's never been any error 🎉",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n    rate (controller_runtime_reconcile_total{cluster_id=~\"$cluster\", app=~\"$operator\", controller=~\"$controller\", result=\"error\"}[$__rate_interval])) by (cluster_id, app, controller)\n/\nsum(\n    rate (controller_runtime_reconcile_total{cluster_id=~\"$cluster\", app=~\"$operator\", controller=~\"$controller\"}[$__rate_interval])) by (cluster_id, app, controller)",
     "legendFormat": "{{cluster_id}}: {{app}}/{{controller}}"
    }
   ]
  },
  {
   "title": "Controller Runtime Reconciliation total & errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "Reconciliation total count per controller",
     "type": "timeseries",
     "description": "Per-second rate of total reconciliation as measured over the last 5 minutes",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
     "targets": [
      {
       "expr": "sum(rate(controller_runtime_reconcile_total{cluster_id=~\"$cluster\", app=~\"$operator\", controller=~\"$controller\"}[5m])) by (cluster_id, app, controller)",
       "legendFormat": "{{cluster_id}}: {{app}}/{{controller}}"
      }
     ]
    },
    {
     "title": "Reconciliation error count per controller",
     "type": "timeseries",
     "description": "Per-second rate of reconciliation errors as measured over the last 5 minutes",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
     "targets": [
      {
       "expr": "sum(rate(controller_runtime_reconcile_errors_total{cluster_id=~\"$cluster\", app=~\"$operator\", controller=~\"$controller\"}[5m])) by (cluster_id, app, controller)",
       "legendFormat": "{{cluster_id}}: {{app}}/{{controller}}"
      }
     ]
    }
   ]
  },
  { "title": "Controller CPU & Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "description": "Per-second rate of CPU usage as measured over the last 5 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{cluster_id=~\"$cluster\", app=~\"$operator\"}[5m]) * 100",
     "legendFormat": "{{cluster_id}} - {{app}}/{{instance}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "description": "Allocated Memory for the running controller",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{cluster_id=~\"$cluster\", app=~\"$operator\"}",
     "legendFormat": "{{cluster_id}} - {{app}}/{{instance}}"
    }
   ]
  },
  { "title": "Work queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Seconds for item stay in queue (before being requested) P50",
   "type": "timeseries",
   "description": "Seconds an item stays in workqueue before being requested.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(workqueue_queue_duration_seconds_bucket{cluster_id=~\"$cluster\", app=~\"$operator\"}[5m])) by (cluster_id, app, le))",
     "legendFormat": "{{cluster_id}}: {{app}} P50"
    }
   ]
  },
  {
   "title": "Seconds processing items in workqueue (P50)",
   "type": "timeseries",
   "description": "Seconds of processing an item from workqueue takes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(workqueue_work_duration_seconds_bucket{cluster_id=~\"$cluster\", app=~\"$operator\"}[5m])) by (cluster_id, app, le))",
     "legendFormat": "{{cluster_id}}: {{app}} P50"
    }
   ]
  },
  {
   "title": "Work queue add rate",
   "type": "timeseries",
   "description": "Per-second rate of items added to work queue",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "sum(rate(workqueue_adds_total{cluster_id=~\"$cluster\", app=~\"$operator\"}[5m])) by (cluster_id, app)",
     "legendFormat": "{{cluster_id}}: {{app}}"
    }
   ]
  },
  {
   "title": "Retries rate in work queue",
   "type": "timeseries",
   "description": "Per-second rate of retries handled by workqueue",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "targets": [
    {
     "expr": "sum(rate(workqueue_retries_total{cluster_id=~\"$cluster\", app=~\"$operator\"}[5m])) by (cluster_id, app)",
     "legendFormat": "{{cluster_id}}: {{app}}"
    }
   ]
  },
  {
   "title": "Number of workers in use",
   "type": "gauge",
   "description": "The number of active controller workers",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "controller_runtime_active_workers{cluster_id=~\"$cluster\", app=~\"$operator\"}",
     "legendFormat": "{{cluster_id}}: {{app}}"
    }
   ]
  },
  {
   "title": "WorkQueue depth",
   "type": "gauge",
   "description": "Current depth of workqueue",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "workqueue_depth{cluster_id=~\"$cluster\", app=~\"$operator\"}",
     "legendFormat": "{{cluster_id}}: {{app}}"
    }
   ]
  },
  {
   "title": "Unfinished seconds",
   "type": "gauge",
   "description": "How many seconds of work has done that is in progress and hasn’t been observed by work_duration.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(workqueue_unfinished_work_seconds{cluster_id=~\"$cluster\", app=~\"$operator\"}[5m])",
     "legendFormat": "{{cluster_id}}: {{app}}"
    }
   ]
  }
 ]
}