{
 "title": "Loki / Canary",
 "tags": [
  "owner:team-atlas",
  "topic:observability",
  "component:loki"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(loki_build_info, cluster_id)"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(loki_build_info{cluster_id=~\"$cluster\"}, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Canary Entries Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count(loki_canary_entries_total{cluster_id=~\"$cluster\", namespace=~\"$namespace\"}))"
    }
   ]
  },
  {
   "title": "Canary Logs Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(loki_canary_entries_total{cluster_id=~\"$cluster\",namespace=~\"$namespace\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Missing",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(loki_canary_missing_entries_total{cluster_id=~\"$cluster\",namespace=~\"$namespace\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Spotcheck Missing",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(loki_canary_spot_check_missing_entries_total{cluster_id=~\"$cluster\",namespace=~\"$namespace\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Spotcheck Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(loki_canary_spot_check_entries_total{cluster_id=~\"$cluster\",namespace=~\"$namespace\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Metric Test Error %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "((sum(loki_canary_metric_test_expected{cluster_id=~\"$cluster\",namespace=~\"$namespace\"}) - sum(loki_canary_metric_test_actual{cluster_id=~\"$cluster\",namespace=~\"$namespace\"}))/(sum(loki_canary_metric_test_actual{cluster_id=~\"$cluster\",namespace=~\"$namespace\"}))) * 100"
    }
   ]
  },
  {
   "title": "Missing %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(loki_canary_missing_entries_total{cluster_id=~\"$cluster\",namespace=~\"$namespace\"}[$__range]))/sum(increase(loki_canary_entries_total{cluster_id=~\"$cluster\",namespace=~\"$namespace\"}[$__range])))*100"
    }
   ]
  },
  {
   "title": "Spotcheck Missing %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(loki_canary_spot_check_missing_entries_total{cluster_id=~\"$cluster\",namespace=~\"$namespace\"}[$__range]))/sum(increase(loki_canary_spot_check_entries_total{cluster_id=~\"$cluster\",namespace=~\"$namespace\"}[$__range]))) * 100"
    }
   ]
  },
  {
   "title": "Metric Test Expected",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(loki_canary_metric_test_expected{cluster_id=~\"$cluster\",namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Metric Test Actual",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(loki_canary_metric_test_actual{cluster_id=~\"$cluster\",namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Websocket Missing",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(loki_canary_websocket_missing_entries_total{cluster_id=~\"$cluster\",namespace=~\"$namespace\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Websocket Missing %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(loki_canary_websocket_missing_entries_total{cluster_id=~\"$cluster\",namespace=~\"$namespace\"}[$__range]))/sum(increase(loki_canary_entries_total{cluster_id=~\"$cluster\",namespace=~\"$namespace\"}[$__range])))*100"
    }
   ]
  },
  {
   "title": "Log Write to read Latency Percentiles",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_canary_response_latency_seconds_bucket{cluster_id=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(loki_canary_response_latency_seconds_bucket{cluster_id=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Log Write to Read Latency",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "sum(rate(loki_canary_response_latency_seconds_bucket{cluster_id=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Spot Check Query",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(loki_canary_spot_check_request_duration_seconds_bucket{cluster_id=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(loki_canary_spot_check_request_duration_seconds_bucket{cluster_id=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval])) by (le))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Metric Test Query",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(loki_canary_metric_test_request_duration_seconds_bucket{cluster_id=~\"$cluster\",namespace=~\"$namespace\"}[15m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(loki_canary_metric_test_request_duration_seconds_bucket{cluster_id=~\"$cluster\",namespace=~\"$namespace\"}[15m])) by (le))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Spot Check Missing %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(20, (sum by (cluster_id, pod) (increase(loki_canary_spot_check_missing_entries_total{cluster_id=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval]))/sum by (cluster_id, pod) (increase(loki_canary_spot_check_entries_total{cluster_id=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval])) * 100)) > 0"
    }
   ]
  },
  {
   "title": "Missing logs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(20,(sum by (cluster_id, pod)(increase(loki_canary_missing_entries_total{cluster_id=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval]))/sum by (cluster_id, pod)(increase(loki_canary_entries_total{cluster_id=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval])))*100) > 0",
     "legendFormat": "Missing {{ cluster_id }} {{ pod }}"
    }
   ]
  }
 ]
}