{
 "title": "Loki / Resource Efficiency",
 "tags": [
  "owner:team-atlas",
  "topic:observability",
  "component:loki"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ratio_small",
    "query": "sum(increase(loki_distributor_bytes_received_total{}[1d])) / 3000000000000"
   },
   {
    "name": "ratio_medium",
    "query": "sum(increase(loki_distributor_bytes_received_total{}[1d])) / 30000000000000"
   },
   {
    "name": "ratio_big",
    "query": "sum(increase(loki_distributor_bytes_received_total{}[1d])) / 300000000000000"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 0 },
   "options": {
    "content": "# Intro\n\nThis dashboard compares actual resource usage for Loki compared to [official sizing rules](https://grafana.com/docs/loki/latest/setup/size/).\n\n# How to read it\n\nOn top of the dashboard, you see your actual volume of processed data, and how it compares to different types of cluster sizes.\n\n- The green \"actual\" line is the real actual resource usage on this cluster.\n- The red \"reserved\" line is the reserved resources (via pod's resource `requests`).\n- The thin purple \"small\", \"medium\" and \"big\" lines are estimations of expected resource usage according to Grafana sizing rules.\n\n# How do estimations work\n\nGrafana defines 3 cluster types:\n- small, up to 3TB/day of ingested logs\n- medium, up to 30TB/day of ingested logs\n- big, over 30TB/day. We considered a 300TB/day limit for these.\n\nWe compute 3 ratios, showing what percentage of each type your cluster's data ingestion is.\n\nThen, for each graph, we compute:\n```\n(small expected resource usage) * (ratio to small)\n```\nThis gives a basic projection of optimal resource usage according to sizing guide.\n\n# limitations\n\nOn small clusters (less than 10% of `small`), we may be higher than expected because of incompressible resources.\n\n"
   }
  },
  {
   "title": "Total loki ingested bytes per day",
   "type": "stat",
   "gridPos": { "h": 4, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(loki_distributor_bytes_received_total{}[1d]))",
     "legendFormat": "Reveived bytes"
    }
   ]
  },
  {
   "title": "Total loki ingested bytes per day",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "$ratio_small", "legendFormat": "ratio to small" },
    { "expr": "$ratio_medium", "legendFormat": "ratio to medium" },
    { "expr": "$ratio_big", "legendFormat": "ratio to big" }
   ]
  },
  { "title": "Simple Scalable setup", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Write Path CPU",
   "type": "timeseries",
   "description": "Distributors + Ingesters",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "(12+8) * $ratio_small", "legendFormat": "small cluster sizing" },
    { "expr": "(180+80) * $ratio_medium", "legendFormat": "medium cluster sizing" },
    { "expr": "(600+200) * $ratio_big", "legendFormat": "big cluster sizing" },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container=\"loki\", pod=~\"loki-write-.*\", cluster_type=\"management_cluster\"}[$__rate_interval]))",
     "legendFormat": "actual usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{container=\"loki\", pod=~\"loki-write-.*\", cluster_type=\"management_cluster\", resource=\"cpu\"})",
     "legendFormat": "reserved"
    }
   ]
  },
  {
   "title": "Write Path RAM",
   "type": "timeseries",
   "description": "Distributors + Ingesters",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "(36+2)*1024*1024*1204 * $ratio_small",
     "legendFormat": "small cluster sizing"
    },
    {
     "expr": "(540+40)*1024*1024*1204 * $ratio_medium",
     "legendFormat": "medium cluster sizing"
    },
    {
     "expr": "(1200+100)*1024*1024*1204 * $ratio_medium",
     "legendFormat": "big cluster sizing"
    },
    {
     "expr": "sum(container_memory_usage_bytes{container=\"loki\", pod=~\"loki-write-.*\", cluster_type=\"management_cluster\"})",
     "legendFormat": "actual usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{container=\"loki\", pod=~\"loki-write-.*\", cluster_type=\"management_cluster\", resource=\"memory\"})",
     "legendFormat": "reserved"
    }
   ]
  },
  {
   "title": "Read Path CPU",
   "type": "timeseries",
   "description": "Queriers + Query Frontends",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "(10+2) * $ratio_small", "legendFormat": "small cluster sizing" },
    { "expr": "(150+8) * $ratio_medium", "legendFormat": "medium cluster sizing" },
    { "expr": "(375+16) * $ratio_big", "legendFormat": "big cluster sizing" },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container=\"loki\", pod=~\"loki-read-.*\", cluster_type=\"management_cluster\"}[$__rate_interval]))",
     "legendFormat": "actual usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{container=\"loki\", pod=~\"loki-read-.*\", cluster_type=\"management_cluster\", resource=\"cpu\"})",
     "legendFormat": "reserved"
    }
   ]
  },
  {
   "title": "Read Path RAM",
   "type": "timeseries",
   "description": "Queriers + Query Frontends",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "(10+4)*1024*1024*1204 * $ratio_small",
     "legendFormat": "small cluster sizing"
    },
    {
     "expr": "(200+16)*1024*1024*1204 * $ratio_medium",
     "legendFormat": "medium cluster sizing"
    },
    {
     "expr": "(750+64)*1024*1024*1204 * $ratio_medium",
     "legendFormat": "big cluster sizing"
    },
    {
     "expr": "sum(container_memory_usage_bytes{container=\"loki\", pod=~\"loki-read-.*\", cluster_type=\"management_cluster\"})",
     "legendFormat": "actual usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{container=\"loki\", pod=~\"loki-read-.*\", cluster_type=\"management_cluster\", resource=\"memory\"})",
     "legendFormat": "reserved"
    }
   ]
  },
  {
   "title": "Backend Path CPU",
   "type": "timeseries",
   "description": "Compactor + Index Gateway + Query Scheduler + Ruler",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "(2+2+2) * $ratio_small", "legendFormat": "small cluster sizing" },
    { "expr": "(5+2+6) * $ratio_medium", "legendFormat": "medium cluster sizing" },
    { "expr": "(20+4+6) * $ratio_big", "legendFormat": "big cluster sizing" },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container=\"loki\", pod=~\"loki-backend-.*\", cluster_type=\"management_cluster\"}[$__rate_interval]))",
     "legendFormat": "actual usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{container=\"loki\", pod=~\"loki-backend-.*\", cluster_type=\"management_cluster\", resource=\"cpu\"})",
     "legendFormat": "reserved"
    }
   ]
  },
  {
   "title": "Backend Path RAM",
   "type": "timeseries",
   "description": "Compactor + Index Gateway + Query Scheduler + Ruler",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "(8+1+10)*1024*1024*1204 * $ratio_small",
     "legendFormat": "small cluster sizing"
    },
    {
     "expr": "(40+1+20)*1024*1024*1204 * $ratio_medium",
     "legendFormat": "medium cluster sizing"
    },
    {
     "expr": "(80+1+40)*1024*1024*1204 * $ratio_medium",
     "legendFormat": "big cluster sizing"
    },
    {
     "expr": "sum(container_memory_usage_bytes{container=\"loki\", pod=~\"loki-backend-.*\", cluster_type=\"management_cluster\"})",
     "legendFormat": "actual usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{container=\"loki\", pod=~\"loki-backend-.*\", cluster_type=\"management_cluster\", resource=\"memory\"})",
     "legendFormat": "reserved"
    }
   ]
  }
 ]
}