{
 "title": "Observability Resource Usage",
 "description": "Overview of resource usage for observability applications",
 "tags": [
  "owner:team-atlas",
  "topic:observability"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(capi_cluster_info,cluster_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Documentation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Observability resource usage",
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "This dashboard shows resource usage for observability-related apps.\n\nFor per-application details, you can have a look at more specific dashboards:\n- [Loki cost estimation](/d/loki-cost-estimation/loki-cost-estimation)\n- [Mimir cost estimation](/d/d37ffc71-9200-4f0b-8f9a-9e2af9f6b3232/mimir-cost-estimation)\n- [Alloy resources](/d/d6a8574c31f3d7cb8f1345ec84d15a67/alloy-resources)"
   }
  },
  {
   "title": "Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"loki|mimir|monitoring\", cluster_id=~\"$cluster\"}[$__rate_interval])) by (namespace, cluster_id)",
     "legendFormat": "{{namespace}} namespace on {{cluster_id}}"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"alloy.*\", cluster_id=~\"$cluster\"}[$__rate_interval])) by (cluster_id)",
     "legendFormat": "alloy {{cluster_id}}"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"promtail.*\", cluster_id=~\"$cluster\"}[$__rate_interval])) by (cluster_id)",
     "legendFormat": "promtail {{cluster_id}}"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"grafana-agent.*\", cluster_id=~\"$cluster\"}[$__rate_interval])) by (cluster_id)",
     "legendFormat": "grafana-agent {{cluster_id}}"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\".*prometheus-agent.*\", cluster_id=~\"$cluster\"}[$__rate_interval])) by (cluster_id)",
     "legendFormat": "prometheus-agent {{cluster_id}}"
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~\"loki|mimir|monitoring\", cluster_id=~\"$cluster\"}) by (namespace, cluster_id)",
     "legendFormat": "{{namespace}} namespace on {{cluster_id}}"
    },
    {
     "expr": "sum(container_memory_usage_bytes{pod=~\"alloy.*\", cluster_id=~\"$cluster\"}) by (cluster_id)",
     "legendFormat": "alloy on {{cluster_id}}"
    },
    {
     "expr": "sum(container_memory_usage_bytes{pod=~\"promtail.*\", cluster_id=~\"$cluster\"}) by (cluster_id)",
     "legendFormat": "promtail on {{cluster_id}}"
    },
    {
     "expr": "sum(container_memory_usage_bytes{pod=~\"grafana-agent.*\", cluster_id=~\"$cluster\"}) by (cluster_id)",
     "legendFormat": "grafana-agent on {{cluster_id}}"
    },
    {
     "expr": "sum(container_memory_usage_bytes{pod=~\".*prometheus-agent.*\", cluster_id=~\"$cluster\"}) by (cluster_id)",
     "legendFormat": "prometheus-agent on {{cluster_id}}"
    }
   ]
  },
  {
   "title": "Network usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=~\"loki|mimir|monitoring\", cluster_id=~\"$cluster\"}[$__rate_interval])) by (namespace, cluster_id)",
     "legendFormat": "{{namespace}} namespace on {{cluster_id}} - rx"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod=~\"alloy.*\", cluster_id=~\"$cluster\"}[$__rate_interval])) by (cluster_id)",
     "legendFormat": "alloy on {{cluster_id}} - rx"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod=~\"promtail.*\", cluster_id=~\"$cluster\"}[$__rate_interval])) by (cluster_id)",
     "legendFormat": "promtail on {{cluster_id}} - rx"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod=~\"grafana-agent.*\", cluster_id=~\"$cluster\"}[$__rate_interval])) by (cluster_id)",
     "legendFormat": "grafana-agent on {{cluster_id}} - rx"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod=~\".*prometheus-agent.*\", cluster_id=~\"$cluster\"}[$__rate_interval])) by (cluster_id)",
     "legendFormat": "prometheus-agent on {{cluster_id}} - rx"
    },
    {
     "expr": "-sum(rate(container_network_transmit_bytes_total{namespace=~\"loki|mimir|monitoring\", cluster_id=~\"$cluster\"}[$__rate_interval])) by (namespace, cluster_id)",
     "legendFormat": "{{namespace}} namespace on {{cluster_id}} - tx"
    },
    {
     "expr": "-sum(rate(container_network_transmit_bytes_total{pod=~\"alloy.*\", cluster_id=~\"$cluster\"}[$__rate_interval])) by (cluster_id)",
     "legendFormat": "alloy on {{cluster_id}} - tx"
    },
    {
     "expr": "-sum(rate(container_network_transmit_bytes_total{pod=~\"promtail.*\", cluster_id=~\"$cluster\"}[$__rate_interval])) by (cluster_id)",
     "legendFormat": "promtail on {{cluster_id}} - tx"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{pod=~\"grafana-agent.*\", cluster_id=~\"$cluster\"}[$__rate_interval])) by (cluster_id)",
     "legendFormat": "grafana-agent on {{cluster_id}} - tx"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{pod=~\".*prometheus-agent.*\", cluster_id=~\"$cluster\"}[$__rate_interval])) by (cluster_id)",
     "legendFormat": "prometheus-agent on {{cluster_id}} - tx"
    }
   ]
  }
 ]
}