{
 "title": "Alerts",
 "description": "Installation-wide information on alerts, inhibitions, and silences",
 "tags": [ "owner:team-atlas" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(ALERTS, cluster_id)"
    }
   },
   {
    "name": "organization",
    "label": "Organization",
    "query": {
     "query": "label_values(ALERTS{cluster_id=\"$cluster\"}, organization)"
    }
   }
  ]
 },
 "panels": [
  { "title": "  ", "type": "macropower-analytics-panel", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "About this dashboard",
   "type": "text",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 2 },
   "options": {
    "content": "This dashboard provides metrics about alerts, inhibitions, and silences on a cluster level (workload cluster or management cluster).\n\n**Alert:** An alert is created by Prometheus Alertmanager based on a set of rules. For example, when some metric exceeds a configured threshold.\n\nAlerts are defined in the [prometheus-rules](https://github.com/giantswarm/prometheus-rules) repository. To learn about a particular alert, you can search that repository for the alert name.\n\n**Inhibition:** An inhibition is a rule to prevent an alert from being created. At Giant Swarm we use this for example to avoid certain alerts from being created when a cluster is freshly created, as this would otherwise trigger pages to staff on call.\n\n**Silence:** A silence is another specific override rule to opress one or several alerts from firing. Silences are not cluster specific, but instead are effective for the entire installation."
   }
  },
  {
   "title": "Alerts by name",
   "type": "stat",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(prometheus_rule_group_rules{cluster_id=~\"$cluster\",organization=~\"$organization\",rule_group!~\".*;(cortex|helm-operations|labelling-schema|inhibit|service-level.*|.+\\\\.rules)$\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(prometheus_rule_group_rules{cluster_id=~\"$cluster\",organization=~\"$organization\",rule_group!~\".*;(cortex|helm-operations|labelling-schema|inhibit|service-level.*|.+\\\\.rules)$\"})-count(count(ALERTS{alertname!~\"^(Inhibition.*|Heartbeat|InvalidLabellingSchema)\",cluster_id=~\"$cluster\",organization=~\"$organization\"})by(alertname))",
     "legendFormat": "Inactive"
    },
    {
     "expr": "count(count(ALERTS{alertname!~\"^(Inhibition.*|Heartbeat|InvalidLabellingSchema)\",cluster_id=~\"$cluster\",organization=~\"$organization\"})by(alertname))",
     "legendFormat": "Active"
    },
    {
     "expr": "count(count(ALERTS{alertname=~\"^Inhibition.*\",cluster_id=~\"$cluster\",organization=~\"$organization\"})by(alertname))",
     "legendFormat": "Inhibitions"
    }
   ]
  },
  {
   "title": "Global silences",
   "type": "stat",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:alertmanager:silences_active_total)",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(aggregation:alertmanager:silences_expired_total)",
     "legendFormat": "Expired"
    },
    {
     "expr": "sum(aggregation:alertmanager:silences_pending_total)",
     "legendFormat": "Pending"
    }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Active alerts instances",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(ALERTS{alertname!~\"^(Inhibition.*|Heartbeat|InvalidLabellingSchema)\",cluster_id=~\"$cluster\",organization=~\"$organization\"})by(alertname)",
     "legendFormat": "{{cluster_id}}"
    }
   ]
  },
  {
   "title": "Inhibitions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(ALERTS{alertname=~\"^Inhibition.*\",cluster_id=~\"$cluster\",organization=~\"$organization\"}) by (alertname)",
     "legendFormat": "{{ alertname }}"
    }
   ]
  }
 ]
}