{
 "title": "CAPI overview",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster_name",
    "label": "cluster_name",
    "query": {
     "query": "label_values(capi_cluster_info,name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "# Clusters",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(capi_cluster_info)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Cluster conditions where not ready",
   "type": "table",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "count(capi_cluster_status_condition{status=~\"False|Unknown\"} == 1) by (type, name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of machines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "count(capi_machine_status_condition{type=\"Ready\",status=\"True\",name!~\".*bastion.*\"} == 1)",
     "legendFormat": "ready"
    },
    {
     "expr": "count(capi_machine_status_condition{type!=\"Ready\",status=~\"False|Unknown\",name!~\".*bastion.*\"} == 1) * -1",
     "legendFormat": "not ready"
    }
   ]
  },
  {
   "title": "Control Plane",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "kubeadm control plane where conditions not ready",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "count(capi_kubeadmcontrolplane_status_condition{status=~\"False|Unknown\"} == 1) by (type, name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Control Plane Nodes by version for ${cluster_name}",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
     "repeat": "cluster_name",
     "targets": [
      {
       "expr": "count(capi_machine_info{control_plane_name!=\"\",cluster_name=\"${cluster_name:string}\"}) by (version)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Worker Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "machine deployments where conditions not ready",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "count(capi_machinedeployment_status_condition{status=~\"False|Unknown\"} == 1) by (type, name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Worker Nodes by version for ${cluster_name}",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 24 },
   "repeat": "cluster_name",
   "targets": [
    {
     "expr": "count(capi_machine_info{control_plane_name=\"\",cluster_name=\"${cluster_name:string}\"}) by (version)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}