{
 "title": "DNS",
 "tags": [ "owner:team-phoenix" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "organization",
    "label": "Organization",
    "query": {
     "query": "label_values(kubernetes_build_info{}, organization)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kubernetes_build_info{organization=\"$organization\"}, cluster_id)"
    }
   },
   {
    "name": "zone",
    "label": "DNS zone",
    "query": {
     "query": "label_values(coredns_dns_requests_total,zone)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "DNS Request Rate in zone ${zone}",
   "type": "graph",
   "description": "Rate of requests made to CoreDNS.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by(app) (rate(coredns_dns_request_duration_seconds_count{cluster_id=\"$cluster\", organization=\"$organization\", zone!=\"dropped\",zone=\"$zone\"}[5m]))",
     "legendFormat": "{{ app }}"
    }
   ]
  },
  {
   "title": "DNS Response Rate By Code in zone ${zone}",
   "type": "graph",
   "description": "Rate of responses returned by CoreDNS, broken down by response code.\n\nWe expect some degree of `NXDOMAIN` responses.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate({__name__=~\"coredns_dns_response_rcode_count_total|coredns_dns_responses_total\", cluster_id=\"$cluster\", organization=\"$organization\", zone=\"$zone\"}[5m])) by (rcode)",
     "legendFormat": "{{ rcode }}"
    }
   ]
  },
  {
   "title": "Latency - overall",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "DNS Request Latency Percentiles (logarithmic) zone ${zone}",
   "type": "timeseries",
   "description": "- Mean is defined here as the sum of all samples (latency durations), divided by the number of samples.\n- 50th percentile is the value under which 50% of samples fall (equivalent to the median).\n- 95th percentile is the value under which 95% of samples fall.\n\n\n- Lower latencies are, on the whole, better.\n- If the mean is equal or close to the 50th percentile, we have a symmetrical distribution (a bell curve).\n- If the mean is lower than the 50th percentile, the distribution is skewed to the left, or negatively skewed.\n- If the mean is greater than the 50th percentile, the distribution is skewed to the right, or positively skewed.\n\n\n- We expect the 50th percentile to be lower than the mean (positively skewed), as most requests execute quickly.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(irate(coredns_dns_request_duration_seconds_sum{cluster_id=\"$cluster\", organization=\"$organization\",zone=\"$zone\"}[5m])) / sum(irate(coredns_dns_request_duration_seconds_count{cluster_id=\"$cluster\", organization=\"$organization\",zone=\"$zone\"}[5m]))",
     "legendFormat": "Mean"
    },
    {
     "expr": "histogram_quantile(0.5, sum(irate(coredns_dns_request_duration_seconds_bucket{cluster_id=\"$cluster\", organization=\"$organization\",zone=\"$zone\"}[5m])) by (le))",
     "legendFormat": "50th percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(coredns_dns_request_duration_seconds_bucket{cluster_id=\"$cluster\", organization=\"$organization\",zone=\"$zone\"}[5m])) by (le))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(coredns_dns_request_duration_seconds_bucket{cluster_id=\"$cluster\", organization=\"$organization\",zone=\"$zone\"}[5m])) by (le))",
     "legendFormat": "99th percentile"
    }
   ]
  },
  {
   "title": "DNS Request Latency By Percentage of Cumulative Bucket zone ${zone}",
   "type": "heatmap",
   "description": "For each cumulative bucket exposed by CoreDNS, the percentage of requests that take less than that amount of time to complete.\n\nE.g:\n- 0.001s = 95% means that 95% of requests took less than 0.001s to complete.\n- 0.128s = 99.9% means that 99.9% of requests took less than 0.128s to complete.\n\nAs buckets are cumulative, buckets for higher latencies (e.g: 0.128 is higher than 0.001s) include the values of the smaller lower latencies.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(irate(coredns_dns_request_duration_seconds_bucket{cluster_id=\"$cluster\", organization=\"$organization\", le!=\"+Inf\",zone=\"$zone\"}[5m])) by (le) / ignoring (le) group_left sum(irate(coredns_dns_request_duration_seconds_count{cluster_id=\"$cluster\", organization=\"$organization\", le!=\"+Inf\",zone=\"$zone\"}[5m]))",
     "legendFormat": "{{ le }}s"
    }
   ]
  },
  { "title": "Latency - upstream coreDNS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "DNS Request Latency Percentiles (logarithmic) zone ${zone}",
   "type": "timeseries",
   "description": "- Mean is defined here as the sum of all samples (latency durations), divided by the number of samples.\n- 50th percentile is the value under which 50% of samples fall (equivalent to the median).\n- 95th percentile is the value under which 95% of samples fall.\n\n\n- Lower latencies are, on the whole, better.\n- If the mean is equal or close to the 50th percentile, we have a symmetrical distribution (a bell curve).\n- If the mean is lower than the 50th percentile, the distribution is skewed to the left, or negatively skewed.\n- If the mean is greater than the 50th percentile, the distribution is skewed to the right, or positively skewed.\n\n\n- We expect the 50th percentile to be lower than the mean (positively skewed), as most requests execute quickly.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(irate(coredns_dns_request_duration_seconds_sum{cluster_id=\"$cluster\", organization=\"$organization\",app=\"coredns\",zone=\"$zone\"}[5m])) / sum(irate(coredns_dns_request_duration_seconds_count{cluster_id=\"$cluster\", organization=\"$organization\",app=\"coredns\",zone=\"$zone\"}[5m]))",
     "legendFormat": "Mean"
    },
    {
     "expr": "histogram_quantile(0.5, sum(irate(coredns_dns_request_duration_seconds_bucket{cluster_id=\"$cluster\", organization=\"$organization\",app=\"coredns\",zone=\"$zone\"}[5m])) by (le))",
     "legendFormat": "50th percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(coredns_dns_request_duration_seconds_bucket{cluster_id=\"$cluster\", organization=\"$organization\",app=\"coredns\",zone=\"$zone\"}[5m])) by (le))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(coredns_dns_request_duration_seconds_bucket{cluster_id=\"$cluster\", organization=\"$organization\",app=\"coredns\",zone=\"$zone\"}[5m])) by (le))",
     "legendFormat": "99th percentile"
    }
   ]
  },
  {
   "title": "DNS Request Latency By Percentage of Cumulative Bucket zone ${zone}",
   "type": "heatmap",
   "description": "For each cumulative bucket exposed by CoreDNS, the percentage of requests that take less than that amount of time to complete.\n\nE.g:\n- 0.001s = 95% means that 95% of requests took less than 0.001s to complete.\n- 0.128s = 99.9% means that 99.9% of requests took less than 0.128s to complete.\n\nAs buckets are cumulative, buckets for higher latencies (e.g: 0.128 is higher than 0.001s) include the values of the smaller lower latencies.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum(irate(coredns_dns_request_duration_seconds_bucket{cluster_id=\"$cluster\", organization=\"$organization\", le!=\"+Inf\",app=\"coredns\",zone=\"$zone\"}[5m])) by (le) / ignoring (le) group_left sum(irate(coredns_dns_request_duration_seconds_count{cluster_id=\"$cluster\", organization=\"$organization\", le!=\"+Inf\",app=\"coredns\",zone=\"$zone\"}[5m]))",
     "legendFormat": "{{ le }}s"
    }
   ]
  },
  { "title": "Latency - node-local DNS cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "DNS Request Latency Percentiles (logarithmic) zone ${zone}",
   "type": "timeseries",
   "description": "- Mean is defined here as the sum of all samples (latency durations), divided by the number of samples.\n- 50th percentile is the value under which 50% of samples fall (equivalent to the median).\n- 95th percentile is the value under which 95% of samples fall.\n\n\n- Lower latencies are, on the whole, better.\n- If the mean is equal or close to the 50th percentile, we have a symmetrical distribution (a bell curve).\n- If the mean is lower than the 50th percentile, the distribution is skewed to the left, or negatively skewed.\n- If the mean is greater than the 50th percentile, the distribution is skewed to the right, or positively skewed.\n\n\n- We expect the 50th percentile to be lower than the mean (positively skewed), as most requests execute quickly.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(irate(coredns_dns_request_duration_seconds_sum{cluster_id=\"$cluster\", organization=\"$organization\",app=\"k8s-dns-node-cache\",zone=\"$zone\"}[5m])) / sum(irate(coredns_dns_request_duration_seconds_count{cluster_id=\"$cluster\", organization=\"$organization\",app=\"k8s-dns-node-cache\",zone=\"$zone\"}[5m]))",
     "legendFormat": "Mean"
    },
    {
     "expr": "histogram_quantile(0.5, sum(irate(coredns_dns_request_duration_seconds_bucket{cluster_id=\"$cluster\", organization=\"$organization\",app=\"k8s-dns-node-cache\",zone=\"$zone\"}[5m])) by (le))",
     "legendFormat": "50th percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(coredns_dns_request_duration_seconds_bucket{cluster_id=\"$cluster\", organization=\"$organization\",app=\"k8s-dns-node-cache\",zone=\"$zone\"}[5m])) by (le))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(coredns_dns_request_duration_seconds_bucket{cluster_id=\"$cluster\", organization=\"$organization\",app=\"k8s-dns-node-cache\",zone=\"$zone\"}[5m])) by (le))",
     "legendFormat": "99th percentile"
    }
   ]
  },
  {
   "title": "DNS Request Latency By Percentage of Cumulative Bucket zone ${zone}",
   "type": "heatmap",
   "description": "For each cumulative bucket exposed by CoreDNS, the percentage of requests that take less than that amount of time to complete.\n\nE.g:\n- 0.001s = 95% means that 95% of requests took less than 0.001s to complete.\n- 0.128s = 99.9% means that 99.9% of requests took less than 0.128s to complete.\n\nAs buckets are cumulative, buckets for higher latencies (e.g: 0.128 is higher than 0.001s) include the values of the smaller lower latencies.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum(irate(coredns_dns_request_duration_seconds_bucket{cluster_id=\"$cluster\", organization=\"$organization\", le!=\"+Inf\",app=\"k8s-dns-node-cache\",zone=\"$zone\"}[5m])) by (le) / ignoring (le) group_left sum(irate(coredns_dns_request_duration_seconds_count{cluster_id=\"$cluster\", organization=\"$organization\", le!=\"+Inf\",app=\"k8s-dns-node-cache\",zone=\"$zone\"}[5m]))",
     "legendFormat": "{{ le }}s"
    }
   ]
  },
  {
   "title": "Resources - upstream coreDNS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CoreDNS Pod CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=\"coredns\", cluster_id=\"$cluster\", organization=\"$organization\"}[5m])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "CoreDNS Pod Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{app=\"coredns\", cluster_id=\"$cluster\", organization=\"$organization\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Resources - node-local DNS cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node-local DNS cache Pod CPU Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{container=\"node-cache\", cluster_id=\"$cluster\", organization=\"$organization\"}[5m])",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Node-local DNS cache Pod Memory Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_alloc_bytes{app=\"k8s-dns-node-cache\", cluster_id=\"$cluster\", organization=\"$organization\"}",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "% difference of requests handled compared to expected rate",
     "type": "timeseries",
     "description": "Ideally the lines on this chart should always be around 0. If they are not, it means DNS requests load is not spread evenly across the CoreDNS replicas running in the cluster. Please be aware that this chart is more accurate when the number of DNS queries is higher.",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 54 },
     "targets": [
      {
       "expr": "(sum by (pod) (rate(coredns_dns_requests_total{app=\"coredns\",cluster_id=\"$cluster\", organization=\"$organization\"}[5m])) / ignoring (pod) group_left sum(rate(coredns_dns_requests_total{app=\"coredns\",cluster_id=\"$cluster\", organization=\"$organization\"}[5m])) * 100) - ignoring (pod) group_left 100 / sum(kube_deployment_status_replicas{deployment=~\"coredns-workers|coredns-controlplane\",cluster_id=\"$cluster\", organization=\"$organization\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  { "title": "Latency per-node breakdown", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "99th percentile DNS resolution time by node - overall (logarithmic) zone ${zone}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(irate(coredns_dns_request_duration_seconds_bucket{cluster_id=\"$cluster\", organization=\"$organization\",zone=\"$zone\"}[5m])) by (le,node))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "99th percentile DNS resolution time by node - upstrem coredns (logarithmic) zone ${zone}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(irate(coredns_dns_request_duration_seconds_bucket{cluster_id=\"$cluster\", organization=\"$organization\", app=\"coredns\",zone=\"$zone\"}[5m])) by (le,node))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "99th percentile DNS resolution time by node - node-local DNS cache (logarithmic) zone ${zone}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(irate(coredns_dns_request_duration_seconds_bucket{cluster_id=\"$cluster\", organization=\"$organization\", app=\"k8s-dns-node-cache\",zone=\"$zone\"}[5m])) by (le,node))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 } },
  {
   "title": "CoreDNS hits and miss ratios",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
   "targets": [
    {
     "expr": "sum(rate(coredns_cache_hits_total{cluster_id=\"$cluster\", organization=\"$organization\", app=\"coredns\", type=\"success\"}[5m])) / sum(rate(coredns_cache_requests_total{cluster_id=\"$cluster\", organization=\"$organization\", app=\"coredns\"}[5m]))",
     "legendFormat": "hits ratio: success"
    },
    {
     "expr": "sum(rate(coredns_cache_hits_total{cluster_id=\"$cluster\", organization=\"$organization\", app=\"coredns\", type=\"denial\"}[5m])) / sum(rate(coredns_cache_requests_total{cluster_id=\"$cluster\", organization=\"$organization\", app=\"coredns\"}[5m]))",
     "legendFormat": "hits ratio: denial"
    },
    {
     "expr": "1 - (sum(rate(coredns_cache_hits_total{cluster_id=\"$cluster\", organization=\"$organization\", app=\"coredns\"}[5m])) / sum(rate(coredns_cache_requests_total{cluster_id=\"$cluster\", organization=\"$organization\", app=\"coredns\"}[5m])))",
     "legendFormat": "miss"
    }
   ]
  },
  {
   "title": "NodeLocal hits and miss ratios",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 94 },
   "targets": [
    {
     "expr": "sum(rate(coredns_cache_hits_total{cluster_id=\"$cluster\", organization=\"$organization\", app=\"k8s-dns-node-cache\", type=\"success\"}[5m])) / sum(rate(coredns_cache_requests_total{cluster_id=\"$cluster\", organization=\"$organization\", app=\"k8s-dns-node-cache\"}[5m]))",
     "legendFormat": "hits ratio: success"
    },
    {
     "expr": "sum(rate(coredns_cache_hits_total{cluster_id=\"$cluster\", organization=\"$organization\", app=\"k8s-dns-node-cache\", type=\"denial\"}[5m])) / sum(rate(coredns_cache_requests_total{cluster_id=\"$cluster\", organization=\"$organization\", app=\"k8s-dns-node-cache\"}[5m]))",
     "legendFormat": "hits ratio: denial"
    },
    {
     "expr": "1 - (sum(rate(coredns_cache_hits_total{cluster_id=\"$cluster\", organization=\"$organization\", app=\"k8s-dns-node-cache\"}[5m])) / sum(rate(coredns_cache_requests_total{cluster_id=\"$cluster\", organization=\"$organization\", app=\"k8s-dns-node-cache\"}[5m])))",
     "legendFormat": "miss"
    }
   ]
  },
  {
   "title": "Prefetch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 102 },
   "targets": [
    {
     "expr": "sum by (app) (rate(coredns_cache_prefetch_total{cluster_id=\"$cluster\", organization=\"$organization\", zones=\"$zone\"}[5m]))",
     "legendFormat": "{{ app }}"
    }
   ]
  }
 ]
}