{
 "title": "Kong Connection Distribution",
 "tags": [
  "kong",
  "topic:workload-cluster",
  "owner:team-cabbage"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kong_datastore_reachable,cluster_id)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kong_datastore_reachable{cluster_id=~\"$cluster\"},namespace)"
    }
   },
   {
    "name": "proxy",
    "label": "Proxy",
    "query": {
     "query": "label_values(kong_datastore_reachable{cluster_id=~\"$cluster\", namespace=~\"$namespace\"},service)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kong_datastore_reachable{cluster_id=~\"$cluster\",namespace=~\"$namespace\",service=~\"$proxy\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Active Connections by Pod",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kong_nginx_http_current_connections{cluster_id=\"$cluster\",namespace=~\"$namespace\",service=~\"$proxy\",pod=~\"$pod\",state=\"active\"} or kong_nginx_connections_total{cluster_id=\"$cluster\",namespace=~\"$namespace\",service=~\"$proxy\",pod=~\"$pod\",state=\"active\"}"
    }
   ]
  },
  {
   "title": "Active Connections by Node",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by (node) (kong_nginx_http_current_connections{cluster_id=\"$cluster\",namespace=~\"$namespace\",service=~\"$proxy\",pod=~\"$pod\",state=\"active\"} or kong_nginx_connections_total{cluster_id=\"$cluster\",namespace=~\"$namespace\",service=~\"$proxy\",pod=~\"$pod\",state=\"active\"})"
    }
   ]
  },
  {
   "title": "Active Connections by Zone",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum by (zone) (kong_nginx_http_current_connections{cluster_id=\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",state=\"active\"} * on (node) group_left(zone) (group by (node, zone) (kube_node_labels{cluster_id=\"$cluster\"})))"
    }
   ]
  }
 ]
}