{
 "title": "Kong ingress controller",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(ingress_controller_configuration_push_duration_milliseconds_bucket, cluster_id)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(ingress_controller_configuration_push_duration_milliseconds_bucket{cluster_id=\"$cluster\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "  ", "type": "macropower-analytics-panel", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Configuration push duration (ms)",
   "type": "histogram",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "ingress_controller_configuration_push_duration_milliseconds_bucket{cluster_id=\"$cluster\", namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Successful configuration pushes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ingress_controller_configuration_push_count{success=\"true\",cluster_id=\"$cluster\", namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Failed configuration pushes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (failure_reason) (ingress_controller_configuration_push_count{success=\"false\", cluster_id=\"$cluster\", namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Successful configuration translations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ingress_controller_translation_count{success=\"true\", cluster_id=\"$cluster\", namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Failed configuration translations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ingress_controller_translation_count{success=\"false\"}"
    }
   ]
  }
 ]
}