{
 "title": "Prometheus",
 "tags": [
  "owner:team-atlas",
  "topic:management-cluster",
  "topic:workload-cluster"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{container=\"prometheus\",cluster_type=~\"management_cluster\", pod=~\".*prometheus.*\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pronmetheus logs",
     "type": "logs",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "{app=\"prometheus\", instance=~\"$cluster\"}"
      }
     ]
    }
   ]
  },
  { "title": "Prometheus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Rate of Samples Appended",
   "type": "timeseries",
   "description": "5 minute rate of samples appended",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_samples_appended_total{type!=\"histogram\", cluster_id=~\"($cluster)\"}[5m])",
     "legendFormat": "{{cluster_id}}"
    }
   ]
  },
  {
   "title": "Total Series",
   "type": "stat",
   "description": "Total number of time series in prometheus",
   "gridPos": { "h": 7, "w": 4, "x": 13, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(prometheus_tsdb_head_series{cluster_id=~\"($cluster)\"}) by (cluster_id))",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "stat",
   "description": "Number of restarts during the current time range",
   "gridPos": { "h": 7, "w": 3, "x": 17, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(max(increase(kube_pod_container_status_restarts_total{container=\"prometheus\", pod=~\"prometheus-($cluster)-[0-9]+\", cluster_type=~\"management_cluster\"}[$__range]) > 0) by (pod))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod age",
   "type": "stat",
   "description": "Number of restarts during the current time range",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max(kube_pod_start_time{pod=~\"prometheus-($cluster)-0\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Rule Evaluation Duration",
   "type": "timeseries",
   "description": "Time take for rule evaluation",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "prometheus_rule_evaluation_duration_seconds{app=\"prometheus\",quantile=\"0.99\", cluster_id=~\"($cluster)\"}",
     "legendFormat": "{{cluster_id}} - 0.99 quantile"
    },
    {
     "expr": "prometheus_rule_evaluation_duration_seconds{app=\"prometheus\",quantile=\"0.9\", cluster_id=~\"($cluster)\"}",
     "legendFormat": "{{cluster_id}} - 0.9 quantile"
    },
    {
     "expr": "prometheus_rule_evaluation_duration_seconds{app=\"prometheus\",quantile=\"0.5\", cluster_id=~\"($cluster)\"}",
     "legendFormat": "{{cluster_id}} - 0.5 quantile"
    }
   ]
  },
  {
   "title": "Notification Latency",
   "type": "timeseries",
   "description": "TIme taken to send notifications",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "prometheus_notifications_latency_seconds{app=\"prometheus\",quantile=\"0.99\", cluster_id=~\"($cluster)\"}",
     "legendFormat": "{{cluster_id}} - 0.99 quantile"
    },
    {
     "expr": "prometheus_notifications_latency_seconds{app=\"prometheus\",quantile=\"0.9\", cluster_id=~\"($cluster)\"}",
     "legendFormat": "{{cluster_id}} - 0.9 quantile"
    },
    {
     "expr": "prometheus_notifications_latency_seconds{app=\"prometheus\",quantile=\"0.5\", cluster_id=~\"($cluster)\"}",
     "legendFormat": "{{cluster_id}} - 0.5 quantile"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Memory working/usage",
   "type": "timeseries",
   "description": "Memory usage by Prometheus instances.\n\nDashed lines show pod limit and node capacity.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(\n    container_memory_working_set_bytes{container=\"prometheus\", pod=~\"prometheus-($cluster).*\", cluster_type=~\"management_cluster\"}\n    ) by (container, pod, cluster_type)",
     "legendFormat": "working {{ pod }}"
    },
    {
     "expr": "max(\n    container_memory_usage_bytes{container=\"prometheus\", pod=~\"prometheus-($cluster).*\", cluster_type=~\"management_cluster\"}\n) by (container, pod, cluster_type)\n",
     "legendFormat": "used {{pod}}"
    },
    {
     "expr": "max(\n    kube_pod_container_resource_limits{container=\"prometheus\",resource=\"memory\", unit=\"byte\", pod=~\"prometheus-($cluster).*\", cluster_type=~\"management_cluster\"}\n) by (container, pod, cluster_type)",
     "legendFormat": "limit {{ pod }}"
    },
    {
     "expr": "max (node_memory_MemTotal_bytes{node=~\".+\"} * on (node) group_right(pod) (kube_pod_info{pod=~\"prometheus-.*-0\",cluster_type=\"management_cluster\", namespace=~\"($cluster)-prometheus\"})) by (namespace)",
     "legendFormat": "node memory - {{ namespace }}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "description": "CPU usage by Prometheus instances.\n\nDashed lines show pod limit and node capacity.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"prometheus\", pod=~\"prometheus-($cluster)-.*\", cluster_type=~\"management_cluster\"}[3m])) by (pod)",
     "legendFormat": "used {{pod}}"
    },
    {
     "expr": "max(\n    kube_pod_container_resource_limits{container=\"prometheus\",resource=\"cpu\", unit=\"core\", pod=~\"prometheus-($cluster)-.*\", cluster_type=~\"management_cluster\"}\n) by (container, pod, cluster_type)",
     "legendFormat": "limit {{pod}}"
    },
    {
     "expr": "max(node:node_num_cpu:sum{node=~\".+\"} * on (node) group_right(pod) (topk(1, kube_pod_info{pod=~\"prometheus-.*-0\"}))) by (namespace)",
     "legendFormat": "node cpu - {{ namespace }}"
    }
   ]
  },
  {
   "title": "CPU throttling %",
   "type": "timeseries",
   "description": "CPU throttling percentage\n\nHow much CPU had to be throttled down by CFS scheduler. No worries as long as youre <100%.",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_cfs_throttled_seconds_total{pod=~\"prometheus-($cluster)-0\", container=\"prometheus\"}[$__rate_interval])) by (pod, container)\n/\nsum(irate(container_cpu_usage_seconds_total{pod=~\"prometheus-($cluster)-0\", container=\"prometheus\"}[$__rate_interval])) by (pod,container)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Persistent Volume Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max (\n    (\n        kubelet_volume_stats_capacity_bytes{cluster_type=~\"management_cluster\", app=\"kubelet\", persistentvolumeclaim=~\"prometheus-($cluster)-db-prometheus-($cluster)-.*\"}\n        - \n        kubelet_volume_stats_available_bytes{cluster_type=~\"management_cluster\", app=\"kubelet\", persistentvolumeclaim=~\"prometheus-($cluster)-db-prometheus-($cluster)-.*\"}\n    )\n    / kubelet_volume_stats_capacity_bytes{cluster_type=~\"management_cluster\", app=\"kubelet\", persistentvolumeclaim=~\"prometheus-($cluster)-db-prometheus-($cluster)-.*\"}\n    * 100\n) by (persistentvolumeclaim)",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Scraping info (⚠️ heavy metrics)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Samples scraped",
     "type": "stat",
     "description": "Number of samples scraped by app / job.\n\nShows which jobs scrape the most data.\n\nMetric: `scrape_samples_scraped`",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 45 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(10, sum(scrape_samples_scraped) by (app, job, cluster_id))",
       "legendFormat": "{{app}} | {{job}} | {{cluster_id}}"
      }
     ]
    },
    {
     "title": "Top metrics",
     "type": "stat",
     "description": "Top number metrics and associated job.\n\nShows which metrics have the highest instant cardinality.",
     "gridPos": { "h": 12, "w": 8, "x": 8, "y": 45 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(10, count by (__name__, job, cluster_id)({__name__=~\".+\"}))",
       "legendFormat": "{{__name__}} | {{job}} | {{cluster_id}}"
      }
     ]
    },
    {
     "title": "Top churning jobs",
     "type": "stat",
     "description": "Top number of metrics per job.\n\nShows which metrics add new labels, increasing cardinality over time.\n\nMetric: `scrape_series_added`",
     "gridPos": { "h": 12, "w": 8, "x": 16, "y": 45 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(10, max_over_time(scrape_series_added[5m]))",
       "legendFormat": "{{job}} | {{app}} | {{cluster_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Rules info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rules evaluation duration",
     "type": "stat",
     "description": "Duration of rules evaluation per group / cluster.\n\nShows which ones use most CPU.",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 58 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(10, prometheus_rule_group_last_duration_seconds)",
       "legendFormat": "{{rule_group}} | {{cluster_id}}"
      }
     ]
    }
   ]
  }
 ]
}