{
 "title": "Webhook Health",
 "tags": [ "team:phoenix" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Percentage of webhooks with PBDs",
   "type": "gauge",
   "description": "Shows the percentage of webhooks with a pod disruption budget. Ideally it should be 100%",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "webhook_exporter_webhooks_pod_disruption_budget"
    }
   ]
  },
  {
   "title": "Percentage of webhooks with valid namespace selectors",
   "type": "gauge",
   "description": "A metric showing the percentage of webhooks that a valid namespace selector. That is webhooks that follow the following rules:\n namespaceSelector:\n\t matchExpressions:\n\t\t - key: name\n\t\t   operator: NotIn\n\t\t    values: [\"kube-system\", \"giantswarm\"]\n\t\t\t   ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "webhook_exporter_webhooks_valid_namespace_selectors"
    }
   ]
  },
  {
   "title": "All Webhooks without PDB",
   "type": "table",
   "description": "List of webhooks whose pods don't have a PDB set. In an ideal scenario, this table should be empty",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "webhook_exporter_webhooks_pod_disruption_budget == 0"
    }
   ]
  },
  {
   "title": "Customer Webhooks without PDB",
   "type": "table",
   "description": "List of webhooks not in the giantswarm namespace whose pods don't have a PDB set. In an ideal scenario, this table should be empty",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "webhook_exporter_webhooks_pod_disruption_budget == 0"
    }
   ]
  },
  {
   "title": "Webhooks without valid namespace selectors",
   "type": "table",
   "description": "List of webhooks that have a valid namespace selector. That is webhooks that follow the following rules:\n     namespaceSelector:\n\t matchExpressions:\n\t\t - key: name\n\t\t   operator: NotIn\n\t\t    values: [\"kube-system\", \"giantswarm\"]\n\t\t\t  ",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "webhook_exporter_webhooks_valid_namespace_selectors == 0"
    }
   ]
  },
  {
   "title": "Customer Webhooks without valid namespace selectors",
   "type": "table",
   "description": "List of webhooks that aren't in the giantswarm namespace that have a valid namespace selector. That is webhooks that follow the following rules:\n     namespaceSelector:\n\t matchExpressions:\n\t\t - key: name\n\t\t   operator: NotIn\n\t\t    values: [\"kube-system\", \"giantswarm\"]\n\t\t\t  ",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "webhook_exporter_webhooks_valid_namespace_selectors == 0"
    }
   ]
  },
  {
   "title": "Mutating webhooks - Backend replicas",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "min(webhook_exporter_webhooks_replicas{webhook_type=\"mutating\"}) by (webhook)",
     "legendFormat": "{{ webhook }}"
    }
   ]
  },
  {
   "title": "Validating webhooks - Backend replicas",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "min(webhook_exporter_webhooks_replicas{webhook_type=\"validating\"}) by (webhook)",
     "legendFormat": "{{ webhook }}"
    }
   ]
  }
 ]
}