{
 "title": "Observability Platform: Cost Estimate",
 "tags": [ "owner:team-atlas" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pods",
    "query": "mimir-.*,\nloki-.*,\ngrafana-.*,\nalertmanager-.*,\nalloy-.*,\nprometheus-.*,\nmetrics-server-.*,\noauth2-proxy-.*,\nobservability-operator-.*,\nsilence-operator-.*,\nsloth-.*,"
   }
  ]
 },
 "panels": [
  {
   "title": "Basic Resource Usage of Observability Platform Components",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "description": "Number of average RAM used in $range",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(\nsum(max(container_memory_usage_bytes{pod=~\"${pods:raw}\", cluster_type=~\"management_cluster\", container!=\"\", image!=\"\"}) by(pod,container))\n[$__range:])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "description": "Number of average CPU Cores in use in $range",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(\nsum(sum(rate(container_cpu_usage_seconds_total{pod=~\"${pods:raw}\", cluster_type=~\"management_cluster\"}[5m])) by (pod))\n[$__range:])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network IN",
   "type": "stat",
   "description": "Incoming network traffic",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(\nsum(irate(container_network_receive_bytes_total{pod=~\"${pods:raw}\"}[5m]))\n[$__range:])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Out",
   "type": "stat",
   "description": "Outgoing network traffic",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(\nsum(irate(container_network_transmit_bytes_total{pod=~\"${pods:raw}\"}[$__rate_interval]))[$__range:])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "options": {
    "content": "# Cost Calculation \n\nWith the above numbers you can create a cost estimate by using the [AWS price calculator](https://calculator.aws/#/).\n\nThe general idea is to get a rough estimate how much the resources cost that are needed to run all the components of the observability platform. \n\nThe above numbers already include the typical replication of the components for their resiliency, so no need to add any overhead for this.\n\nThe machines our typical CAPA installations use is: **r6i.2xlarge**\n\n"
   }
  },
  {
   "title": "Additional Interesting Numbers for Comparisons",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 }
  },
  {
   "title": "Amount of Log Lines received by Loki over $range",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(loki_distributor_lines_received_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Amount of Bytes received by Loki over $range",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(loki_distributor_bytes_received_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes stored by Loki ingesters in S3 over $range",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (increase(loki_ingester_chunk_stored_bytes_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Metric Time Series in Mimir Ingesters",
   "type": "stat",
   "description": "Average number of time series in mimirs ingesters  over $range",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(\n    sum(cortex_ingester_active_series{cluster_type=~\"management_cluster\"})\n[$__range:])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average amount of nodes in cluster type over $range",
   "type": "stat",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(\nsum by(cluster_type)(kube_node_info)\n[$__range:])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}