{
 "title": "AWS ENA Network Performance",
 "description": "A dashbaord for monitoring AWS Elastic Network Adapter performance using the Prometheus Node exporter.",
 "tags": [
  "provider:aws",
  "owner:team-phoenix"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "device",
    "label": "Interface",
    "query": {
     "query": "label_values(node_ethtool_info{driver=\"ena\"}, device)"
    }
   },
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(cluster_id)" } }
  ]
 },
 "panels": [
  {
   "title": "Exceeded max amount of packets per second",
   "type": "timeseries",
   "description": "The number of packets queued or dropped because the inbound aggregate bandwidth exceeded the maximum for the instance.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(node_ethtool_pps_allowance_exceeded{cluster_id=~\"$cluster\"}[5m])) by (node, device)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exceeded DNS, NTP, METADATA network calls",
   "type": "timeseries",
   "description": "The number of packets dropped because the PPS of the traffic to local proxy services exceeded the maximum for the network interface. This impacts traffic to the DNS service, the Instance Metadata Service, and the Amazon Time Sync Service.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(node_ethtool_linklocal_allowance_exceeded{cluster_id=~\"$cluster\"}[5m])) by (node, device)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exceeded Incoming Bandwidth",
   "type": "timeseries",
   "description": "The number of packets queued or dropped because the inbound aggregate bandwidth exceeded the maximum for the instance.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(node_ethtool_bw_in_allowance_exceeded{cluster_id=~\"$cluster\"}[5m])) by (node, device)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exceeded outgoing bandwidth",
   "type": "timeseries",
   "description": "The number of packets queued or dropped because the outbound aggregate bandwidth exceeded the maximum for the instance.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(node_ethtool_bw_out_allowance_exceeded{cluster_id=~\"$cluster\"}[5m])) by (node, device)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exceeded TCP Conntrack allowance (Nitro-based instance types only)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum(rate(node_ethtool_conntrack_allowance_exceeded{cluster_id=~\"$cluster\"}[5m])) by (node, device)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Established Connections",
   "type": "timeseries",
   "description": "The total number of established TCP connections.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{cluster_id=~\"$cluster\"}",
     "legendFormat": "{{ node }} - connections"
    }
   ]
  }
 ]
}