exclusions:
  target-instance-rule:
    reason: We are not using it.
  target-job-rule:
    reason: We are not using it.
  template-instance-rule:
    reason: We are not using it.
  template-job-rule:
    reason: We are not using it.
  target-rate-interval-rule:
    reason: We are not using it.
  panel-units-rule:
    reason: We are not using it even though we should.
  panel-title-description-rule:
    reason: We are not using it even though we should.
  template-on-time-change-reload-rule:
    reason: We are not using it.
