{
 "title": "Kubernetes / Kube Proxy",
 "tags": [
  "owner:team-rocket",
  "owner:team-phoenix",
  "provider:aws",
  "provider:azure"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(rest_client_requests_total{container=\"kube-proxy\"}, pod)"
    }
   },
   {
    "name": "cluster_id",
    "query": {
     "query": "label_values(process_cpu_seconds_total{container=\"kube-proxy\"}, cluster_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Up",
   "type": "stat",
   "description": "How many instances are up",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "sum(up{container=\"kube-proxy\"})"
    }
   ]
  },
  {
   "title": "Rules Sync Rate",
   "type": "timeseries",
   "description": "The rate of proxy rules synced by second",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kubeproxy_sync_proxy_rules_duration_seconds_count{container=\"kube-proxy\", cluster_id=\"$cluster_id\", pod=~\"$instance\"}[5m]))",
     "legendFormat": "rate"
    }
   ]
  },
  {
   "title": "Rule Sync Latency 99th Quantile",
   "type": "timeseries",
   "description": "The 99th percentile of proxy rules synced",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99,rate(kubeproxy_sync_proxy_rules_duration_seconds_bucket{container=\"kube-proxy\",cluster_id=\"$cluster_id\",pod=~\"$instance\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network Programming Rate",
   "type": "timeseries",
   "description": "The number of operations per second compute by the proxy",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kubeproxy_network_programming_duration_seconds_count{container=\"kube-proxy\", cluster_id=\"$cluster_id\",pod=~\"$instance\"}[5m]))",
     "legendFormat": "rate"
    }
   ]
  },
  {
   "title": "Network Programming Latency 99th Quantile",
   "type": "timeseries",
   "description": "The 99th percentile of proxy operation duration",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(kubeproxy_network_programming_duration_seconds_bucket{container=\"kube-proxy\", cluster_id=\"$cluster_id\",pod=~\"$instance\"}[5m])) by (instance, le))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Kube API Request Rate",
   "type": "timeseries",
   "description": "The Kubernetes API requests per second made by the proxy",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{container=\"kube-proxy\", cluster_id=\"deu01\", code=~\"2..\"}[5m]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{container=\"kube-proxy\", cluster_id=\"deu01\", code=~\"3..\"}[5m]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{container=\"kube-proxy\", cluster_id=\"deu01\", code=~\"4..\"}[5m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{container=\"kube-proxy\", cluster_id=\"deu01\", code=~\"5..\"}[5m]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Post Request Latency 99th Quantile",
   "type": "timeseries",
   "description": "The 99th percentile of the duration of proxy POST requests to the kubernetes API",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rest_client_request_duration_seconds_count{container=\"kube-proxy\",cluster_id=\"$cluster_id\",pod=~\"$instance\",verb=\"POST\"}[5m]))",
     "legendFormat": "{{verb}} {{url}}"
    }
   ]
  },
  {
   "title": "Get Request Latency 99th Quantile",
   "type": "timeseries",
   "description": "The 99th percentile of the duration of proxy GET requests to the kubernetes API",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rest_client_request_duration_seconds_count{container=\"kube-proxy\", cluster_id=\"$cluster_id\",pod=~\"$instance\", verb=\"GET\"}[5m]))",
     "legendFormat": "{{verb}} {{url}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "description": "The proxy memory usage",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{container=\"kube-proxy\",cluster_id=\"$cluster_id\",pod=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "description": "The proxy CPU usage",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{container=\"kube-proxy\",cluster_id=\"$cluster_id\",pod=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "description": "The number of go routines managed by the proxy",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{container=\"kube-proxy\",cluster_id=\"$cluster_id\",pod=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}