{
 "title": "Azure VMSS Api Rate Limit",
 "tags": [
  "provider:azure",
  "owner:team-phoenix"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "subscription_id",
    "label": "Subscription",
    "query": "label_values(azure_operator_rate_limit_vmss_instance_list, subscription)"
   }
  ]
 },
 "panels": [
  { "title": "Subscription: $subscription_id", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "subscription_id" },
  {
   "title": "Available VMSS API calls",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min by (countername) (azure_operator_rate_limit_vmss_instance_list{subscription=\"$subscription_id\"})",
     "legendFormat": "{{countername}}"
    }
   ]
  },
  {
   "title": "Remaining Calls (3 Minutes)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(azure_operator_rate_limit_vmss_instance_list{subscription=\"$subscription_id\",countername=\"Microsoft.Compute/HighCostGetVMScaleSet3Min\"})"
    }
   ]
  },
  {
   "title": "Remaining Calls (30 Minutes)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(azure_operator_rate_limit_vmss_instance_list{subscription=\"$subscription_id\",countername=\"Microsoft.Compute/HighCostGetVMScaleSet30Min\"})"
    }
   ]
  },
  {
   "title": "3 Min Measured Calls During API Request Limiting",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "min by (countername) (azure_operator_rate_limit_vmss_measured{subscription=\"$subscription_id\",countername=\"HighCostGetVMScaleSet3Min\"})",
     "legendFormat": "3 Min"
    }
   ]
  },
  {
   "title": "30 Min Measured Calls During API Request Limiting",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "min by (countername) (azure_operator_rate_limit_vmss_measured{subscription=\"$subscription_id\",countername=\"HighCostGetVMScaleSet30Min\"})",
     "legendFormat": "30 Min"
    }
   ]
  }
 ]
}