{
 "title": "Network Traffic Analysis",
 "tags": [
  "owner:team-atlas",
  "topic:networking",
  "topic:networking-traffic-analysis"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "cluster_id",
    "label": "cluster_id",
    "query": {
     "query": "label_values(kubernetes_build_info,cluster_id)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_namespace_created{cluster_id=\"$cluster_id\"},namespace)"
    }
   },
   { "name": "include_non_namespaced", "label": "Include non-namespaced", "query": ".*" },
   {
    "name": "private_subnets",
    "query": "(10\\..*|100\\.(1[0-9][0-9]|[6-9][0-9]|[1-9])\\..*|172\\.(1[6-9]|2[0-9]|3[01])\\..*|192\\.168\\..*)"
   }
  ]
 },
 "panels": [
  { "title": "Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "# Data availability\n\nThis dashboard relies on optional network metrics.\nNetwork metrics can be enable on a per cluster basis, see our tutorial at https://docs.giantswarm.io/tutorials/observability/network-monitoring/. Please contact team Atlas for more information.\n\n# Information\n\nThis dashboard visualizes a detailed view of network traffic for Kubernetes **Pods**, aggregated by **Namespace**. Traffic is classified as \"Private\" based on [RFC 1918](https://datatracker.ietf.org/doc/html/rfc1918#section-3) standards and the AWS-specific range (`100.64.0.0/16`).\n\nTo visualize those data over a long period of time (above ~1day), use the `Network Traffic Analysis - Overview` dashboard.\n\nTraffic not explicitly bound to a Kubernetes namespace is labeled as `none`. This typically includes Node and other non Pod entities (e.g. Cilium endpoints) traffic.\n\n<details>\n\n<summary>Technical reference: Exploring the <b>beyla_network_flow_bytes_total</b> metric</summary>\n\nUse these guidelines to interpret metric labels when querying manually via Grafana Explore:\n\n- Node traffic is identified by `k8s_src_type` or `k8s_dst_type` label set to `Node`. Those do not have `k8s_src_namespace` or `k8s_dst_namespace` label set.\n- Non Kubernetes entities have no `k8s` labels set.\n- Cilium health endpoints reside within the `100.64.0.0/10` IP range within and have no `k8s` labels set.\n\n</details>"
   }
  },
  {
   "title": "${cluster_id} network traffic for ${namespace} namespace(s)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "Private Traffic vs. Public Traffic",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 22 }
   ]
  },
  {
   "title": "Top Private Network Users",
   "type": "table",
   "gridPos": { "h": 10, "w": 7, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sort(\n  sum by (k8s_src_namespace, cluster_id) (\n    rate(\n      beyla_network_flow_bytes_total{\n        dst_address=~\"^$private_subnets\",\n        dst_zone=\"\",\n        direction=\"request\",\n        k8s_src_namespace=~\"$namespace\",\n        cluster_id=\"${cluster_id}\"\n      }[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sort(\n  sum by (k8s_src_namespace, cluster_id) (\n    rate(\n      beyla_network_flow_bytes_total{\n        dst_address!~\"^$private_subnets\",\n        direction=\"request\",\n        k8s_src_namespace=~\"$namespace\",\n        cluster_id=\"${cluster_id}\"\n      }[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Cross-AZ Network Users",
   "type": "table",
   "gridPos": { "h": 10, "w": 7, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sort(\n  sum by (k8s_src_namespace, cluster_id) (\n    rate(\n      beyla_network_flow_bytes_total{\n        dst_address=~\"^$private_subnets\",\n        direction=\"request\",\n        src_zone!=\"\",\n        dst_zone!=\"\",\n        k8s_src_namespace=~\"$namespace\",\n        cluster_id=\"${cluster_id}\"\n      }[$__rate_interval]\n    )\n    unless on (dst_zone, src_zone)\n      label_replace(beyla_network_flow_bytes_total{src_zone!=\"\", dst_zone!=\"\"},\n        \"dst_zone\", \"$1\", \"src_zone\", \"(.*)\")\n  )\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sort(\n  sum by (k8s_src_namespace, cluster_id) (\n    rate(\n      beyla_network_flow_bytes_total{\n        dst_address=~\"^$private_subnets\",\n        direction=\"request\",\n        src_zone!=\"\",\n        dst_zone!=\"\",\n        k8s_src_namespace=~\"$namespace\",\n        cluster_id=\"${cluster_id}\"\n      }[$__rate_interval]\n    )\n    and on (dst_zone, src_zone)\n      label_replace(beyla_network_flow_bytes_total{src_zone!=\"\", dst_zone!=\"\"},\n        \"dst_zone\", \"$1\", \"src_zone\", \"(.*)\")\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Public Network Users",
   "type": "table",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    { "panelId": 22 }
   ]
  },
  {
   "title": "Cross-AZ vs. In-AZ",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 24 }
   ]
  },
  {
   "title": "Top 10 Private known destination",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (dst_name, cluster_id) (\n  rate(\n    beyla_network_flow_bytes_total{\n      dst_address=~\"^$private_subnets\",\n      dst_zone=\"\",\n      dst_name!=\"\",\n      direction=\"request\",\n      k8s_src_namespace=~\"$namespace\",\n      cluster_id=\"${cluster_id}\"\n    }[$__rate_interval]\n  )\n))",
     "legendFormat": "{{ dst_name }}"
    }
   ]
  },
  {
   "title": "Top 10 Public known destination",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (dst_name, cluster_id) (\n  rate(\n    beyla_network_flow_bytes_total{\n      dst_address!~\"^$private_subnets\",\n      dst_name!=\"\",\n      direction=\"request\",\n      k8s_src_namespace=~\"$namespace\",\n      cluster_id=\"${cluster_id}\"\n    }[$__rate_interval]\n  )\n))",
     "legendFormat": "{{ dst_name }}"
    }
   ]
  },
  {
   "title": "Total Public Traffic",
   "type": "timeseries",
   "description": "Displays the total bytes sent for public traffic.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    { "panelId": 22 }
   ]
  },
  {
   "title": "Total Private Traffic",
   "type": "timeseries",
   "description": "Displays the total bytes sent for public traffic.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    { "panelId": 22 }
   ]
  },
  {
   "title": "Total In-AZ Private Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    { "panelId": 24 }
   ]
  },
  {
   "title": "Total Cross-AZ Private Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    { "panelId": 24 }
   ]
  }
 ]
}