{
 "title": "Management cluster Kubernetes",
 "tags": [
  "topic:management-cluster",
  "topic:kubernetes",
  "owner:team-honeybadger"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Pods Schedulable",
   "type": "timeseries",
   "description": "Number of pods being able to be scheduled per node.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(sum(kube_node_status_capacity_pods) by (node)) - (sum(kube_pod_info) by (node))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Pods Restarting",
   "type": "timeseries",
   "description": "Number of pods restarting within the Kubernetes cluster.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(changes(kube_pod_container_status_restarts_total[5m]))",
     "legendFormat": "restarts"
    }
   ]
  },
  {
   "title": "Error Rates",
   "type": "timeseries",
   "description": "Error rates of the Kubernetes apiserver grouped by request verb. Note that the graph's values are stacked to have a better idea about the overall error rate within the Kubernetes cluster.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{code!~\"2..\", cluster_type=\"management_cluster\"}[5m])) by (verb)",
     "legendFormat": "{{verb}}"
    }
   ]
  }
 ]
}