{
 "title": "Management cluster Overview",
 "tags": [
  "topic:management-cluster",
  "owner:team-honeybadger"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   { "name": "Applications" }
  ]
 },
 "panels": [
  {
   "title": "Cluster stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Number of applications",
   "type": "stat",
   "gridPos": { "h": 4, "w": 15, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(count(kube_pod_labels{cluster_type=~\"management_cluster\",label_app_kubernetes_io_name=~\".+\"}) by (label_app_kubernetes_io_name))",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Pods deployed per applications",
   "type": "table",
   "gridPos": { "h": 12, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(kube_pod_labels{cluster_type=~\"management_cluster\",label_app_kubernetes_io_name=~\".+\"}) by (label_app_kubernetes_io_name)"
    }
   ]
  },
  {
   "title": "Management cluster CPU Requested",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:kubernetes:pod_resource_requests_cpu_cores{cluster_type=~\"management_cluster\"})"
    }
   ]
  },
  {
   "title": "Management cluster CPU Limits",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:kubernetes:pod_resource_limits_cpu_cores{cluster_type=~\"management_cluster\"})"
    }
   ]
  },
  {
   "title": "Management cluster CPU Allocatable",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:kubernetes:node_allocatable_cpu_cores_total{cluster_type=~\"management_cluster\"})"
    }
   ]
  },
  {
   "title": "Management cluster Memory Requested",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:kubernetes:pod_resource_requests_memory_bytes{cluster_type=~\"management_cluster\"})"
    }
   ]
  },
  {
   "title": "Management cluster Memory Limits",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:kubernetes:pod_resource_limits_memory_bytes{cluster_type=~\"management_cluster\"})\n"
    }
   ]
  },
  {
   "title": "Management cluster Allocatable Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:kubernetes:node_allocatable_memory_bytes{cluster_type=~\"management_cluster\"})"
    }
   ]
  },
  {
   "title": "Pods stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Throttled CPU per container",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n    rate(container_cpu_cfs_throttled_periods_total{cluster_type=~\"management_cluster\",container!~\"\"}[5m])) \nby (container)",
     "legendFormat": "{{ container }}"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory utilization per app",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{name!~\".+POD.+\",cluster_type=~\"management_cluster\", container!=\"\"}) by (container)",
     "legendFormat": "{{ container }}"
    }
   ]
  }
 ]
}