{
 "title": "Mimir / Resource Efficiency",
 "tags": [
  "owner:team-atlas",
  "topic:observability",
  "component:mimir"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ingested_metrics",
    "query": "sum(irate(cortex_distributor_samples_in_total{cluster_type=\"management_cluster\", pod=~\"mimir-distributor-.*\"}[$__rate_interval]))"
   },
   {
    "name": "active_series",
    "query": "sum(max by (pod) (cortex_ingester_active_series{cluster_type=\"management_cluster\", pod=~\"mimir-ingester-.*\"}))"
   },
   {
    "name": "queries",
    "query": "sum(irate(cortex_query_frontend_queries_total{cluster_type=\"management_cluster\", pod=~\"mimir-query-frontend-.*\"}[$__rate_interval]))"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "# Intro\n\nThis dashboard compares actual resource usage for Mimir compared to [official sizing rules](https://grafana.com/docs/mimir/latest/manage/run-production-environment/planning-capacity/).\n\n# How to read it\n\nOn top of the dashboard, you see your actual volume of processed data.\n\n- The green \"actual\" line is the real actual resource usage on this cluster.\n- The red \"reserved\" line is the reserved resources (via pod's resource `requests`).\n- The purple \"expected\" line is the estimation of expected resource usage according to Grafana sizing rules.\n\n# limitations\n\nOn small clusters, we may be higher than expected because of incompressible resources.\n\n"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "recps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "$ingested_metrics", "legendFormat": "Ingested Metrics" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "recps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "$active_series", "legendFormat": "Active Series" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "recps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "$queries", "legendFormat": "Queries" }
   ]
  },
  { "title": "Mimir Micro Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Distributor CPU",
   "type": "timeseries",
   "description": "The distributor component resources utilization is determined by the number of received samples per second.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "$ingested_metrics / 25000", "legendFormat": "Expected" },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container=\"distributor\", pod=~\"mimir-distributor-.*\", cluster_type=\"management_cluster\"}[$__rate_interval]))",
     "legendFormat": "Actual usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{container=\"distributor\", pod=~\"mimir-distributor-.*\", cluster_type=\"management_cluster\", resource=\"cpu\"})",
     "legendFormat": "Reserved"
    }
   ]
  },
  {
   "title": "Distributor RAM",
   "type": "timeseries",
   "description": "The distributor component resources utilization is determined by the number of received samples per second.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "($ingested_metrics / 25000) * 1024 * 1024 * 1024",
     "legendFormat": "Expected"
    },
    {
     "expr": "sum(container_memory_usage_bytes{container=\"distributor\", pod=~\"mimir-distributor-.*\", cluster_type=\"management_cluster\"})",
     "legendFormat": "Actual usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{container=\"distributor\", pod=~\"mimir-distributor-.*\", cluster_type=\"management_cluster\", resource=\"memory\"})",
     "legendFormat": "Reserved"
    }
   ]
  },
  {
   "title": "Ingester CPU",
   "type": "timeseries",
   "description": "The ingester component resources’ utilization is determined by the number of series that are in memory.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "$active_series / 300000", "legendFormat": "Expected" },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container=\"ingester\", pod=~\"mimir-ingester-.*\", cluster_type=\"management_cluster\"}[$__rate_interval]))",
     "legendFormat": "Actual usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{container=\"ingester\", pod=~\"mimir-ingester-.*\", cluster_type=\"management_cluster\", resource=\"cpu\"})",
     "legendFormat": "Reserved"
    }
   ]
  },
  {
   "title": "Ingester RAM",
   "type": "timeseries",
   "description": "The ingester component resources’ utilization is determined by the number of series that are in memory.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "($active_series / 300000) * 1024 * 1024 * 1024 * 2.5",
     "legendFormat": "Expected"
    },
    {
     "expr": "sum(container_memory_usage_bytes{container=\"ingester\", pod=~\"mimir-ingester-.*\", cluster_type=\"management_cluster\"})",
     "legendFormat": "Actual usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{container=\"ingester\", pod=~\"mimir-ingester-.*\", cluster_type=\"management_cluster\", resource=\"memory\"})",
     "legendFormat": "Reserved"
    }
   ]
  },
  {
   "title": "Query-frontend CPU",
   "type": "timeseries",
   "description": "The query-frontend component resources utilization is determined by the number of queries per second.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "$queries / 250", "legendFormat": "Expected" },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container=\"query-frontend\", pod=~\"mimir-query-frontend-.*\", cluster_type=\"management_cluster\"}[$__rate_interval]))",
     "legendFormat": "Actual usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{container=\"query-frontend\", pod=~\"mimir-query-frontend-.*\", cluster_type=\"management_cluster\", resource=\"cpu\"})",
     "legendFormat": "Reserved"
    }
   ]
  },
  {
   "title": "Query-frontend RAM",
   "type": "timeseries",
   "description": "The query-frontend component resources utilization is determined by the number of queries per second.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "($queries / 250) * 1024 * 1024 * 1024",
     "legendFormat": "Expected"
    },
    {
     "expr": "sum(container_memory_usage_bytes{container=\"query-frontend\", pod=~\"mimir-query-frontend-.*\", cluster_type=\"management_cluster\"})",
     "legendFormat": "Actual usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{container=\"query-frontend\", pod=~\"mimir-query-frontend-.*\", cluster_type=\"management_cluster\", resource=\"memory\"})",
     "legendFormat": "Reserved"
    }
   ]
  },
  {
   "title": "Query-scheduler CPU",
   "type": "timeseries",
   "description": "The query-scheduler component resources’ utilization is determined by the number of queries per second.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "$queries / 500", "legendFormat": "Expected" },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container=\"query-scheduler\", pod=~\"mimir-query-scheduler-.*\", cluster_type=\"management_cluster\"}[$__rate_interval]))",
     "legendFormat": "Actual usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{container=\"query-scheduler\", pod=~\"mimir-query-scheduler-.*\", cluster_type=\"management_cluster\", resource=\"cpu\"})",
     "legendFormat": "Reserved"
    }
   ]
  },
  {
   "title": "Query-scheduler RAM",
   "type": "timeseries",
   "description": "The query-scheduler component resources’ utilization is determined by the number of queries per second.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "($queries / 500) * 1024 * 1024 * 100",
     "legendFormat": "Expected"
    },
    {
     "expr": "sum(container_memory_usage_bytes{container=\"query-scheduler\", pod=~\"mimir-query-scheduler-.*\", cluster_type=\"management_cluster\"})",
     "legendFormat": "Actual usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{container=\"query-scheduler\", pod=~\"mimir-query-scheduler-.*\", cluster_type=\"management_cluster\", resource=\"memory\"})",
     "legendFormat": "Reserved"
    }
   ]
  },
  {
   "title": "Querier CPU",
   "type": "timeseries",
   "description": "The querier component resources utilization is determined by the number of queries per second.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "$queries / 10", "legendFormat": "Expected" },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container=\"querier\", pod=~\"mimir-querier-.*\", cluster_type=\"management_cluster\"}[$__rate_interval]))",
     "legendFormat": "Actual usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{container=\"querier\", pod=~\"mimir-querier-.*\", cluster_type=\"management_cluster\", resource=\"cpu\"})",
     "legendFormat": "Reserved"
    }
   ]
  },
  {
   "title": "Querier RAM",
   "type": "timeseries",
   "description": "The querier component resources utilization is determined by the number of queries per second.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "($queries) * 1024 * 1024 * 1024",
     "legendFormat": "Expected"
    },
    {
     "expr": "sum(container_memory_usage_bytes{container=\"querier\", pod=~\"mimir-querier-.*\", cluster_type=\"management_cluster\"})",
     "legendFormat": "Actual usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{container=\"querier\", pod=~\"mimir-querier-.*\", cluster_type=\"management_cluster\", resource=\"memory\"})",
     "legendFormat": "Reserved"
    }
   ]
  },
  {
   "title": "Store-gateway CPU",
   "type": "timeseries",
   "description": "The store-gateway component resources’ utilization is determined by the number of queries per second and active series before ingesters replication.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "$queries / 10", "legendFormat": "Expected" },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container=\"store-gateway\", pod=~\"mimir-store-gateway-.*\", cluster_type=\"management_cluster\"}[$__rate_interval]))",
     "legendFormat": "Actual usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{container=\"store-gateway\", pod=~\"mimir-store-gateway-.*\", cluster_type=\"management_cluster\", resource=\"cpu\"})",
     "legendFormat": "Reserved"
    }
   ]
  },
  {
   "title": "Store-gateway RAM",
   "type": "timeseries",
   "description": "The store-gateway component resources’ utilization is determined by the number of queries per second and active series before ingesters replication.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "($queries / 10) * 1024 * 1024 * 1024",
     "legendFormat": "Expected"
    },
    {
     "expr": "sum(container_memory_usage_bytes{container=\"store-gateway\", pod=~\"mimir-store-gateway-.*\", cluster_type=\"management_cluster\"})",
     "legendFormat": "Actual usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{container=\"store-gateway\", pod=~\"mimir-store-gateway-.*\", cluster_type=\"management_cluster\", resource=\"memory\"})",
     "legendFormat": "Reserved"
    }
   ]
  },
  {
   "title": "Compactor CPU",
   "type": "timeseries",
   "description": "The compactor component resources utilization is determined by the number of active series.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "$active_series / 20000000", "legendFormat": "Expected" },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container=\"compactor\", pod=~\"mimir-compactor-.*\", cluster_type=\"management_cluster\"}[$__rate_interval]))",
     "legendFormat": "Actual usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{container=\"compactor\", pod=~\"mimir-compactor-.*\", cluster_type=\"management_cluster\", resource=\"cpu\"})",
     "legendFormat": "Reserved"
    }
   ]
  },
  {
   "title": "Compactor RAM",
   "type": "timeseries",
   "description": "The compactor component resources utilization is determined by the number of active series.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "($active_series / 20000000) * 1024 * 1024 * 1024 * 4",
     "legendFormat": "Expected"
    },
    {
     "expr": "sum(container_memory_usage_bytes{container=\"compactor\", pod=~\"mimir-compactor-.*\", cluster_type=\"management_cluster\"})",
     "legendFormat": "Actual usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{container=\"compactor\", pod=~\"mimir-compactor-.*\", cluster_type=\"management_cluster\", resource=\"memory\"})",
     "legendFormat": "Reserved"
    }
   ]
  }
 ]
}