{
 "title": "net-exporter",
 "tags": [
  "owner:team-ludacris",
  "topic:management-cluster",
  "topic:workload-cluster"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(kubernetes_build_info, cluster_id)"
   }
  ]
 },
 "panels": [
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Network Errors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(network_dial_error_total{cluster_id=\"$cluster\"}[15m])) or vector(0)"
    }
   ]
  },
  {
   "title": "DNS Errors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(dns_resolve_error_total{cluster_id=\"$cluster\"}[15m])) or vector(0)"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Network Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(network_latency_seconds_sum{cluster_id=\"$cluster\", host!=\"net-exporter:8000\"}[15m])) / sum(irate(network_latency_seconds_count{cluster_id=\"$cluster\", host!=\"net-exporter:8000\"}[15m]))",
     "legendFormat": "Mean Latency"
    },
    {
     "expr": "histogram_quantile(0.5, sum(irate(network_latency_seconds_bucket{cluster_id=\"$cluster\"}[15m])) by (le))",
     "legendFormat": "50th Percentile Latency"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(network_latency_seconds_bucket{cluster_id=\"$cluster\"}[15m])) by (le))",
     "legendFormat": "95th Percentile Latency"
    }
   ]
  },
  { "title": "DNS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "DNS UDP Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(dns_udp_latency_seconds_sum{cluster_id=\"$cluster\"}[15m])) / sum(irate(dns_udp_latency_seconds_count{cluster_id=\"$cluster\"}[15m]))",
     "legendFormat": "Mean Latency"
    },
    {
     "expr": "histogram_quantile(0.5, sum(irate(dns_udp_latency_seconds_bucket{cluster_id=\"$cluster\"}[15m])) by (le))",
     "legendFormat": "50th Percentile Latency"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(dns_udp_latency_seconds_bucket{cluster_id=\"$cluster\"}[15m])) by (le))",
     "legendFormat": "95th Percentile Latency"
    }
   ]
  },
  {
   "title": "DNS TCP Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(dns_tcp_latency_seconds_sum{cluster_id=\"$cluster\"}[15m])) / sum(irate(dns_tcp_latency_seconds_count{cluster_id=\"$cluster\"}[15m]))",
     "legendFormat": "Mean Latency"
    },
    {
     "expr": "histogram_quantile(0.5, sum(irate(dns_tcp_latency_seconds_bucket{cluster_id=\"$cluster\"}[15m])) by (le))",
     "legendFormat": "50th Percentile Latency"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(dns_tcp_latency_seconds_bucket{cluster_id=\"$cluster\"}[15m])) by (le))",
     "legendFormat": "95th Percentile Latency"
    }
   ]
  }
 ]
}