{
 "title": "NGINX Ingress Controller - Admission",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster ID",
    "query": {
     "query": "label_values(kubernetes_build_info{},cluster_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Tested duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(nginx_ingress_controller_admission_tested_duration{cluster_id=\"$cluster\"}) by (pod) "
    }
   ]
  },
  {
   "title": "Tested ingresses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "irate(nginx_ingress_controller_admission_tested_ingresses{cluster_id=\"$cluster\"}[2m])"
    }
   ]
  },
  {
   "title": "Rendered Ingresses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg(nginx_ingress_controller_admission_render_ingresses{cluster_id=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "api-server errors",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{app=\"api-server\",cluster_id=\"$cluster\"} |= \"validate.nginx.ingress.kubernetes.io\" |= \"failed\""
    }
   ]
  }
 ]
}