{
 "title": "Operatorkit",
 "description": "Operatorkit-based operators metrics",
 "tags": [
  "owner:team-atlas",
  "topic:operators",
  "component:operatorkit"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "app",
    "query": {
     "query": "label_values(operatorkit_controller_event_count, app)"
    }
   },
   {
    "name": "event",
    "query": {
     "query": "label_values(operatorkit_controller_event_count{app=\"$app\"}, event)"
    }
   },
   {
    "name": "operation",
    "query": {
     "query": "label_values(operatorkit_controller_operation_count{app=\"$app\"}, operation)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Documentation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Operatorkit dashboard",
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "This dashboard shows metrics about all operatorkit-based operators."
     }
    }
   ]
  },
  { "title": "$operation operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }, "repeat": "operation" },
  {
   "title": "Operation duration histogram",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "sum(rate(operatorkit_controller_operation_bucket{app=\"$app\", operation=\"$operation\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Operation duration quantiles",
   "type": "graph",
   "description": "Percentiles of delete event durations.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99,  sum(irate(operatorkit_controller_operation_bucket{app=\"$app\", operation=\"$operation\"}[5m])) by (app, event, le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.9,  sum(irate(operatorkit_controller_operation_bucket{app=\"$app\", operation=\"$operation\"}[5m])) by (app, operation, le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.75,  sum(irate(operatorkit_controller_operation_bucket{app=\"$app\", operation=\"$operation\"}[5m])) by (app, operation, le))",
     "legendFormat": "75%"
    }
   ]
  },
  { "title": "$event events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 }, "repeat": "event" },
  {
   "title": "Event duration histogram",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(rate(operatorkit_controller_event_bucket{app=\"$app\", event=\"$event\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Event duration quantiles",
   "type": "graph",
   "description": "Percentiles of delete event durations.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99,  sum(irate(operatorkit_controller_event_bucket{app=\"$app\", event=\"$event\"}[5m])) by (app, event, le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.9,  sum(irate(operatorkit_controller_event_bucket{app=\"$app\", event=\"$event\"}[5m])) by (app, event, le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.75,  sum(irate(operatorkit_controller_event_bucket{app=\"$app\", event=\"$event\"}[5m])) by (app, event, le))",
     "legendFormat": "75%"
    }
   ]
  },
  { "title": "Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Errors",
   "type": "graph",
   "description": "Errors occurring while reconciling. Note operators reconcile sequentially which implies there can only be one error at a time.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(operatorkit_controller_error_total{app=\"$app\"}) by (instance)",
     "legendFormat": "instance {{instance}}"
    },
    {
     "expr": "sum(operatorkit_controller_errors_total{app=\"$app\"}) by (pod)",
     "legendFormat": "pod {{pod}}"
    }
   ]
  },
  {
   "title": "Build Info history",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "sum(changes(giantswarm_build_info{app=\"$app\"}[5m])) by (commit, golang_version, version) + 1",
     "legendFormat": "{{version}} - {{golang_version}} - {{commit}}"
    }
   ]
  }
 ]
}