{
 "title": "Prometheus / Mimir comparative",
 "tags": [
  "owner:team-atlas",
  "topic:observability",
  "component:prometheus",
  "component:mimir"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  { "title": "Prometheus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Prom Total cpu used ",
   "type": "stat",
   "description": "Total cpu used by all prometheus pods",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"prometheus\", namespace=~\".*-prometheus\", cluster_type=~\"management_cluster\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total memory used ",
   "type": "stat",
   "description": "Total memory used by all prometheus pods accounting the max memory used by every pod in tside the range",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max_over_time(container_memory_usage_bytes{container=\"prometheus\", namespace=~\".*-prometheus\", cluster_type=~\"management_cluster\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Received data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace=~\".*-prometheus\"}[$__range])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Emitted data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{namespace=~\".*-prometheus\"}[$__range])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Mimir", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Mimir Total cpu used ",
   "type": "stat",
   "description": "Total cpu % used by all mimir pods",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum(rate(container_cpu_usage_seconds_total{pod=~\"mimir-.*\", cluster_type=~\"management_cluster\"}[$__range])) by (pod))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mimir Total memory used ",
   "type": "stat",
   "description": "Total memory used by all mimir pods accounting the max memory inside the range",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum(max_over_time(container_memory_usage_bytes{pod=~\"mimir-.*\", cluster_type=~\"management_cluster\"}[$__range] ) ) by (pod))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Received data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{pod=~\"mimir-.*\"}[$__range])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Emitted data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{pod=~\"mimir-.*\"}[$__range])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}