{
 "title": "Prometheus / Overview",
 "tags": [
  "owner:team-atlas",
  "topic:observability",
  "component:prometheus",
  "source:prometheus-mixin"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "60s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{container=\"prometheus\",cluster_type=~\"management_cluster\", pod=~\".*prometheus.*\"}, pod)"
    }
   },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(prometheus_build_info{job=\"prometheus\", cluster_id=~\"$cluster\"}, job)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(prometheus_build_info{job=~\"$job\", cluster_id=~\"$cluster\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Prometheus Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Prometheus Stats",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (job, instance, version, cluster_id) (prometheus_build_info{job=~\"$job\", instance=~\"$instance\", cluster_id=~\"$cluster\"})"
    },
    {
     "expr": "max by (job, instance, cluster_id) (time() - process_start_time_seconds{job=~\"$job\", instance=~\"$instance\", cluster_id=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Discovery",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Target Sync",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prometheus_target_sync_length_seconds_sum{job=~\"$job\",instance=~\"$instance\", cluster_id=~\"$cluster\"}[5m])) by (scrape_job) * 1e3",
     "legendFormat": "{{scrape_job}}"
    }
   ]
  },
  {
   "title": "Targets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(prometheus_sd_discovered_targets{job=~\"$job\",instance=~\"$instance\", cluster_id=~\"$cluster\"}) by (cluster_id)",
     "legendFormat": "{{cluster_id}} targets"
    }
   ]
  },
  {
   "title": "Retrieval",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Average Scrape Interval Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_target_interval_length_seconds_sum{job=~\"$job\",instance=~\"$instance\", cluster_id=~\"$cluster\"}[5m]) / rate(prometheus_target_interval_length_seconds_count{job=~\"$job\",instance=~\"$instance\", cluster_id=~\"$cluster\"}[5m]) * 1e3",
     "legendFormat": "{{cluster_id}} - {{interval}} configured"
    }
   ]
  },
  {
   "title": "Scrape failures",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job, cluster_id) (rate(prometheus_target_scrapes_exceeded_body_size_limit_total{cluster_id=~\"$cluster\"}[1m]))",
     "legendFormat": "exceeded body size limit: {{cluster_id}}/{{job}}"
    },
    {
     "expr": "sum by (job, cluster_id) (rate(prometheus_target_scrapes_exceeded_sample_limit_total{cluster_id=~\"$cluster\"}[1m]))",
     "legendFormat": "exceeded sample limit: {{cluster_id}}/{{job}}"
    },
    {
     "expr": "sum by (job, cluster_id) (rate(prometheus_target_scrapes_sample_duplicate_timestamp_total{cluster_id=~\"$cluster\"}[1m]))",
     "legendFormat": "duplicate timestamp: {{cluster_id}}/{{job}}"
    },
    {
     "expr": "sum by (job, cluster_id) (rate(prometheus_target_scrapes_sample_out_of_bounds_total{cluster_id=~\"$cluster\"}[1m]))",
     "legendFormat": "out of bounds: {{cluster_id}}/{{job}}"
    },
    {
     "expr": "sum by (job, cluster_id) (rate(prometheus_target_scrapes_sample_out_of_order_total{cluster_id=~\"$cluster\"}[1m]))",
     "legendFormat": "out of order: {{cluster_id}}/{{job}}"
    }
   ]
  },
  {
   "title": "Appended Samples",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_samples_appended_total{job=~\"$job\",instance=~\"$instance\", cluster_id=~\"$cluster\"}[5m])",
     "legendFormat": "{{job}} {{instance}}"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Head Series",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_tsdb_head_series{job=~\"$job\",instance=~\"$instance\", cluster_id=~\"$cluster\"}",
     "legendFormat": "{{job}} {{instance}} head series"
    }
   ]
  },
  {
   "title": "Head Chunks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_tsdb_head_chunks{job=~\"$job\",instance=~\"$instance\", cluster_id=~\"$cluster\"}",
     "legendFormat": "{{job}} {{instance}} head chunks"
    }
   ]
  },
  {
   "title": "Query",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Query Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_engine_query_duration_seconds_count{job=~\"$job\",instance=~\"$instance\", cluster_id=~\"$cluster\",slice=\"inner_eval\"}[5m])",
     "legendFormat": "{{job}} {{instance}}"
    }
   ]
  },
  {
   "title": "Stage Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max by (slice, cluster_id) (prometheus_engine_query_duration_seconds{quantile=\"0.9\",job=~\"$job\",instance=~\"$instance\", cluster_id=~\"$cluster\"}) * 1e3",
     "legendFormat": "{{cluster_id}} {{slice}}"
    }
   ]
  }
 ]
}