{
 "title": "Service Level Agreement / Cluster",
 "tags": [
  "topic:sla",
  "owner:atlas"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(slo:sli_error:ratio_rate1h, cluster_id)"
   },
   { "name": "sla", "query": "0.9995" }
  ]
 },
 "panels": [
  { "title": "Kubernetes API Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Service Level Agreement (SLA)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "$sla", "legendFormat": "SLA" }
   ]
  },
  {
   "title": "Kubernetes API Server Uptime",
   "type": "timeseries",
   "description": "Average SLA over last 30d",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1-avg_over_time(avg(slo:sli_error:ratio_rate1h{sloth_id=\"apiserver-availability\", cluster_id=\"$cluster\"})[30d:1h])",
     "legendFormat": "Public Ingress"
    },
    { "expr": "$sla", "legendFormat": "SLA" }
   ]
  },
  {
   "title": "Internal API Tests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1-avg_over_time(avg(slo:sli_error:ratio_rate1h{sloth_id=\"apiserver-availability\", cluster_id=\"$cluster\"})[30d:1h])",
     "legendFormat": "Internal API Tests"
    }
   ]
  },
  { "title": "Public NGINX Ingress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Service Level Agreement (SLA)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "$sla", "legendFormat": "SLA" }
   ]
  },
  {
   "title": "Public NGINX Ingress Availability",
   "type": "timeseries",
   "description": "Average SLA over last 30d",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "min(1,1-avg_over_time(avg(slo:sli_error:ratio_rate1h{sloth_id=\"cluster-nginx-availability\", cluster_id=\"$cluster\"})[30d:1h]))",
     "legendFormat": "Public Ingress"
    },
    { "expr": "$sla", "legendFormat": "SLA" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(1,1-avg_over_time(avg(slo:sli_error:ratio_rate1h{sloth_id=\"cluster-nginx-availability\", cluster_id=\"$cluster\"})[30d:1h]))",
     "legendFormat": "Internal Ingress Tests"
    }
   ]
  },
  { "title": "Private NGINX Ingress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Service Level Agreement (SLA)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "$sla", "legendFormat": "SLA" }
   ]
  },
  {
   "title": "Private NGINX Ingress Availability",
   "type": "timeseries",
   "description": "Average SLA over last 30d",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "min(1,1-avg_over_time(avg(slo:sli_error:ratio_rate1h{sloth_id=\"cluster-nginx-availability\", cluster_id=\"$cluster\"})[30d:1h]))",
     "legendFormat": "Public Ingress"
    },
    { "expr": "$sla", "legendFormat": "SLA" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(1,1-avg_over_time(avg(slo:sli_error:ratio_rate1h{sloth_id=\"cluster-internal-nginx-availability\", cluster_id=\"$cluster\"})[30d:1h]))",
     "legendFormat": "Internal Ingress Tests"
    }
   ]
  },
  { "title": "CoreDNS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Service Level Agreement (SLA)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "$sla", "legendFormat": "SLA" }
   ]
  },
  {
   "title": "DNS Availability",
   "type": "timeseries",
   "description": "Average SLA over last 30d",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1-avg_over_time(avg(slo:sli_error:ratio_rate1h{sloth_id=\"dns-dns-service-availability\", cluster_id=\"$cluster\"})[30d:1h])",
     "legendFormat": "DNS Resolution"
    },
    { "expr": "$sla", "legendFormat": "SLA" }
   ]
  },
  {
   "title": "DNS Resolution",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1-avg_over_time(avg(slo:sli_error:ratio_rate1h{sloth_id=\"dns-dns-service-availability\", cluster_id=\"$cluster\"})[30d:1h])",
     "legendFormat": "DNS Resolution"
    }
   ]
  }
 ]
}