{
 "title": "Service Level Agreement / Reporting KPIs",
 "description": "This dashboard provides KPIs we use in monthly reporting.",
 "tags": [
  "KPI",
  "reporting"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "offset", "label": "Offset", "query": "0d" }
  ]
 },
 "panels": [
  {
   "title": "Size",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Giantswarm Packages Total (AVG)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(sum(group_cluster:kube_node_status_capacity_cpu_cores:sum:avg60m)/64,sum(group_cluster:kube_node_status_capacity_memory_bytes:sum:avg60m)/1024/1024/1024/256) offset $offset",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Giantswarm Packages Difference (AVG)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(group_cluster:kube_node_status_capacity_memory_bytes:sum:avg60m)/1024/1024/1024/256)-(sum(group_cluster:kube_node_status_capacity_cpu_cores:sum:avg60m)/64) offset $offset",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "All Cluster Size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(kube_node_info_count:avg30d)by(odp_cluster)) offset $offset",
     "legendFormat": "Cluster"
    },
    {
     "expr": "sum(kube_node_info_count:avg30d) offset $offset",
     "legendFormat": "Nodes"
    },
    {
     "expr": "sum(kube_namespace_annotations_count:avg30d) offset $offset",
     "legendFormat": "Namespaces"
    },
    {
     "expr": "sum(kube_service_info_count:avg30d) offset $offset",
     "legendFormat": "Services"
    },
    {
     "expr": "sum(kube_pod_info_count:avg30d) offset $offset",
     "legendFormat": "Pods"
    }
   ]
  },
  {
   "title": "Giantswarm Packages per Unit (AVG)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(group_cluster:kube_node_status_capacity_memory_bytes:sum:avg60m{})/1024/1024/1024/256 offset $offset",
     "legendFormat": "Memory"
    },
    {
     "expr": "sum(group_cluster:kube_node_status_capacity_cpu_cores:sum:avg60m{})/64 offset $offset",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "General Purpose Cluster Size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(kube_node_info_count:avg30d{odp_project=\"general\"})by(odp_cluster)) offset $offset",
     "legendFormat": "Cluster"
    },
    {
     "expr": "sum(kube_node_info_count:avg30d{odp_project=\"general\"}) offset $offset",
     "legendFormat": "Nodes"
    },
    {
     "expr": "sum(kube_namespace_annotations_count:avg30d{odp_project=\"general\"}) offset $offset",
     "legendFormat": "Namespaces"
    },
    {
     "expr": "sum(kube_service_info_count:avg30d{odp_project=\"general\"}) offset $offset",
     "legendFormat": "Services"
    },
    {
     "expr": "sum(kube_pod_info_count:avg30d{odp_project=\"general\"}) offset $offset",
     "legendFormat": "Pods"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cluster Uptime Production",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(blazemeter_uptime_success_ratio{test_name=~\".*Ingress.*\",odp_environment=\"production\"}[30d])) offset $offset",
     "legendFormat": "Ingress Controller"
    },
    {
     "expr": "avg(avg_over_time(blazemeter_uptime_success_ratio{test_name=~\".*API.*\",odp_environment=\"production\"}[30d])) offset $offset",
     "legendFormat": "API Server"
    }
   ]
  },
  {
   "title": "Public NGINX Ingress Uptime",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(avg_over_time(avg(blazemeter_uptime_success_ratio{test_name=~\".*Ingress.*\",timeframe=\"day\",odp_environment=\"production\"})by(odp_cluster, test_name, env_name)[$__range:1d])) offset $offset",
     "legendFormat": "{{test_name}} {{env_name}} - {{odp_cluster}}"
    }
   ]
  },
  {
   "title": "Kubernetes API Server Uptime",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(avg_over_time(avg(blazemeter_uptime_success_ratio{test_name=~\".*API.*\",timeframe=\"day\",odp_environment=\"production\"})by(odp_cluster, test_name, env_name)[$__range:1d])) offset $offset",
     "legendFormat": "{{test_name}} {{env_name}} - {{odp_cluster}}"
    }
   ]
  }
 ]
}