{
 "title": "Service Level Agreement / Cluster Status",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kube_node_status_condition, cluster_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster exhaustions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Node Condition",
   "type": "stat",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition!=\"Ready\",status=\"true\",cluster_id=\"$cluster\"})by(condition)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running pods exhaustion",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{cluster_id=\"$cluster\"}) / sum(min(kube_pod_info{cluster_id=\"$cluster\"}) by (node))"
    }
   ]
  },
  {
   "title": "Description",
   "type": "text",
   "gridPos": { "h": 3, "w": 18, "x": 0, "y": 6 },
   "options": {
    "content": "Number of nodes with any NotReady conditino flag raised\n(behind line for last hour)"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Description",
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 6 },
   "options": {
    "content": "Average number of running pods (per node) in the cluster\n\nDefault k8s max value: 110"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cluster network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "DNS lookup performance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(k8s_dns_lookup_duration_seconds_bucket{cluster_id=\"$cluster\"}[5m])) by (le, type, host, proto))",
     "legendFormat": "{{ proto }} - {{ type }} - {{ host }}"
    }
   ]
  },
  {
   "title": "Description",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 17 },
   "options": { "content": "DNS lookup's 99th percentile" },
   "targets": [
    {}
   ]
  },
  {
   "title": "DNS network errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(k8s_dns_lookup_errors_total{cluster_id=\"$cluster\"}[5m])) by (type, host, proto)",
     "legendFormat": "{{ proto }} - {{ type }} - {{ host }}"
    }
   ]
  },
  {
   "title": "Description",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 25 },
   "options": {
    "content": "Number of DNS errors seen in the cluster"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "CoreDNS performance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_request_duration_seconds_bucket{cluster_id=\"$cluster\"}[5m])) by (le))",
     "legendFormat": "latency"
    }
   ]
  },
  {
   "title": "Inter-nodes network errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sort_desc(sum(rate(k8s_node_inter_network_errors_total{cluster_id=\"$cluster\"}[5m])) by (src, dest) > 0)",
     "legendFormat": "{{ src }} -> {{ dest }}"
    }
   ]
  },
  {
   "title": "kube-proxy network errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(k8s_kube_proxy_service_errors_total{cluster_id=\"$cluster\"}[5m])) by (node)",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Description",
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 43 },
   "options": {
    "content": "Nodes network connectivity errors"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Description",
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 43 },
   "options": {
    "content": "Nodes network connectivity errors"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Ingress Request performance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(k8s_ingress_ingress_request_duration_seconds_bucket{cluster_id=\"$cluster\"}[5m])) by (le, host))",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Ingress Request network errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sort_desc(sum(rate(k8s_ingress_request_errors_total{cluster_id=\"$cluster\"}[5m])) by (src, host) > 0)",
     "legendFormat": "{{ src }} -> {{ host }}"
    }
   ]
  },
  {
   "title": "Description",
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 54 },
   "options": {
    "content": "NGINX Ingress request performance"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Description",
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 54 },
   "options": { "content": "NGINX Ingress request errors" },
   "targets": [
    {}
   ]
  },
  {
   "title": "etcd latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(histogram_quantile(0.99, rate(etcd_request_duration_seconds_bucket{cluster_id=\"$cluster\"}[5m]))) by (operation)",
     "legendFormat": "{{ operation }}"
    },
    { "expr": "sum(etcd_object_counts)", "legendFormat": "etcd object counts" }
   ]
  },
  {
   "title": "Description",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 64 },
   "options": {
    "content": "Shows etcd latencies of the different requests verbs on the left Y axis.\n\nShows etcd amount of stored objects on the right Y axis."
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "API Server CONNECT latencies",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(apiserver_request_duration_seconds_bucket{cluster_id=\"$cluster\", verb!=\"WATCH\"}[5m])) by (le,verb))",
     "legendFormat": "{{ verb }}"
    }
   ]
  },
  {
   "title": "API Server Terminations Total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_terminations_total{cluster_id=\"$cluster\"}[5m]))by(verb)",
     "legendFormat": "{{ verb }}"
    }
   ]
  },
  {
   "title": "Description",
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 74 },
   "options": {
    "content": "API Server latency when services connect to it"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Description",
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 74 },
   "options": { "content": "API Server terminations" },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cluster pods availability",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Unavailable coreDNS pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{condition=\"false\",namespace=\"kube-system\",pod=~\"coredns.*\",cluster_id=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Unavailable cilium pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{condition=\"false\",namespace=\"kube-system\",pod=~\"cilium.*\",cluster_id=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Unavailable Nginx IC pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{condition=\"false\",namespace=\"kube-system\",pod=~\"nginx-ingress-controller.*\",cluster_id=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Description",
   "type": "text",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 82 },
   "options": {
    "content": "CoreDNS is not running on the cluster\n(background line for last hour)\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Description",
   "type": "text",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 82 },
   "options": {
    "content": "Cilium is not running on the cluster\n(background line for last hour)\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Description",
   "type": "text",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 82 },
   "options": {
    "content": "NGINX ICs not running on the cluster\n(background line for last hour)"
   },
   "targets": [
    {}
   ]
  }
 ]
}