{
 "title": "Node utilization",
 "description": "Utilization of a cluster on a node level, focusing on requests",
 "tags": [ "owner:team-honeybadger" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kube_pod_container_resource_requests,cluster_id)"
    }
   },
   {
    "name": "role",
    "label": "Node role",
    "query": {
     "query": "label_values(kube_node_role{role!=\"master\"},role)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "About this dashboard",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
     "options": {
      "content": "This dashboard helps to analyze node resource (CPU and RAM) utilization based on resource requests.\n\n**Utilization** is the ratio of resources requested by workloads, divided by the total amount of resources provided by the node. As the cluster owner, your general aim should be to keep both memory and CPU utilization high, to avoid paying for unused resources. On the other hand, you want to keep head room, as maximized utilization can lead to increased latency and instability.\n\nFor CPU, the basis in this dashboard are _logical_ cores as provided by the `machine_cpu_cores` metric. This may differ from the _physical_ number of cores."
     }
    }
   ]
  },
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Worker nodes",
   "type": "stat",
   "description": "Number of nodes currently (at the end of the selected time window)",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_node_role{cluster_id=\"$cluster\",role=\"worker\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Worker nodes ready",
   "type": "stat",
   "description": "Number of nodes in condition Ready, currently (at the end of the selected time window)",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_role{cluster_id=\"$cluster\",role=\"worker\"} \n+ on(node) group_left(role)\n(\n    sum(kube_node_status_condition{cluster_id=\"$cluster\",condition=\"Ready\",status=\"true\"}) by (node) * 0\n))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resource utilization",
   "type": "bargauge",
   "description": "Most recent utilization based on resource requests divided by the resource capacity",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(\n    kube_node_role{role=\"worker\"} * 0\n    + on(node) group_left()\n    (\n        sum(kube_pod_container_resource_requests{cluster_id=\"$cluster\",resource=\"memory\"}) by (node)\n        /\n        sum(machine_memory_bytes{cluster_id=\"$cluster\"}) by (node)\n    )\n)",
     "legendFormat": "Memory"
    },
    {
     "expr": "avg(\n    kube_node_role{role=\"worker\"} * 0\n    + on(node) group_left()\n    (\n        sum(kube_pod_container_resource_requests{cluster_id=\"$cluster\",resource=\"cpu\"}) by (node)\n        /\n        sum(machine_cpu_cores{cluster_id=\"$cluster\"}) by (node)\n    )\n)",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Memory capacity",
   "type": "stat",
   "description": "Total of memory available in worker nodes currently (at the end of the selected time window)",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    kube_node_role{cluster_id=\"$cluster\",role=\"worker\"} * 0\n    + on(node) group_left()\n    (\n        sum(machine_memory_bytes{cluster_id=\"$cluster\"}) by (node)\n    )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory requests",
   "type": "stat",
   "description": "Total memory requests in worker nodes currently (at the end of the selected time window)",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    kube_node_role{cluster_id=\"$cluster\",role=\"worker\"} * 0\n    + on(node) group_left()\n    (\n        sum(kube_pod_container_resource_requests{cluster_id=\"$cluster\",resource=\"memory\"}) by (node)\n    )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU capacity",
   "type": "stat",
   "description": "Total CPU cores available in worker nodes currently (at the end of the selected time window)",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    kube_node_role{cluster_id=\"$cluster\",role=\"worker\"} * 0\n    + on(node) group_left()\n    (\n        sum(machine_cpu_cores{cluster_id=\"$cluster\"}) by (node)\n    )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU requests",
   "type": "stat",
   "description": "Total CPU requests in worker nodes currently (at the end of the selected time window)",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    kube_node_role{cluster_id=\"$cluster\",role=\"worker\"} * 0\n    + on(node) group_left()\n    (\n        sum(kube_pod_container_resource_requests{cluster_id=\"$cluster\",resource=\"cpu\"}) by (node)\n    )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Worker nodes over time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "count(kube_node_role{cluster_id=\"$cluster\",role=\"worker\"})",
     "legendFormat": "Worker nodes"
    }
   ]
  },
  {
   "title": "Memory request utilization average",
   "type": "timeseries",
   "description": "Total of memory requests, divided by the total memory available in worker nodes",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(\n    kube_node_role{role=\"worker\"} * 0\n    + on(node) group_left()\n    (\n        sum(kube_pod_container_resource_requests{cluster_id=\"$cluster\",resource=\"memory\"}) by (node)\n        /\n        sum(machine_memory_bytes{cluster_id=\"$cluster\"}) by (node)\n    )\n)",
     "legendFormat": "Average memory utilization"
    }
   ]
  },
  {
   "title": "Memory request total",
   "type": "timeseries",
   "description": "Total of memory requests in worker nodes",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(\n    kube_node_role{role=\"worker\"} * 0\n    + on(node) group_left()\n    (\n        sum(kube_pod_container_resource_requests{cluster_id=\"$cluster\",resource=\"memory\"}) by (node)\n    )\n)",
     "legendFormat": "Average memory utilization"
    }
   ]
  },
  {
   "title": "CPU requests utilization average",
   "type": "timeseries",
   "description": "Total CPU requests, divided by the number of cores available in worker nodes",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(\n    kube_node_role{role=\"worker\"} * 0\n    + on(node) group_left()\n    (\n        sum(kube_pod_container_resource_requests{cluster_id=\"$cluster\",resource=\"cpu\"}) by (node)\n        /\n        sum(machine_cpu_cores{cluster_id=\"$cluster\"}) by (node)\n    )\n)",
     "legendFormat": "Average CPU utilization"
    }
   ]
  },
  {
   "title": "CPU requests total",
   "type": "timeseries",
   "description": "Total CPU requests in worker nodes",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(\n    kube_node_role{role=\"worker\"} * 0\n    + on(node) group_left()\n    (\n        sum(kube_pod_container_resource_requests{cluster_id=\"$cluster\",resource=\"cpu\"}) by (node)\n    )\n)",
     "legendFormat": "Total CPU requests"
    }
   ]
  },
  { "title": "Node level requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Worker node resource requests",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n    kube_node_role{cluster_id=\"$cluster\",role=\"worker\"} * 0\n    + on(node) group_left()\n    (\n        sum(kube_pod_container_resource_requests{cluster_id=\"$cluster\",resource=\"memory\"}) by (node)\n        /\n        sum(machine_memory_bytes{cluster_id=\"$cluster\"}) by (node)\n    )\n) without (app, cluster_id, cluster_type, container, customer, endpoint, installation, instance, job, namespace, organization, pipeline, pod, provider, service, service_priority)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n    kube_node_role{cluster_id=\"$cluster\",role=\"worker\"} * 0\n    + on(node) group_left()\n    (\n        sum(kube_pod_container_resource_requests{cluster_id=\"$cluster\",resource=\"memory\"}) by (node)\n    )\n) without (app, cluster_id, cluster_type, container, customer, endpoint, installation, instance, job, namespace, organization, pipeline, pod, provider, service, service_priority)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n    kube_node_role{cluster_id=\"$cluster\",role=\"worker\"} * 0\n    + on(node) group_left()\n    (\n        sum(kube_pod_container_resource_requests{cluster_id=\"$cluster\",resource=\"cpu\"}) by (node)\n        /\n        sum(machine_cpu_cores{cluster_id=\"$cluster\"}) by (node)\n    )\n) without (app, cluster_id, cluster_type, container, customer, endpoint, installation, instance, job, namespace, organization, pipeline, pod, provider, service, service_priority)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n    kube_node_role{cluster_id=\"$cluster\",role=\"worker\"} * 0\n    + on(node) group_left()\n    (\n        sum(kube_pod_container_resource_requests{cluster_id=\"$cluster\",resource=\"cpu\"}) by (node)\n    )\n) without (app, cluster_id, cluster_type, container, customer, endpoint, installation, instance, job, namespace, organization, pipeline, pod, provider, service, service_priority)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n    kube_node_role{cluster_id=\"$cluster\",role=\"worker\"} * 0\n    + on(node) group_left(zone)\n    (\n        kube_node_labels{cluster_id=\"$cluster\"}\n    )\n) without (cluster_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Workload level requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Requests drill-down",
   "type": "table",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster_id=\"$cluster\",resource=\"memory\"}) by (node, namespace, pod, container, uid)\n+ on(node) group_left() kube_node_role{role=\"worker\"} * 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster_id=\"$cluster\",resource=\"cpu\"}) by (node, namespace, pod, container, uid)\n+ on(node) group_left() kube_node_role{role=\"worker\"} * 0",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}