{
 "title": "In-cluster container registry (Zot)",
 "description": "Usage metrics for the internal registry powered by Zot",
 "tags": [ "owner:team-honeybadger" ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "http_method",
    "query": {
     "query": "label_values(zot_http_method_latency_seconds_bucket,method)"
    }
   },
   {
    "name": "scheduler_workers_tasks_duration",
    "query": {
     "query": "label_values(zot_scheduler_workers_tasks_duration_seconds_bucket,name)"
    }
   },
   {
    "name": "storageName",
    "query": {
     "query": "label_values(zot_storage_lock_latency_seconds_bucket,storageName)"
    }
   },
   {
    "name": "repo_prefix",
    "label": "Repository prefix",
    "query": {
     "query": "label_values(zot_repo_downloads_total,repo)"
    }
   },
   {
    "name": "zot_pvc_name",
    "query": {
     "query": "label_values(kube_persistentvolumeclaim_info{cluster_type=\"management_cluster\", namespace=\"zot\"},persistentvolumeclaim)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Storage usage",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(zot_repo_storage_bytes) / sum(kube_persistentvolumeclaim_resource_requests_storage_bytes{persistentvolumeclaim=\"$zot_pvc_name\",namespace=\"zot\"})",
     "legendFormat": "Capacity"
    }
   ]
  },
  {
   "title": "Storage usage (absolute)",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(zot_repo_storage_bytes)", "legendFormat": "Capacity" }
   ]
  },
  {
   "title": "Storage capacity and usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(kube_persistentvolumeclaim_resource_requests_storage_bytes{persistentvolumeclaim=\"$zot_pvc_name\",namespace=\"zot\"})",
     "legendFormat": "Volume size"
    },
    { "expr": "sum(zot_repo_storage_bytes)", "legendFormat": "Storage space used" }
   ]
  },
  {
   "title": "Data transfer",
   "type": "timeseries",
   "description": "Data transmitted (pulled from the registry) and received (pushed to the registry)",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{namespace=~\"zot\", pod=~\".*-zot.*\"}[$__rate_interval]))",
     "legendFormat": "Transmitted"
    },
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace=~\"zot\", pod=~\".*-zot.*\"}[$__rate_interval])) * -1",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "Downloads",
   "type": "timeseries",
   "description": "Total number of image pulls served by the registry",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sum(zot_repo_downloads_total)", "legendFormat": "total" }
   ]
  },
  {
   "title": "Downloads rate",
   "type": "timeseries",
   "description": "Total images pulled in the time interval",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "sum(rate(zot_repo_downloads_total[$__rate_interval]))*60",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Uploads",
   "type": "timeseries",
   "description": "Total number of image uploads to the registry",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sum(zot_repo_uploads_total)", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Uploads rate",
   "type": "timeseries",
   "description": "Uploads per time interval",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "sum(rate(zot_repo_uploads_total[$__rate_interval]))*60.0",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Usage by repository",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Downloads by repository",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "sum(zot_repo_downloads_total{repo=~\"$repo_prefix.*\"}) by (repo)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Download rate by repository",
     "type": "timeseries",
     "description": "Download rate broken down by image repository",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "opm" } },
     "targets": [
      {
       "expr": "sum(rate(zot_repo_downloads_total{repo=~\"$repo_prefix.*\"}[$__rate_interval])) by (repo) *60",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Uploads by repository",
     "type": "timeseries",
     "description": "Uploaded images broken down by repository",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "sum(zot_repo_uploads_total{repo=~\"$repo_prefix.*\"}) by (repo)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Upload rate by repository",
     "type": "timeseries",
     "description": "Uploads per time interval, broken down by image repository",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "opm" } },
     "targets": [
      {
       "expr": "sum(rate(zot_repo_uploads_total{repo=~\"$repo_prefix.*\"}[$__rate_interval])) by (repo) *60",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Storage usage by repository",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(zot_repo_storage_bytes{repo=~\"$repo_prefix.*\"}) by (repo)",
       "legendFormat": "{{repo}}"
      }
     ]
    },
    {
     "title": "Storage usage rate by repository",
     "type": "timeseries",
     "description": "Storage usage rate broken down by image repository",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(zot_repo_storage_bytes{repo=~\"$repo_prefix.*\"}[$__rate_interval])) by (repo)",
       "legendFormat": "{{repo}}"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP response latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP latency",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(zot_http_repo_latency_seconds_sum[$__rate_interval]))",
       "legendFormat": "{{repo}}"
      }
     ]
    },
    {
     "title": "HTT latency by repository",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(zot_http_repo_latency_seconds_sum[$__rate_interval])",
       "legendFormat": "{{repo}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Uploads by prefix",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uploads by repo prefix $repo_prefix",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
     "repeat": "repo_prefix",
     "targets": [
      {
       "expr": "sum(zot_repo_uploads_total{repo=~\"$repo_prefix.*\"})",
       "legendFormat": "$repo_prefix"
      }
     ]
    },
    {
     "title": "Uploads rate by repo prefix $repo_prefix",
     "type": "timeseries",
     "description": "rate per minute",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
     "repeat": "repo_prefix",
     "targets": [
      {
       "expr": "sum(rate(zot_repo_uploads_total{repo=~\"$repo_prefix.*\"}[$__rate_interval]))*60",
       "legendFormat": "$repo_prefix"
      }
     ]
    }
   ]
  },
  {
   "title": "Downloads by repo prefix",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Downloads by repo prefix $repo_prefix",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
     "repeat": "repo_prefix",
     "targets": [
      {
       "expr": "sum(zot_repo_downloads_total{repo=~\"$repo_prefix.*\"})",
       "legendFormat": "$repo_prefix"
      }
     ]
    },
    {
     "title": "Downloads rate by repo prefix $repo_prefix",
     "type": "timeseries",
     "description": "rate per minute",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
     "repeat": "repo_prefix",
     "targets": [
      {
       "expr": "sum(rate(zot_repo_downloads_total{repo=~\"$repo_prefix.*\"}[$__rate_interval]))*60",
       "legendFormat": "$repo_prefix"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage per prefix",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Storage Usage by repo prefix $repo_prefix",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
     "repeat": "repo_prefix",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(zot_repo_storage_bytes{repo=~\"$repo_prefix.*\"})",
       "legendFormat": "$repo_prefix"
      }
     ]
    },
    {
     "title": "Storage usage change by repo prefix $repo_prefix",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
     "repeat": "repo_prefix",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(zot_repo_storage_bytes{repo=~\"$repo_prefix.*\"}[$__rate_interval]))*60",
       "legendFormat": "$repo_prefix"
      }
     ]
    }
   ]
  },
  {
   "title": "Scheduler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Generators - Priority High",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(zot_scheduler_generators_status{priority=\"high\"}) by (state)",
       "legendFormat": "{{priority}} {{state}}"
      }
     ]
    },
    {
     "title": "Generators - Priority Medium",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(zot_scheduler_generators_status{priority=\"medium\"}) by (state)",
       "legendFormat": "{{priority}} {{state}}"
      }
     ]
    },
    {
     "title": "Generators - Priority Low",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(zot_scheduler_generators_status{priority=\"low\"}) by (state)",
       "legendFormat": "{{priority}} {{state}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Scheduler workers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Task Queue Length by priority",
     "type": "timeseries",
     "description": "Number of tasks in the queue waiting to be processed by scheduler workers",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(zot_scheduler_tasksqueue_length) by (priority)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total workers",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(zot_scheduler_workers_total)",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Workers by state",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(zot_scheduler_workers) by (state)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP latency heatmaps by method",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "$http_method",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 27 },
     "repeat": "http_method",
     "targets": [
      {
       "expr": "sum(increase(zot_http_method_latency_seconds_bucket{method=\"$http_method\"}[$__interval])) by (le)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Task duration heatmaps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "$scheduler_workers_tasks_duration",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 28 },
     "repeat": "scheduler_workers_tasks_duration",
     "targets": [
      {
       "expr": "sum(increase(zot_scheduler_workers_tasks_duration_seconds_bucket{name=\"$scheduler_workers_tasks_duration\"}[$__interval])) by (le)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage lock latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "$storageName",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
     "repeat": "storageName",
     "targets": [
      {
       "expr": "sum(increase(zot_storage_lock_latency_seconds_bucket{storageName=\"$storageName\"}[$__interval])) by (le)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}