{
 "title": "Cilium Agent logs",
 "tags": [ "owner:team-cabbage" ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kubernetes_build_info,cluster_id)"
    }
   },
   {
    "name": "k8sversion",
    "label": "k8sversion",
    "query": {
     "query": "label_values(kubernetes_build_info{cluster_id=\"$cluster\"},git_version)"
    }
   },
   {
    "name": "ciliumversion",
    "label": "ciliumversion",
    "query": {
     "query": "label_values(cilium_version{cluster_id=\"$cluster\"},version)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster Info",
   "type": "text",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"display:grid; justify-content:center;align-items: center;\">\n  <div style=\"text-align: center;\">\n  <img src=\"https://upload.wikimedia.org/wikipedia/commons/3/39/Kubernetes_logo_without_workmark.svg\" \n   style=\"max-height:50px; float:right; margin-top:20px\"/>\n  <p >\n   Cluster ID: <b>${cluster}</b><br/>\n   K8S Version: <b>${k8sversion}</b><br/>\n  </p>\n   \n</div>\n<div style=\"text-align: center;\">\n<img src=\"https://cilium.io/static/cilium-dark-1-8c7358e82e52a0ccab8d1d056de00c50.svg\" \n   style=\"max-height:50px; float:right; margin-top:20px\"/>\n  <p>\n   Cilium Version: <b>${ciliumversion}</b><br/>\n  </p>\n</div>\n</div>"
   }
  },
  {
   "title": "Errors & Warnings",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 5, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (level) (count_over_time({service_name=\"cilium-agent\", cluster_id=\"$cluster\"} | logfmt | level =~ `error|warning`[$__auto]))",
     "legendFormat": "{{ level }}"
    }
   ]
  },
  {
   "title": "Errors & Warnings",
   "type": "logs",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 7 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"cilium-agent\", cluster_id=\"$cluster\"} | logfmt | level =~ `error|warning` | line_format \"pod={{.pod}} msg={{.msg}} error={{.error}} endpoint={{.ciliumEndpointName}}\""
    }
   ]
  },
  {
   "title": "Top 10 Errors",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (msg) (count_over_time({service_name=\"cilium-agent\", cluster_id=\"$cluster\"} | logfmt | level = `error`[$__auto]))",
     "legendFormat": "{{ msg }}"
    }
   ]
  },
  {
   "title": "Top 10 Warnings",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (msg) (count_over_time({service_name=\"cilium-agent\", cluster_id=\"$cluster\"} | logfmt | level = `warning`[$__auto]))",
     "legendFormat": "{{ msg }}"
    }
   ]
  },
  {
   "title": "Failing Cilium Network Policies ",
   "type": "table",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 23 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (k8sNamespace, ciliumNetworkPolicyName) (rate({service_name=\"cilium-agent\", cluster_id=\"$cluster\"} | logfmt | msg = `Unable to add CiliumNetworkPolicy` | level =~ `error|warning`[$__auto]))"
    }
   ]
  }
 ]
}