{
 "title": "AWS Service Limits",
 "tags": [
  "provider:aws",
  "owner:team-phoenix"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "region",
    "label": "Region",
    "query": "label_values(aws_operator_service_usage, region)"
   },
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(aws_operator_service_usage, service)"
   },
   {
    "name": "name",
    "label": "Name",
    "query": "label_values(aws_operator_service_usage, name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Number of resources exceeding critical usage limit",
   "type": "stat",
   "description": "The number of resources that are currently exceeding 80% of their usage limit",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(aws_operator_service_usage / aws_operator_service_limit * 100 > 80) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Is service limit usage data available?",
   "type": "stat",
   "description": "Only AWS accounts with Business or Enterprise level support plans can expose service limits and usage.",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_operator_trusted_advisor_supported"
    }
   ]
  },
  {
   "title": "Resources exceeding critical usage percentage",
   "type": "table",
   "description": "All resources that are currently using more than 80% of their limit",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "aws_operator_service_usage / aws_operator_service_limit * 100 > 80"
    }
   ]
  },
  {
   "title": "Service Limit Usage Percentage",
   "type": "timeseries",
   "description": "The usage of AWS resources, as a percentage of their overall limit.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "aws_operator_service_usage{region=~\"$region\", service=~\"$service\", name=~\"$name\"} / aws_operator_service_limit{region=~\"$region\", service=~\"$service\", name=~\"$name\"} * 100",
     "legendFormat": " {{ service }} - {{ name }} ({{ region }})"
    }
   ]
  },
  {
   "title": "Service Usage",
   "type": "timeseries",
   "description": "The usage of AWS resources.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_operator_service_usage{region=~\"$region\", service=~\"$service\", name=~\"$name\"}",
     "legendFormat": " {{ service }} - {{ name }} ({{ region }})"
    }
   ]
  },
  {
   "title": "Service Limit",
   "type": "timeseries",
   "description": "The limits of AWS resources.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_operator_service_limit{region=~\"$region\", service=~\"$service\", name=~\"$name\"}",
     "legendFormat": " {{ service }} - {{ name }} ({{ region }})"
    }
   ]
  }
 ]
}