{
 "title": "AWS Instances",
 "tags": [
  "provider:aws",
  "topic:management-cluster",
  "topic:workload-cluster",
  "owner:team-phoenix"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Current status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Instances",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(aws_operator_ec2_instance_status)"
    }
   ]
  },
  {
   "title": "Unhealthy Instances",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(aws_operator_ec2_instance_status == 0)"
    }
   ]
  },
  {
   "title": "Total Instances in Management cluster",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(aws_operator_ec2_instance_status{cluster_id=\"\"})"
    }
   ]
  },
  {
   "title": "Unhealthy in Management cluster",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(aws_operator_ec2_instance_status{cluster_id=\"\"} == 0)"
    }
   ]
  },
  {
   "title": "Total Instances in Workload Clusters",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(aws_operator_ec2_instance_status{cluster_id!=\"\"})"
    }
   ]
  },
  {
   "title": "Unhealthy in Workload Clusters",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(aws_operator_ec2_instance_status{cluster_id!=\"\"} == 0)"
    }
   ]
  },
  {
   "title": "Status over time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Healthy EC2 Instances",
   "type": "timeseries",
   "description": "Number of healthy instances per cluster",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(aws_operator_ec2_instance_status{cluster_id=\"\"}) by (account)",
     "legendFormat": "Management cluster (account {{ account }})"
    },
    {
     "expr": "sum(aws_operator_ec2_instance_status{cluster_id!=\"\"}) by (account, cluster_id)",
     "legendFormat": "Workload cluster {{ cluster_id }}  (account {{ account }})"
    }
   ]
  },
  {
   "title": "Unhealthy EC2 Instances",
   "type": "timeseries",
   "description": "Information on instances not running/ok. This could also mean that an instance is coming up or being removed.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(aws_operator_ec2_instance_status == 0) by (account, cluster_id, state, status)",
     "legendFormat": "Account {{ account }} – {{ cluster_id }}: {{ state }}/{{ status }} "
    }
   ]
  },
  {
   "title": "Tables",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Instances by type and account",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "count(aws_operator_ec2_instance_status) by (account, instance_type)"
    }
   ]
  },
  {
   "title": "Instances by state and status",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "count(aws_operator_ec2_instance_status) by (account, availability_zone, cluster_id, state, status)"
    }
   ]
  }
 ]
}