{
 "title": "Container images from docker.io",
 "description": "Helps to identify workloads using images from Docker Hub (docker.io)",
 "tags": [ "owner:team-honeybadger" ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "About this dashboard",
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "# Images from docker.io\n\nThis dashboard should help you identify containers using images from `docker.io`. Images from the `giantswarm` registry namespace (`docker.io/giantswarm/*`) are filtered out. If there is no data shown, this means that none of the containers in this installation is using a docker.io image."
   }
  },
  {
   "title": "Containers total",
   "type": "stat",
   "description": "Number of all containers running in workload clusters",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_info or kube_pod_init_container_info)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Containers from docker.io",
   "type": "stat",
   "description": "Number of containers in workload clusters with image from docker.io",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_info{image_spec=~\"docker.io.*\",image_spec!~\".*/giantswarm/.*\",cluster_type=\"workload_cluster\"} or kube_pod_init_container_info{image_spec=~\"docker.io.*\",image_spec!~\".*/giantswarm/.*\",cluster_type=\"workload_cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Share of containers from docker.io",
   "type": "stat",
   "description": "Percentage of containers in workload clusters with image from docker.io",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_info{image_spec=~\"docker.io.*\",image_spec!~\".*/giantswarm/.*\",cluster_type=\"workload_cluster\"} or kube_pod_init_container_info{image_spec=~\"docker.io.*\",image_spec!~\".*/giantswarm/.*\",cluster_type=\"workload_cluster\"}) / sum(kube_pod_container_info or kube_pod_init_container_info)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Containers over time",
   "type": "timeseries",
   "description": "Count of all containers in workload clusters using images from docker.io, excluding those with prefix \"docker.io/giantswarm\".",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_info{image_spec=~\"docker.io.*\",image_spec!~\".*/giantswarm/.*\",cluster_type=\"workload_cluster\"} or kube_pod_init_container_info{image_spec=~\"docker.io.*\",image_spec!~\".*/giantswarm/.*\",cluster_type=\"workload_cluster\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Container details",
   "type": "table",
   "description": "Details of all containers in workload clusters using images from docker.io, excluding those with prefix \"docker.io/giantswarm\".",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_info{image_spec=~\"docker.io.*\",image_spec!~\".*giantswarm.*\",cluster_type=\"workload_cluster\"} or kube_pod_init_container_info{image_spec=~\"docker.io.*\",image_spec!~\".*giantswarm.*\",cluster_type=\"workload_cluster\"}) by (organization, cluster_id, namespace, pod, container, image)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Image list",
   "type": "table",
   "description": "A flat list of the images used and the number of containers using the image",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_info{image_spec=~\"docker.io.*\",image_spec!~\".*/giantswarm/.*\",cluster_type=\"workload_cluster\"} or kube_pod_init_container_info{image_spec=~\"docker.io.*\",image_spec!~\".*/giantswarm/.*\",cluster_type=\"workload_cluster\"}) by (image)",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}