{
 "title": "Kubernetes / Compute Resources / Cluster",
 "tags": [
  "origin:kubernetes-mixin",
  "owner:team-turtles"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(up{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\"}, cluster_id)"
   }
  ]
 },
 "panels": [
  {
   "title": "Headlines",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Utilisation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cluster:node_cpu:ratio_rate5m{cluster_id=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "CPU Requests Commitment",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(namespace_cpu:kube_pod_container_resource_requests:sum{cluster_id=\"$cluster\"}) / sum(kube_node_status_allocatable{resource=\"cpu\",cluster_id=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "CPU Limits Commitment",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(namespace_cpu:kube_pod_container_resource_limits:sum{cluster_id=\"$cluster\"}) / sum(kube_node_status_allocatable{resource=\"cpu\",cluster_id=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Memory Utilisation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1 - sum(:node_memory_MemAvailable_bytes:sum{cluster_id=\"$cluster\"}) / sum(node_memory_MemTotal_bytes{cluster_id=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Memory Requests Commitment",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(namespace_memory:kube_pod_container_resource_requests:sum{cluster_id=\"$cluster\"}) / sum(kube_node_status_allocatable{resource=\"memory\",cluster_id=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Memory Limits Commitment",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(namespace_memory:kube_pod_container_resource_limits:sum{cluster_id=\"$cluster\"}) / sum(kube_node_status_allocatable{resource=\"memory\",cluster_id=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster_id=\"$cluster\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "CPU Quota",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Quota",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_owner{cluster_id=\"$cluster\"}) by (namespace)"
    },
    {
     "expr": "count(avg(namespace_workload_pod:kube_pod_owner:relabel{cluster_id=\"$cluster\"}) by (workload, namespace)) by (namespace)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster_id=\"$cluster\"}) by (namespace)"
    },
    {
     "expr": "sum(namespace_cpu:kube_pod_container_resource_requests:sum{cluster_id=\"$cluster\"}) by (namespace)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster_id=\"$cluster\"}) by (namespace) / sum(namespace_cpu:kube_pod_container_resource_requests:sum{cluster_id=\"$cluster\"}) by (namespace)"
    },
    {
     "expr": "sum(namespace_cpu:kube_pod_container_resource_limits:sum{cluster_id=\"$cluster\"}) by (namespace)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster_id=\"$cluster\"}) by (namespace) / sum(namespace_cpu:kube_pod_container_resource_limits:sum{cluster_id=\"$cluster\"}) by (namespace)"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Usage (w/o cache)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{cluster_id=\"$cluster\", container!=\"\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Memory Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requests by Namespace",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_owner{cluster_id=\"$cluster\"}) by (namespace)"
    },
    {
     "expr": "count(avg(namespace_workload_pod:kube_pod_owner:relabel{cluster_id=\"$cluster\"}) by (workload, namespace)) by (namespace)"
    },
    {
     "expr": "sum(container_memory_rss{cluster_id=\"$cluster\", container!=\"\"}) by (namespace)"
    },
    {
     "expr": "sum(namespace_memory:kube_pod_container_resource_requests:sum{cluster_id=\"$cluster\"}) by (namespace)"
    },
    {
     "expr": "sum(container_memory_rss{cluster_id=\"$cluster\", container!=\"\"}) by (namespace) / sum(namespace_memory:kube_pod_container_resource_requests:sum{cluster_id=\"$cluster\"}) by (namespace)"
    },
    {
     "expr": "sum(namespace_memory:kube_pod_container_resource_limits:sum{cluster_id=\"$cluster\"}) by (namespace)"
    },
    {
     "expr": "sum(container_memory_rss{cluster_id=\"$cluster\", container!=\"\"}) by (namespace) / sum(namespace_memory:kube_pod_container_resource_limits:sum{cluster_id=\"$cluster\"}) by (namespace)"
    }
   ]
  },
  {
   "title": "Current Network Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Current Network Usage",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{cluster_id=\"$cluster\", namespace=~\".+\"}[$__rate_interval])) by (namespace)"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{cluster_id=\"$cluster\", namespace=~\".+\"}[$__rate_interval])) by (namespace)"
    },
    {
     "expr": "sum(irate(container_network_receive_packets_total{cluster_id=\"$cluster\", namespace=~\".+\"}[$__rate_interval])) by (namespace)"
    },
    {
     "expr": "sum(irate(container_network_transmit_packets_total{cluster_id=\"$cluster\", namespace=~\".+\"}[$__rate_interval])) by (namespace)"
    },
    {
     "expr": "sum(irate(container_network_receive_packets_dropped_total{cluster_id=\"$cluster\", namespace=~\".+\"}[$__rate_interval])) by (namespace)"
    },
    {
     "expr": "sum(irate(container_network_transmit_packets_dropped_total{cluster_id=\"$cluster\", namespace=~\".+\"}[$__rate_interval])) by (namespace)"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Receive Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{cluster_id=\"$cluster\", namespace=~\".+\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{cluster_id=\"$cluster\", namespace=~\".+\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Average Container Bandwidth by Namespace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Average Container Bandwidth by Namespace: Received",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg(irate(container_network_receive_bytes_total{cluster_id=\"$cluster\", namespace=~\".+\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Average Container Bandwidth by Namespace: Transmitted",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg(irate(container_network_transmit_bytes_total{cluster_id=\"$cluster\", namespace=~\".+\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Rate of Packets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate of Received Packets",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_packets_total{cluster_id=\"$cluster\", namespace=~\".+\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Rate of Transmitted Packets",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_packets_total{cluster_id=\"$cluster\", namespace=~\".+\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Rate of Packets Dropped",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate of Received Packets Dropped",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_packets_dropped_total{cluster_id=\"$cluster\", namespace=~\".+\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Rate of Transmitted Packets Dropped",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_packets_dropped_total{cluster_id=\"$cluster\", namespace=~\".+\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Storage IO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 },
   "targets": [
    {}
   ]
  },
  {
   "title": "IOPS(Reads+Writes)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ceil(sum by(namespace) (rate(container_fs_reads_total{container!=\"\", device=~\"(/dev.+)|mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\", cluster_id=\"$cluster\", namespace!=\"\"}[$__rate_interval]) + rate(container_fs_writes_total{container!=\"\", cluster_id=\"$cluster\", namespace!=\"\"}[$__rate_interval])))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "ThroughPut(Read+Write)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(namespace) (rate(container_fs_reads_bytes_total{container!=\"\", device=~\"(/dev.+)|mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\", cluster_id=\"$cluster\", namespace!=\"\"}[$__rate_interval]) + rate(container_fs_writes_bytes_total{container!=\"\", cluster_id=\"$cluster\", namespace!=\"\"}[$__rate_interval]))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Storage IO - Distribution",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Current Storage IO",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(namespace) (rate(container_fs_reads_total{device=~\"(/dev.+)|mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\", container!=\"\", cluster_id=\"$cluster\", namespace!=\"\"}[$__rate_interval]))"
    },
    {
     "expr": "sum by(namespace) (rate(container_fs_writes_total{device=~\"(/dev.+)|mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\", container!=\"\", cluster_id=\"$cluster\", namespace!=\"\"}[$__rate_interval]))"
    },
    {
     "expr": "sum by(namespace) (rate(container_fs_reads_total{device=~\"(/dev.+)|mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\", container!=\"\", cluster_id=\"$cluster\", namespace!=\"\"}[$__rate_interval]) + rate(container_fs_writes_total{device=~\"(/dev.+)|mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\", container!=\"\", cluster_id=\"$cluster\", namespace!=\"\"}[$__rate_interval]))"
    },
    {
     "expr": "sum by(namespace) (rate(container_fs_reads_bytes_total{device=~\"(/dev.+)|mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\", container!=\"\", cluster_id=\"$cluster\", namespace!=\"\"}[$__rate_interval]))"
    },
    {
     "expr": "sum by(namespace) (rate(container_fs_writes_bytes_total{device=~\"(/dev.+)|mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\", container!=\"\", cluster_id=\"$cluster\", namespace!=\"\"}[$__rate_interval]))"
    },
    {
     "expr": "sum by(namespace) (rate(container_fs_reads_bytes_total{device=~\"(/dev.+)|mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\", container!=\"\", cluster_id=\"$cluster\", namespace!=\"\"}[$__rate_interval]) + rate(container_fs_writes_bytes_total{device=~\"(/dev.+)|mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\", container!=\"\", cluster_id=\"$cluster\", namespace!=\"\"}[$__rate_interval]))"
    }
   ]
  }
 ]
}