{
 "title": "Kubernetes / Networking / Namespace (Pods)",
 "tags": [
  "origin:kubernetes-mixin",
  "owner:team-cabbage"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(up{app=\"cadvisor\"}, cluster_id)"
   },
   {
    "name": "namespace",
    "query": "label_values(container_network_receive_packets_total{cluster_id=\"$cluster\"}, namespace)"
   },
   { "name": "resolution", "query": "30s,5m,1h" },
   { "name": "interval", "query": "4h" }
  ]
 },
 "panels": [
  {
   "title": "Current Bandwidth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Current Rate of Bytes Received",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "format": "time_series",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{cluster_id=\"$cluster\",namespace=~\"$namespace\"}[$interval:$resolution]))"
    }
   ]
  },
  {
   "title": "Current Rate of Bytes Transmitted",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "format": "time_series",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{cluster_id=\"$cluster\",namespace=~\"$namespace\"}[$interval:$resolution]))"
    }
   ]
  },
  {
   "title": "Current Status",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{cluster_id=\"$cluster\",namespace=~\"$namespace\"}[$interval:$resolution])) by (pod)"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{cluster_id=\"$cluster\",namespace=~\"$namespace\"}[$interval:$resolution])) by (pod)"
    },
    {
     "expr": "sum(irate(container_network_receive_packets_total{cluster_id=\"$cluster\",namespace=~\"$namespace\"}[$interval:$resolution])) by (pod)"
    },
    {
     "expr": "sum(irate(container_network_transmit_packets_total{cluster_id=\"$cluster\",namespace=~\"$namespace\"}[$interval:$resolution])) by (pod)"
    },
    {
     "expr": "sum(irate(container_network_receive_packets_dropped_total{cluster_id=\"$cluster\",namespace=~\"$namespace\"}[$interval:$resolution])) by (pod)"
    },
    {
     "expr": "sum(irate(container_network_transmit_packets_dropped_total{cluster_id=\"$cluster\",namespace=~\"$namespace\"}[$interval:$resolution])) by (pod)"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Receive Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{cluster_id=\"$cluster\",namespace=~\"$namespace\"}[$interval:$resolution])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{cluster_id=\"$cluster\",namespace=~\"$namespace\"}[$interval:$resolution])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Packets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate of Received Packets",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_packets_total{cluster_id=\"$cluster\",namespace=~\"$namespace\"}[$interval:$resolution])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Rate of Transmitted Packets",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_packets_total{cluster_id=\"$cluster\",namespace=~\"$namespace\"}[$interval:$resolution])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate of Received Packets Dropped",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_packets_dropped_total{cluster_id=\"$cluster\",namespace=~\"$namespace\"}[$interval:$resolution])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Rate of Transmitted Packets Dropped",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_packets_dropped_total{cluster_id=\"$cluster\",namespace=~\"$namespace\"}[$interval:$resolution])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}