{
 "title": "Envoy Gateway | Performance comparison (Ingress-NGINX)",
 "description": "Compare performance and behavior under load: Envoy Gateway vs Nginx Ingress Controller",
 "tags": [
  "owner:team-cabbage",
  "managed-by: observability-operator"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "workload_cluster",
    "label": "Workload Cluster",
    "query": {
     "query": "label_values(kubernetes_build_info,cluster_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Resources usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Envoy Gateway CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(\n    max by (cluster_id, namespace, pod, container)(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate5m{cluster_id=\"$workload_cluster\", namespace=\"envoy-gateway-system\"})\n  * on(cluster_id, namespace, pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster_id=\"$workload_cluster\", namespace=\"envoy-gateway-system\", workload_type=\"deployment\"}\n) by (workload)",
     "legendFormat": "{{workload}}"
    },
    {
     "expr": "sum(\n    max by (cluster_id, namespace, pod, container)(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate5m{cluster_id=\"$workload_cluster\", namespace=\"envoy-gateway-system\"})\n  * on(cluster_id, namespace, pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster_id=\"$workload_cluster\", namespace=\"envoy-gateway-system\", workload_type=\"deployment\"}\n) by (cluster_id)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "NGINX Ingress Controller CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(\n    max by (cluster_id, namespace, pod, container)(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate5m{cluster_id=\"$workload_cluster\", namespace=\"kube-system\"})\n  * on(cluster_id, namespace, pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster_id=\"$workload_cluster\", namespace=\"kube-system\", workload=\"ingress-nginx-controller\", workload_type=\"deployment\"}\n) by (workload)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Envoy Gateway Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\n    max by (cluster_id, namespace, pod, container)(container_memory_working_set_bytes{cluster_id=\"$workload_cluster\", namespace=\"envoy-gateway-system\", container!=\"\", image!=\"\"})\n  * on(cluster_id, namespace, pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster_id=\"$workload_cluster\", namespace=\"envoy-gateway-system\", workload_type=\"deployment\"}\n) by (workload)",
     "legendFormat": "{{workload}}"
    },
    {
     "expr": "sum(\n    max by (cluster_id, namespace, pod, container)(container_memory_working_set_bytes{cluster_id=\"$workload_cluster\", namespace=\"envoy-gateway-system\", container!=\"\", image!=\"\"})\n  * on(cluster_id, namespace, pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster_id=\"$workload_cluster\", namespace=\"envoy-gateway-system\", workload_type=\"deployment\"}\n) by (cluster_id)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "NGINX Ingress Controller Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\n    max by (cluster_id, namespace, pod, container)(container_memory_working_set_bytes{cluster_id=\"$workload_cluster\", namespace=\"kube-system\", container!=\"\", image!=\"\"})\n  * on(cluster_id, namespace, pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster_id=\"$workload_cluster\", namespace=\"kube-system\", workload=\"ingress-nginx-controller\", workload_type=\"deployment\"}\n) by (workload)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Downstream network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Envoy Gateway downstram RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_total{cluster_id=\"$workload_cluster\"}[5m]))",
     "legendFormat": "Envoy HTTP Downstream Rq total"
    }
   ]
  },
  {
   "title": "Nginx Ingress Controller downstream RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{cluster_id=\"$workload_cluster\",controller_namespace=\"kube-system\"}[5m]))",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "Envoy Gateway downstream Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(envoy_http_downstream_rq_time_bucket{cluster_id=\"$workload_cluster\"}[5m])))",
     "legendFormat": "{{service}} 90%"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(envoy_http_downstream_rq_time_bucket{cluster_id=\"$workload_cluster\"}[5m])))",
     "legendFormat": "{{service}} 50% "
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(envoy_http_downstream_rq_time_bucket{cluster_id=\"$workload_cluster\"}[5m])))",
     "legendFormat": "{{service}} 99%"
    }
   ]
  },
  {
   "title": "Nginx Ingress Controller downstream Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{cluster_id=\"$workload_cluster\"}[5m]))) * 1000",
     "legendFormat": "{{service}} 90%"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{cluster_id=\"$workload_cluster\"}[5m]))) * 1000",
     "legendFormat": "{{service}} 50% "
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{cluster_id=\"$workload_cluster\"}[5m]))) * 1000",
     "legendFormat": "{{service}} 99%"
    }
   ]
  },
  {
   "title": "Envoy Gateway downstream requests success rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_xx{\n    cluster_id=\"$workload_cluster\",\n    envoy_response_code_class!~\"4|5\"\n    }[5m])) by (cluster_id)\n/\nsum(rate(envoy_http_downstream_rq_xx{\n    cluster_id=\"$workload_cluster\"\n    }[5m])) by (cluster_id)\n* 100",
     "legendFormat": "Value"
    }
   ]
  },
  {
   "title": "Nginx Ingress Controller downstream requests success rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{\n    cluster_id=\"$workload_cluster\",\n    status!~\"[4-5].*\"\n    }[5m])) by (cluster_id)\n/\nsum(rate(nginx_ingress_controller_requests{\n    cluster_id=\"$workload_cluster\",\n    }[5m])) by (cluster_id)\n* 100",
     "legendFormat": "Value"
    }
   ]
  },
  { "title": "Upstream network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Envoy Gateway upstream RPS",
   "type": "timeseries",
   "description": "Displays the number of Requests per Second being performed against each Upstream.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(namespace) (rate(envoy_cluster_upstream_rq_total{cluster_id=\"$workload_cluster\", namespace=\"envoy-gateway-system\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nginx Ingress Controller upstream RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_upstream_latency_seconds_count{cluster_id=\"$workload_cluster\",controller_namespace=\"kube-system\"}[5m]))",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "Envoy Gateway upstream Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(envoy_cluster_upstream_rq_time_bucket{cluster_id=\"$workload_cluster\", namespace=\"envoy-gateway-system\"}[5m])) by (le, namespace))",
     "legendFormat": "{{namespace}} 99%"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(envoy_cluster_upstream_rq_time_bucket{cluster_id=\"$workload_cluster\", namespace=\"envoy-gateway-system\"}[5m])) by (le, namespace))",
     "legendFormat": "{{namespace}} 90%"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(envoy_cluster_upstream_rq_time_bucket{cluster_id=\"$workload_cluster\", namespace=\"envoy-gateway-system\"}[5m])) by (le, namespace))",
     "legendFormat": "{{namespace}} 50% "
    }
   ]
  }
 ]
}