{
 "title": "API Security",
 "description": "An overview on the success rate of authentication via the old Giant Swarm REST API (if present).",
 "tags": [
  "owner:team-rainbow",
  "provider:kvm",
  "provider:aws",
  "provider:azure",
  "topic:management-cluster"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "About this dashboard",
   "type": "text",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# API Security\n\nThis Dashboard gives an overview on success and error responses for the old Giant Swarm `api` components running on your management cluster.\nAs we are in the process of replacing these services with SSO, this dashboard will mostly be interesting to you if your installation is on `kvm`, you have clusters in versions older than `v16.0.1` on cloud providers or you are not using `SSO` to authenticate yet.\nAccordingly, if you can not see metrics here it is because these legacy components are no longer present on your management cluster.\n\n\nAll graph metrics are calculated based on error/success rate within a sliding 5 minute window. The single stats show the average of these metrics within the selected time frame.\n\n**HTTP Response Codes** [More Info](https://restfulapi.net/http-status-codes/)\n\n`1xx` Info `2xx` Success `3xx` Redirect `4xx` Client error `5xx` Server error\n"
   }
  },
  {
   "title": "API Success Response Rate",
   "type": "stat",
   "description": "Percentage of successful responses across all api requests in the last 5 minutes. Displays the average value in the selected time window.",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (increase(endpoint_total{code=~\"^[2]..$\", app=\"api\"}[5m]))/sum (increase(endpoint_total{app=\"api\"}[5m]))"
    }
   ]
  },
  {
   "title": "API Success Response Codes",
   "type": "timeseries",
   "description": "Successful api responses in the last 5 minutes.",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (increase(endpoint_total{code=~\"^[2]..$\", app=\"api\"}[5m])) by (code)",
     "legendFormat": "{{code}}"
    },
    { "expr": "health" }
   ]
  },
  {
   "title": "Endpoint Errors",
   "type": "stat",
   "description": "Number of api endpoint error responses in the last 5 minutes. Displays the average value in the selected time window.",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (increase(endpoint_total{code=~\"^[^2]..$\", app=\"api\"}[5m]))"
    }
   ]
  },
  {
   "title": "API Error Response Codes",
   "type": "timeseries",
   "description": "Error api responses in the last 5 minutes.",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (increase(endpoint_total{code=~\"^[^2]..$\", app=\"api\"}[5m])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Cluster-Service Success Response Rate",
   "type": "stat",
   "description": "Percentage of successful responses across all cluster-service requests in the last 5 minutes. Displays the average value in the selected time window.",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (increase(endpoint_total{code=~\"^[2]..$\", app=\"cluster-service\"}[5m]))/sum (increase(endpoint_total{app=\"cluster-service\"}[5m]))"
    }
   ]
  },
  {
   "title": "Cluster-Service Success Response Codes",
   "type": "timeseries",
   "description": "Successful cluster-service responses in the last 5 minutes.",
   "gridPos": { "h": 6, "w": 10, "x": 5, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (increase(endpoint_total{code=~\"^[2]..$\", app=\"cluster-service\"}[5m])) by (code)",
     "legendFormat": "{{code}}"
    },
    { "expr": "health" }
   ]
  },
  {
   "title": "Cluster-Service Error Response Codes",
   "type": "timeseries",
   "description": "Error cluster-service responses in the last 5 minutes.",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (increase(endpoint_total{code=~\"^[^2]..$\", app=\"cluster-service\"}[5m])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Failed Authentication Attempts",
   "type": "timeseries",
   "description": "Error endpoint responses in the last 5 minutes.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(api_endpoint_authtoken_creator_failed_attempts_total[5m]))",
     "legendFormat": "Email/Password failures"
    },
    {
     "expr": "sum(increase(endpoint_total{code=\"401\"}[5m]))",
     "legendFormat": "401 Errors"
    }
   ]
  }
 ]
}