{
 "title": "Credentials",
 "tags": [ "owner:team-biscuit" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Credentials",
   "type": "table",
   "description": "List of credentials currently installed",
   "gridPos": { "h": 21, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(credentiald_credential_info) by (name, organization)"
    }
   ]
  },
  {
   "title": "Credentiald Requests",
   "type": "graph",
   "description": "Rate of requests to credentiald to create, list, and search for credentials.",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(credentiald_credentials_create_count[5m]))",
     "legendFormat": "create"
    },
    {
     "expr": "sum(rate(credentiald_credentials_list_count[5m]))",
     "legendFormat": "list"
    },
    {
     "expr": "sum(rate(credentiald_credentials_search_count[5m]))",
     "legendFormat": "search"
    }
   ]
  },
  {
   "title": "Credentiald Latency",
   "type": "graph",
   "description": "95th percentile latency for credentiald for creating, listing, and searching for credentials.",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(histogram_quantile(0.95, rate(credentiald_credentials_create_bucket[5m])))",
     "legendFormat": "create"
    },
    {
     "expr": "sum(histogram_quantile(0.95, rate(credentiald_credentials_list_bucket[5m])))",
     "legendFormat": "list"
    },
    {
     "expr": "sum(histogram_quantile(0.95, rate(credentiald_credentials_search_bucket[5m])))",
     "legendFormat": "search"
    }
   ]
  },
  {
   "title": "Credentiald Kubernetes Errors",
   "type": "graph",
   "description": "Rate of errors for credentiald for accessing Kubernetes.",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(credentiald_credentials_kubernetes_create_error_total[5m]))",
     "legendFormat": "create"
    },
    {
     "expr": "sum(rate(credentiald_credentials_kubernetes_list_error_total[5m]))",
     "legendFormat": "list"
    },
    {
     "expr": "sum(rate(credentiald_credentials_kubernetes_search_error_total[5m]))",
     "legendFormat": "search"
    }
   ]
  }
 ]
}