{
 "title": "Crossplane",
 "description": "Monitoring Crossplane events and influence on CRDs & API Server",
 "tags": [
  "owner:team-honeybadger",
  "topic:management-cluster",
  "topic:crossplane"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "rate_interval",
    "label": "Rate Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "namespace", "label": "Namespace", "query": "crossplane" }
  ]
 },
 "panels": [
  { "title": "Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Normal Events by Reason",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(reason) (rate(kube_event_count{type=\"Normal\", namespace=\"$namespace\"}[$rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Warning Events by Reason",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by(reason) (rate(kube_event_count{type=\"Warning\", namespace=\"$namespace\"}[$rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "API Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "API Server Requests from Crossplane namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by (job) (rate(rest_client_requests_total{job=~\"$namespace/.*\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Server Requests by Resource (Top 10)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "topk(10, sum by (resource) (rate(apiserver_request_total[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Controller reconciliation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Reconciles by Controller (Top 10)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "topk(10, sum by (controller) (rate(controller_runtime_reconcile_total{job=~\"$namespace/.*\"}[$rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workqueue Depth by Controller (Top 10)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "topk(10, sum by (name) (workqueue_depth{job=~\"$namespace/.+\"}))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}