{
 "title": "Kubernetes Events & Resources Count",
 "tags": [ "owner:team-phoenix" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster ID",
    "query": {
     "query": "label_values(etcd_kubernetes_resources_count, cluster_id)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(etcd_kubernetes_resources_count, namespace)"
    }
   },
   {
    "name": "kind",
    "label": "Kind",
    "query": {
     "query": "label_values(etcd_kubernetes_resources_count, kind)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "How to get the charts filled with data.",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "Install the [etcd-kubernetes-resources-count-exporter](https://github.com/giantswarm/etcd-kubernetes-resources-count-exporter) app from the Playground catalog."
   }
  },
  {
   "title": "$cluster -  Rate of Events every 5m in 1m buckets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "rate(etcd_kubernetes_events_count{cluster_id=\"$cluster\"}[5m])[24h:1m]",
     "legendFormat": "{{namespace}} - {{kind}} - {{ reason}}"
    }
   ]
  },
  {
   "title": "$cluster -  Total Number of Events",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(rate(etcd_kubernetes_events_count{cluster_id=\"$cluster\"}[1m])[$__range:1m]))"
    }
   ]
  },
  {
   "title": "$cluster -  Total number of events every minute grouped by Kind of the involved object",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(etcd_kubernetes_events_count{cluster_id=\"$cluster\"}[1m])[$__range:1m]"
    }
   ]
  },
  {
   "title": "$cluster - Total number of events every minute grouped by the reporting component",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "rate(etcd_kubernetes_events_count{cluster_id=\"$cluster\"}[1m])[$__range:1m]"
    }
   ]
  },
  {
   "title": "$cluster - Table of events",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(etcd_kubernetes_events_count{cluster_id=\"$cluster\"}[1m])[$__range:1m]"
    }
   ]
  },
  {
   "title": "$cluster - Events Counted every minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "rate(etcd_kubernetes_events_count{cluster_id=\"$cluster\"}[1m])",
     "legendFormat": "{{namespace}} - {{kind}} - {{reason}} in object namespace {{objectNamespace}}"
    }
   ]
  },
  {
   "title": "$cluster - Kubernetes objects by Kind",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum (etcd_kubernetes_resources_count{cluster_id=\"$cluster\", namespace=~\"$namespace\", kind=~\"$kind\"}) by (kind)",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "$cluster - Kubernetes objects by Namespace",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "sum (etcd_kubernetes_resources_count{cluster_id=\"$cluster\", namespace=~\"$namespace\", kind=~\"$kind\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  }
 ]
}