{
 "title": "ETCD Backup",
 "tags": [ "owner:team-phoenix" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(etcd_backup_latest_attempt, tenant_cluster_id)"
    }
   }
  ]
 },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Backup file size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg by (tenant_cluster_id) (etcd_backup_size_bytes)",
     "legendFormat": "{{tenant_cluster_id}}"
    }
   ]
  },
  {
   "title": "Backup Creation Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg by (tenant_cluster_id) (etcd_backup_creation_time_ms)",
     "legendFormat": "{{tenant_cluster_id}}"
    }
   ]
  },
  {
   "title": "Encryption Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg by (tenant_cluster_id) (etcd_backup_encryption_time_ms)",
     "legendFormat": "{{tenant_cluster_id}}"
    }
   ]
  },
  {
   "title": "Upload Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg by (tenant_cluster_id) (etcd_backup_upload_time_ms)",
     "legendFormat": "{{tenant_cluster_id}}"
    }
   ]
  },
  { "title": "Management cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Number of Workload Clusters",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count(sum(max_over_time(cluster_service_cluster_info{}[$__range])) by (cluster_id)) OR on() vector(0)) + (count(count(max_over_time(cluster_operator_cluster_status{}[$__range])) by (cluster_id)) OR on() vector(0)) - (count(count(max_over_time(cluster_operator_cluster_status{status=\"Deleting\"}[$__range]) == 1) by (cluster_id)) OR on() vector(0))"
    }
   ]
  },
  {
   "title": "Count of TC ETCD Backups",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count (etcd_backup_latest_success{tenant_cluster_id != \"ManagementCluster\"}) by (tenant_cluster_id))"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 4, "w": 17, "x": 6, "y": 10 }, "options": { "content": "\n\n\n" } },
  { "type": "text", "gridPos": { "h": 2, "w": 3, "x": 0, "y": 14 }, "options": { "content": "# V2\n\n\n\n" } },
  {
   "title": "Latest backup attempt",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 3, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(etcd_backup_latest_attempt{tenant_cluster_id=\"ManagementCluster\",etcd_version=\"V2\"}*1000)"
    }
   ]
  },
  {
   "title": "Latest successful backup",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 9, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(etcd_backup_latest_success{tenant_cluster_id=\"ManagementCluster\",etcd_version=\"V2\"}*1000)"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 3, "x": 0, "y": 16 }, "options": { "content": "# V3\n\n\n\n" } },
  {
   "title": "Latest backup attempt",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 3, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(etcd_backup_latest_attempt{tenant_cluster_id=\"ManagementCluster\",etcd_version=\"V3\"}*1000)"
    }
   ]
  },
  {
   "title": "Latest successful backup",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 9, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(etcd_backup_latest_success{tenant_cluster_id=\"ManagementCluster\",etcd_version=\"V3\"}*1000)"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 14, "x": 0, "y": 18 }, "options": { "content": "\n# Workload Clusters\n\n\n\n" } },
  { "title": "$cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 }, "repeat": "cluster" },
  {
   "title": "Latest backup attempt",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(etcd_backup_latest_attempt{tenant_cluster_id=\"$cluster\",etcd_version=\"V3\"}*1000)"
    }
   ]
  },
  {
   "title": "Latest successful backup",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(etcd_backup_latest_success{tenant_cluster_id=\"$cluster\",etcd_version=\"V3\"}*1000)"
    }
   ]
  }
 ]
}