{
 "title": "External DNS",
 "description": "Dashboard to display external-dns metrics",
 "tags": [
  "external-dns",
  "dns"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kubernetes_build_info,cluster_id)"
    }
   },
   {
    "name": "app",
    "label": "App",
    "query": {
     "query": "label_values(external_dns_registry_endpoints_total{cluster_id=~\"$cluster\"},app)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "External-dns endpoints",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total external-dns registry endpoints",
   "type": "timeseries",
   "description": "Number of Endpoints in the registry",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "external_dns_registry_endpoints_total{cluster_id=\"$cluster\", app=\"$app\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total external-dns source endpoints",
   "type": "timeseries",
   "description": "Number of Endpoints in all sources",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "external_dns_source_endpoints_total{cluster_id=\"$cluster\", app=\"$app\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "External-dns errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total external-dns registry errors",
   "type": "timeseries",
   "description": "Number of Registry errors",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "external_dns_registry_errors_total{cluster_id=\"$cluster\", app=\"$app\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total external-dns source errors",
   "type": "timeseries",
   "description": "Number of Source errors",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "external_dns_source_errors_total{cluster_id=\"$cluster\", app=\"$app\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "External-dns sync",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Timestamp of last successful sync with the DNS provider",
   "type": "bargauge",
   "description": "Timestamp of last successful sync with the DNS provider",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1000 * (external_dns_controller_last_sync_timestamp_seconds{cluster_id=\"$cluster\", app=\"$app\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "External-dns pods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster_id=\"$cluster\",pod=~\".*external-dns.*\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "scalar(kube_resourcequota{cluster_id=\"$cluster\",pod=~\".*external-dns.*\", type=\"hard\",resource=\"requests.cpu\"})",
     "legendFormat": "quota - requests"
    },
    {
     "expr": "scalar(kube_resourcequota{cluster_id=\"$cluster\",pod=~\".*external-dns.*\", type=\"hard\",resource=\"limits.cpu\"})",
     "legendFormat": "quota - limits"
    }
   ]
  },
  {
   "title": "Memory Usage (w/o cache)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\".*external-dns.*\",container!=\"\", image!=\"\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "scalar(kube_resourcequota{pod=~\".*external-dns.*\", type=\"hard\",resource=\"requests.memory\"})",
     "legendFormat": "quota - requests"
    },
    {
     "expr": "scalar(kube_resourcequota{pod=~\".*external-dns.*\",type=\"hard\",resource=\"limits.memory\"})",
     "legendFormat": "quota - limits"
    }
   ]
  }
 ]
}