{
 "title": "External Secrets",
 "description": "Monitoring External Secrets and related components",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "rate_interval",
    "label": "Rate Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "namespace", "label": "Namespace", "query": "external-secrets" }
  ]
 },
 "panels": [
  { "title": "Controller reconciliation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total reconciled resources",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(controller) (controller_runtime_reconcile_total{namespace=\"$namespace\", controller!=\"customresourcedefinition\", controller!=\"validatingwebhookconfiguration\"})",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Workqueue Depth by Controller (Top 10)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "topk(10, sum by (name) (workqueue_depth{job=~\"$namespace/.+\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reconciles by Controller (Top 10)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "topk(10, sum by (controller) (rate(controller_runtime_reconcile_total{job=~\"$namespace/.*\"}[$rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}