{
 "title": "Grafana",
 "description": "The meta-dashboard about Grafana health and usage",
 "tags": [
  "owner:team-atlas",
  "topic:meta"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "At  a Glance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Restarts",
   "type": "singlestat",
   "description": "Pod restarts",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{pod=~\"grafana-.*\"})"
    }
   ]
  },
  {
   "title": "Users Logged In",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 2, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(grafana_stat_active_users)" }
   ]
  },
  {
   "title": "Dashboards",
   "type": "singlestat",
   "description": "The number of dashboards existing",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(grafana_stat_totals_dashboard)"
    }
   ]
  },
  {
   "title": "API Error Rate",
   "type": "singlestat",
   "description": "As a percentage of all Grafana API requests",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 1 },
   "format": "percentunit",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(grafana_api_response_status_total{code!=\"200\"}) / sum(grafana_api_response_status_total)"
    }
   ]
  },
  {
   "title": "Proxy Error Rate",
   "type": "singlestat",
   "description": "As a percentage of all proxy requests (Prom, Elasticsearch, ...)",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 1 },
   "format": "percentunit",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(grafana_proxy_response_status_total{code!=\"200\"}) / sum(grafana_proxy_response_status_total)"
    }
   ]
  },
  {
   "title": "Average Requests per Second",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(grafana_api_response_status_total[5m]))"
    }
   ]
  },
  {
   "title": "CPU Requests",
   "type": "singlestat",
   "description": "Number of CPU cores reserved",
   "gridPos": { "h": 5, "w": 2, "x": 17, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{cluster_type=~\"management_cluster\",pod=~\"grafana.*\"})"
    }
   ]
  },
  {
   "title": "Memory Request",
   "type": "singlestat",
   "description": "Amount of memory reserved",
   "gridPos": { "h": 5, "w": 3, "x": 19, "y": 1 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{cluster_type=~\"management_cluster\",pod=~\"grafana.*\"})"
    }
   ]
  },
  { "title": "User Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Users Logins (beta)",
   "type": "graph",
   "description": "This is supposed to display the number of logins over time.",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(grafana_api_login_post_total)"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "graph",
   "description": "Current users logged in",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "sum(grafana_stat_active_users)" }
   ]
  },
  {
   "title": "Proxy Requests",
   "type": "graph",
   "description": "Number of proxy requests processed over time",
   "gridPos": { "h": 7, "w": 8, "x": 14, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(grafana_api_dataproxy_request_all_milliseconds_sum) / sum(grafana_api_dataproxy_request_all_milliseconds_count)",
     "legendFormat": "Requests"
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Proxy Request Latency",
   "type": "graph",
   "description": "Time it takes to fulfill a query via the proxy",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max(grafana_api_dataproxy_request_all_milliseconds) by (quantile)",
     "legendFormat": "{{ quantile }} quantile"
    }
   ]
  },
  {
   "title": "Dashboard Load Latency",
   "type": "graph",
   "description": "Time it takes to fetch a dashboard (the main resource)",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max(grafana_api_dashboard_get_milliseconds) by (quantile)",
     "legendFormat": "{{ quantile }} Quantile"
    }
   ]
  },
  {
   "title": "API Errors",
   "type": "graph",
   "description": "Errors in requests to the Grafana API",
   "gridPos": { "h": 7, "w": 5, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(irate(grafana_api_response_status_total{code!=\"200\"}[3m]))",
     "legendFormat": "Errors per second"
    }
   ]
  },
  {
   "title": "Proxy Error Rate",
   "type": "graph",
   "description": "Errors in requests to the datasource proxy",
   "gridPos": { "h": 7, "w": 5, "x": 17, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(irate(grafana_proxy_response_status_total{code!=\"200\"}[3m]))",
     "legendFormat": "Errors per second"
    }
   ]
  }
 ]
}