{
 "title": "Logging",
 "description": "Info from the logging stack",
 "tags": [
  "owner:team-atlas",
  "topic:management-cluster",
  "topic:workload-cluster"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Deployment status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Elasticsearch: current replicas",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{cluster_type=~\"management_cluster\",deployment=\"elasticsearch\"})",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Fluent-bit: current pods",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(kube_daemonset_status_number_ready{cluster_type=~\"management_cluster\",daemonset=\"fluentbit\"})",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Kibana: current replicas",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{cluster_type=~\"management_cluster\",deployment=\"kibana\"})",
     "legendFormat": "Count"
    }
   ]
  },
  { "title": "Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Elasticsearch: memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{cluster_type=~\"management_cluster\",container=\"elasticsearch\"}",
     "legendFormat": "Memory usage"
    }
   ]
  },
  {
   "title": "Fluent-bit: memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{cluster_type=~\"management_cluster\",container=\"fluentbit\"}",
     "legendFormat": "{{ ip }}"
    }
   ]
  },
  {
   "title": "Kibana: memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{cluster_type=~\"management_cluster\",container=\"kibana\"})",
     "legendFormat": "Memory usage"
    }
   ]
  },
  { "title": "CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Elasticsearch: CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percentunit", "label": "Usage in percentage of 1 core" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{cluster_type=~\"management_cluster\",container=\"elasticsearch\"}[3m]))",
     "legendFormat": "CPU usage"
    }
   ]
  },
  {
   "title": "Fluent-bit: CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "percentunit", "label": "Usage in percentage of 1 core" }
   ],
   "targets": [
    {
     "expr": "irate(container_cpu_usage_seconds_total{cluster_type=~\"management_cluster\",container=\"fluentbit\"}[2m])",
     "legendFormat": "{{ ip }}"
    }
   ]
  },
  {
   "title": "Kibana: CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "percentunit", "label": "Usage in percentage of 1 core" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{cluster_type=~\"management_cluster\",container=\"kibana\"}[2m]))",
     "legendFormat": "CPU usage"
    }
   ]
  },
  { "title": "Fluent-bit Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Fluentbit: Throughput (Bytes)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bytes", "label": "Data rate per second" }
   ],
   "targets": [
    {
     "expr": "sum(irate(fluentbit_input_bytes_total[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Fluentbit: Throughput (Items)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "none", "label": "Items per second" }
   ],
   "targets": [
    {
     "expr": "sum(irate(fluentbit_input_records_total[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Fluent-bit: output errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "none", "label": "errors" }
   ],
   "targets": [
    {
     "expr": "sum(irate(fluentbit_output_errors_total[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Fluent-bit: output retries",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 36 },
   "yaxes": [
    { "format": "none", "label": "retries" }
   ],
   "targets": [
    {
     "expr": "sum(irate(fluentbit_output_retries_total[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Fluent-bit: failed output retries",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 36 },
   "yaxes": [
    { "format": "none", "label": "failed retries" }
   ],
   "targets": [
    {
     "expr": "sum(irate(fluentbit_output_retries_failed_total[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Storage (where available)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Elasticsearch: Data storage used",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "kubelet_volume_stats_used_bytes{cluster_type=~\"management_cluster\",persistentvolumeclaim=\"elasticsearch-data\"}",
       "legendFormat": "{{ip}}"
      }
     ]
    }
   ]
  },
  { "title": "Elasticsearch Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Elasticsearch log entries per day",
   "type": "graph",
   "description": "Note: we normally expect to store logs for 14 days only.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "_id:*",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Kibana Usage: Elasticsearch queries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "+kubernetes.container_name:kibana +log:\"/elasticsearch/_msearch\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Kibana: Elasticsearch request timeout errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "5m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "+kubernetes.container_name:kibana +tags:error",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}