{
 "title": "Loki / Cost estimation",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(loki_build_info, cluster_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Resource",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "description": "request => indicates how many CPU is reserved by Loki\n\nusage => indicates how many CPU is used by Loki",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"loki\"}[5m]))",
     "legendFormat": "usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{container=\"loki\", resource=\"cpu\"})",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "description": "request => indicates how many memory is reserved by Loki\n\nusage => indicates how many memory is used by Loki",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_memory_usage_bytes{container=\"loki\"}[5m])) / 1000000000",
     "legendFormat": "usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{container=\"loki\", resource=\"memory\"}) / 1000000000",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "description": "All the traffic received by Loki Gateway (even the one sent by promtail on the MC)",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(increase(container_network_receive_bytes_total{pod=~\"loki-gateway.*\"}[5m]))",
     "legendFormat": "Bandwidth"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Data stored on S3",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(loki_distributor_bytes_received_total) by(container) / 1024 / 1024",
     "legendFormat": "data received by loki"
    },
    {
     "expr": "sum(promtail_sent_bytes_total) by (container) / 1024 / 1024",
     "legendFormat": "data sent by promtail"
    },
    {
     "expr": "sum(loki_ingester_chunk_stored_bytes_total) by (container) / 1024 / 1024",
     "legendFormat": "chunk stored"
    }
   ]
  }
 ]
}