{
 "title": "Management cluster Overview",
 "tags": [
  "topic:management-cluster",
  "owner:team-biscuit"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Applications" }
  ]
 },
 "panels": [
  { "title": "Cluster stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of applications",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 15, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count(kube_pod_labels{cluster_type=~\"management_cluster\",label_app=~\".+\"}) by (label_app))",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Pods deployed per applications",
   "type": "table",
   "gridPos": { "h": 12, "w": 9, "x": 15, "y": 1 },
   "targets": [
    {
     "expr": "count(kube_pod_labels{cluster_type=~\"management_cluster\",label_app=~\".+\"}) by (label_app)"
    }
   ]
  },
  {
   "title": "Management cluster CPU Requested",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{cluster_type=~\"management_cluster\"})"
    }
   ]
  },
  {
   "title": "Management cluster CPU Limits",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{cluster_type=~\"management_cluster\"})"
    }
   ]
  },
  {
   "title": "Management cluster CPU Allocatable",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_cpu_cores{cluster_type=~\"management_cluster\"})"
    }
   ]
  },
  {
   "title": "Management cluster Memory Requested",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 9 },
   "format": "decgbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{cluster_type=~\"management_cluster\"}/(1024*1024*1024))"
    }
   ]
  },
  {
   "title": "Management cluster Memory Limits",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 9 },
   "format": "decgbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{cluster_type=~\"management_cluster\"}/(1024*1024*1024))\n"
    }
   ]
  },
  {
   "title": "Management cluster Allocatable Memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 9 },
   "format": "decgbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_memory_bytes{cluster_type=~\"management_cluster\"}/(1024*1024*1024))"
    }
   ]
  },
  { "title": "Pods stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Throttled CPU per container",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "seconds / 5 minutes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(\n    rate(container_cpu_cfs_throttled_seconds_total{cluster_type=~\"management_cluster\",container!~\"\"}[5m])) \nby (container))\n",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Memory utilization per app",
   "type": "graph",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(container_memory_working_set_bytes{name!~\".+POD.+\",cluster_type=~\"management_cluster\"}) by (container) / (1024*1024*1024))",
     "legendFormat": "{{ container }}"
    }
   ]
  }
 ]
}