{
 "title": "Mimir Cost Estimate",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(kube_pod_container_info{image=~\".*mimir.*\"},cluster_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "description": "Shows how much CPU is reserved by mimir and how much is actually used",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"mimir-.*\", cluster_type=~\"management_cluster\"}[3m])) by (pod)",
     "legendFormat": "used {{pod}}"
    },
    {
     "expr": "max(\n    kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\", pod=~\"mimir-.*\", cluster_type=~\"management_cluster\"}\n) by (container, pod, cluster_type)",
     "legendFormat": "limit {{pod}}"
    },
    {
     "expr": "max(node:node_num_cpu:sum{node=~\".+\"} * on (node) group_right(pod) (topk(1, kube_pod_info{pod=~\"mimir-.*\"}))) by (namespace)",
     "legendFormat": "node cpu - {{ namespace }}"
    }
   ]
  },
  {
   "title": "Total cpu used ",
   "type": "stat",
   "description": "Total cpu % used by all mimir pods",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum(rate(container_cpu_usage_seconds_total{pod=~\"mimir-.*\", cluster_type=~\"management_cluster\"}[5m])) by (pod))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "description": "Shows how much memory is reserved by mimir",
   "gridPos": { "h": 7, "w": 21, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\n    container_memory_working_set_bytes{pod=~\"mimir-.*\", cluster_type=~\"management_cluster\"}\n    ) by (pod, cluster_type)",
     "legendFormat": "working {{ pod }}"
    },
    {
     "expr": "sum(\n    container_memory_usage_bytes{pod=~\"mimir-.*\", cluster_type=~\"management_cluster\"}\n) by (pod, cluster_type)",
     "legendFormat": "used {{pod}}"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\", pod=~\"mimir-.*\", cluster_type=~\"management_cluster\"}\n) by ( pod, cluster_type)",
     "legendFormat": "limit {{ pod }}"
    }
   ]
  },
  {
   "title": "Total memory used ",
   "type": "stat",
   "description": "Total memory used by all mimir pods",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum(max_over_time(container_memory_usage_bytes{pod=~\"mimir-.*\", cluster_type=~\"management_cluster\"}[$__range] ) ) by (pod))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Storage usage",
   "type": "timeseries",
   "description": "Storage space used by mimir - To be completed with AWS S3 info",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "cortex", "legendFormat": "{{persistentvolumeclaim}}" },
    {
     "expr": "1",
     "legendFormat": "Total space used - To be completed with AWS S3 info"
    }
   ]
  },
  {
   "title": "Total space used ",
   "type": "stat",
   "description": "Total storage space used by all mimir instances on the installation - To be completed with AWS S3 info",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "1", "legendFormat": "__auto" }
   ]
  },
  { "title": "Network transfer usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Received data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{pod=~\"mimir-.*\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Emitted data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{pod=~\"mimir-.*\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Timeseries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Total series",
   "type": "stat",
   "description": "Total number of time series in mimir",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cortex_ingester_active_series{cluster_id=~\"($cluster)\"}) by (cluster_id)",
     "legendFormat": "{{cluster}}"
    }
   ]
  }
 ]
}