{
 "title": "Network",
 "tags": [
  "owner:team-biscuit",
  "topic:management-cluster",
  "topic:workload-cluster"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(kubernetes_build_info, cluster_id)"
   },
   {
    "name": "dns_host",
    "label": "DNS Host",
    "query": "label_values(dns_udp_latency_seconds_bucket, host)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Network Latency Overview",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(network_latency_seconds_sum{cluster_id=\"$cluster\", host!=\"net-exporter:8000\"}[15m])) / sum(irate(network_latency_seconds_count{cluster_id=\"$cluster\", host!=\"net-exporter:8000\"}[15m]))",
     "legendFormat": "Mean Latency"
    },
    {
     "expr": "histogram_quantile(0.5, sum(irate(network_latency_seconds_bucket{cluster_id=\"$cluster\"}[15m])) by (le))",
     "legendFormat": "50th Percentile Latency"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(network_latency_seconds_bucket{cluster_id=\"$cluster\"}[15m])) by (le))",
     "legendFormat": "95th Percentile Latency"
    }
   ]
  },
  {
   "title": "DNS Latency Overview",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(irate(dns_udp_latency_seconds_bucket{cluster_id=\"$cluster\", host=~\"$dns_host\"}[15m])) by (le))",
     "legendFormat": "50th Percentile Latency"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "content": "### Data Source\n   - For network latency, net-exporter (a DaemonSet) pings every other net-exporter instance, exposing the total time to ping as latency.\n   - For DNS latency, net-exporter resolves `giantswarm.io` and `kubernetes.default.svc.cluster.local`, exposing the total time to resolve as latency.\n\n\n### Mean, 50th Percentile Latency, 95th Percentile Latency\n   - Mean is defined here as the sum of all samples (latency durations), divided by the number of samples.\n   - 50th percentile is the value under which 50% of samples fall (equivalent to the median).\n   - 95th percentile is the value under which 95% of samples fall.\n"
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "content": "### Intepretation\n- Lower latencies are, on the whole, better.\n- If the mean is equal or close to the 50th percentile, we have a symmetrical distribution (a bell curve).\n- If the mean is lower than the 50th percentile, the distribution is skewed to the left, or _negatively_ skewed.\n- If the mean is greater than the 50th percentile, the distribution is skewed to the right, or _positively_ skewed.\n- For network traffic, a positive skew (mean being greater than the 50th percentile) is expected - meaning we have a lot of low latency requests, and some high latency requests.\n- For DNS resolution, no skew (mean being equal to the 50th percentile) is expected - meaning most requests take the same amount of time, and we have some low and some high latency requests."
  },
  { "title": "Breakdown", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Network Latency By Cumulative Bucket",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(network_latency_seconds_bucket{cluster_id=\"$cluster\", le!=\"+Inf\", host!=\"net-exporter:8000\"}[15m])) by (le) / ignoring (le) group_left sum(irate(network_latency_seconds_count{cluster_id=\"$cluster\", le!=\"+Inf\", host!=\"net-exporter:8000\"}[15m]))",
     "legendFormat": "{{ le }}s"
    }
   ]
  },
  {
   "title": "DNS Latency By Cumulative Bucket",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(dns_udp_latency_seconds_bucket{cluster_id=\"$cluster\", host=~\"$dns_host\", le!=\"+Inf\"}[15m])) by (le) / ignoring (le) group_left sum(irate(dns_udp_latency_seconds_count{cluster_id=\"$cluster\", host=~\"$dns_host\", le!=\"+Inf\"}[15m]))",
     "legendFormat": "{{ le }}s"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
   "content": "### Cumulative Buckets\n- Network and DNS latencies are put into cumulative buckets by net-exporter.\n- E.g: A request that takes 2 seconds would be placed in the bucket for requests taking less than or equal to 2 seconds, as well as the bucket for requests taking less than or equal to 3 seconds, but not in the bucket for requests taking less than or equal to 1 second.\n- The bucket counts the number of requests that have taken less than the threshold amount (e.g: less than 0.128 seconds). This is then presented in these graphs as a percentage of the overall number of requests.\n- The thresholds for the buckets are exponential."
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
   "content": "### Interpretation\n- A decrease in the number of requests in lower latency buckets means that most requests are taking longer - we have an increase in overall latency.\n- A non-skewed distribution will have a spread over all buckets.\n- A negatively skewed distribution will have most requests in higher buckets.\n- A positively skewed distribution will have most requests in lower buckets.\n- As we expect network latency to be positively skewed, we expect most requests in lower latency buckets.\n- As we expect DNS latency to not be skewed, we expect a spread of buckets."
  },
  {
   "title": "Net-Exporter Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Check Error Rate",
     "type": "graph",
     "description": "The rate of errors raised checking network latency.",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(network_error_total{cluster_id=\"$cluster\"}[1h]))"
      }
     ]
    },
    {
     "title": "DNS Check Error Rate",
     "type": "graph",
     "description": "The rate of errors raised checking DNS latency.",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(dns_error_total{cluster_id=\"$cluster\"}[1h]))"
      }
     ]
    }
   ]
  }
 ]
}