{
 "title": "NGINX Ingress controller",
 "tags": [
  "nginx",
  "topic:management-cluster",
  "topic:workload-cluster",
  "owner:team-cabbage"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kubernetes_build_info, cluster_id)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(nginx_ingress_controller_config_hash{cluster_id=~\"$cluster\"}, controller_namespace)"
    }
   },
   {
    "name": "app",
    "label": "App",
    "query": {
     "query": "label_values(nginx_ingress_controller_config_hash{cluster_id=~\"$cluster\",namespace=~\"$namespace\"}, app) "
    }
   },
   {
    "name": "controller_class",
    "label": "Controller Class",
    "query": {
     "query": "label_values(nginx_ingress_controller_config_hash{cluster_id=~\"$cluster\",namespace=~\"$namespace\"}, controller_class)"
    }
   },
   {
    "name": "controller",
    "label": "Controller",
    "query": {
     "query": "label_values(nginx_ingress_controller_config_hash{cluster_id=~\"$cluster\",namespace=~\"$namespace\",app=~\"$app\",controller_class=~\"$controller_class\"}, controller_pod) "
    }
   },
   {
    "name": "ingress",
    "label": "Ingress",
    "query": {
     "query": "label_values(nginx_ingress_controller_requests{cluster_id=~\"$cluster\",namespace=~\"$namespace\",app=~\"$app\",controller_class=~\"$controller_class\",controller=~\"$controller\"}, ingress) "
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Controller Request Volume",
   "type": "stat",
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "round(sum(irate(nginx_ingress_controller_requests{cluster_id=~\"$cluster\",namespace=~\"$namespace\",app=~\"$app\",controller_class=~\"$controller_class\",controller_pod=~\"$controller\"}[2m])), 0.001)"
    }
   ]
  },
  {
   "title": "Controller Connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(nginx_ingress_controller_nginx_process_connections{cluster_id=~\"$cluster\",namespace=~\"$namespace\",app=~\"$app\",controller_class=~\"$controller_class\",controller_pod=~\"$controller\"}[2m]))"
    }
   ]
  },
  {
   "title": "Controller Success Rate (non-4|5xx responses)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{\n    cluster_id=~\"$cluster\",\n    namespace=~\"$namespace\",\n    app=~\"$app\",\n    controller_class=~\"$controller_class\",\n    controller_pod=~\"$controller\",\n    status!~\"[4-5].*\"}[2m]\n)) / \nsum(rate(nginx_ingress_controller_requests{\n    cluster_id=~\"$cluster\",\n    namespace=~\"$namespace\",\n    app=~\"$app\",\n    controller_class=~\"$controller_class\",\n    controller_pod=~\"$controller\"}[2m]\n))"
    }
   ]
  },
  {
   "title": "Config Reloads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "avg(irate(nginx_ingress_controller_success{cluster_id=~\"$cluster\",namespace=~\"$namespace\",app=~\"$app\",controller_class=~\"$controller_class\",controller_pod=~\"$controller\"}[1m])) * 60"
    }
   ]
  },
  {
   "title": "Last Config Failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(nginx_ingress_controller_config_last_reload_successful{cluster_id=~\"$cluster\",namespace=~\"$namespace\",app=~\"$app\",controller_class=~\"$controller_class\",controller_pod=~\"$controller\"} == 0)"
    }
   ]
  },
  {
   "title": "Ingress Request Volume",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "round(sum(irate(nginx_ingress_controller_requests{cluster_id=~\"$cluster\",namespace=~\"$namespace\",app=~\"$app\",controller_class=~\"$controller_class\",controller_pod=~\"$controller\",ingress=~\"$ingress\"}[2m])) by (ingress), 0.001)",
     "legendFormat": "{{ ingress }}"
    }
   ]
  },
  {
   "title": "Ingress Success Rate (non-4|5xx responses)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{cluster_id=~\"$cluster\",namespace=~\"$namespace\",app=~\"$app\",controller_class=~\"$controller_class\",controller_pod=~\"$controller\",ingress=~\"$ingress\",status!~\"[4-5].*\"}[2m])) by (ingress) / sum(rate(nginx_ingress_controller_requests{cluster_id=~\"$cluster\",namespace=~\"$namespace\",app=~\"$app\",controller_class=~\"$controller_class\",controller_pod=~\"$controller\",ingress=~\"$ingress\"}[2m])) by (ingress)",
     "legendFormat": "{{ ingress }}"
    }
   ]
  },
  {
   "title": "Network I/O pressure",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum (irate (nginx_ingress_controller_request_size_sum{cluster_id=~\"$cluster\",namespace=~\"$namespace\",app=~\"$app\",controller_class=~\"$controller_class\",controller_pod=~\"$controller\"}[2m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum (irate (nginx_ingress_controller_response_size_sum{cluster_id=~\"$cluster\",namespace=~\"$namespace\",app=~\"$app\",controller_class=~\"$controller_class\",controller_pod=~\"$controller\"}[2m]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Average Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(nginx_ingress_controller_nginx_process_resident_memory_bytes{cluster_id=~\"$cluster\",namespace=~\"$namespace\",app=~\"$app\",controller_class=~\"$controller_class\",controller_pod=~\"$controller\"}) ",
     "legendFormat": "nginx"
    }
   ]
  },
  {
   "title": "Average CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "expr": "sum (rate (nginx_ingress_controller_nginx_process_cpu_seconds_total{cluster_id=~\"$cluster\",namespace=~\"$namespace\",app=~\"$app\",controller_class=~\"$controller_class\",controller_pod=~\"$controller\"}[2m])) ",
     "legendFormat": "nginx"
    }
   ]
  },
  {
   "title": "Ingress Percentile Response Times and Transfer Rates",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{cluster_id=~\"$cluster\",controller_namespace=~\"$namespace\",app=~\"$app\",controller_class=~\"$controller_class\",controller_pod=~\"$controller\",ingress!=\"\",ingress=~\"$ingress\"}[2m])) by (le, ingress))",
     "legendFormat": "{{ ingress }}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{cluster_id=~\"$cluster\",controller_namespace=~\"$namespace\",app=~\"$app\",controller_class=~\"$controller_class\",controller_pod=~\"$controller\",ingress!=\"\",ingress=~\"$ingress\"}[2m])) by (le, ingress))",
     "legendFormat": "{{ ingress }}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{cluster_id=~\"$cluster\",controller_namespace=~\"$namespace\",app=~\"$app\",controller_class=~\"$controller_class\",controller_pod=~\"$controller\",ingress!=\"\",ingress=~\"$ingress\"}[2m])) by (le, ingress))",
     "legendFormat": "{{ destination_service }}"
    },
    {
     "expr": "sum(irate(nginx_ingress_controller_request_size_sum{cluster_id=~\"$cluster\",controller_namespace=~\"$namespace\",app=~\"$app\",controller_class=~\"$controller_class\",controller_pod=~\"$controller\",ingress!=\"\",ingress=~\"$ingress\"}[2m])) by (ingress)",
     "legendFormat": "{{ ingress }}"
    },
    {
     "expr": "sum(irate(nginx_ingress_controller_response_size_sum{cluster_id=~\"$cluster\",controller_namespace=~\"$namespace\",app=~\"$app\",controller_class=~\"$controller_class\",controller_pod=~\"$controller\",ingress!=\"\",ingress=~\"$ingress\"}[2m])) by (ingress)",
     "legendFormat": "{{ ingress }}"
    }
   ]
  },
  {
   "title": "Ingress Certificate Expiry",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(host) (nginx_ingress_controller_ssl_expire_time_seconds{cluster_id=~\"$cluster\", namespace=~\"$namespace\", app=~\"$app\", controller_class=~\"$controller_class\", controller_pod=~\"$controller\"}) - time()",
     "legendFormat": "{{ host }}"
    }
   ]
  }
 ]
}