{
 "title": "NGINX Ingress Controller Connection Distribution",
 "tags": [
  "nginx",
  "topic:management-cluster",
  "topic:workload-cluster",
  "owner:team-cabbage"
 ],
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kubernetes_build_info, cluster_id)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(nginx_ingress_controller_config_hash{cluster_id=~\"$cluster\"}, controller_namespace)"
    }
   },
   {
    "name": "app",
    "label": "App",
    "query": {
     "query": "label_values(nginx_ingress_controller_config_hash{cluster_id=~\"$cluster\",namespace=~\"$namespace\"}, app)"
    }
   },
   {
    "name": "controller_class",
    "label": "Controller Class",
    "query": {
     "query": "label_values(nginx_ingress_controller_config_hash{cluster_id=~\"$cluster\",namespace=~\"$namespace\"}, controller_class)"
    }
   },
   {
    "name": "controller",
    "label": "Controller",
    "query": {
     "query": "label_values(nginx_ingress_controller_config_hash{cluster_id=~\"$cluster\",namespace=~\"$namespace\",app=~\"$app\",controller_class=~\"$controller_class\"}, controller_pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Active Connections by Pod",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "nginx_ingress_controller_nginx_process_connections{cluster_id=\"$cluster\",controller_namespace=~\"$namespace\",app=~\"$app\",controller_class=~\"$controller_class\",controller_pod=~\"$controller\",state=\"active\"}"
    }
   ]
  },
  {
   "title": "Active Connections by Node",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum by (node) (nginx_ingress_controller_nginx_process_connections{cluster_id=\"$cluster\",controller_namespace=~\"$namespace\",app=~\"$app\",controller_class=~\"$controller_class\",controller_pod=~\"$controller\",state=\"active\"})"
    }
   ]
  },
  {
   "title": "Active Connections by Zone",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum by (zone) (nginx_ingress_controller_nginx_process_connections{cluster_id=\"$cluster\",controller_namespace=~\"$namespace\",app=~\"$app\",controller_class=~\"$controller_class\",controller_pod=~\"$controller\",state=\"active\"} * on (node) group_left(zone) kube_node_labels{cluster_id=\"$cluster\"})"
    }
   ]
  }
 ]
}