{
 "title": "Prometheus Benchmark - 2.3.x",
 "description": "Metrics useful for benchmarking and loadtesting Prometheus itself. Designed primarily for Prometheus 2.3.x",
 "tags": [ "owner:team-atlas" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Prometheus", "label": "Prometheus", "query": "query_result(up{} == 1)" },
   {
    "name": "RuleGroup",
    "label": "RuleGroup",
    "query": "prometheus_rule_group_last_duration_seconds{instance=\"$Prometheus:9090\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Prometheus Version",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "prometheus_build_info" }
   ]
  },
  {
   "title": "Uptime",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{instance=\"$Prometheus:9090\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_max_fds{instance=\"$Prometheus:9090\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "process_open_fds{job=\"prometheus\",instance=\"$Prometheus:9090\"}",
     "legendFormat": "Open"
    }
   ]
  },
  {
   "title": "Head Time series",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_tsdb_head_series{instance=\"$Prometheus:9090\"}",
     "legendFormat": "Time series"
    }
   ]
  },
  {
   "title": "Head Active Appenders",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_tsdb_head_active_appenders{instance=\"$Prometheus:9090\"}",
     "legendFormat": "Head Appenders"
    }
   ]
  },
  {
   "title": "Samples Appended/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_samples_appended_total{instance=\"$Prometheus:9090\"}[1m])",
     "legendFormat": "samples/s"
    }
   ]
  },
  {
   "title": "Head Chunks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_tsdb_head_chunks{instance=\"$Prometheus:9090\"}",
     "legendFormat": "Chunks"
    }
   ]
  },
  {
   "title": "Head Chunks Created",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_chunks_created_total{instance=\"$Prometheus:9090\"}[1m])",
     "legendFormat": "Created"
    }
   ]
  },
  {
   "title": "Head Chunks Removed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_chunks_removed_total{instance=\"$Prometheus:9090\"}[1m])",
     "legendFormat": "Removed"
    }
   ]
  },
  {
   "title": "Head Time Range",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "dateTimeAsIso" }
   ],
   "targets": [
    {
     "expr": "prometheus_tsdb_head_min_time{job=\"prometheus\",instance=\"$Prometheus:9090\"}",
     "legendFormat": "Min"
    },
    { "expr": "time() * 1000", "legendFormat": "Now" },
    {
     "expr": "prometheus_tsdb_head_max_time{job=\"prometheus\",instance=\"$Prometheus:9090\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Head GC Time/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_gc_duration_seconds_sum{instance=\"$Prometheus:9090\"}[1m])",
     "legendFormat": "GC Time/s"
    }
   ]
  },
  {
   "title": "Blocks Loaded",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_tsdb_blocks_loaded{instance=\"$Prometheus:9090\"}",
     "legendFormat": "Blocks Loaded"
    }
   ]
  },
  {
   "title": "TSDB Reloads/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_reloads_total{instance=\"$Prometheus:9090\"}[10m])",
     "legendFormat": "Reloads"
    }
   ]
  },
  {
   "title": "WAL Fsync&Truncate Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_wal_fsync_duration_seconds_sum{instance=\"$Prometheus:9090\"}[1m]) / rate(prometheus_tsdb_wal_fsync_duration_seconds_count{instance=\"$Prometheus:9090\"}[1m])",
     "legendFormat": "Fsync Latency"
    },
    {
     "expr": "rate(prometheus_tsdb_wal_truncate_duration_seconds_sum{instance=\"$Prometheus:9090\"}[1m]) / rate(prometheus_tsdb_wal_truncate_duration_seconds_count{instance=\"$Prometheus:9090\"}[1m])",
     "legendFormat": "Truncate Latency"
    }
   ]
  },
  {
   "title": "TSDB Problems/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_wal_corruptions_total{instance=\"$Prometheus:9090\"}[10m])",
     "legendFormat": "WAL Corruptions"
    },
    {
     "expr": "rate(prometheus_tsdb_reloads_failures_total{instance=\"$Prometheus:9090\"}[10m])",
     "legendFormat": "Reload Failures"
    },
    {
     "expr": "rate(prometheus_tsdb_head_series_not_found{instance=\"$Prometheus:9090\"}[10m])",
     "legendFormat": "Head Series Not Found"
    },
    {
     "expr": "rate(prometheus_tsdb_compactions_failed_total{instance=\"$Prometheus:9090\"}[10m])",
     "legendFormat": "Compaction Failures"
    },
    {
     "expr": "rate(prometheus_tsdb_retention_cutoffs_failures_total{instance=\"$Prometheus:9090\"}[10m])",
     "legendFormat": "Retention Cutoff Failures"
    }
   ]
  },
  {
   "title": "Compactions/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_compactions_total{instance=\"$Prometheus:9090\"}[10m])",
     "legendFormat": "Compactions"
    }
   ]
  },
  {
   "title": "Compaction Time/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_compaction_duration_seconds_sum{instance=\"$Prometheus:9090\"}[10m])"
    }
   ]
  },
  {
   "title": "Retention Cutoffs/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_retention_cutoffs_total[10m])",
     "legendFormat": "Retention Cutoffs"
    }
   ]
  },
  {
   "title": "First Compaction, Avg Chunk Time Range",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_compaction_chunk_range_sum{instance=\"$Prometheus:9090\"}[10m]) / rate(prometheus_tsdb_compaction_chunk_range_count{instance=\"$Prometheus:9090\"}[10m])",
     "legendFormat": "Chunk Time Range"
    }
   ]
  },
  {
   "title": "First Compaction, Avg Bytes/Sample",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 42 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_compaction_chunk_size_sum{instance=\"$Prometheus:9090\"}[10m]) / rate(prometheus_tsdb_compaction_chunk_samples_sum{instance=\"$Prometheus:9090\"}[10m])",
     "legendFormat": "Bytes/Sample"
    }
   ]
  },
  {
   "title": "First Compaction, Avg Chunk Samples",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 42 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_compaction_chunk_samples_sum{instance=\"$Prometheus:9090\"}[10m]) / rate(prometheus_tsdb_compaction_chunk_samples_count{instance=\"$Prometheus:9090\"}[10m])",
     "legendFormat": "Chunk Samples"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=\"$Prometheus:9090\"}",
     "legendFormat": "RSS"
    },
    {
     "expr": "prometheus_local_storage_target_heap_size_bytes{instance=\"$Prometheus:9090\"}",
     "legendFormat": "Target heap size"
    },
    {
     "expr": "go_memstats_next_gc_bytes{instance=\"$Prometheus:9090\"}",
     "legendFormat": "Next GC"
    },
    {
     "expr": "go_memstats_alloc_bytes{instance=\"$Prometheus:9090\"}",
     "legendFormat": "Allocated"
    }
   ]
  },
  {
   "title": "Allocations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 49 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{instance=\"$Prometheus:9090\"}[1m])",
     "legendFormat": "Allocated Bytes/s"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 49 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{instance=\"$Prometheus:9090\"}[1m])",
     "legendFormat": "Irate"
    },
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"$Prometheus:9090\"}[5m])",
     "legendFormat": "5m rate"
    }
   ]
  },
  {
   "title": "HTTP requests/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_http_request_duration_seconds_count{instance=\"$Prometheus:9090\"}[1m])",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "HTTP request latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 56 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_http_request_duration_seconds_sum{instance=\"$Prometheus:9090\"}[1m]) / rate(prometheus_http_request_duration_seconds_count{instance=\"$Prometheus:9090\"}[1m])",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Time spent in HTTP requests/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 56 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_http_request_duration_seconds_sum{instance=\"$Prometheus:9090\"}[1m])",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Query engine timings/s",
   "type": "graph",
   "description": "Time spent in each mode, per second",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_engine_query_duration_seconds_sum{instance=\"$Prometheus:9090\"}[1m])",
     "legendFormat": "{{slice}}"
    }
   ]
  },
  {
   "title": "Rule group evaulation problems/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_rule_group_iterations_missed_total{instance=\"$Prometheus:9090\"}[1m])  ",
     "legendFormat": "Rule group missed"
    },
    {
     "expr": "rate(prometheus_rule_evaluation_failures_total{instance=\"$Prometheus:9090\"}[1m])",
     "legendFormat": "Rule evals failed"
    }
   ]
  },
  {
   "title": "Evaluation time of rule groups/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 63 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_rule_group_duration_seconds_sum{instance=\"$Prometheus:9090\"}[1m])",
     "legendFormat": "Rule evaluation duration"
    }
   ]
  },
  {
   "title": "Rule Group: $RuleGroup",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 70 },
   "repeat": "RuleGroup",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "prometheus_rule_group_interval_seconds{instance=\"$Prometheus:9090\",rule_group=~\"$RuleGroup\"}\n",
     "legendFormat": "Interval"
    },
    {
     "expr": "prometheus_rule_group_last_duration_seconds{instance=\"$Prometheus:9090\",rule_group=~\"$RuleGroup\"}\n",
     "legendFormat": "Last Duration"
    }
   ]
  }
 ]
}