{
 "title": "AutoScaling Groups",
 "tags": [
  "provider:aws",
  "topic:workload-cluster",
  "topic:management-cluster",
  "owner:team-firecracker"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "aws_account_id",
    "label": "AWS Account",
    "query": "label_values(aws_operator_asg_desired_count, account)"
   }
  ]
 },
 "panels": [
  { "title": "Installation-wide", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "How many unfulfilled ASGs are there?",
   "type": "singlestat",
   "description": "Current number of ASGs with actual number of instances < desired number",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count((avg(aws_operator_asg_desired_count) by (asg)) - (avg(aws_operator_asg_inservice_count) by (asg)) != 0)"
    }
   ]
  },
  {
   "title": "Unfulfilled Auto Scaling Groups",
   "type": "graph",
   "description": "Number of instances missing in ASGs over time",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Auto Scaling Groups" }
   ],
   "targets": [
    {
     "expr": "aws_operator_asg_desired_count - aws_operator_asg_inservice_count != 0",
     "legendFormat": "{{ asg }}"
    }
   ]
  },
  { "title": "AWS Account $aws_account_id", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 }, "repeat": "aws_account_id" },
  {
   "title": "How many unfulfilled ASGs are there?",
   "type": "singlestat",
   "description": "Current number of ASGs with actual number of instances < desired number",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count((avg(aws_operator_asg_desired_count{account=\"$aws_account_id\"}) by (asg)) - (avg(aws_operator_asg_inservice_count{account=\"$aws_account_id\"}) by (asg)) != 0)"
    }
   ]
  },
  {
   "title": "Unfulfilled Auto Scaling Groups",
   "type": "graph",
   "description": "Number of instances missing in ASGs over time",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "Auto Scaling Groups" }
   ],
   "targets": [
    {
     "expr": "aws_operator_asg_desired_count{account=\"$aws_account_id\"} - aws_operator_asg_inservice_count{account=\"$aws_account_id\"} != 0",
     "legendFormat": "{{ asg }}"
    }
   ]
  },
  {
   "title": "Instances desired vs. actual",
   "type": "graph",
   "description": "The difference between capacity and InService instances. Negative values stand for missing instances, positive stands for too many instances.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(avg(aws_operator_asg_inservice_count{account=\"$aws_account_id\"}) by (asg)) - (avg(aws_operator_asg_desired_count{account=\"$aws_account_id\"}) by (asg))",
     "legendFormat": "{{ asg }}"
    }
   ]
  },
  {
   "title": "ASG Capacity",
   "type": "graph",
   "description": "Desired number of EC2 instances per Auto Scaling Group",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short", "label": "Instances" }
   ],
   "targets": [
    {
     "expr": "avg(aws_operator_asg_desired_count{account=\"$aws_account_id\"}) by (asg)",
     "legendFormat": "{{ asg }}"
    }
   ]
  },
  {
   "title": "Instances in Service in ASGs",
   "type": "graph",
   "description": "The current number of EC2 instances \"InService\" (which means: working)",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "Instances" }
   ],
   "targets": [
    {
     "expr": "avg(aws_operator_asg_inservice_count{account=\"$aws_account_id\"}) by (asg)",
     "legendFormat": "{{ asg }}"
    }
   ]
  }
 ]
}