{
 "title": "AWS Cluster Status",
 "tags": [
  "provider:aws",
  "topic:workload-cluster",
  "owner:team-firecracker"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cluster_id",
    "label": "Cluster ID",
    "query": {
     "query": "label_values(kubernetes_build_info, cluster_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pod Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{cluster_id=\"$cluster_id\"}) by (phase)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Node Ready",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_nodes_count{state=\"ready\",cluster_id=\"$cluster_id\"})/sum(cluster_autoscaler_nodes_count{cluster_id=\"$cluster_id\"})*100"
    }
   ]
  },
  {
   "title": "Autoscaling activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "Num nodes" }
   ],
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_scaled_up_nodes_total{cluster_id=\"$cluster_id\"})",
     "legendFormat": "scaled up total"
    },
    {
     "expr": "sum(cluster_autoscaler_unneeded_nodes_count{cluster_id=\"$cluster_id\"})",
     "legendFormat": "unneeded nodes"
    },
    {
     "expr": "sum(cluster_autoscaler_nodes_count{cluster_id=\"$cluster_id\"})\n",
     "legendFormat": "total nodes"
    }
   ]
  },
  {
   "title": "CNI Issues",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(awscni_ipamd_error_count{cluster_id=\"$cluster_id\"}) by (fn)",
     "legendFormat": "{{ fn }}"
    }
   ]
  },
  {
   "title": "Deployments",
   "type": "stat",
   "gridPos": { "h": 16, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{cluster_id=\"$cluster_id\",namespace=\"kube-system\", deployment!=\"calico-typha\"} / kube_deployment_spec_replicas{cluster_id=\"$cluster_id\",namespace=\"kube-system\", deployment!=\"calico-typha\"} ",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Daemonsets",
   "type": "stat",
   "gridPos": { "h": 16, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kube_daemonset_status_number_available{cluster_id=\"$cluster_id\",namespace=\"kube-system\"}  / kube_daemonset_status_desired_number_scheduled{cluster_id=\"$cluster_id\",namespace=\"kube-system\"}",
     "legendFormat": "{{daemonset}}"
    }
   ]
  },
  {
   "title": "Cluster CPU Usage",
   "type": "gauge",
   "description": "CPU used by containers in comparison to the amount of CPU cores available in machines",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (irate (container_cpu_usage_seconds_total{cluster_id='$cluster_id'}[3m])) / sum (kube_node_status_capacity{cluster_id='$cluster_id', resource=\"cpu\" * 100"
    }
   ]
  },
  {
   "title": "Nginx Requests Per Second",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "round(sum(irate(nginx_ingress_controller_requests{cluster_id=~\"$cluster_id\"}[2m])), 0.001)"
    }
   ]
  },
  {
   "title": "Available IP Count",
   "type": "stat",
   "description": "Number of IPs that are still available per aws-cni subnet .",
   "gridPos": { "h": 14, "w": 3, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_operator_subnet_available_ips{subnet_type=\"aws-cni\", cluster_id=\"$cluster_id\"}",
     "legendFormat": "{{availability_zone}}"
    }
   ]
  },
  {
   "title": "Available IP Percentage",
   "type": "stat",
   "description": "Percentage of IPs that are still available per aws-cni subnet .",
   "gridPos": { "h": 14, "w": 3, "x": 13, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_operator_subnet_available_ips_percentage{subnet_type=\"aws-cni\", cluster_id=\"$cluster_id\"}",
     "legendFormat": "{{availability_zone}}"
    }
   ]
  },
  {
   "title": "Cluster Memory Usage",
   "type": "gauge",
   "description": "Memory used by containers, in comparision to the memory available on machines",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "sum(container_memory_working_set_bytes{cluster_id=\"$cluster_id\"}) / sum(kube_node_status_capacity{cluster_id=\"$cluster_id\", resource=\"memory\"}) * 100",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Nginx Request Success Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{cluster_id=~\"$cluster_id\",status!~\"[4-5].*\"}[2m])) / sum(rate(nginx_ingress_controller_requests{cluster_id=~\"$cluster_id\"}[2m]))"
    }
   ]
  },
  { "title": "Upgrade Batch Settings", "type": "text", "gridPos": { "h": 2, "w": 2, "x": 8, "y": 15 } },
  {
   "title": "DNS Request Latency Mean",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(coredns_dns_request_duration_seconds_sum{cluster_id=\"$cluster_id\"}[15m])) / sum(irate(coredns_dns_request_duration_seconds_count{cluster_id=\"$cluster_id\"}[15m])) * 1000",
     "legendFormat": "Mean"
    }
   ]
  },
  {
   "title": "Max Pause Time",
   "type": "stat",
   "description": "The max wait time between rolling of node batches during upgrades.",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(aws_operator_update_pause_time_seconds{cluster_id=\"$cluster_id\"})"
    }
   ]
  },
  {
   "title": "Max Nodes Rolled",
   "type": "stat",
   "description": "The maximum percentage of nodes (batches) that can be rolled during upgrades at the same time.",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(aws_operator_update_max_batch_percentage{cluster_id=\"$cluster_id\"})",
     "legendFormat": "{{node_pool_id}}"
    }
   ]
  }
 ]
}