{
 "title": "Kubernetes Cluster Autoscaler",
 "description": "Super simple dashboard showing an overview of kubernetes cluster autoscaling activity and status, using metrics reported by the autoscaler to prometheus.\r\n\r\nhttps://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler",
 "tags": [
  "topic:workload-cluster",
  "provider:aws",
  "owner:team-celestial",
  "owner:team-firecracker"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(cluster_autoscaler_last_activity, cluster_id)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total nodes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_nodes_count{cluster_id=\"$cluster\"}) \n"
    }
   ]
  },
  {
   "title": "Nodes available",
   "type": "singlestat",
   "description": "Shows the nodes which are ready as a percent of the total nodes",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_nodes_count{state=\"ready\",cluster_id=\"$cluster\"})/sum(cluster_autoscaler_nodes_count{cluster_id=\"$cluster\"})*100"
    }
   ]
  },
  {
   "title": "Is cluster safe to scale?",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_cluster_safe_to_autoscale{cluster_id=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Number of unscheduled pods",
   "type": "singlestat",
   "description": "Tells you if there are unscheduled pods",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_unschedulable_pods_count{cluster_id=\"$cluster\"})",
     "legendFormat": " pods"
    }
   ]
  },
  {
   "title": "Last scaleDown activity",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(time()-cluster_autoscaler_last_activity{activity=\"scaleDown\",cluster_id=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Last autoscale activity",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(time()-cluster_autoscaler_last_activity{activity=\"autoscaling\",cluster_id=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Pod activity",
   "type": "graph",
   "description": "Shows the evicted and unscheduled pods",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "none", "label": "Num Nodes" }
   ],
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_evicted_pods_total{cluster_id=\"$cluster\"})",
     "legendFormat": "evicted pods"
    },
    {
     "expr": "sum(cluster_autoscaler_unschedulable_pods_count{cluster_id=\"$cluster\"})",
     "legendFormat": "unscheduled pods"
    }
   ]
  },
  {
   "title": "Node activity",
   "type": "graph",
   "description": "Shows the state of the nodes as scaling happens",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "none", "label": "Num Nodes" }
   ],
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_nodes_count{state=\"ready\",cluster_id=\"$cluster\"})",
     "legendFormat": "ready"
    },
    {
     "expr": "sum(cluster_autoscaler_nodes_count{state=\"unready\",cluster_id=\"$cluster\"})",
     "legendFormat": "unready"
    },
    {
     "expr": "sum(cluster_autoscaler_nodes_count{state=\"notStarted\",cluster_id=\"$cluster\"})\n",
     "legendFormat": "not started"
    }
   ]
  },
  {
   "title": "Autoscaling activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "none", "label": "Num nodes" }
   ],
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_scaled_up_nodes_total{cluster_id=\"$cluster\"})",
     "legendFormat": "scaled up total"
    },
    {
     "expr": "sum(cluster_autoscaler_unneeded_nodes_count{cluster_id=\"$cluster\"})",
     "legendFormat": "unneeded nodes"
    },
    {
     "expr": "sum(cluster_autoscaler_nodes_count{cluster_id=\"$cluster\"})\n",
     "legendFormat": "total nodes"
    }
   ]
  },
  {
   "title": "Cluster direction?",
   "type": "singlestat",
   "description": "Is the cluster scaling up, down or ticking along okay?",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_scaled_up_nodes_total{cluster_id=\"$cluster\"})-sum(cluster_autoscaler_scaled_down_nodes_total{cluster_id=\"$cluster\"})"
    }
   ]
  }
 ]
}