{
 "title": "Unschedulable pods",
 "tags": [
  "owner:team-tenet",
  "topic:kubernetes"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(aggregation:giantswarm:cluster_info,cluster_id)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_status_unschedulable{cluster_id=~\"$cluster\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Per cluster",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  sum_over_time(\n    kube_pod_status_unschedulable{cluster_id=~\"$cluster\", namespace=~\"$namespace\"}[$__range]\n  )\n) by (cluster_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Per namespace",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  sum_over_time(\n    kube_pod_status_unschedulable{cluster_id=~\"$cluster\", namespace=~\"$namespace\"}[$__range]\n  )\n) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unschedulable pods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(\n  kube_pod_status_unschedulable{cluster_id=~\"$cluster\", namespace=~\"$namespace\"}\n) by (cluster_id, namespace, pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{cluster_id=~\"$cluster\", scrape_job=\"kubernetes-events\", namespace=~\"$namespace\"} |= `FailedScheduling` | logfmt | line_format `{{.cluster_id}}/{{.namespace}}/{{.name}}: {{.msg}}`"
    }
   ]
  }
 ]
}