{{/* vim: set filetype=mustache: */}}
{{/*
Generate a unique ConfigMap name for a dashboard.
Parameters:
  - .teamName: The team name (e.g., "atlas", "tenet")
  - .org: The organization name extracted from the dashboard path
  - .folder: The folder name extracted from the dashboard path
  - .dashboardName: The dashboard file name without extension
  - .providerKind: (optional) The provider kind (e.g., "capa", "capz") for provider-specific dashboards
*/}}
{{- define "dashboards.configMapName" -}}
{{- if or (eq .teamName "phoenix") (eq .teamName "tenet") -}}
  {{- if .providerKind -}}
  {{- printf "grafana-%s-%s-dashboard" (printf "%s-%s-%s-%s" .teamName .providerKind .org .folder | sha256sum | trunc 8) .dashboardName | trunc 63 | trimSuffix "-" -}}
  {{- else -}}
  {{- printf "grafana-%s-%s-dashboard" (printf "%s-%s-%s" .teamName .org .folder | sha256sum | trunc 8) .dashboardName | trunc 63 | trimSuffix "-" -}}
  {{- end -}}
{{- else -}}
  {{- printf "%s-dashboard" .dashboardName | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end -}}

{{/*
Generate ConfigMap metadata for a dashboard.
Parameters:
  - .teamName: The team name (e.g., "atlas", "tenet")
  - .org: The organization name extracted from the dashboard path
  - .folder: The folder name extracted from the dashboard path
  - .dashboardName: The dashboard file name without extension
  - .ctx: The root context ($)
  - .providerKind: (optional) The provider kind for provider-specific dashboards
*/}}
{{- define "dashboards.configMapMetadata" -}}
annotations:
  application.giantswarm.io/team: {{ .teamName | quote }}
  observability.giantswarm.io/organization: {{ .org | quote }}
  observability.giantswarm.io/folder: {{ .folder | quote }}
labels:
  {{- include "labels.common" .ctx | nindent 2 }}
name: {{ include "dashboards.configMapName" . }}
namespace: {{ .ctx.Values.global.namespace }}
{{- end -}}

{{/*
Generate a single ConfigMap for a dashboard.
Parameters:
  - .teamName: The team name
  - .org: The organization name
  - .folder: The folder name
  - .dashboardName: The dashboard file name without extension
  - .path: The full path to the dashboard file
  - .ctx: The root context ($)
  - .providerKind: (optional) The provider kind for provider-specific dashboards
*/}}
{{- define "dashboards.configMap" }}
- apiVersion: v1
  kind: ConfigMap
  metadata:
    {{- include "dashboards.configMapMetadata" . | nindent 4 }}
  data:
    {{ .dashboardName }}.json: {{ .ctx.Files.Get .path | toJson }}
{{- end -}}

{{/*
Generate ConfigMapList for standard (non-provider-specific) dashboards.
Parameters:
  - .teamName: The team name (e.g., "atlas", "tenet")
  - .ctx: The root context ($)
*/}}
{{- define "dashboards.standard" -}}
# This file is generated by https://github.com/giantswarm/dashboards
apiVersion: v1
kind: ConfigMapList
items:
## Dashboards (always deployed)
{{- range $path, $_ := .ctx.Files.Glob "dashboards/**/*.json" }}
{{- if not (hasPrefix "dashboards/provider/" $path) }}
{{- $dashboardName := regexReplaceAll "(^.*/)(.*)\\.json$" $path "${2}" }}
{{- $org := regexReplaceAll "^dashboards/([^/]+)/.*$" $path "${1}" }}
{{- $folder := regexReplaceAll "^dashboards/[^/]+/(.*)/[^/]+\\.json$" $path "${1}" }}
{{- include "dashboards.configMap" (dict "teamName" $.teamName "org" $org "folder" $folder "dashboardName" $dashboardName "path" $path "ctx" $.ctx) }}
{{- end }}
{{- end }}
{{- end -}}

{{/*
Generate ConfigMapList for provider-specific dashboards.
Parameters:
  - .teamName: The team name (e.g., "atlas", "tenet")
  - .ctx: The root context ($)
*/}}
{{- define "dashboards.provider" -}}
{{- $providerKind := .ctx.Values.global.provider.kind | default "" }}
{{- if $providerKind }}
{{- $globPattern := printf "dashboards/provider/%s/**/*.json" $providerKind }}
{{- $files := .ctx.Files.Glob $globPattern }}
{{- if $files }}
# This file is generated by https://github.com/giantswarm/dashboards
apiVersion: v1
kind: ConfigMapList
items:
## Provider-specific dashboards (only deployed when provider matches)
{{- range $path, $_ := $files }}
{{- $dashboardName := regexReplaceAll "(^.*/)(.*)\\.json$" $path "${2}" }}
{{- $providerPrefix := printf "dashboards/provider/%s/" $providerKind }}
{{- $relativePath := trimPrefix $providerPrefix $path }}
{{- $org := regexReplaceAll "^([^/]+)/.*$" $relativePath "${1}" }}
{{- $folder := regexReplaceAll "^[^/]+/(.*)/[^/]+\\.json$" $relativePath "${1}" }}
{{- include "dashboards.configMap" (dict "teamName" $.teamName "org" $org "folder" $folder "dashboardName" $dashboardName "path" $path "providerKind" $providerKind "ctx" $.ctx) }}
{{- end }}
{{- end }}
{{- end }}
{{- end -}}
