{
 "title": "Karpenter",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "organization", "label": "organization", "query": { "query": "label_values(organization)" } },
   {
    "name": "cluster_id",
    "label": "cluster_id",
    "query": {
     "query": "label_values(kubernetes_build_info{organization=\"$organization\"},cluster_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Provisioner CPU/RAM usage percentage",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "karpenter_provisioner_usage_pct{cluster_id=\"$cluster_id\",resource_type=\"memory\"}"
    },
    {
     "expr": "karpenter_provisioner_usage_pct{cluster_id=\"$cluster_id\",resource_type=\"cpu\"}"
    }
   ]
  },
  {
   "title": "Eligible machines for deprovisioning",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(karpenter_deprovisioning_eligible_machines{cluster_id=\"$cluster_id\"}) by (deprovisioner)"
    }
   ]
  },
  {
   "title": "Interruption actions performed",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(karpenter_interruption_actions_performed{cluster_id=\"$cluster_id\"}) by (action_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deprovisioning actions performed",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "group(karpenter_deprovisioning_actions_performed{cluster_id=\"$cluster_id\"}) by (action)"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(karpenter_cloudprovider_errors_total{cluster_id=\"$cluster_id\"}) by (error)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}