{
 "title": "Flux Control Plane",
 "tags": [
  "flux",
  "component:flux",
  "topic:gitops",
  "owner:team-honeybadger"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "organization",
    "label": "Organization",
    "query": {
     "query": "label_values(gotk_reconcile_duration_seconds_count, organization)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(gotk_reconcile_duration_seconds_count{organization=\"$organization\"}, cluster_id)"
    }
   },
   {
    "name": "namespace",
    "label": "Flux namespace",
    "query": {
     "query": "label_values(workqueue_work_duration_seconds_count{cluster_id=\"$cluster\", pod=~\"(flux-)?(source|kustomize|helm|notification|image-automation|image-reflector)-controller-.*\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Controllers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(go_info{cluster_id=\"$cluster\", namespace=\"$namespace\",pod=~\".*-controller-.*\"})",
     "legendFormat": "pods"
    }
   ]
  },
  {
   "title": "Max Work Queue",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(workqueue_longest_running_processor_seconds{cluster_id=\"$cluster\", namespace=\"$namespace\",pod=~\".*-controller-.*\"})",
     "legendFormat": "seconds"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(go_memstats_alloc_bytes{cluster_id=\"$cluster\", namespace=\"$namespace\",pod=~\".*-controller-.*\"})"
    }
   ]
  },
  {
   "title": "API Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{cluster_id=\"$cluster\", namespace=\"$namespace\",pod=~\".*-controller-.*\"}[$__rate_interval]))",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "Kubernetes API Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{cluster_id=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "total"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{cluster_id=\"$cluster\", namespace=\"$namespace\",code!~\"2..\"}[$__rate_interval]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Resource Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{cluster_id=\"$cluster\", namespace=\"$namespace\",pod=~\".*-controller-.*\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster_id=\"$cluster\", namespace=\"$namespace\",container!=\"POD\",container!=\"\",pod=~\".*-controller-.*\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Reconciliation Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cluster Reconciliation Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "workqueue_longest_running_processor_seconds{cluster_id=\"$cluster\", namespace=\"$namespace\", name=\"kustomization\"}",
     "legendFormat": "kustomizations"
    }
   ]
  },
  {
   "title": "Cluster Reconciliations ops/min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_total{cluster_id=\"$cluster\", namespace=\"$namespace\", controller=\"kustomization\",result!=\"error\"}[$__rate_interval])) by (controller) * 60",
     "legendFormat": "successful reconciliations "
    },
    {
     "expr": "sum(rate(controller_runtime_reconcile_total{cluster_id=\"$cluster\", namespace=\"$namespace\", controller=\"kustomization\",result=\"error\"}[$__rate_interval])) by (controller) * 60",
     "legendFormat": "failed reconciliations "
    }
   ]
  },
  {
   "title": "Sources Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Git Repos ops/min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_total{cluster_id=\"$cluster\", namespace=\"$namespace\", controller=\"gitrepository\",result!=\"error\"}[$__rate_interval])) * 60",
     "legendFormat": "successful git pulls"
    },
    {
     "expr": "sum(rate(controller_runtime_reconcile_total{cluster_id=\"$cluster\", namespace=\"$namespace\", controller=\"gitrepository\",result=\"error\"}[$__rate_interval])) * 60",
     "legendFormat": "failed git pulls"
    }
   ]
  },
  {
   "title": "OCI Repos ops/min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_total{cluster_id=\"$cluster\", namespace=\"$namespace\", controller=\"ocirepository\",result!=\"error\"}[$__rate_interval])) * 60",
     "legendFormat": "successful oci pulls"
    },
    {
     "expr": "sum(rate(controller_runtime_reconcile_total{cluster_id=\"$cluster\", namespace=\"$namespace\", controller=\"ocirepository\",result=\"error\"}[$__rate_interval])) * 60",
     "legendFormat": "failed oci pulls"
    }
   ]
  },
  {
   "title": "Helm Repos ops/min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_total{cluster_id=\"$cluster\", namespace=\"$namespace\", controller=\"helmrepository\",result!=\"error\"}[$__rate_interval])) * 60",
     "legendFormat": "successful helm pulls"
    },
    {
     "expr": "sum(rate(controller_runtime_reconcile_total{cluster_id=\"$cluster\", namespace=\"$namespace\", controller=\"helmrepository\",result=\"error\"}[$__rate_interval])) * 60",
     "legendFormat": "failed helm pulls"
    }
   ]
  },
  {
   "title": "Buckets ops/min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_total{cluster_id=\"$cluster\", namespace=\"$namespace\", controller=\"bucket\",result!=\"error\"}[$__rate_interval])) * 60",
     "legendFormat": "successful bucket pulls"
    },
    {
     "expr": "sum(rate(controller_runtime_reconcile_total{cluster_id=\"$cluster\", namespace=\"$namespace\", controller=\"bucket\",result=\"error\"}[$__rate_interval])) * 60",
     "legendFormat": "failed bucket pulls"
    }
   ]
  },
  {
   "title": "Helm Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Helm Release Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(controller_runtime_reconcile_time_seconds_bucket{cluster_id=\"$cluster\", namespace=\"$namespace\", controller=\"helmrelease\"}[5m])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Helm Releases ops/min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_total{cluster_id=\"$cluster\", namespace=\"$namespace\", controller=\"helmrelease\",result!=\"error\"}[$__rate_interval])) by (controller) * 60",
     "legendFormat": "successful reconciliations "
    },
    {
     "expr": "sum(rate(controller_runtime_reconcile_total{cluster_id=\"$cluster\", namespace=\"$namespace\", controller=\"helmrelease\",result=\"error\"}[$__rate_interval])) by (controller) * 60",
     "legendFormat": "failed reconciliations "
    }
   ]
  },
  {
   "title": "Helm Charts ops/min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_total{cluster_id=\"$cluster\", namespace=\"$namespace\", controller=\"helmchart\",result!=\"error\"}[$__rate_interval])) by (controller) * 60",
     "legendFormat": "successful chart pulls"
    },
    {
     "expr": "sum(rate(controller_runtime_reconcile_total{cluster_id=\"$cluster\", namespace=\"$namespace\", controller=\"helmchart\",result=\"error\"}[$__rate_interval])) by (controller) * 60",
     "legendFormat": "failed chart pulls"
    }
   ]
  }
 ]
}