{
 "title": "Resource Usage",
 "tags": [ "owner:team-atlas" ],
 "time": { "from": "now-1M", "to": "now" },
 "templating": {
  "list": [
   { "name": "customer", "label": "Customer", "query": { "query": "label_values(customer)" } },
   { "name": "provider", "label": "Provider", "query": { "query": "label_values(provider)" } },
   {
    "name": "cluster_id",
    "label": "Cluster",
    "query": {
     "query": "label_values(aggregation:node:cpu_cores_total{customer=~\"$customer\",provider=~\"$provider\"}, cluster_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Usage Packages",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "ceil(\nsum(\naggregation:node:cpu_cores_total{customer=~\"$customer\",provider=~\"$provider\",cluster_id=~\"$cluster_id\",cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"stable\"} / 64 \nunless aggregation:node:memory_memtotal_bytes_total{customer=~\"$customer\",provider=~\"$provider\",cluster_id=~\"$cluster_id\",cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"stable\"} / 274877766206 \n> \naggregation:node:cpu_cores_total{customer=~\"$customer\",provider=~\"$provider\",cluster_id=~\"$cluster_id\",cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"stable\"} / 64\nor \naggregation:node:memory_memtotal_bytes_total{customer=~\"$customer\",provider=~\"$provider\",cluster_id=~\"$cluster_id\",cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"stable\"}/ 274877766206 )\nor on() vector(0)\n)"
    }
   ]
  },
  {
   "title": "With whole KVM CP",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "ceil(sum(aggregation:node:memory_memtotal_bytes_total{customer=~\"$customer\",provider!=\"kvm\",cluster_id=~\"$cluster_id\",cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"stable\"} / 274877766206 > aggregation:node:cpu_cores_total{customer=~\"$customer\",provider!=\"kvm\",cluster_id=~\"$cluster_id\",cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"stable\"} / 64 or aggregation:node:cpu_cores_total{customer=~\"$customer\",provider!=\"kvm\",cluster_id=~\"$cluster_id\",cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"stable\"} / 64) or on() vector(0)) + ceil(sum(aggregation:node:memory_memtotal_bytes_total{customer=~\"$customer\",provider=\"kvm\",cluster_id=~\"$cluster_id\",cluster_type=~\"control_plane|management_cluster\",pipeline=\"stable\"} / 274877766206 > aggregation:node:cpu_cores_total{customer=~\"$customer\",provider=\"kvm\",cluster_id=~\"$cluster_id\",cluster_type=~\"control_plane|management_cluster\",pipeline=\"stable\"} / 64 or aggregation:node:cpu_cores_total{customer=~\"$customer\",provider=\"kvm\",cluster_id=~\"$cluster_id\",cluster_type=~\"control_plane|management_cluster\",pipeline=\"stable\"} / 64) or on() vector(0))"
    }
   ]
  },
  {
   "title": "Usage Packs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(aggregation:node:memory_memtotal_bytes_total{customer=~\"$customer\",provider=~\"$provider\",cluster_id=~\"$cluster_id\",cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"stable\"} / 274877766206) by (cluster_id) > sum(aggregation:node:cpu_cores_total{customer=~\"$customer\",provider=~\"$provider\",cluster_id=~\"$cluster_id\",cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"stable\"} / 64) by (cluster_id) or sum(aggregation:node:cpu_cores_total{customer=~\"$customer\",provider=~\"$provider\",cluster_id=~\"$cluster_id\",cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"stable\"} / 64) by (cluster_id) or on() vector(0)",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(aggregation:kubernetes:up{customer=~\"$customer\",provider=~\"$provider\",cluster_id=~\"$cluster_id\",cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"stable\"}) OR on() vector(0)",
     "legendFormat": "Clusters"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:node:memory_memtotal_bytes_total{customer=~\"$customer\",provider=~\"$provider\",cluster_id=~\"$cluster_id\",cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"stable\"}) OR on() vector(0)",
     "legendFormat": "Workload Clusters"
    },
    {
     "expr": "sum(aggregation:node:memory_memtotal_bytes_total{customer=~\"$customer\",provider=~\"$provider\",cluster_type=~\"control_plane|management_cluster\",pipeline=\"stable\"}) OR on() vector(0)",
     "legendFormat": "Management Clusters"
    }
   ]
  },
  {
   "title": "Pod Memory Usage in Workload Clusters",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:kubernetes:pod_resource_requests_memory_bytes{customer=~\"$customer\",provider=~\"$provider\",cluster_id=~\"$cluster_id\",cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"stable\"}) OR on() vector(0)",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(aggregation:kubernetes:pod_resource_limits_memory_bytes{customer=~\"$customer\",provider=~\"$provider\",cluster_id=~\"$cluster_id\",cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"stable\"}) OR on() vector(0)",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Memory Ratio Available",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum(aggregation:kubernetes:pod_resource_requests_memory_bytes{customer=~\"$customer\",provider=~\"$provider\",cluster_id=~\"$cluster_id\",cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"stable\"}) OR on() vector(0)) / (sum(aggregation:node:memory_memtotal_bytes_total{customer=~\"$customer\",provider=~\"$provider\",cluster_id=~\"$cluster_id\",cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"stable\"}) OR on() vector(0))",
     "legendFormat": "Requests"
    },
    {
     "expr": "(sum(aggregation:kubernetes:pod_resource_limits_memory_bytes{customer=~\"$customer\",provider=~\"$provider\",cluster_id=~\"$cluster_id\",cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"stable\"})  OR on() vector(0)) / (sum(aggregation:node:memory_memtotal_bytes_total{customer=~\"$customer\",provider=~\"$provider\",cluster_id=~\"$cluster_id\",cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"stable\"}) OR on() vector(0))",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Nodes in Workload Clusters",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:kubernetes:node_total{customer=~\"$customer\",provider=~\"$provider\",cluster_id=~\"$cluster_id\",cluster_type=~\"tenant_cluster|workload_cluster\",role=\"master\"}) OR on() vector(0)",
     "legendFormat": "Master"
    },
    {
     "expr": "sum(aggregation:kubernetes:node_total{customer=~\"$customer\",provider=~\"$provider\",cluster_id=~\"$cluster_id\",cluster_type=~\"tenant_cluster|workload_cluster\",role=\"worker\"}) OR on() vector(0)",
     "legendFormat": "Worker"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:kubelet:running_pod_total{customer=~\"$customer\",provider=~\"$provider\",cluster_id=~\"$cluster_id\",cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"stable\"}) OR on() vector(0)",
     "legendFormat": "Pods"
    },
    {
     "expr": "sum(aggregation:kubelet:running_container_total{customer=~\"$customer\",provider=~\"$provider\",cluster_id=~\"$cluster_id\",cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"stable\"})  OR on() vector(0)",
     "legendFormat": "Containers"
    }
   ]
  },
  {
   "title": "vCPU Cores",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:node:cpu_cores_total{customer=~\"$customer\",provider=~\"$provider\",cluster_id=~\"$cluster_id\",cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"stable\"}) OR on() vector(0)",
     "legendFormat": "Workload Clusters"
    },
    {
     "expr": "sum(aggregation:node:cpu_cores_total{customer=~\"$customer\",provider=~\"$provider\",cluster_type=~\"control_plane|management_cluster\",pipeline=\"stable\"}) OR on() vector(0)",
     "legendFormat": "Management Clusters"
    }
   ]
  },
  {
   "title": "Pod vCPU Usage in Workload Clusters",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:kubernetes:pod_resource_requests_cpu_cores{customer=~\"$customer\",provider=~\"$provider\",cluster_id=~\"$cluster_id\",cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"stable\"}) OR on() vector(0)",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(aggregation:kubernetes:pod_resource_limits_cpu_cores{customer=~\"$customer\",provider=~\"$provider\",cluster_id=~\"$cluster_id\",cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"stable\"}) OR on() vector(0)",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "vCPU Ratio Available",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum(aggregation:kubernetes:pod_resource_requests_cpu_cores{customer=~\"$customer\",provider=~\"$provider\",cluster_id=~\"$cluster_id\",cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"stable\"})  OR on() vector(0)) /  (sum(aggregation:node:cpu_cores_total{customer=~\"$customer\",provider=~\"$provider\",cluster_id=~\"$cluster_id\",cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"stable\"}) OR on() vector(0))",
     "legendFormat": "Requests"
    },
    {
     "expr": "(sum(aggregation:kubernetes:pod_resource_limits_cpu_cores{customer=~\"$customer\",provider=~\"$provider\",cluster_id=~\"$cluster_id\",cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"stable\"}) OR on() vector(0)) / (sum(aggregation:node:cpu_cores_total{customer=~\"$customer\",provider=~\"$provider\",cluster_id=~\"$cluster_id\",cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"stable\"}) OR on() vector(0))",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Overhead Management Clusters",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum(aggregation:kubernetes:node_allocatable_memory_bytes{customer=~\"$customer\",provider=~\"$provider\",cluster_type=~\"control_plane|management_cluster\",pipeline=\"stable\"})  OR on() vector(0)) / (sum(aggregation:kubernetes:node_allocatable_memory_bytes{customer=~\"$customer\",provider=~\"$provider\",cluster_id=~\"$cluster_id\",cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"stable\"}) OR on() vector(0))",
     "legendFormat": "Memory Ratio TC/CP"
    },
    {
     "expr": "(sum(aggregation:kubernetes:node_allocatable_cpu_cores_total{customer=~\"$customer\",provider=~\"$provider\",cluster_type=~\"control_plane|management_cluster\",pipeline=\"stable\"}) OR on() vector(0)) / (sum(aggregation:kubernetes:node_allocatable_cpu_cores_total{customer=~\"$customer\",provider=~\"$provider\",cluster_id=~\"$cluster_id\",cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"stable\"}) OR on() vector(0))",
     "legendFormat": "CPU Ratio TC/CP"
    }
   ]
  },
  {
   "title": "vCPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(aggregation:node:cpu_utilization_percentage{customer=~\"$customer\",provider=~\"$provider\",cluster_id=~\"$cluster_id\",cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"stable\"}) by (region)",
     "legendFormat": "{{customer}}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(100 * (1 - (aggregation:node:memory_memavailable_bytes_total{customer=~\"$customer\",provider=~\"$provider\",cluster_id=~\"$cluster_id\",cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"stable\"} / aggregation:node:memory_memtotal_bytes_total{customer=~\"$customer\",provider=~\"$provider\",cluster_id=~\"$cluster_id\",cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"stable\"}))) by (region)",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "vCPU Cores in Workload Clusters",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(aggregation:node:cpu_cores_total{customer=~\"$customer\",provider=~\"$provider\",cluster_id=~\"$cluster_id\",cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"stable\"}) by (region)",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "Memory in Workload Clusters",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(aggregation:node:memory_memtotal_bytes_total{customer=~\"$customer\",provider=~\"$provider\",cluster_id=~\"$cluster_id\",cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"stable\"}) by (region)",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "Allocatable Pods in Workload Clusters",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(aggregation:kubernetes:node_allocatable_pods_total{customer=~\"$customer\",provider=~\"$provider\",cluster_id=~\"$cluster_id\",cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"stable\"}) by (region)",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "vCPU Cores (CP)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(aggregation:node:cpu_cores_total{customer=~\"$customer\",cluster_id=~\"$cluster_id\",provider=~\"$provider\",cluster_type=~\"control_plane|management_cluster\",pipeline=\"stable\"}) by (region)",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "Memory (CP)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(aggregation:node:memory_memtotal_bytes_total{customer=~\"$customer\",provider=~\"$provider\",cluster_type=~\"control_plane|management_cluster\",pipeline=\"stable\"}) by (region)",
     "legendFormat": "{{region}}"
    }
   ]
  }
 ]
}