{
 "title": "Kubernetes",
 "tags": [ "owner:team-turtles" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "customer", "label": "Customer", "query": "label_values(customer)" },
   { "name": "provider", "label": "Provider", "query": "label_values(provider)" }
  ]
 },
 "panels": [
  {
   "title": "Info",
   "type": "text",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "\n# Scraping of kube-state-metrics\n\nOn our workload clusters we currently only scrape kube-state-metrics for the kube-system and giantswarm namespaces. So here is still a lot of information missing.\n\n\n\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Namespaces",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:kubernetes:namespace_total{customer=~\"$customer\",provider=~\"$provider\",cluster_type=~\"tenant_cluster|workload_cluster\"})",
     "legendFormat": "Workload Clusters"
    },
    {
     "expr": "sum(aggregation:kubernetes:namespace_total{customer=~\"$customer\",provider=~\"$provider\",cluster_type=~\"control_plane|management_cluster\"})",
     "legendFormat": "Management Clusters"
    }
   ]
  },
  {
   "title": "Config Maps",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:kubernetes:configmap_total{customer=~\"$customer\",provider=~\"$provider\",cluster_type=~\"tenant_cluster|workload_cluster\"})",
     "legendFormat": "Workload Clusters"
    },
    {
     "expr": "sum(aggregation:kubernetes:configmap_total{customer=~\"$customer\",provider=~\"$provider\",cluster_type=~\"control_plane|management_cluster\"})",
     "legendFormat": "Management Clusters"
    }
   ]
  },
  {
   "title": "Services",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:kubernetes:service_total{customer=~\"$customer\",provider=~\"$provider\",cluster_type=~\"tenant_cluster|workload_cluster\"})",
     "legendFormat": "Workload Clusters"
    },
    {
     "expr": "sum(aggregation:kubernetes:service_total{customer=~\"$customer\",provider=~\"$provider\",cluster_type=~\"control_plane|management_cluster\"})",
     "legendFormat": "Management Clusters"
    }
   ]
  },
  {
   "title": "Ingresses",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:kubernetes:ingress_total{customer=~\"$customer\",provider=~\"$provider\",cluster_type=~\"tenant_cluster|workload_cluster\"})",
     "legendFormat": "Workload Clusters"
    },
    {
     "expr": "sum(aggregation:kubernetes:ingress_total{customer=~\"$customer\",provider=~\"$provider\",cluster_type=~\"control_plane|management_cluster\"})",
     "legendFormat": "Management Clusters"
    }
   ]
  },
  {
   "title": "Cronjobs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:kubernetes:cronjob_total{customer=~\"$customer\",provider=~\"$provider\",cluster_type=~\"tenant_cluster|workload_cluster\"})",
     "legendFormat": "Workload Clusters"
    },
    {
     "expr": "sum(aggregation:kubernetes:cronjob_total{customer=~\"$customer\",provider=~\"$provider\",cluster_type=~\"control_plane|management_cluster\"})",
     "legendFormat": "Management Clusters"
    }
   ]
  },
  {
   "title": "Deployments",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:kubernetes:deployment_total{customer=~\"$customer\",provider=~\"$provider\",cluster_type=~\"tenant_cluster|workload_cluster\"})",
     "legendFormat": "Workload Clusters"
    },
    {
     "expr": "sum(aggregation:kubernetes:deployment_total{customer=~\"$customer\",provider=~\"$provider\",cluster_type=~\"control_plane|management_cluster\"})",
     "legendFormat": "Management Clusters"
    }
   ]
  },
  {
   "title": "Daemonsets",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:kubernetes:daemonset_total{customer=~\"$customer\",provider=~\"$provider\",cluster_type=~\"tenant_cluster|workload_cluster\"})",
     "legendFormat": "Workload Clusters"
    },
    {
     "expr": "sum(aggregation:kubernetes:daemonset_total{customer=~\"$customer\",provider=~\"$provider\",cluster_type=~\"control_plane|management_cluster\"})",
     "legendFormat": "Management Clusters"
    }
   ]
  },
  {
   "title": "Secrets",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:kubernetes:secret_total{customer=~\"$customer\",provider=~\"$provider\",cluster_type=~\"tenant_cluster|workload_cluster\"})",
     "legendFormat": "Workload Clusters"
    },
    {
     "expr": "sum(aggregation:kubernetes:secret_total{customer=~\"$customer\",provider=~\"$provider\",cluster_type=~\"control_plane|management_cluster\"})",
     "legendFormat": "Management Clusters"
    }
   ]
  },
  {
   "title": "Persistent Volumes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:kubernetes:persistentvolume_total{customer=~\"$customer\",provider=~\"$provider\",cluster_type=~\"tenant_cluster|workload_cluster\"})",
     "legendFormat": "Workload Clusters"
    },
    {
     "expr": "sum(aggregation:kubernetes:persistentvolume_total{customer=~\"$customer\",provider=~\"$provider\",cluster_type=~\"control_plane|management_cluster\"})",
     "legendFormat": "Management Clusters"
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:kubernetes:job_total{customer=~\"$customer\",provider=~\"$provider\",cluster_type=~\"tenant_cluster|workload_cluster\"})",
     "legendFormat": "Workload Clusters"
    },
    {
     "expr": "sum(aggregation:kubernetes:job_total{customer=~\"$customer\",provider=~\"$provider\",cluster_type=~\"control_plane|management_cluster\"})",
     "legendFormat": "Management Clusters"
    }
   ]
  },
  {
   "title": "Deployments in Workload Clusters",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aggregation:kubernetes:deployment_total{customer=~\"$customer\",provider=~\"$provider\",cluster_type=~\"tenant_cluster|workload_cluster\"}) by (installation)",
     "legendFormat": "{{installation}}"
    }
   ]
  },
  {
   "title": "Persistent Volume Capacity in Workload Clusters",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(aggregation:kubernetes:persistentvolume_capacity_bytes{customer=~\"$customer\",provider=~\"$provider\",cluster_type=~\"tenant_cluster|workload_cluster\"}) by (installation)",
     "legendFormat": "{{installation}}"
    },
    {
     "expr": "sum(aggregation:kubernetes:persistentvolume_capacity_bytes{customer=~\"$customer\",provider=~\"$provider\",cluster_type=~\"tenant_cluster|workload_cluster\"})",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}