{
 "title": "Managed Apps",
 "tags": [ "owner:team-honeybadger" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "customer",
    "label": "Customer",
    "query": "label_values(aggregation:giantswarm:app_deployed_workload_cluster_total, customer)"
   },
   {
    "name": "provider",
    "label": "Provider",
    "query": "label_values(aggregation:giantswarm:app_deployed_workload_cluster_total, provider)"
   }
  ]
 },
 "panels": [
  {
   "title": "Managed Apps",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:giantswarm:app_deployed_workload_cluster_total{customer=~\"$customer\",provider=~\"$provider\",pipeline=\"stable\"})",
     "legendFormat": "Workload Clusters"
    },
    {
     "expr": "sum(aggregation:giantswarm:app_deployed_management_cluster_total{customer=~\"$customer\",provider=~\"$provider\",pipeline=\"stable\"})",
     "legendFormat": "Management Clusters"
    }
   ]
  },
  {
   "title": "Managed Apps",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 20, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(aggregation:giantswarm:app_deployed_workload_cluster_total{customer=~\"$customer\",provider=~\"$provider\",pipeline=\"stable\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Tenant Apps (Chiara)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aggregation:giantswarm:app_deployed_workload_cluster_total{pipeline=\"stable\"}[7d])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Versions of chart-operator",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(aggregation:giantswarm:app_deployed_workload_cluster_total{customer=~\"$customer\",provider=~\"$provider\",name=\"chart-operator\",pipeline=\"stable\"}) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Versions of node-exporter",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(aggregation:giantswarm:app_deployed_workload_cluster_total{customer=~\"$customer\",provider=~\"$provider\",name=\"node-exporter\",pipeline=\"stable\"}) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Versions of metrics-server",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(aggregation:giantswarm:app_deployed_workload_cluster_total{customer=~\"$customer\",provider=~\"$provider\",name=\"metrics-server\",pipeline=\"stable\"}) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Versions of kube-state-metrics",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(aggregation:giantswarm:app_deployed_workload_cluster_total{customer=~\"$customer\",provider=~\"$provider\",name=\"kube-state-metrics\"}) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Versions of net-exporter",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(aggregation:giantswarm:app_deployed_workload_cluster_total{customer=~\"$customer\",provider=~\"$provider\",name=\"net-exporter\"}) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Versions of cert-exporter",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(aggregation:giantswarm:app_deployed_workload_cluster_total{customer=~\"$customer\",provider=~\"$provider\",name=\"cert-exporter\",pipeline=\"stable\"}) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Versions of coredns",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(aggregation:giantswarm:app_deployed_workload_cluster_total{customer=~\"$customer\",provider=~\"$provider\",name=\"coredns\",pipeline=\"stable\"}) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Versions of nginx-ingress-controller",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(aggregation:giantswarm:app_deployed_workload_cluster_total{customer=~\"$customer\",provider=~\"$provider\",name=\"nginx-ingress-controller\",pipeline=\"stable\"}) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Versions of kiam",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(aggregation:giantswarm:app_deployed_workload_cluster_total{customer=~\"$customer\",provider=~\"$provider\",name=\"kiam\",pipeline=\"stable\"}) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Versions of external-dns",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(aggregation:giantswarm:app_deployed_workload_cluster_total{customer=~\"$customer\",provider=~\"$provider\",name=\"external-dns\",pipeline=\"stable\"}) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Versions of cluster-autoscaler",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(aggregation:giantswarm:app_deployed_workload_cluster_total{customer=~\"$customer\",provider=~\"$provider\",name=\"cluster-autoscaler\",pipeline=\"stable\"}) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Versions of cert-manager",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(aggregation:giantswarm:app_deployed_workload_cluster_total{customer=~\"$customer\",provider=~\"$provider\",name=\"cert-manager\",pipeline=\"stable\"}) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  }
 ]
}