{
 "title": "Ingress Vintage->CAPA migration",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:ingress:base_domain_total) by (customer)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Per customer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Adidas",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:ingress:base_domain_total{customer=\"adidas\"}) by (installation)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Egger",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:ingress:base_domain_total{customer=\"egger\"}) by (installation,cluster_id)",
     "legendFormat": "{{installation}}/{{cluster_id}}"
    }
   ]
  },
  {
   "title": "Adidas / anteater",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:ingress:base_domain_total{customer=\"adidas\", installation=\"anteater\"}) by (cluster_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Babymarkt",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:ingress:base_domain_total{customer=\"babymarkt\"}) by (installation, cluster_id)",
     "legendFormat": "{{installation}}/{{cluster_id}}"
    }
   ]
  }
 ]
}