{
 "title": "Container images from Docker Hub",
 "description": "We want to reduce pulls from Docker Hub as far as possible. This dashboard helps us track our progress.",
 "tags": [ "owner:team-honeybadger" ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "About this dashboard",
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Container images from Docker Hub\n\nThis dashboard tracks usage of container images pulled from `docker.io` throughout all installations and clusters.\n\nThe goal is to get the absolute number down as far as possible by mid January 2024. [Epic](https://github.com/giantswarm/roadmap/issues/2882)\n\nThis dashboard is managed by Team Honeybadger. Please contact the team for questions and feedback."
   }
  },
  {
   "title": "Containers with docker.io images absolute",
   "type": "stat",
   "description": "Number of containers using images from Docker Hub, as a mean of the current dashboard interval",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:docker:containers_using_dockerhub_image)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Containers with docker.io images, percentage of all containers",
   "type": "stat",
   "description": "Number of containers using images from Docker Hub, as a mean of the current dashboard interval",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(aggregation:docker:containers_using_dockerhub_image_relative)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Absolute", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Overall",
   "type": "timeseries",
   "description": "Number of containers that use an image pulled from Docker Hub",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(aggregation:docker:containers_using_dockerhub_image)",
     "legendFormat": "Value"
    }
   ]
  },
  {
   "title": "By cluster type",
   "type": "timeseries",
   "description": "Number of containers that use an image pulled from Docker Hub, by cluster type",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(aggregation:docker:containers_using_dockerhub_image) by (cluster_type)",
     "legendFormat": "{{cluster_type}}"
    }
   ]
  },
  {
   "title": "By customer (logarithmic scale)",
   "type": "timeseries",
   "description": "Number of containers that use an image pulled from Docker Hub, by customer",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(aggregation:docker:containers_using_dockerhub_image) by (customer)",
     "legendFormat": "{{customer}}"
    }
   ]
  },
  {
   "title": "By installation (logarithmic scale)",
   "type": "timeseries",
   "description": "Number of containers that use an image pulled from Docker Hub, by installation",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(aggregation:docker:containers_using_dockerhub_image) by (installation)",
     "legendFormat": "{{installation}}"
    }
   ]
  },
  {
   "title": "Only in workload clusters, by customer (logarithmic scale)",
   "type": "timeseries",
   "description": "Number of containers in workload clusters that use an image pulled from Docker Hub, by customer",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(aggregation:docker:containers_using_dockerhub_image{cluster_type=\"workload_cluster\"}) by (customer)",
     "legendFormat": "{{customer}}"
    }
   ]
  },
  {
   "title": "Only in workload clusters, by installation (logarithmic scale)",
   "type": "timeseries",
   "description": "Number of containers in workload clusters that use an image pulled from Docker Hub, by installation",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(aggregation:docker:containers_using_dockerhub_image{cluster_type=\"workload_cluster\"}) by (installation)",
     "legendFormat": "{{installation}}"
    }
   ]
  },
  { "title": "Relative", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Overall average",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(aggregation:docker:containers_using_dockerhub_image_relative)",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "By cluster type",
   "type": "timeseries",
   "description": "Share of containers that use an image pulled from Docker Hub, by cluster type",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(aggregation:docker:containers_using_dockerhub_image_relative) by (cluster_type)",
     "legendFormat": "{{ cluster_type }}"
    }
   ]
  },
  {
   "title": "By customer",
   "type": "timeseries",
   "description": "Share of containers that use an image pulled from Docker Hub, by customer",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(aggregation:docker:containers_using_dockerhub_image_relative) by (customer)",
     "legendFormat": "{{ installation }}"
    }
   ]
  },
  {
   "title": "By installation",
   "type": "timeseries",
   "description": "Share of containers that use an image pulled from Docker Hub, by installation",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(aggregation:docker:containers_using_dockerhub_image_relative) by (installation)",
     "legendFormat": "{{ installation }}"
    }
   ]
  },
  {
   "title": "Only in workload clusters, by customer",
   "type": "timeseries",
   "description": "Share of containers in workload clusters that use an image pulled from Docker Hub, by customer",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(aggregation:docker:containers_using_dockerhub_image_relative{cluster_type=\"workload_cluster\"}) by (customer)",
     "legendFormat": "{{ installation }}"
    }
   ]
  },
  {
   "title": "Only in workload clusters, by installation",
   "type": "timeseries",
   "description": "Share of containers in workload clusters that use an image pulled from Docker Hub, by installation",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(aggregation:docker:containers_using_dockerhub_image_relative{cluster_type=\"workload_cluster\"}) by (installation)",
     "legendFormat": "{{ installation }}"
    }
   ]
  }
 ]
}