{
 "title": "Ingress",
 "tags": [ "owner:team-cabbage" ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Ingress Requests",
   "type": "timeseries",
   "description": "Ingress requests to all workload clusters",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(aggregation:ingress:requests_total{cluster_type=~\"tenant_cluster|workload_cluster\"})",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Ingress Requests by Customer (log scale)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(aggregation:ingress:requests_total{cluster_type=~\"tenant_cluster|workload_cluster\"}) by (customer)",
     "legendFormat": "{{customer}}"
    }
   ]
  },
  {
   "title": "Ingress Requests by Provider (log scale)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(aggregation:ingress:requests_total{cluster_type=~\"tenant_cluster|workload_cluster\"}) by (provider)",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Ingress Requests by Region (log scale)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(aggregation:ingress:requests_total{cluster_type=~\"tenant_cluster|workload_cluster\",region=~\"eu-.*\"})",
     "legendFormat": "Europe"
    },
    {
     "expr": "sum(aggregation:ingress:requests_total{cluster_type=~\"tenant_cluster|workload_cluster\",region=~\"us-.*\"})",
     "legendFormat": "America"
    },
    {
     "expr": "sum(aggregation:ingress:requests_total{cluster_type=~\"tenant_cluster|workload_cluster\",region=~\"ap-.*\"})",
     "legendFormat": "Asia / Pacific"
    },
    {
     "expr": "sum(aggregation:ingress:requests_total{cluster_type=~\"tenant_cluster|workload_cluster\",region=~\"cn-.*\"})",
     "legendFormat": "China"
    }
   ]
  },
  {
   "title": "Ingress Requests by Installation (log scale)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(aggregation:ingress:requests_total{cluster_type=~\"tenant_cluster|workload_cluster\"}) by (installation)",
     "legendFormat": "{{installation}}"
    }
   ]
  }
 ]
}