{
 "title": "Security: Teams Overview",
 "description": "Breakdown of security issues per-team",
 "tags": [ "owner:team-shield" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "team",
    "label": "Team",
    "query": {
     "query": "label_values(aggregation:kyverno_policy_deployment_status_team,team)"
    }
   },
   {
    "name": "category",
    "label": "Category",
    "query": {
     "query": "label_values(aggregation:kyverno_policy_deployment_status_team,category)"
    }
   },
   {
    "name": "policy",
    "label": "Policy",
    "query": {
     "query": "label_values(aggregation:kyverno_policy_deployment_status_team,policy)"
    }
   },
   {
    "name": "app",
    "label": "App",
    "query": {
     "query": "label_values(aggregation:kyverno_policy_deployment_status_team,app)"
    }
   },
   {
    "name": "deployment",
    "label": "Deployment",
    "query": {
     "query": "label_values(aggregation:kyverno_policy_deployment_status_team,deployment)"
    }
   },
   {
    "name": "daemonset",
    "label": "DaemonSet",
    "query": {
     "query": "label_values(aggregation:kyverno_policy_daemonset_status_team,daemonset)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Workload Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Deployment Status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (sum(aggregation:kyverno_policy_deployment_status_team{team=~\"$team\", app=~\"$app\", deployment=~\"$deployment\", category=~\"$category\"}) by (status) / on() group_left() sum(aggregation:kyverno_policy_deployment_status_team))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DaemonSet Status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (sum(aggregation:kyverno_policy_daemonset_status_team{team=~\"$team\", app=~\"$app\", daemonset=~\"$daemonset\", category=~\"$category\"}) by (status) / on() group_left() sum(aggregation:kyverno_policy_daemonset_status_team))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failing Apps by Team",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "count by (app, team) (aggregation:kyverno_policy_deployment_status_team{status=\"fail\", team=~\"$team\"}) \nor \ncount by (app, team) (aggregation:kyverno_policy_daemonset_status_team{status=\"fail\", team=~\"$team\"})\nor \ncount by (app, team) (aggregation:kyverno_policy_statefulset_status_team{status=\"fail\", team=~\"$team\"})"
    }
   ]
  },
  {
   "title": "Failing Deployments by Team",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum(aggregation:kyverno_policy_deployment_status_team{status=\"fail\", team=~\"$team\", app=~\"$app\", deployment=~\"$deployment\", category=~\"$category\", policy=~\"$policy\"}) by (app, deployment, team, category, policy)"
    }
   ]
  },
  {
   "title": "Failing DaemonSets by Team",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "sum(aggregation:kyverno_policy_daemonset_status_team{status=\"fail\", team=~\"$team\", app=~\"$app\", name=~\"$daemonset\", category=~\"$category\", policy=~\"$policy\"}) by (app, name, team, category, policy)"
    }
   ]
  },
  {
   "title": "Failing StatefulSets by Team",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "sum(aggregation:kyverno_policy_statefulset_status_team{status=\"fail\", team=~\"$team\", app=~\"$app\", name=~\"$deployment\", category=~\"$category\", policy=~\"$policy\"}) by (app, name, team, category, policy)"
    }
   ]
  },
  {
   "title": "Failing CronJobs by Team",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "sum(aggregation:kyverno_policy_cronjob_status_team{status=\"fail\", team=~\"$team\", app=~\"$app\", name=~\"$deployment\", category=~\"$category\", policy=~\"$policy\"}) by (app, name, team, category, policy)"
    }
   ]
  },
  {
   "title": "Failing Jobs by Team",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "sum(aggregation:kyverno_policy_job_status_team{status=\"fail\", team=~\"$team\", app=~\"$app\", name=~\"$deployment\", category=~\"$category\", policy=~\"$policy\"}) by (app, name, team, category, policy)"
    }
   ]
  },
  {
   "title": "Policy Pass/Fail (Baseline)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "count(aggregation:kyverno_policy_status_team{status=\"fail\", team=~\"$team\", app=~\"$app\", deployment=~\"$deployment\", category=\"Pod Security Standards (Baseline)\"})",
     "legendFormat": "Fail"
    },
    {
     "expr": "count(aggregation:kyverno_policy_status_team{status=\"pass\", team=~\"$team\", app=~\"$app\", deployment=~\"$deployment\", category=\"Pod Security Standards (Baseline)\"})",
     "legendFormat": "Pass"
    }
   ]
  },
  {
   "title": "Policy Pass/Fail (Restricted)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "targets": [
    {
     "expr": "count(aggregation:kyverno_policy_status_team{status=\"fail\", team=~\"$team\", app=~\"$app\", deployment=~\"$deployment\", category=\"Pod Security Standards (Restricted)\"})",
     "legendFormat": "Fail"
    },
    {
     "expr": "count(aggregation:kyverno_policy_status_team{status=\"pass\", team=~\"$team\", app=~\"$app\", deployment=~\"$deployment\", category=\"Pod Security Standards (Restricted)\"})",
     "legendFormat": "Pass"
    }
   ]
  },
  {
   "title": "Current App Status",
   "type": "table",
   "description": "Zach is *pretty* sure this is the number of apps with the listed status for each policy.",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": "count by (policy, status) (sum by (app, policy, status) (aggregation:kyverno_policy_deployment_status_team{}))"
    }
   ]
  },
  {
   "title": "Currently Deployed Apps WITHOUT Policy Status",
   "type": "table",
   "description": "These Apps are deployed in WCs and not on MCs, so we don't have data for them. They may be the same app as on an MC with an old name (e.g. with the -app suffix) or they might be apps we don't run on MCs.",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 96 },
   "targets": [
    {
     "expr": "(\n    sum(aggregation:giantswarm:app_info{app!=\"app-exporter\"}) by (app, team) \n    and on(app)\n    sum(aggregation:giantswarm:app_deployed_workload_cluster_total{}) by (app)\n)\nunless on (app)\n(\n    sum(aggregation:kyverno_policy_deployment_status_team{}) by (app)\n    or\n    sum(aggregation:kyverno_policy_daemonset_status_team{}) by (app)\n    or\n    sum(aggregation:kyverno_policy_statefulset_status_team{}) by (app)\n)"
    }
   ]
  },
  {
   "title": "Resource Status by Policy",
   "type": "table",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 115 },
   "targets": [
    {
     "expr": "count(aggregation:kyverno_policy_deployment_status_team{}) by (policy, status) + count(aggregation:kyverno_policy_daemonset_status_team{}) by (policy, status)"
    }
   ]
  },
  { "title": "Rollout Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 135 } },
  {
   "title": "Failing Resources by MC",
   "type": "table",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 136 },
   "targets": [
    {
     "expr": "count(aggregation:kyverno_policy_deployment_status_team{status=\"fail\"}) by (policy, cluster_id) + count(aggregation:kyverno_policy_daemonset_status_team{status=\"fail\"}) by (policy, cluster_id)"
    }
   ]
  },
  {
   "title": "Policy Enforcement Status by MC",
   "type": "table",
   "gridPos": { "h": 30, "w": 24, "x": 0, "y": 156 },
   "targets": [
    {
     "expr": "sum(aggregation:kyverno_policy_status{category=~\"Pod Security Standards.*\", policy!~\".*(-audit|-not-strict)\", cluster_type=\"management_cluster\"}) by (cluster_id, policy, validationFailureAction)"
    }
   ]
  }
 ]
}