{
 "title": "General service metrics",
 "description": "Provide a bunch of metrics for one specific service",
 "tags": [ "owner:team-honeybadger" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "app", "label": "App name", "query": { "query": "label_values(app)" } }
  ]
 },
 "panels": [
  {
   "title": "About this dashboard",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "About this dashboard",
     "type": "text",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
     "options": {
      "content": "The purpose of this dashboard is to give details about a single service/app throughout all installations and clusters.\n\nThe data displayed shows the a momentary snapshot within the selected timeframe.\n\nIf you see \"No data\" on a panel, the selected app has not been deployed in any clusters within the selected time frame.\n\nPlease contact Team Honeybadger with feedback and questions."
     }
    }
   ]
  },
  { "title": "Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Number of deployments",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:giantswarm:app_info{app=~\"$app\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of deployments by status",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 7, "x": 4, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:giantswarm:app_info{app=~\"$app\"}) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Number of upgradable deployments",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 11, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:giantswarm:app_info{app=~\"$app\",upgrade_available=\"true\"})",
     "legendFormat": "{{ cluster_type }}"
    }
   ]
  },
  {
   "title": "Number of deployments by provider",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:giantswarm:app_info{app=~\"$app\"}) by (provider)",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  { "title": "App deployment details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Latest deployment data",
   "type": "table",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "aggregation:giantswarm:app_info{app=~\"$app\"}"
    }
   ]
  },
  { "title": "Kyverno policy status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Kyverno policy status for deployments",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "aggregation:kyverno_policy_deployment_status_team{app=\"$app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kyverno policy status for daemonsets",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "aggregation:kyverno_policy_daemonset_status_team{app=\"$app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kyverno policy status for statefulsets",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "aggregation:kyverno_policy_statefulset_status_team{app=\"$app\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}