{
 "title": "End users and UX",
 "description": "Metrics on humans using our systems",
 "tags": [
  "owner:team-bigmac",
  "component:api",
  "component:dex",
  "component:dex-operator",
  "component:dex-app"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "REST API requests - all installations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(aggregation:giantswarm:api_requests)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "REST API Error 4xx",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(aggregation:giantswarm:api_requests{status=~\"4..\"}) by (installation)",
     "legendFormat": "{{ installation }}"
    }
   ]
  },
  {
   "title": "REST API Error 500",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(aggregation:giantswarm:api_requests{status=~\"5..\"}) by (installation)",
     "legendFormat": "{{ installation }}"
    }
   ]
  },
  {
   "title": "Dex - successful requests ",
   "type": "timeseries",
   "description": "Requests to dex with status 200 or 30x",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(aggregation:dex_requests_status_ok[10m])) by (installation)",
     "legendFormat": "{{ installation }}"
    }
   ]
  },
  {
   "title": "REST API legacy token usage (percent)",
   "type": "stat",
   "description": "Uses of the legacy token auth mechanism, compared to the overall number of requests. Values over 100% are explained by the fact that we use different metrics to calculate the ratio.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(aggregation:giantswarm:api_auth_giantswarm_successful_attempts_total) / sum(aggregation:giantswarm:api_requests)",
     "legendFormat": "{{ cluster_id }}"
    }
   ]
  },
  {
   "title": "Dex errors (4xx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(aggregation:dex_requests_status_4xx[10m])) by (installation)",
     "legendFormat": "{{ installation }}"
    }
   ]
  },
  {
   "title": "Dex errors (5xx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(aggregation:dex_requests_status_5xx[10m])) by (installation)",
     "legendFormat": "{{installation}}"
    }
   ]
  },
  {
   "title": "Dex Operator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Managed Dex App Registrations",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count by(provider_type) (aggregation:dex_operator_idp_secret_expiry_time)",
       "legendFormat": "{{provider_type}}"
      }
     ]
    },
    {
     "title": "By Cluster Type",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(aggregation:dex_operator_idp_secret_expiry_time{app_namespace=\"giantswarm\"})",
       "legendFormat": "management cluster"
      },
      {
       "expr": "count(aggregation:dex_operator_idp_secret_expiry_time{app_namespace!=\"giantswarm\"})",
       "legendFormat": "workload cluster"
      }
     ]
    },
    {
     "title": "Management Clusters without Managed Dex",
     "type": "table",
     "gridPos": { "h": 9, "w": 4, "x": 8, "y": 1 },
     "targets": [
      {
       "expr": "count by(installation) (aggregation:kubelet:version{cluster_type=\"management_cluster\"}) unless count by(installation)(aggregation:dex_operator_idp_secret_expiry_time{app_namespace=\"giantswarm\"})",
       "legendFormat": "{{provider_type}}"
      }
     ]
    },
    {
     "title": "Secret Renewal",
     "type": "table",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "min by(app_registration_name, app_owner, app_namespace, provider_name, provider_type, installation) (aggregation:dex_operator_idp_secret_expiry_time * 1000)"
      }
     ]
    },
    {
     "title": "By Identity Provider",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count by(provider_type) (aggregation:dex_operator_idp_secret_expiry_time)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "By Owner",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count by(app_owner) (aggregation:dex_operator_idp_secret_expiry_time)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Clusters with Managed Dex",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(count by(app_registration_name)  (aggregation:dex_operator_idp_secret_expiry_time{app_namespace!=\"giantswarm\"})) / count(count by(cluster_id) (aggregation:kubelet:version{cluster_type=\"workload_cluster\"}))",
       "legendFormat": "workload clusters"
      },
      {
       "expr": "count(count by(installation)(aggregation:dex_operator_idp_secret_expiry_time{app_namespace=\"giantswarm\"})) / count(count by(installation) (aggregation:kubelet:version{cluster_type=\"management_cluster\"}))",
       "legendFormat": "management clusters"
      }
     ]
    }
   ]
  },
  {
   "title": "Authentication systems",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "REST API legacy token usage",
     "type": "timeseries",
     "description": "Use of legacy auth tokens in the REST API, as a rate. We want this to become zero.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "aggregation:giantswarm:api_auth_giantswarm_successful_attempts_total",
       "legendFormat": "{{ cluster_id }}"
      }
     ]
    },
    {
     "title": "Kubernetes audit events",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(aggregation:kubernetes:audit_event_total{cluster_type=\"management_cluster\"}[5m])) by (installation)",
       "legendFormat": "{{ installation }}"
      }
     ]
    },
    {
     "title": "REST API requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "avg(aggregation:giantswarm:api_requests) by (installation)",
       "legendFormat": "{{ installation }}"
      }
     ]
    },
    {
     "title": "Passage requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "avg(aggregation:giantswarm:passage_requests) by (installation)",
       "legendFormat": "{{ installation }}"
      }
     ]
    },
    {
     "title": "REST API authentication failures (legacy token auth)",
     "type": "timeseries",
     "description": "Authentication failures counted in the REST API, using the legacy giantswarm token authentication mechanism.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "avg(aggregation:giantswarm:api_auth_giantswarm_failed_attempts_total) by (installation)",
       "legendFormat": "{{ installation }}"
      }
     ]
    },
    {
     "title": "REST API authentication failures (SSO)",
     "type": "timeseries",
     "description": "Authentication failures counted in the REST, via the single sign-on authentication mechanism",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "avg(aggregation:giantswarm:api_auth_jwt_failed_attempts_total) by (installation)",
       "legendFormat": "{{ installation }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Dex",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Dex - successful requests ",
     "type": "timeseries",
     "description": "Requests to dex with status 200 or 30x",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(aggregation:dex_requests_status_ok[1m])) by (installation)",
       "legendFormat": "{{ installation }}"
      }
     ]
    },
    {
     "title": "Dex - erros (5xx)",
     "type": "timeseries",
     "description": "Requests to dex with status 5xx",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(aggregation:dex_requests_status_5xx[1m])) by (installation)",
       "legendFormat": "{{ installation }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Kubernetes and Management API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Management API requests",
     "type": "timeseries",
     "description": "Requests to the management cluster Kubernetes API",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(aggregation:kubernetes:apiserver_request_count{cluster_type=\"management_cluster\"}[5m])) by (installation)",
       "legendFormat": "{{ installation }}"
      }
     ]
    },
    {
     "title": "Management API requests (logarithmic)",
     "type": "timeseries",
     "description": "Requests to the management cluster Kubernetes API",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(aggregation:kubernetes:apiserver_request_count{cluster_type=\"management_cluster\"}[5m])) by (installation)",
       "legendFormat": "{{ installation }}"
      }
     ]
    }
   ]
  },
  {
   "title": "REST API Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Errors by installation",
     "type": "barchart",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 39 },
     "targets": [
      {
       "expr": "sum(aggregation:giantswarm:api_requests{status=~\"[45]..\"}) by (installation)"
      }
     ]
    },
    {
     "title": "Timeouts (status 499)",
     "type": "timeseries",
     "description": "NGINX ingress controller logs status 499 in cases where the client closed the connection before the API could return a response. This means that processing the request took longer than the configured limit in the client.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
     "targets": [
      {
       "expr": "sum(aggregation:giantswarm:api_requests{status=\"499\"}) by (installation)",
       "legendFormat": "{{installation}}"
      }
     ]
    },
    {
     "title": "Timeout errors (status 499) by installation",
     "type": "barchart",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 53 },
     "targets": [
      {
       "expr": "sum(aggregation:giantswarm:api_requests{status=\"499\"}) by (installation)"
      }
     ]
    }
   ]
  }
 ]
}