{
 "title": "Alerts in relation to prediction",
 "description": "Hackathon project by Marian",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Average and standard deviation",
   "type": "timeseries",
   "description": "Statistical summary of alert activity in all installations",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(alerts_forecast:actual / on (installation) group_right() clamp_min(alerts_forecast:predicted{ml_forecast=\"yhat\"}, 1)) + stddev(alerts_forecast:actual / on (installation) group_right() clamp_min(alerts_forecast:predicted{ml_forecast=\"yhat\"}, 1)) / 2",
     "legendFormat": "stddev-upper"
    },
    {
     "expr": "avg(alerts_forecast:actual / on (installation) group_right() clamp_min(alerts_forecast:predicted{ml_forecast=\"yhat\"}, 1)) - stddev(alerts_forecast:actual / on (installation) group_right() clamp_min(alerts_forecast:predicted{ml_forecast=\"yhat\"}, 1)) / 2",
     "legendFormat": "stddev-lower"
    },
    {
     "expr": "avg(alerts_forecast:actual / on (installation) group_right() clamp_min(alerts_forecast:predicted{ml_forecast=\"yhat\"}, 1))",
     "legendFormat": "average"
    }
   ]
  },
  {
   "title": "Current alert volume in relation to prediction (log scale)",
   "type": "timeseries",
   "description": "The current volume of alerts, per installation, in relation to the prediction value for the installation. The y value is a multitude. For example, the value 4 means that the current volume is four times the predicted volume.",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "(alerts_forecast:actual{} / on (installation) group_right() clamp_min(alerts_forecast:predicted{ml_forecast=\"yhat\"}, 1))",
     "legendFormat": "{{installation}}"
    }
   ]
  },
  {
   "title": "Current alert volume in relation to prediction (linear scale)",
   "type": "timeseries",
   "description": "The current volume of alerts, per installation, in relation to the prediction value for the installation. The y value is a multitude. For example, the value 4 means that the current volume is four times the predicted volume.",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "(alerts_forecast:actual{} / on (installation) group_right() clamp_min(alerts_forecast:predicted{ml_forecast=\"yhat\"}, 1))",
     "legendFormat": "{{installation}}"
    }
   ]
  },
  {
   "title": "Current alert volume",
   "type": "timeseries",
   "description": "Current active alerts per installations, not normalized",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "aggregation:alertmanager:alerts_active_total",
     "legendFormat": "{{installation}}"
    }
   ]
  }
 ]
}