{
 "title": "Utilization",
 "time": { "from": "now-4d", "to": "now" },
 "templating": {
  "list": [
   { "name": "customer", "label": "Customer", "query": "label_values(customer)" },
   {
    "name": "provider",
    "label": "Provider",
    "query": "label_values(aggregation:node:cpu_utilization_percentage{customer=~\"$customer\"}, provider)"
   },
   {
    "name": "region",
    "label": "Region",
    "query": "label_values(aggregation:node:cpu_utilization_percentage{customer=~\"$customer\",provider=~\"$provider\"}, region)"
   },
   {
    "name": "installation",
    "label": "Installation",
    "query": "label_values(aggregation:node:cpu_utilization_percentage{customer=~\"$customer\",region=~\"$region\"}, installation)"
   },
   {
    "name": "cluster_id",
    "label": "Cluster",
    "query": "label_values(aggregation:node:cpu_utilization_percentage{customer=~\"$customer\",region=~\"$region\",installation=~\"$installation\"}, cluster_id)"
   }
  ]
 },
 "panels": [
  {
   "title": "Nodes",
   "type": "stat",
   "description": "Latest value in the selected time interval",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:kubernetes:node_total{customer=~\"$customer\",cluster_id=~\"$cluster_id\",cluster_type=~\"tenant_cluster|workload_cluster\",installation=~\"$installation\"})",
     "legendFormat": "{{ cluster_id }}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "gauge",
   "description": "Effective CPU utilizaiton in all nodes (aggregation:node:cpu_utilization_percentage)",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(aggregation:node:cpu_utilization_percentage{customer=~\"$customer\",provider=~\"$provider\",region=~\"$region\",installation=~\"$installation\",cluster_id=~\"$cluster_id\",cluster_type=~\"tenant_cluster|workload_cluster\"})",
     "legendFormat": "Average for selected customer/provider/region"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "gauge",
   "description": "Based on aggregation:node:memory_memavailable_bytes_total divided by aggregation:node:memory_memtotal_bytes_total",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - (sum(aggregation:node:memory_memavailable_bytes_total{customer=~\"$customer\",provider=~\"$provider\",region=~\"$region\",installation=~\"$installation\",cluster_id=~\"$cluster_id\",cluster_type=~\"tenant_cluster|workload_cluster\"}) / sum(aggregation:node:memory_memtotal_bytes_total{customer=~\"$customer\",provider=~\"$provider\",region=~\"$region\",installation=~\"$installation\",cluster_id=~\"$cluster_id\",cluster_type=~\"tenant_cluster|workload_cluster\"})))",
     "legendFormat": "Average for selected customer/provider/region"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(aggregation:kubernetes:node_total{customer=~\"$customer\",cluster_id=~\"$cluster_id\",cluster_type=~\"tenant_cluster|workload_cluster\",installation=~\"$installation\"}) by (cluster_id)",
     "legendFormat": "{{ cluster_id }}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(avg_over_time(aggregation:node:cpu_utilization_percentage{customer=~\"$customer\",provider=~\"$provider\",region=~\"$region\",installation=~\"$installation\",cluster_id=~\"$cluster_id\",pipeline=\"stable\",cluster_type=~\"tenant_cluster|workload_cluster\"}[5m]))",
     "legendFormat": "Average for selected customer/provider/region"
    },
    {
     "expr": "avg(avg_over_time(aggregation:node:cpu_utilization_percentage{pipeline=\"stable\",cluster_type=~\"tenant_cluster|workload_cluster\"}[5m]))",
     "legendFormat": "Average of all clusters"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(100 * (1 - (aggregation:node:memory_memavailable_bytes_total{customer=~\"$customer\",provider=~\"$provider\",region=~\"$region\",installation=~\"$installation\",cluster_id=~\"$cluster_id\",cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"stable\"} / aggregation:node:memory_memtotal_bytes_total{customer=~\"$customer\",provider=~\"$provider\",region=~\"$region\",installation=~\"$installation\",cluster_id=~\"$cluster_id\",cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"stable\"})))",
     "legendFormat": "Average for selected customer/provider/region"
    },
    {
     "expr": "avg(100 * (1 - (aggregation:node:memory_memavailable_bytes_total{cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"stable\"} / aggregation:node:memory_memtotal_bytes_total{cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"stable\"})))",
     "legendFormat": "Average of all clusters"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(aggregation:node:network_receive_bytes_total{customer=~\"$customer\",provider=~\"$provider\",region=~\"$region\",installation=~\"$installation\",cluster_id=~\"$cluster_id\",cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"stable\"})",
     "legendFormat": "Receive"
    },
    {
     "expr": "sum(aggregation:node:network_transmit_bytes_total{customer=~\"$customer\",provider=~\"$provider\",region=~\"$region\",installation=~\"$installation\",cluster_id=~\"$cluster_id\",cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"stable\"})",
     "legendFormat": "Transmit"
    }
   ]
  },
  {
   "title": "Ingress",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(aggregation:ingress:requests_total{customer=~\"$customer\",provider=~\"$provider\",region=~\"$region\",installation=~\"$installation\",cluster_id=~\"$cluster_id\",cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"stable\"})",
     "legendFormat": "Requests per second"
    }
   ]
  }
 ]
}