{
 "title": "Pod Density Lab",
 "tags": [ "joe" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "customer",
    "label": "Customer",
    "query": "label_values(aggregation:kubelet:version{cluster_type=~\"tenant_cluster|workload_cluster\", pipeline=\"stable\"}, customer)"
   }
  ]
 },
 "panels": [
  {
   "title": "Pod Density",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aggregation:kubelet:running_pod_total{cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"stable\"})\n/\nsum(aggregation:kubelet:version{cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"stable\"})",
     "legendFormat": "{{ customer }}"
    }
   ]
  },
  {
   "title": "Pod Density Per Customer",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aggregation:kubelet:running_pod_total{cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"stable\"}) by (customer)\n/\nsum(aggregation:kubelet:version{cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"stable\"}) by (customer)",
     "legendFormat": "{{ customer }}"
    }
   ]
  },
  {
   "title": "Pod Density Per Installation",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aggregation:kubelet:running_pod_total{cluster_type=~\"tenant_cluster|workload_cluster\", pipeline=\"stable\", customer=~\"$customer\"}) by (installation)\n/\nsum(aggregation:kubelet:version{cluster_type=~\"tenant_cluster|workload_cluster\", pipeline=\"stable\", customer=~\"$customer\"}) by (installation)",
     "legendFormat": "{{ installation }}"
    }
   ]
  },
  {
   "title": "Pod Density Per Provider",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "sum(aggregation:kubelet:running_pod_total{cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"stable\"}) by (provider)\n/\nsum(aggregation:kubelet:version{cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"stable\"}) by (provider)",
     "legendFormat": "{{ installation }}"
    }
   ]
  }
 ]
}