{
 "title": "Alerts timeline",
 "description": "Installation-wide information on alerts, inhibitions, and silences",
 "tags": [ "owner:team-atlas" ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "installation",
    "label": "Installation",
    "query": {
     "query": "label_values(aggregation:prometheus:alerts,installation)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(aggregation:prometheus:alerts{installation=~\"$installation\"},cluster_id)"
    }
   },
   {
    "name": "severity",
    "label": "Severity",
    "query": {
     "query": "label_values(aggregation:prometheus:alerts{installation=~\"$installation\", cluster_id=~\"$cluster\"},severity)"
    }
   },
   {
    "name": "team",
    "label": "Team",
    "query": {
     "query": "label_values(aggregation:prometheus:alerts{installation=~\"$installation\", cluster_id=~\"$cluster\"},team)"
    }
   },
   {
    "name": "alertname",
    "query": {
     "query": "query_result(count(max_over_time(aggregation:prometheus:alerts{alertname!~\"^(Heartbeat|InvalidLabellingSchema)\",cluster_id=~'($cluster)|$^', team=~'($team)|$^', severity=~'($severity)|$^'}[$__range:])) by (alertname))"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "About this dashboard",
   "type": "text",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 1 },
   "options": {
    "content": "This dashboard provides metrics about alerts and silences on a installation/cluster level (workload cluster or management cluster).\n\n**Alert:** An alert is created by Prometheus based on a set of rules. For example, when some metric exceeds a configured threshold.\n\nAlerts are defined in the [prometheus-rules](https://github.com/giantswarm/prometheus-rules) repository. To learn about a particular alert, you can search that repository for the alert name.\n\n**Silence:** A silence is a specific override rule to supress one or several alerts from firing. Silences are interpreted by alertmanager. They are not cluster specific, but instead are effective for the entire installation."
   }
  },
  {
   "title": "Global alerts stats",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(aggregation:prometheus:alerts{alertname=~'($alertname)|$^',cluster_id=~'($cluster)|$^', team=~'($team)|$^', severity=~'($severity)|$^'})by(alertname))",
     "legendFormat": "Firing (filtered)"
    },
    {
     "expr": "count(sum(max_over_time(aggregation:prometheus:alerts{alertname=~'($alertname)|$^',cluster_id=~'($cluster)|$^', team=~'($team)|$^', severity=~'($severity)|$^'}[$__range:])) by (alertname))",
     "legendFormat": "Fired over period (filtered)"
    }
   ]
  },
  {
   "title": "Global silences",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:alertmanager:silences_active_total{installation=\"$installation\"})",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(aggregation:alertmanager:silences_expired_total{installation=\"$installation\"})",
     "legendFormat": "Expired"
    },
    {
     "expr": "sum(aggregation:alertmanager:silences_pending_total{installation=\"$installation\"})",
     "legendFormat": "Pending"
    }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Alerts timeline",
   "type": "state-timeline",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(aggregation:prometheus:alerts{alertname=~'($alertname)|$^',cluster_id=~'($cluster)|$^', severity=~'($severity)|$^', team=~'($team)|$^'})by(alertname, cluster_id)",
     "legendFormat": "{{alertname}} on {{cluster_id}}"
    }
   ]
  },
  {
   "title": "Firing alerts for selected period",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "count(max_over_time(aggregation:prometheus:alerts{alertname=~'($alertname)|$^',cluster_id=~'($cluster)|$^', team=~'($team)|$^', severity=~'($severity)|$^'}[$__range:])) by (alertname, cluster_id, team, severity)"
    }
   ]
  }
 ]
}