{
 "title": "Provider",
 "description": "Insights into usage on each provider",
 "tags": [ "owner:team-phoenix" ],
 "time": { "from": "now-14d", "to": "now" },
 "templating": {
  "list": [
   { "name": "provider", "label": "Provider", "query": { "query": "label_values(provider)" } }
  ]
 },
 "panels": [
  {
   "title": "Clusters",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:kubernetes:version{provider=~\"$provider\",cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"stable\"})",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Management Clusters",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count(aggregation:kubernetes:version{provider=~\"$provider\",cluster_type=~\"control_plane|management_cluster\",pipeline=\"stable\"})",
     "legendFormat": "Management Clusters"
    }
   ]
  },
  {
   "title": "Workload Clusters ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(aggregation:kubernetes:version{provider=~\"$provider\",cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"stable\"})",
     "legendFormat": "Clusters"
    }
   ]
  },
  {
   "title": "Kubelets",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:kubelet:version{provider=~\"$provider\",pipeline=\"stable\"})",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Workload Cluster Nodes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(aggregation:kubelet:version{provider=~\"$provider\",cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"stable\"})",
     "legendFormat": "Nodes"
    }
   ]
  },
  {
   "title": "Workload Clusters Per Customer",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aggregation:kubernetes:version{provider=~\"$provider\",cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"stable\"}) by (customer)",
     "legendFormat": "{{customer}}"
    }
   ]
  },
  {
   "title": "Workload Cluster Nodes Per Customer",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(aggregation:kubelet:version{provider=~\"$provider\",cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"stable\"}) by (customer)",
     "legendFormat": "{{customer}}"
    }
   ]
  },
  {
   "title": "Clusters Per Continent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aggregation:kubernetes:version{provider=~\"$provider\",cluster_type=~\"tenant_cluster|workload_cluster\",region=~\"eu-.*\",pipeline=\"stable\"})",
     "legendFormat": "Europe"
    },
    {
     "expr": "sum(aggregation:kubernetes:version{provider=~\"$provider\",cluster_type=~\"tenant_cluster|workload_cluster\",region=~\"us-.*\",pipeline=\"stable\"})",
     "legendFormat": "America"
    },
    {
     "expr": "sum(aggregation:kubernetes:version{provider=~\"$provider\",cluster_type=~\"tenant_cluster|workload_cluster\",region=~\"ap-.*\",pipeline=\"stable\"})",
     "legendFormat": "Asia / Pacific"
    },
    {
     "expr": "sum(aggregation:kubernetes:version{provider=~\"$provider\",cluster_type=~\"tenant_cluster|workload_cluster\",region=~\"cn-.*\",pipeline=\"stable\"})",
     "legendFormat": "China"
    }
   ]
  },
  {
   "title": "Workload Cluster Nodes Per Continent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(aggregation:kubelet:version{provider=~\"$provider\",cluster_type=~\"tenant_cluster|workload_cluster\",region=~\"eu-.*\",pipeline=\"stable\"})",
     "legendFormat": "Europe"
    },
    {
     "expr": "sum(aggregation:kubelet:version{provider=~\"$provider\",cluster_type=~\"tenant_cluster|workload_cluster\",region=~\"us-.*\",pipeline=\"stable\"})",
     "legendFormat": "America"
    },
    {
     "expr": "sum(aggregation:kubelet:version{provider=~\"$provider\",cluster_type=~\"tenant_cluster|workload_cluster\",region=~\"ap-.*\",pipeline=\"stable\"})",
     "legendFormat": "Asia / Pacific"
    },
    {
     "expr": "sum(aggregation:kubelet:version{provider=~\"$provider\",cluster_type=~\"tenant_cluster|workload_cluster\",region=~\"cn-.*\",pipeline=\"stable\"})",
     "legendFormat": "China"
    }
   ]
  },
  {
   "title": "Workload Clusters Per Region",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aggregation:kubernetes:version{provider=~\"$provider\",cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"stable\"}) by (region)",
     "legendFormat": " {{region}}"
    }
   ]
  },
  {
   "title": "Workload Cluster Nodes Per Region",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(aggregation:kubelet:version{provider=~\"$provider\",cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"stable\"}) by (region)",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "Workload Clusters Per Installation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aggregation:kubernetes:version{provider=~\"$provider\",cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"stable\"}) by (installation)",
     "legendFormat": "{{installation}}"
    }
   ]
  },
  {
   "title": "Workload Cluster Nodes Per Installation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(aggregation:kubelet:version{provider=~\"$provider\",cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"stable\"}) by (installation)",
     "legendFormat": "{{installation}}"
    }
   ]
  },
  {
   "title": "Workload Cluster Cluster Kubernetes Versions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aggregation:kubernetes:version{provider=~\"$provider\",cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"stable\"}) by (gitVersion)",
     "legendFormat": "{{gitVersion}}"
    }
   ]
  },
  {
   "title": "Workload Cluster Nodes Per Kubernetes Version",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aggregation:kubelet:version{provider=~\"$provider\",cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"stable\",pipeline=\"stable\"}) by (gitVersion)",
     "legendFormat": "{{gitVersion}}"
    }
   ]
  },
  {
   "title": "Percentage Workload Cluster Cluster Per Kubernetes Version",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aggregation:kubernetes:version{provider=~\"$provider\",cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"stable\"}) by (gitVersion) / scalar(sum(aggregation:kubernetes:version{provider=~\"$provider\",cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"stable\"}) * 100)",
     "legendFormat": "{{gitVersion}}"
    }
   ]
  },
  {
   "title": "Percentage Workload Cluster Nodes Per Kubernetes Version",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aggregation:kubelet:version{provider=~\"$provider\",cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"stable\"}) by (gitVersion) / scalar(sum(aggregation:kubelet:version{provider=\"$provider\",cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"stable\"}) * 100)",
     "legendFormat": "{{gitVersion}}"
    }
   ]
  },
  {
   "title": "Workload Clusters Per Release Version",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aggregation:giantswarm:cluster_release_version{provider=~\"$provider\",pipeline=\"stable\"}) by (release_version)",
     "legendFormat": "{{release_version}}"
    }
   ]
  },
  {
   "title": "Percentage Workload Clusters By Release Version",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aggregation:giantswarm:cluster_release_version{provider=~\"$provider\",pipeline=\"stable\"}) by (release_version) / scalar(sum(aggregation:giantswarm:cluster_release_version{provider=~\"$provider\",pipeline=\"stable\"}) * 100)",
     "legendFormat": "{{release_version}}"
    }
   ]
  }
 ]
}