{
 "title": "AWS EC2 instance types",
 "description": "Which installations use which instance types",
 "tags": [ "owner:team-phoenix" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "installation",
    "query": {
     "query": "label_values(aggregation:aws:instance_types{provider=\"aws\"}, installation)"
    }
   },
   { "name": "instancetype", "query": { "query": "label_values(instance_type)" } }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "EC2 Instances by type",
   "type": "graph",
   "description": "Which instance types are used and how much",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "aggregation:aws:instance_types", "legendFormat": "{{ instance_type }}" }
   ]
  },
  {
   "title": "Per Installation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "EC2 instances by type in $installation",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "repeat": "installation",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aggregation:aws:instance_types{installation=\"$installation\"}",
       "legendFormat": "{{ instance_type }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Per instance type series",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Installations using instance type series c5",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(aggregation:aws:instance_types{instance_type=~\"c5.*\"}) by (installation)",
     "legendFormat": "{{ installation }}"
    }
   ]
  },
  {
   "title": "Installations using instance type series c5n",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(aggregation:aws:instance_types{instance_type=~\"c5n.*\"}) by (installation)",
     "legendFormat": "{{ installation }}"
    }
   ]
  },
  {
   "title": "Installations using instance type series m4",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(aggregation:aws:instance_types{instance_type=~\"m4.*\"}) by (installation)",
     "legendFormat": "{{ installation }}"
    }
   ]
  },
  {
   "title": "Installations using instance type series m5",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(aggregation:aws:instance_types{instance_type=~\"m5.*\"}) by (installation)",
     "legendFormat": "{{ installation }}"
    }
   ]
  },
  {
   "title": "Installations using instance type series p2",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(aggregation:aws:instance_types{instance_type=~\"p2.*\"}) by (installation)",
     "legendFormat": "{{ installation }}"
    }
   ]
  },
  {
   "title": "Installations using instance type series p3",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(aggregation:aws:instance_types{instance_type=~\"p3.*\"}) by (installation)",
     "legendFormat": "{{ installation }}"
    }
   ]
  },
  {
   "title": "Installations using instance type series r3",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(aggregation:aws:instance_types{instance_type=~\"r3.*\"}) by (installation)",
     "legendFormat": "{{ installation }}"
    }
   ]
  },
  {
   "title": "Installations using instance type series r5",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(aggregation:aws:instance_types{instance_type=~\"r5.*\"}) by (installation)",
     "legendFormat": "{{ installation }}"
    }
   ]
  },
  {
   "title": "Installations using instance type series t2",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(aggregation:aws:instance_types{instance_type=~\"t2.*\"}) by (installation)",
     "legendFormat": "{{ installation }}"
    }
   ]
  },
  {
   "title": "Installations using instance type series t3",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(aggregation:aws:instance_types{instance_type=~\"t3.*\"}) by (installation)",
     "legendFormat": "{{ installation }}"
    }
   ]
  }
 ]
}