{
 "title": "Metrics",
 "tags": [ "owner:team-atlas" ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "customer",
    "label": "Customer",
    "query": "label_values(prometheus_tsdb_head_series, customer)"
   },
   {
    "name": "management_cluster",
    "label": "Management Cluster",
    "query": "label_values(prometheus_tsdb_head_series{customer=~\"$customer\"}, installation)"
   }
  ]
 },
 "panels": [
  {
   "title": "Number of Time Series In Prometheus (Total)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_head_series{customer=~\"$customer\", installation=~\"$management_cluster\"})",
     "legendFormat": "Time Series"
    }
   ]
  },
  {
   "title": "Number of Time Series In Prometheus (Per Installation)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_head_series{customer=~\"$customer\", installation=~\"$management_cluster\"}) by (installation)",
     "legendFormat": "{{installation}}"
    }
   ]
  },
  {
   "title": "Number of Time Series In Prometheus (Per Customer)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_head_series{customer=~\"$customer\", installation=~\"$management_cluster\"}) by (customer)",
     "legendFormat": "{{customer}}"
    }
   ]
  },
  {
   "title": "Number of Time Series In Prometheus (Per Cluster)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_head_series{customer=~\"$customer\", installation=~\"$management_cluster\", cluster_id=~\".*\"}) by (cluster_id)",
     "legendFormat": "{{cluster_id}}"
    }
   ]
  },
  {
   "title": "Memory Usage Of Prometheus (Per Cluster)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "aggregation:prometheus:memory_usage{customer=~\"$customer\", installation=~\"$management_cluster\", cluster_id=~\".*\"}",
     "legendFormat": "{{installation}} - {{cluster_id}}"
    }
   ]
  },
  {
   "title": "Percentage Of Node Memory (Per Cluster)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "aggregation:prometheus:memory_percentage{customer=~\"$customer\", installation=~\"$management_cluster\", cluster_id=~\".*\"}",
     "legendFormat": "{{installation}} - {{cluster_id}}"
    }
   ]
  },
  {
   "title": "Percentage Time Series (Per Installation)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_head_series{customer=~\"$customer\", installation=~\"$management_cluster\"}) by (installation) / scalar(sum(prometheus_tsdb_head_series{installation!=\"\"}))",
     "legendFormat": "{{installation}}"
    }
   ]
  },
  {
   "title": "Percentage Time Series (Per Customer)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_head_series{customer=~\"$customer\", installation=~\"$management_cluster\"}) by (customer) / scalar(sum(prometheus_tsdb_head_series{customer!=\"\"}))",
     "legendFormat": "{{installation}}"
    }
   ]
  },
  {
   "title": "Percentage Memory (Per Installation)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(aggregation:prometheus:memory_usage{customer=~\"$customer\", installation=~\"$management_cluster\"}) by (installation) / scalar(sum(aggregation:prometheus:memory_usage{installation!=\"\"}))",
     "legendFormat": "{{installation}}"
    }
   ]
  }
 ]
}