{
 "title": "Customer Success",
 "tags": [ "owner:team-teddyfriends" ],
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Support Threads by Customer",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(support_alfred_threads_total[$__range:10m])) by (customer)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Support Threads by Team",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(support_alfred_threads_total[$__range:10m])) by (team)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Support Duration By Customer",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(histogram_quantile(0.95, support_alfred_threads_duration_seconds_bucket)) by(customer)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Support Time To Resolve By Team",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(support_alfred_threads_duration_seconds_sum) by (team) / sum(support_alfred_threads_duration_seconds_count) by (team)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}