{
 "title": "Observability Platform Product Signals",
 "description": "Product signls for the observability platform",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "customer",
    "label": "Customer",
    "query": {
     "query": "label_values(aggregation:giantswarm:cluster_info,customer)"
    }
   },
   {
    "name": "installation",
    "label": "Installation",
    "query": {
     "query": "label_values(aggregation:giantswarm:cluster_info{customer=~\"$customer\"},installation)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Setup", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of non-GS logins",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n    count by (installation, uname) (\n       count_over_time(aggregation:giantswarm:observability:signals:user_logins{customer=~\"$customer\", installation=~\"$installation\"}[$__range])\n    )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Non-GS logins in the last 30 days",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 7, "y": 1 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count by (domain) (\n  count by (domain, uname) (\n    count_over_time(\n      (label_replace(aggregation:giantswarm:observability:signals:user_logins{customer=~\"$customer\", installation=~\"$installation\"}, \"domain\", \"$1\", \"uname\", \".*@(.+)\"))[$__range:1h]\n    )\n  )\n)"
    }
   ]
  },
  {
   "title": "Tenant List",
   "type": "table",
   "description": "List of tenants currently in place",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "group by (tenant) (\n  aggregation:giantswarm:observability:signals:ingested_metrics{customer=~\"$customer\", installation=~\"$installation\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Data exploration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Dashboard accessed in the last 30 days",
   "type": "table",
   "gridPos": { "h": 14, "w": 7, "x": 0, "y": 10 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (dashboard_name) (\n  count_over_time(aggregation:giantswarm:observability:signals:dashboard_views{customer=~\"$customer\", installation=~\"$installation\"}[30d])\n)"
    }
   ]
  },
  {
   "title": "Explore Visits - 200",
   "type": "stat",
   "description": "Number of successful (200) visits of Explore Page",
   "gridPos": { "h": 7, "w": 5, "x": 7, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  count_over_time(aggregation:giantswarm:observability:signals:explore_visits{customer=~\"$customer\", installation=~\"$installation\", status_code=\"200\"}[$__range])\n) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Executed queries in given time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(\n  count_over_time(aggregation:giantswarm:observability:grafana:executed_queries:total{customer=~\"$customer\", installation=~\"$installation\"}[$__range])\n) or vector(0)",
     "legendFormat": "{{ explorations }}"
    }
   ]
  },
  {
   "title": "Explore Visits - Not 200!",
   "type": "stat",
   "description": "Every Page Visit to Explore that was not a Status Code 200",
   "gridPos": { "h": 7, "w": 5, "x": 7, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  count_over_time(aggregation:giantswarm:observability:signals:explore_visits{customer=~\"$customer\", installation=~\"$installation\", status_code!=\"200\"}[$__range])\n) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Drilldown visits",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(\n  count_over_time(aggregation:giantswarm:observability:signals:drilldown_visits{customer=~\"$customer\", installation=~\"$installation\", status_code=\"200\"}[$__range])\n) or vector(0)",
     "legendFormat": "{{ explorations }}"
    }
   ]
  },
  { "title": "Data ingestion", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Ingested metrics per tenant",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(aggregation:giantswarm:observability:signals:ingested_metrics{customer=~\"$customer\", installation=~\"$installation\"}) by (customer, installation, tenant)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingested logs per tenant",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "targets": [
    {
     "expr": "sum(aggregation:giantswarm:observability:signals:ingested_logs{customer=~\"$customer\", installation=~\"$installation\"}) by (customer, installation, tenant)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingested traces per tenant",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "targets": [
    {
     "expr": "sum(aggregation:giantswarm:observability:signals:ingested_traces{customer=~\"$customer\", installation=~\"$installation\"}) by (customer, installation, tenant)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Metrics datasources",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum(aggregation:giantswarm:observability:signals:metrics_datasource_count{customer=~\"$customer\", installation=~\"$installation\"}) by (customer, installation, tenant)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Log datasources",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
   "targets": [
    {
     "expr": "sum(aggregation:giantswarm:observability:signals:logs_datasource_count{customer=~\"$customer\", installation=~\"$installation\"}) by (customer, installation, tenant)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Trace datasources",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
   "targets": [
    {
     "expr": "sum(aggregation:giantswarm:observability:signals:traces_datasource_count{customer=~\"$customer\", installation=~\"$installation\"}) by (customer, installation, tenant)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Rules", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Rules by cluster type",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(aggregation:giantswarm:observability:signals:rules{customer=~\"$customer\", installation=~\"$installation\"}) by (cluster_type))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rules by creation mode",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(aggregation:giantswarm:observability:signals:rules{customer=~\"$customer\", installation=~\"$installation\"}) by (creation_mode))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rules by source",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(aggregation:giantswarm:observability:signals:rules{customer=~\"$customer\", installation=~\"$installation\"}) by (source_system))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Alerting", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Fired alerts per tenant over 24h",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sort(\n  sum(\n    max_over_time(aggregation:giantswarm:observability:signals:fired_alerts{customer=~\"$customer\", installation=~\"$installation\"}[24h])\n  ) by (tenant, org)\n  > 0\n)"
    }
   ]
  },
  {
   "title": "Routes per tenant",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "sort(\n  max(\n    aggregation:giantswarm:observability:signals:alerting:routes{customer=~\"$customer\", installation=~\"$installation\"}\n  ) by (tenant)\n)"
    }
   ]
  }
 ]
}