{
 "title": "Test infrastructure",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "provider", "label": "Provider", "query": { "query": "label_values(provider)" } },
   {
    "name": "installation",
    "label": "Installation",
    "query": {
     "query": "label_values(aggregation:kubernetes:node_total{pipeline=\"testing\",provider=~\"$provider\"}, installation)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(aggregation:kubernetes:version{provider=~\"$provider\",cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"testing\",installation=~\"$installation\"})",
     "legendFormat": "Workload Clusters"
    },
    {
     "expr": "count(aggregation:kubernetes:version{provider=~\"$provider\",cluster_type=~\"control_plane|management_cluster\",pipeline=\"testing\",installation=~\"$installation\"})",
     "legendFormat": "Management Clusters"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:kubernetes:node_total{provider=~\"$provider\",cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"testing\",installation=~\"$installation\",role!=\"\"})",
     "legendFormat": "Workload Clusters"
    },
    {
     "expr": "sum(aggregation:kubernetes:node_total{provider=~\"$provider\",cluster_type=~\"control_plane|management_cluster\",pipeline=\"testing\",installation=~\"$installation\",role!=\"\"})",
     "legendFormat": "Management Clusters"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:kubernetes:node_allocatable_cpu_cores_total{provider=~\"$provider\",cluster_type=~\"tenant_cluster|workload_cluster\",installation=~\"$installation\",pipeline=\"testing\"})",
     "legendFormat": "Workload Clusters"
    },
    {
     "expr": "sum(aggregation:kubernetes:node_allocatable_cpu_cores_total{provider=~\"$provider\",cluster_type=~\"control_plane|management_cluster\",installation=~\"$installation\",pipeline=\"testing\"})",
     "legendFormat": "Management Clusters"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:kubernetes:node_allocatable_memory_bytes{provider=~\"$provider\",cluster_type=~\"tenant_cluster|workload_cluster\",installation=~\"$installation\",pipeline=\"testing\"})",
     "legendFormat": "Workload Clusters"
    },
    {
     "expr": "sum(aggregation:kubernetes:node_allocatable_memory_bytes{provider=~\"$provider\",cluster_type=~\"control_plane|management_cluster\",installation=~\"$installation\",pipeline=\"testing\"})",
     "legendFormat": "Management Clusters"
    }
   ]
  },
  {
   "title": "Workload cluster currently existing",
   "type": "table",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "count(prometheus_tsdb_head_series{cluster_type=\"workload_cluster\",pipeline=\"testing\",provider=~\"$provider\",installation=~\"$installation\"}) by (provider, installation, cluster_id)"
    }
   ]
  },
  {
   "title": "Nodes in workload clusters currently",
   "type": "table",
   "description": "Based on `aggregation:kubernetes:node_total`",
   "gridPos": { "h": 9, "w": 6, "x": 5, "y": 6 },
   "targets": [
    {
     "expr": "sum(aggregation:kubernetes:node_total{pipeline=\"testing\",cluster_type=\"workload_cluster\",provider=~\"$provider\",installation=~\"$installation\"}) by (provider, installation, cluster_id)"
    }
   ]
  },
  {
   "title": "Nodes in workload clusters by installation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 11, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(aggregation:kubernetes:node_total{provider=~\"$provider\",installation=~\"$installation\", cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"testing\",role!=\"\"}) by (installation)",
     "legendFormat": "{{installation}}"
    }
   ]
  },
  {
   "title": "Nodes in management clusters",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(aggregation:kubernetes:node_total{provider=~\"$provider\", installation=~\"$installation\", cluster_type=~\"control_plane|management_cluster\", pipeline=\"testing\", role!=\"\"}) by (installation)",
     "legendFormat": "{{installation}}"
    }
   ]
  },
  {
   "title": "Nodes in workload clusters",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(aggregation:kubernetes:node_total{provider=~\"$provider\",installation=~\"$installation\",cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"testing\",role!=\"\"}) by (installation, cluster_id)",
     "legendFormat": "{{ installation }}/{{ cluster_id }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 16, "x": 0, "y": 24 },
   "options": {
    "content": "\n# AWS test cluster stats\nIn order to keep the costs for our aws test clusters low,\nit's recommended to use spot-instances, single master setup and c5-xlarge instances where possible.\nWe should also make sure to delete the clusters after testing.\nThese stats give an overview on how good we are with this."
   }
  },
  {
   "title": "Spot Instances",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:aws:instance_lifecycle{lifecycle=\"spot\",pipeline=~\"testing\",installation=~\"$installation\"}) / sum(aggregation:aws:instance_lifecycle{pipeline=~\"testing\",installation=~\"$installation\"}) *100",
     "legendFormat": "hi"
    }
   ]
  },
  {
   "title": "single master clusters",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(aggregation:kubernetes:node_total{provider= \"aws\", cluster_type=~\"tenant_cluster|workload_cluster\", pipeline=~\"testing\", role=\"master\",installation=~\"$installation\"}) by (cluster_id) == 1)/count(sum(aggregation:kubernetes:node_total{provider= \"aws\",cluster_type=~\"tenant_cluster|workload_cluster\", pipeline=~\"testing\", role=\"master\",installation=~\"$installation\"}) by (cluster_id))*100"
    }
   ]
  },
  {
   "title": "c5.xlarge Instances",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:aws:instance_types{instance_type=~\"c5.xlarge\",pipeline=~\"testing\",installation=~\"$installation\"}) / sum(aggregation:aws:instance_types{pipeline=~\"testing\",installation=~\"$installation\"}) *100",
     "legendFormat": "hi"
    }
   ]
  },
  {
   "title": "clusters aged < 12h",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(aggregation:giantswarm:cluster_release_version{pipeline=\"testing\", provider=\"aws\",installation=~\"$installation\"} unless on (cluster_id) (aggregation:giantswarm:cluster_release_version{pipeline=\"testing\", provider=\"aws\",installation=~\"$installation\"} offset 12h)) / count(aggregation:giantswarm:cluster_release_version{pipeline=\"testing\", provider=\"aws\",installation=~\"$installation\"}) *100"
    }
   ]
  }
 ]
}