{
 "title": "Managed Apps usage",
 "tags": [ "owner:team-honeybadger" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "catalog",
    "query": "giantswarm, giantswarm-playground"
   }
  ]
 },
 "panels": [
  {
   "title": "App usage per app and customer",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(aggregation:giantswarm:app_deployed_workload_cluster_total{catalog=\"$catalog\"}) by (customer, app)"
    }
   ]
  },
  {
   "title": "App usage per customer",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:giantswarm:app_deployed_workload_cluster_total{catalog=\"$catalog\"}) by (customer)",
     "legendFormat": "{{customer}}"
    }
   ]
  },
  {
   "title": "Unique apps usage per customer",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(aggregation:giantswarm:app_deployed_workload_cluster_total{catalog=\"$catalog\"}) by (app, customer)) by (customer)",
     "legendFormat": "{{customer}}"
    }
   ]
  },
  {
   "title": "App usage per app",
   "type": "stat",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:giantswarm:app_deployed_workload_cluster_total{catalog=\"$catalog\"}) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  }
 ]
}