{
 "title": "Alerts Analysis",
 "tags": [ "owner:team-atlas" ],
 "time": { "from": "now-14d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "team",
    "label": "Team",
    "query": "label_values(aggregation:prometheus:alerts, team)"
   },
   {
    "name": "alertname",
    "label": "Alert",
    "query": "label_values(aggregation:prometheus:alerts{alertname!~\"^(Inhibition.+|Heartbeat)\"}, alertname)"
   },
   {
    "name": "customer",
    "label": "Customer",
    "query": "label_values(aggregation:prometheus:alerts, customer)"
   },
   {
    "name": "provider",
    "label": "Provider",
    "query": "label_values(aggregation:prometheus:alerts, provider)"
   },
   {
    "name": "severity",
    "label": "Severity",
    "query": {
     "query": "label_values(aggregation:prometheus:alerts,severity)"
    }
   },
   {
    "name": "pipeline",
    "label": "Pipeline",
    "query": {
     "query": "label_values(aggregation:prometheus:alerts,pipeline)"
    }
   },
   {
    "name": "installation",
    "label": "Installation",
    "query": {
     "query": "label_values(aggregation:prometheus:alerts,installation)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Documentation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Documentation",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": {
    "content": "# Count-based vs time-based:\n\nOur data is very bad at counting number of changes in status.\nSo, some graphs try to count number of times alerts fired, but they lack precision. We may miss some alerts.\n\nNewer graphs count the time alerts spent firing.\n\nNote that time can be more than 100%, when the same alert fires multiple occurences."
   }
  },
  {
   "title": "Time-based",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Alerting time per alert",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "m" } },
     "targets": [
      {
       "expr": "sum(\n    sum_over_time(\n        aggregation:prometheus:alerts{pipeline=~'($pipeline)|$^', team=~'($team)|$^', alertname=~\"$alertname\", customer=~'($customer)|$^', provider=~'($provider)|$^',installation=~\"($installation)|$^\"}[1d:1m]\n    )\n) by (alertname)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Currently Alerting Clusters",
     "type": "barchart",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(\n    aggregation:prometheus:alerts{cluster_id!~'^$|giantswarm', pipeline=~'($pipeline)|$^', severity=~'($severity)|$^', customer=~'($customer)|$^', team=~'($team)|$^', provider=~'($provider)|$^', installation=~'($installation)|$^'}\n    ) by (installation, cluster_id)",
       "legendFormat": "{{ installation }}/{{ cluster_id  }}"
      }
     ]
    },
    {
     "title": "Alerting time (Last 7 Days)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "m" } },
     "targets": [
      {
       "expr": "sum(\n    sum_over_time(\n        aggregation:prometheus:alerts{severity=~'($severity)|$^', pipeline=~'($pipeline)|$^', team=~'($team)|$^', alertname=~\"$alertname\", customer=~'($customer)|$^', provider=~'($provider)|$^',installation=~\"($installation)|$^\"}[7d:1m]\n    )\n)",
       "legendFormat": "Alerting time (Last 7 Days)"
      },
      {
       "expr": "sum(\n    avg_over_time(\n        aggregation:prometheus:alerts{alertname!~\"^(Inhibition.+|Heartbeat)\", severity=~\"$severity\", pipeline=~\"$pipeline\", team=~\"$team\", alertname=~\"$alertname\", customer=~\"$customer\", provider=~\"$provider\"}[7d:1m]\n    )\n)",
       "legendFormat": "Average time (Last 7 Days)"
      },
      {
       "expr": "sum(\n    avg_over_time(\n        aggregation:prometheus:alerts{alertname!~\"^(Inhibition.+|Heartbeat)\", severity=~\"$severity\", pipeline=~\"$pipeline\", team=~\"$team\", alertname=~\"$alertname\", customer=~\"$customer\", provider=~\"$provider\"}[7d:1m]\n    )\n)\n + (2 * sum(\n    stddev_over_time(\n        aggregation:prometheus:alerts{alertname!~\"^(Inhibition.+|Heartbeat)\", severity=~\"$severity\", pipeline=~\"$pipeline\", team=~\"$team\", alertname=~\"$alertname\", customer=~\"$customer\", provider=~\"$provider\"}[7d:1m]\n    )\n))",
       "legendFormat": "Average Plus 2 Stddev (Last 7 Days)"
      },
      {
       "expr": "sum(\n    avg_over_time(\n            aggregation:prometheus:alerts{alertname!~\"^(Inhibition.+|Heartbeat)\", severity=~\"page\", pipeline=~\"stable\", team=~\"$team\", alertname=~\"$alertname\", customer=~\"$customer\", provider=~\"$provider\"}[7d:1m]\n    )\n) - (2 * sum(\n    stddev_over_time(\n            aggregation:prometheus:alerts{alertname!~\"^(Inhibition.+|Heartbeat)\", severity=~\"page\", pipeline=~\"stable\", team=~\"$team\", alertname=~\"$alertname\", customer=~\"$customer\", provider=~\"$provider\"}[7d:1m])\n    )\n)",
       "legendFormat": "Average Minus 2 Stddev (Last 7 Days)"
      }
     ]
    },
    {
     "title": "Most Firing Alerts",
     "type": "table",
     "description": "Sum for selected range",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "m" } },
     "targets": [
      {
       "expr": "sum(\n    sum_over_time(\n        aggregation:prometheus:alerts{severity=~'($severity)|$^', pipeline=~'($pipeline)|$^', team=~'($team)|$^', alertname=~\"$alertname\", customer=~'($customer)|$^', provider=~'($provider)|$^', installation=~'($installation)|$^'}[$__range:1m]\n    )\n) by (alertname) > 0"
      }
     ]
    },
    {
     "title": "Most Firing Clusters",
     "type": "table",
     "description": "Sum for selected range",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "m" } },
     "targets": [
      {
       "expr": "sum(\n    sum_over_time(\n        aggregation:prometheus:alerts{severity=~'($severity)|$^', pipeline=~'($pipeline)|$^', team=~'($team)|$^', alertname=~'($alertname)|$^', customer=~'($customer)|$^', provider=~'($provider)|$^', installation=~'($installation)|$^'}[$__range:1m]\n    )\n) by (installation, cluster_id) > 0"
      }
     ]
    },
    {
     "title": "Most Firing Alerts & Clusters",
     "type": "table",
     "description": "Sum for selected range",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "m" } },
     "targets": [
      {
       "expr": "sum(\n    sum_over_time(\n        aggregation:prometheus:alerts{severity=~'($severity)|$^', pipeline=~'($pipeline)|$^', team=~'($team)|$^', alertname=~\"$alertname\", customer=~'($customer)|$^', provider=~'($provider)|$^', installation=~'($installation)|$^'}[$__range:1m]\n    )\n) by (alertname, installation, cluster_id) > 0"
      }
     ]
    },
    {
     "title": "Most Firing teams",
     "type": "table",
     "description": "Sum for selected range",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "m" } },
     "targets": [
      {
       "expr": "sum(\n    sum_over_time(\n        aggregation:prometheus:alerts{severity=~'($severity)|$^', pipeline=~'($pipeline)|$^', team=~'($team)|$^', alertname=~'($alertname)|$^', customer=~'($customer)|$^', provider=~'($provider)|$^', installation=~'($installation)|$^'}[$__range:1m]\n    )\n) by (team) > 0"
      }
     ]
    },
    {
     "title": "Most Firing Alerts per Topic",
     "type": "table",
     "description": "Sum for selected range",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "m" } },
     "targets": [
      {
       "expr": "sum(\n    sum_over_time(\n        aggregation:prometheus:alerts{severity=~'($severity)|$^', pipeline=~'($pipeline)|$^', team=~'($team)|$^', alertname=~'($alertname)|$^', customer=~'($customer)|$^', provider=~'($provider)|$^', installation=~'($installation)|$^'}[$__range:1m]\n    )\n) by (topic) > 0"
      }
     ]
    },
    {
     "title": "Most Firing Area",
     "type": "table",
     "description": "Sum for selected range",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "m" } },
     "targets": [
      {
       "expr": "sum(\n    sum_over_time(\n        aggregation:prometheus:alerts{severity=~'($severity)|$^', pipeline=~'($pipeline)|$^', team=~'($team)|$^', alertname=~'($alertname)|$^', customer=~'($customer)|$^', provider=~'($provider)|$^', installation=~'($installation)|$^'}[$__range:1m]\n    )\n) by (area) > 0"
      }
     ]
    }
   ]
  },
  { "title": "Count-based", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Currently Alerting Clusters",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(\n    aggregation:prometheus:alerts{cluster_id!~'^$|giantswarm', pipeline=~'($pipeline)|$^', severity=~'($severity)|$^', customer=~'($customer)|$^', team=~'($team)|$^', provider=~'($provider)|$^', alertname!~\"^Inhibition.*\", installation=~'($installation)|$^'}\n    ) by (installation, cluster_id)",
     "legendFormat": "{{ installation }}/{{ cluster_id  }}"
    }
   ]
  },
  {
   "title": "Number Of Alerts (Last 7 Days)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n    changes(\n        aggregation:prometheus:alerts{severity=~'($severity)|$^', pipeline=~'($pipeline)|$^', team=~'($team)|$^', alertname=~'($alertname)|$^', customer=~'($customer)|$^', provider=~'($provider)|$^', alertname!~\"^Inhibition.*\", installation=~'($installation)|$^'}[7d]\n    )\n)",
     "legendFormat": "Number Of Alerts (Last 7 Days)"
    },
    {
     "expr": "sum(\n    avg_over_time(\n        changes(\n            aggregation:prometheus:alerts{alertname!~\"^(Inhibition.+|Heartbeat)\", severity=~\"$severity\", pipeline=~\"$pipeline\", team=~\"$team\", alertname=~\"$alertname\", customer=~\"$customer\", provider=~\"$provider\"}[7d]\n        )[7d:]\n    )\n)",
     "legendFormat": "Average Of Alerts (Last 7 Days)"
    },
    {
     "expr": "sum(\n    avg_over_time(\n        changes(\n            aggregation:prometheus:alerts{alertname!~\"^(Inhibition.+|Heartbeat)\", severity=~\"$severity\", pipeline=~\"$pipeline\", team=~\"$team\", alertname=~\"$alertname\", customer=~\"$customer\", provider=~\"$provider\"}[7d]\n        )[7d:]\n    )\n)\n + (2 * sum(\n    stddev_over_time(\n        changes(\n            aggregation:prometheus:alerts{alertname!~\"^(Inhibition.+|Heartbeat)\", severity=~\"$severity\", pipeline=~\"$pipeline\", team=~\"$team\", alertname=~\"$alertname\", customer=~\"$customer\", provider=~\"$provider\"}[7d]\n        )[7d:]\n    )\n))",
     "legendFormat": "Average Plus 2 Stddev (Last 7 Days)"
    },
    {
     "expr": "sum(\n    avg_over_time(\n        changes(\n            aggregation:prometheus:alerts{alertname!~\"^(Inhibition.+|Heartbeat)\", severity=~\"page\", pipeline=~\"stable\", team=~\"$team\", alertname=~\"$alertname\", customer=~\"$customer\", provider=~\"$provider\"}[7d]\n        )[7d:]\n    )\n) - (2 * sum(\n    stddev_over_time(\n        changes(\n            aggregation:prometheus:alerts{alertname!~\"^(Inhibition.+|Heartbeat)\", severity=~\"page\", pipeline=~\"stable\", team=~\"$team\", alertname=~\"$alertname\", customer=~\"$customer\", provider=~\"$provider\"}[7d])\n        [7d:])\n    )\n)",
     "legendFormat": "Average Minus 2 Stddev (Last 7 Days)"
    }
   ]
  },
  {
   "title": "Most Fired Alerts",
   "type": "table",
   "description": "Sum for selected range",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(\n    changes(\n        aggregation:prometheus:alerts{severity=~'($severity)|$^', pipeline=~'($pipeline)|$^', team=~'($team)|$^', alertname=~\"$alertname\", customer=~'($customer)|$^', provider=~'($provider)|$^', alertname!~\"^Inhibition.*\", installation=~'($installation)|$^'}[$__range]\n    )\n) by (alertname) > 0"
    }
   ]
  },
  {
   "title": "Most Fired Clusters",
   "type": "table",
   "description": "Sum for selected range",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "sum(\n    changes(\n        aggregation:prometheus:alerts{severity=~'($severity)|$^', pipeline=~'($pipeline)|$^', team=~'($team)|$^', alertname=~'($alertname)|$^', customer=~'($customer)|$^', provider=~'($provider)|$^', alertname!~\"^Inhibition.*\", installation=~'($installation)|$^'}[$__range]\n    )\n) by (installation, cluster_id) > 0"
    }
   ]
  },
  {
   "title": "Most Fired Alerts & Clusters",
   "type": "table",
   "description": "Sum for selected range",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum(\n    changes(\n        aggregation:prometheus:alerts{severity=~'($severity)|$^', pipeline=~'($pipeline)|$^', team=~'($team)|$^', alertname=~\"$alertname\", customer=~'($customer)|$^', provider=~'($provider)|$^', alertname!~\"^Inhibition.*\", installation=~'($installation)|$^'}[$__range]\n    )\n) by (alertname, installation, cluster_id) > 0"
    }
   ]
  },
  {
   "title": "Most Fired Teams",
   "type": "table",
   "description": "Sum for selected range",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "sum(\n    changes(\n        aggregation:prometheus:alerts{severity=~'($severity)|$^', pipeline=~'($pipeline)|$^', team=~'($team)|$^', alertname=~'($alertname)|$^', customer=~'($customer)|$^', provider=~'($provider)|$^', alertname!~\"^Inhibition.*\", installation=~'($installation)|$^'}[$__range]\n    )\n) by (team) > 0"
    }
   ]
  },
  {
   "title": "Most Fired Alerts per Topic",
   "type": "table",
   "description": "Sum for selected range",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum(\n    changes(\n        aggregation:prometheus:alerts{severity=~'($severity)|$^', pipeline=~'($pipeline)|$^', team=~'($team)|$^', alertname=~'($alertname)|$^', customer=~'($customer)|$^', provider=~'($provider)|$^', alertname!~\"^Inhibition.*\", installation=~'($installation)|$^'}[$__range]\n    )\n) by (topic) > 0"
    }
   ]
  },
  {
   "title": "Most Fired Area",
   "type": "table",
   "description": "Sum for selected range",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "sum(\n    changes(\n        aggregation:prometheus:alerts{severity=~'($severity)|$^', pipeline=~'($pipeline)|$^', team=~'($team)|$^', alertname=~'($alertname)|$^', customer=~'($customer)|$^', provider=~'($provider)|$^', alertname!~\"^Inhibition.*\", installation=~'($installation)|$^'}[$__range]\n    )\n) by (area) > 0"
    }
   ]
  }
 ]
}