{
 "title": "Customers",
 "tags": [ "owner:team-teddyfriends" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "customer", "label": "Customer", "query": "label_values(customer)" },
   { "name": "provider", "label": "Provider", "query": "label_values(provider)" },
   { "name": "installation", "label": "Installation", "query": "label_values(installation)" },
   { "name": "release_version", "label": "Release Version", "query": "label_values(release_version)" }
  ]
 },
 "panels": [
  {
   "title": "Release and Ages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Clusters Age Overview",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "min(time()-aggregation:kubernetes:master_node_created{customer=~\"$customer\",provider=~\"$provider\",installation=~\"$installation\"}) by (installation,customer,cluster_id)",
     "legendFormat": "{{customer}}/{{ installation }}/{{ cluster_id  }}"
    }
   ]
  },
  {
   "title": "Clusters older than 3 months",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(time() - aggregation:kubernetes:master_node_created{customer=~\"$customer\",installation=~\"$installation\",provider=~\"$provider\"} > 7987803)"
    }
   ]
  },
  {
   "title": "Cluster version",
   "type": "table",
   "gridPos": { "h": 26, "w": 9, "x": 7, "y": 1 },
   "targets": [
    {
     "expr": "count(aggregation:giantswarm:cluster_release_version{customer=~\"$customer\",provider=~\"$provider\",installation=~\"$installation\",release_version=~\"$release_version\",pipeline=\"stable\"}) by (customer, cluster_id, installation, provider, release_version)"
    },
    {
     "expr": "count(aggregation:giantswarm:cluster_release_version)"
    }
   ]
  },
  {
   "title": "Cluster version currently used",
   "type": "bargauge",
   "gridPos": { "h": 26, "w": 5, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sort(count(aggregation:giantswarm:cluster_release_version{customer=~\"$customer\",provider=~\"$provider\",installation=~\"$installation\",release_version=~\"$release_version\",pipeline=\"stable\"}) by (release_version,provider))",
     "legendFormat": "{{provider}}/{{release_version}}"
    }
   ]
  },
  {
   "title": "# of used releases",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(count(aggregation:giantswarm:cluster_release_version{customer=~\"$customer\",installation=~\"$installation\",pipeline=\"stable\"}) by (provider,release_version)) by (provider)",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Last Update",
   "type": "table",
   "gridPos": { "h": 19, "w": 7, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "min(aggregation:kubernetes:master_node_created{customer=~\"$customer\",provider=~\"$provider\",installation=~\"$installation\"} * 1000) by (cluster_id,customer,installation) < ((time()-7987803)*1000)"
    }
   ]
  },
  {
   "title": "# of clusters with k8s release",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 3, "x": 21, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(label_replace(aggregation:kubelet:version{customer=~\"$customer\",installation=~\"$installation\",pipeline=\"stable\",provider=\"$provider\"}, \"git_version\", \"$1\", \"git_version\", \"(v[0-9]+.[0-9]+).*\")) by (git_version)",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Certificates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Certificate Expiry < 1 month",
   "type": "table",
   "description": "Show the clusters with certificate expiry in less than  month.",
   "gridPos": { "h": 25, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "min((aggregation:giantswarm:cluster_certificate_not_after_seconds{customer=~\"$customer\",provider=~\"$provider\",installation=~\"$installation\",pipeline=\"stable\"} - time()) < 28 * 24 * 60 * 60) by (cluster_id,customer,installation)"
    }
   ]
  },
  {
   "title": "# of Certificate Expiry < 1 month",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(min((aggregation:giantswarm:cluster_certificate_not_after_seconds{customer=~\"$customer\",provider=~\"$provider\",installation=~\"$installation\",pipeline=\"stable\"} - time()) < 28 * 24 * 60 * 60) by (cluster_id,customer,installation))"
    }
   ]
  },
  {
   "title": "Certificates",
   "type": "table",
   "gridPos": { "h": 20, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "min(aggregation:giantswarm:cluster_certificate_not_after_seconds{customer=~\"$customer\",provider=~\"$provider\",installation=~\"$installation\",pipeline=\"stable\"}) by (customer,cluster_id,installation,provider) * 1000"
    }
   ]
  }
 ]
}