{
 "title": "AWS Service Quotas",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "installation",
    "label": "Installation",
    "query": {
     "query": "label_values(aggregation:giantswarm:cluster_certificate_not_after_seconds{customer=~\"$customer\",provider=~\"$provider\"},installation)"
    }
   },
   { "name": "provider", "label": "Provider", "query": { "query": "label_values(provider)" } },
   { "name": "customer", "label": "Customer", "query": { "query": "label_values(customer)" } }
  ]
 },
 "panels": [
  {
   "title": "Current applied AWS service quotas",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(aggregation:giantswarm:aws_servicequotas_operator_quota_applied_values{customer=~\"$customer\",installation=~\"$installation\",provider=~\"$provider\"}) by (account_id,service_name,quota_description,quota_code) / count(aggregation:giantswarm:aws_servicequotas_operator_quota_applied_values{customer=~\"$customer\",installation=~\"$installation\",provider=~\"$provider\"}) by (account_id,service_name,quota_description,quota_code)",
     "legendFormat": "AWS Account {{account_id}}:  {{quota_description}}"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Applied Request Errors",
   "type": "timeseries",
   "description": "Returns errors for getting applied service quotas",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(aggregation:giantswarm:aws_servicequotas_operator_quota_applied_request_errors{customer=~\"$customer\",installation=~\"$installation\",provider=~\"$provider\"}) by (cluster_id)",
     "legendFormat": "{{cluster_id}}"
    }
   ]
  },
  {
   "title": "History Request Errors",
   "type": "timeseries",
   "description": "Returns errors for getting history of service quotas",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum(aggregation:giantswarm:aws_servicequotas_operator_quota_history_request_errors{customer=~\"$customer\",installation=~\"$installation\",provider=~\"$provider\"}) by (cluster_id)",
     "legendFormat": "{{cluster_id}}"
    }
   ]
  },
  {
   "title": "Increase Request Errors",
   "type": "timeseries",
   "description": "Returns errors for increasing service quotas",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum(aggregation:giantswarm:aws_servicequotas_operator_quota_increase_request_errors{customer=~\"$customer\",installation=~\"$installation\",provider=~\"$provider\"}) by (cluster_id)",
     "legendFormat": "{{cluster_id}}"
    }
   ]
  }
 ]
}