{
 "title": "Resource capacity (request vs allocatable)",
 "description": "This dashboards shows the current resources requested (as in request/limits) vs total amount of resource allocatable by kubernetes.",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "customer",
    "label": "Customer",
    "query": {
     "query": "label_values(aggregation:kubernetes:node_allocatable_memory_bytes,customer)"
    }
   },
   {
    "name": "installation",
    "label": "Installation",
    "query": {
     "query": "label_values(aggregation:kubernetes:node_allocatable_memory_bytes{customer=\"$customer\"},installation)"
    }
   },
   {
    "name": "cluster_id",
    "label": "Cluster",
    "query": {
     "query": "label_values(aggregation:node:cpu_utilization_percentage{installation=~\"$installation\", customer=\"$customer\"},cluster_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Requested CPU",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:kubernetes:pod_resource_requests_cpu_cores{customer=~\"$customer\",installation=~\"$installation\",cluster_id=~\"$cluster_id\"})/sum(aggregation:kubernetes:node_allocatable_cpu_cores_total{customer=~\"$customer\",installation=~\"$installation\",cluster_id=~\"$cluster_id\"})*100"
    }
   ]
  },
  {
   "title": "Requestes CPU details",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(aggregation:kubernetes:pod_resource_requests_cpu_cores{customer=~\"$customer\",installation=~\"$installation\",cluster_id=~\"$cluster_id\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(aggregation:kubernetes:node_allocatable_cpu_cores_total{customer=~\"$customer\",installation=~\"$installation\",cluster_id=~\"$cluster_id\"})-sum(aggregation:kubernetes:pod_resource_requests_cpu_cores{customer=~\"$customer\",installation=~\"$installation\",cluster_id=~\"$cluster_id\"})",
     "legendFormat": "left"
    },
    {
     "expr": "sum(aggregation:kubernetes:node_allocatable_cpu_cores_total{customer=~\"$customer\",installation=~\"$installation\",cluster_id=~\"$cluster_id\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Requested memory",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:kubernetes:pod_resource_requests_memory_bytes{customer=~\"$customer\",installation=~\"$installation\",cluster_id=~\"$cluster_id\"})/sum(aggregation:kubernetes:node_allocatable_memory_bytes{customer=~\"$customer\",installation=~\"$installation\",cluster_id=~\"$cluster_id\"})*100",
     "legendFormat": "{{ cluster_id }}"
    }
   ]
  },
  {
   "title": "Requested memory details",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(aggregation:kubernetes:pod_resource_requests_memory_bytes{customer=~\"$customer\",installation=~\"$installation\",cluster_id=~\"$cluster_id\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(aggregation:kubernetes:node_allocatable_memory_bytes{customer=~\"$customer\",installation=~\"$installation\",cluster_id=~\"$cluster_id\"})-sum(aggregation:kubernetes:pod_resource_requests_memory_bytes{customer=~\"$customer\",installation=~\"$installation\",cluster_id=~\"$cluster_id\"})",
     "legendFormat": "left"
    },
    {
     "expr": "sum(aggregation:kubernetes:node_allocatable_memory_bytes{installation=~\"$installation\",cluster_id=~\"$cluster_id\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Requested CPU overview",
   "type": "table",
   "gridPos": { "h": 11, "w": 15, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "label_join(sum(aggregation:kubernetes:pod_resource_requests_cpu_cores{customer=~\"$customer\", installation=~\"$installation\", cluster_id=~\"$cluster_id\"}) by (cluster_id, installation) / sum(aggregation:kubernetes:node_allocatable_cpu_cores_total{customer=~\"$customer\", installation=~\"$installation\", cluster_id=~\"$cluster_id\"}) by (cluster_id, installation) * 100, \"combined\", \"_\", \"installation\", \"cluster_id\")",
     "legendFormat": "{{ installation }} / {{ cluster_id }}"
    },
    {
     "expr": "label_join(sum(aggregation:kubernetes:pod_resource_requests_memory_bytes{customer=~\"$customer\", installation=~\"$installation\"})by(cluster_id,installation)/sum(aggregation:kubernetes:node_allocatable_memory_bytes{customer=~\"$customer\", installation=~\"$installation\"})by(cluster_id,installation)*100, \"combined\", \"_\", \"installation\", \"cluster_id\")",
     "legendFormat": "{{ installation }} / {{ cluster_id }}"
    }
   ]
  },
  {
   "title": "Top10 cpu request by pod",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(10,sum(aggregation:kubernetes:pod_resource_requests_cpu_cores{customer=~\"$customer\",installation=~\"$installation\",cluster_id=~\"$cluster_id\"}) by (container))",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Top10 memory request by container",
   "type": "bargauge",
   "description": "This works only for the management cluster",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(10,sum(aggregation:kubernetes:pod_resource_requests_memory_bytes{customer=~\"$customer\",installation=~\"$installation\",cluster_id=~\"$cluster_id\"}) by (container))",
     "legendFormat": "{{ container }}"
    }
   ]
  }
 ]
}