{
 "title": "Machines",
 "tags": [ "owner:team-turtles" ],
 "time": { "from": "now-90d", "to": "now" },
 "panels": [
  {
   "title": "Machines",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:node:kernel_version)",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Machines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aggregation:node:kernel_version)"
    }
   ]
  },
  {
   "title": "Machines Per Customer",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(aggregation:node:kernel_version{customer!=\"\"}) by (customer)",
     "legendFormat": "{{customer}}"
    }
   ]
  },
  {
   "title": "Machines Per Installation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(aggregation:node:kernel_version) by (installation)",
     "legendFormat": "{{installation}}"
    }
   ]
  },
  {
   "title": "Machines Per Provider",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(aggregation:node:kernel_version{provider!=\"\"}) by (provider)",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Machines Per Kernel Version",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aggregation:node:kernel_version) by (release)",
     "legendFormat": "{{release}}"
    }
   ]
  },
  {
   "title": "Percentage Machines Per Kernel Version",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(aggregation:node:kernel_version) by (release) / scalar(sum(aggregation:node:kernel_version) * 100)",
     "legendFormat": "{{release}}"
    }
   ]
  },
  {
   "title": "Percentage Production Machines Running Flatcar",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(aggregation:node:kernel_version{pipeline=\"stable\", release=~\".*flatcar.*\"}) / sum(aggregation:node:kernel_version{pipeline=\"stable\"}) * 100",
     "legendFormat": "Stable"
    }
   ]
  },
  {
   "title": "Number Of Machines Still Running CoreOS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(aggregation:node:kernel_version{pipeline=\"stable\"}) - sum(aggregation:node:kernel_version{pipeline=\"stable\", release=~\".*flatcar.*\"}) ",
     "legendFormat": "Stable"
    }
   ]
  }
 ]
}