{
 "title": "AWS Cluster Status",
 "tags": [
  "provider:aws",
  "topic:workload-cluster",
  "owner:team-phoenix"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "organization",
    "label": "Organization",
    "query": {
     "query": "label_values(kubernetes_build_info, organization)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kubernetes_build_info{organization=\"$organization\"}, cluster_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pod Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{organization=\"$organization\", cluster_id=\"$cluster\"}) by (phase)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Node Ready",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_nodes_count{state=\"ready\",organization=\"$organization\", cluster_id=\"$cluster\"})/sum(cluster_autoscaler_nodes_count{organization=\"$organization\", cluster_id=\"$cluster\"})*100"
    }
   ]
  },
  {
   "title": "Autoscaling activity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_scaled_up_nodes_total{organization=\"$organization\", cluster_id=\"$cluster\"})",
     "legendFormat": "scaled up total"
    },
    {
     "expr": "sum(cluster_autoscaler_unneeded_nodes_count{organization=\"$organization\", cluster_id=\"$cluster\"})",
     "legendFormat": "unneeded nodes"
    },
    {
     "expr": "sum(cluster_autoscaler_nodes_count{organization=\"$organization\", cluster_id=\"$cluster\"})\n",
     "legendFormat": "total nodes"
    }
   ]
  },
  {
   "title": "Deployments",
   "type": "stat",
   "gridPos": { "h": 16, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{organization=\"$organization\", cluster_id=\"$cluster\",namespace=\"kube-system\", deployment!=\"calico-typha\"} / kube_deployment_spec_replicas{organization=\"$organization\", cluster_id=\"$cluster\",namespace=\"kube-system\", deployment!=\"calico-typha\"} ",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Daemonsets",
   "type": "stat",
   "gridPos": { "h": 16, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kube_daemonset_status_number_available{organization=\"$organization\", cluster_id=\"$cluster\",namespace=\"kube-system\"}  / kube_daemonset_status_desired_number_scheduled{organization=\"$organization\", cluster_id=\"$cluster\",namespace=\"kube-system\"}",
     "legendFormat": "{{daemonset}}"
    }
   ]
  },
  {
   "title": "Cluster CPU Usage",
   "type": "gauge",
   "description": "CPU used by containers in comparison to the amount of CPU cores available in machines",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (irate (container_cpu_usage_seconds_total{cluster_id='$cluster_id'}[3m])) / sum (kube_node_status_capacity{cluster_id='$cluster_id', resource=\"cpu\" }) * 100"
    }
   ]
  },
  {
   "title": "Ingress NGINX Controller Requests Per Second",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "round(sum(irate(nginx_ingress_controller_requests{cluster_id=~\"$cluster_id\"}[2m])), 0.001)"
    }
   ]
  },
  {
   "title": "Ingress NGINX Controller Request Success Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{cluster_id=~\"$cluster_id\",status!~\"[4-5].*\"}[2m])) / sum(rate(nginx_ingress_controller_requests{cluster_id=~\"$cluster_id\"}[2m]))"
    }
   ]
  },
  {
   "title": "Cluster Memory Usage",
   "type": "gauge",
   "description": "Memory used by containers, in comparision to the memory available on machines",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "sum(container_memory_working_set_bytes{organization=\"$organization\", cluster_id=\"$cluster\"}) / sum(kube_node_status_capacity{organization=\"$organization\", cluster_id=\"$cluster\", resource=\"memory\"}) * 100",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "DNS Request Latency Mean",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 10, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(coredns_dns_request_duration_seconds_sum{organization=\"$organization\", cluster_id=\"$cluster\"}[15m])) / sum(irate(coredns_dns_request_duration_seconds_count{organization=\"$organization\", cluster_id=\"$cluster\"}[15m])) * 1000",
     "legendFormat": "Mean"
    }
   ]
  },
  { "title": "Upgrade Batch Settings", "type": "text", "gridPos": { "h": 2, "w": 2, "x": 8, "y": 15 } }
 ]
}