{
 "title": "Kyverno Health",
 "tags": [ "owner:team-shield" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(etcd_kubernetes_resources_count,cluster_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$cluster - Kyverno objects by Kind",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aggregation:kyverno_resource_counts{cluster_id=\"$cluster\"}",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Configured replicas",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kube_deployment_spec_replicas{cluster_id=\"$cluster\", deployment=~\"kyverno|kyverno-admission-controller\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validating Webhooks",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_validatingwebhookconfiguration_info{cluster_id=\"$cluster\", validatingwebhookconfiguration=~\"kyverno-.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mutating Webhooks",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_mutatingwebhookconfiguration_info{cluster_id=\"$cluster\", mutatingwebhookconfiguration=~\"kyverno-.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current amount of replicas by Deployment",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{cluster_id=\"$cluster\", deployment=~\"kyverno.*\"}) by (deployment)",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  { "title": "Admission Review Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Avg - Admission Review Duration Over Time (by operation)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(kyverno_admission_review_duration_seconds_sum{cluster_id=\"$cluster\"}[5m])) by (resource_request_operation) / sum(rate(kyverno_admission_review_duration_seconds_count{cluster_id=\"$cluster\"}[5m])) by (resource_request_operation)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg - Admission Review Duration Over Time (by resource kind)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(kyverno_admission_review_duration_seconds_sum{cluster_id=\"$cluster\"}[5m])) by (resource_kind) / sum(rate(kyverno_admission_review_duration_seconds_count{cluster_id=\"$cluster\"}[5m])) by (resource_kind)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Policies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Average Policy Execution Latency Over Time by Policy",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(kyverno_policy_execution_duration_seconds_sum{cluster_id=\"$cluster\"}[5m])) by (policy_name) / sum(rate(kyverno_policy_execution_duration_seconds_count{cluster_id=\"$cluster\"}[5m])) by (policy_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Policy Failures",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(sum(increase(kyverno_policy_results_total{rule_result=\"fail\", cluster_id=\"$cluster\"}[5m])) by (policy_name, policy_type)) by (policy_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Policies",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 21, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(kyverno_policy_rule_info_total{cluster_id=\"$cluster\"}==1) by (policy_name, policy_type)) by (policy_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Admission Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Admission Requests (by operation)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(kyverno_admission_requests_total{cluster_id=\"$cluster\"}[5m])) by (resource_request_operation)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Admission Requests (by resource kind)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 10, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(kyverno_admission_requests_total{cluster_id=\"$cluster\"}[5m])) by (resource_kind)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Admission Requests (Last 24 Hours)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(kyverno_admission_requests_total{cluster_id=\"$cluster\"}[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Webhooks Rejection Count by name and error type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "avg(apiserver_admission_webhook_rejection_count{cluster_id=\"$cluster\", name=~\".*.kyverno.*\"}) by (error_type, name)",
     "legendFormat": "{{name}} - {{error_type}}"
    }
   ]
  },
  {
   "title": "Webhooks Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(apiserver_admission_webhook_admission_duration_seconds_sum{cluster_id=\"$cluster\",name=~\".*kyverno.*\"}[5m])) by (name) ",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}