{
 "title": "Alerts",
 "description": "Installation-wide information on alerts, inhibitions, and silences",
 "tags": [
  "owner:team-atlas",
  "topic:observability",
  "component:alertmanager"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(ALERTS{},cluster_id)"
    }
   },
   {
    "name": "severity",
    "label": "Severity",
    "query": {
     "query": "label_values(ALERTS{},severity)"
    }
   },
   { "name": "team", "label": "Team", "query": { "query": "label_values(ALERTS{},team)" } },
   {
    "name": "alertname",
    "query": {
     "query": "query_result(count(max_over_time(ALERTS{alertname!~\"^(Heartbeat|InvalidLabellingSchema)\",cluster_id=~'($cluster)|$^', team=~'($team)|$^', severity=~'($severity)|$^'}[$__range:])) by (alertname))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "About this dashboard",
   "type": "text",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
   "options": {
    "content": "This dashboard provides metrics about alerts, inhibitions, and silences on a cluster level (workload cluster or management cluster).\n\n**Alert:** An alert is created by Prometheus Alertmanager based on a set of rules. For example, when some metric exceeds a configured threshold.\n\nAlerts are defined in the [prometheus-rules](https://github.com/giantswarm/prometheus-rules) repository. To learn about a particular alert, you can search that repository for the alert name.\n\n**Inhibition:** An inhibition is a rule to prevent an alert from being created. At Giant Swarm we use this for example to avoid certain alerts from being created when a cluster is freshly created, as this would otherwise trigger pages to staff on call.\n\n**Silence:** A silence is another specific override rule to opress one or several alerts from firing. Silences are not cluster specific, but instead are effective for the entire installation."
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Global alerts stats",
   "type": "stat",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(prometheus_rule_group_rules{cluster_id=~\"$cluster\",rule_group!~\".*;(cortex|helm-operations|labelling-schema|inhibit|service-level.*|.+\\\\.rules)$\"})",
     "legendFormat": "Total (global)"
    },
    {
     "expr": "sum(prometheus_rule_group_rules{cluster_id=~'($cluster)|$^',rule_group!~\".*;(cortex|helm-operations|labelling-schema|inhibit|service-level.*|.+\\\\.rules)$\"})-count(count(ALERTS{alertname!~\"^(Inhibition.*|Heartbeat|InvalidLabellingSchema)\",cluster_id=~'($cluster)|$^'})by(alertname))",
     "legendFormat": "Inactive (global)"
    },
    {
     "expr": "count(count(ALERTS{alertname=~'($alertname)|$^',cluster_id=~'($cluster)|$^', team=~'($team)|$^', severity=~'($severity)|$^'})by(alertname))",
     "legendFormat": "Currently active (filtered)"
    },
    {
     "expr": "count(sum(max_over_time(ALERTS{alertname=~'($alertname)|$^',cluster_id=~'($cluster)|$^', team=~'($team)|$^', severity=~'($severity)|$^'}[$__range:])) by (alertname))",
     "legendFormat": "Active over period (filtered)"
    }
   ]
  },
  {
   "title": "Global silences",
   "type": "stat",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:alertmanager:silences_active_total)",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(aggregation:alertmanager:silences_expired_total)",
     "legendFormat": "Expired"
    },
    {
     "expr": "sum(aggregation:alertmanager:silences_pending_total)",
     "legendFormat": "Pending"
    }
   ]
  },
  {
   "title": "Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Alerts timeline",
   "type": "state-timeline",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(ALERTS{alertname=~'($alertname)|$^',cluster_id=~'($cluster)|$^', severity=~'($severity)|$^', team=~'($team)|$^'})by(alertname, cluster_id)",
     "legendFormat": "{{alertname}} on {{cluster_id}}"
    }
   ]
  },
  {
   "title": "Firing alerts for selected period",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "count(max_over_time(ALERTS{alertname=~'($alertname)|$^',cluster_id=~'($cluster)|$^', team=~'($team)|$^', severity=~'($severity)|$^'}[$__range:])) by (alertname, cluster_id, team, severity)"
    }
   ]
  }
 ]
}