{
 "title": "API audit",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "organization",
    "label": "Organization",
    "query": {
     "query": "label_values(up{app=\"node-exporter\"}, organization)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(up{app=\"node-exporter\", organization=\"$organization\"}, cluster_id)"
    }
   },
   {
    "name": "verb",
    "label": "Verb",
    "query": {
     "query": "label_values(apiserver_request_duration_seconds_count, verb)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 9, "x": 0, "y": 0 },
   "options": {
    "content": "To view metrics in the panels you need to install [k8s-audit-exporter](https://github.com/giantswarm/k8s-audit-metrics) in your cluster"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total requests by User",
   "type": "timeseries",
   "description": "Rate of requests by user",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (user) (rate(k8s_api_audit_requests_total{cluster_id=\"$cluster\",organization=~\"$organization\"}[5m])*60)",
     "legendFormat": "{{ user }}"
    }
   ]
  },
  {
   "title": "Total requests by agent",
   "type": "timeseries",
   "description": "Rate of requests by user agent",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (user_agent) (rate(k8s_api_audit_requests_total{cluster_id=\"$cluster\",organization=~\"$organization\"}[5m])*60)",
     "legendFormat": "{{ user_agent }}"
    }
   ]
  },
  {
   "title": "Number of requests by resource",
   "type": "timeseries",
   "description": "Number of requests by resource",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (resource) (rate(apiserver_request_duration_seconds_count{cluster_id=\"$cluster\",organization=~\"$organization\", verb=~\"$verb\"}[5m]))",
     "legendFormat": "{{ resource }}"
    }
   ]
  },
  {
   "title": "Latency of requests (seconds)",
   "type": "timeseries",
   "description": "Latency of requests in seconds by client",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (user) (rate(k8s_api_audit_request_duration_nanoseconds{cluster_id=\"$cluster\",organization=~\"$organization\"}[5m])/(10000000000))",
     "legendFormat": "{{ user }}"
    }
   ]
  },
  {
   "title": "Total events by app",
   "type": "timeseries",
   "description": "Rate of events by app",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (app) (rate(apiserver_audit_event_total{cluster_id=\"$cluster\",organization=~\"$organization\"}[5m]))",
     "legendFormat": "{{ user_agent }}"
    }
   ]
  }
 ]
}