{
 "title": "Backstage",
 "description": "Metrics and logs from Backstage",
 "tags": [ "owner:team-honeybadger" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster_id",
    "label": "Cluster",
    "query": {
     "query": "label_values(kube_pod_info{pod=~\"backstage.*\"},cluster_id)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info{pod=~\"backstage.*\"},namespace)"
    }
   },
   { "name": "logfilter", "label": "Log filter" }
  ]
 },
 "panels": [
  {
   "title": "About this dashboard",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "This dashboard shows details and logs about/from the [Backstage](https://docs.giantswarm.io/overview/developer-portal/) developer portal provided by Giant Swarm."
     }
    }
   ]
  },
  { "title": "Workload overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Pod Info",
   "type": "table",
   "description": "This table shows pods up (at the end of the selected time interval)",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "kube_pod_container_info{cluster_id=~\"$cluster_id\", namespace=~\"$namespace\", pod=~\"backstage-.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Errors and warnings in logs",
   "type": "logs",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"backstage\", namespace=~\"$namespace\", cluster_id=~\"$cluster_id\"} |= `$logfilter` | json | level != `info`"
    }
   ]
  },
  {
   "title": "All logs",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"backstage\", namespace=~\"$namespace\", cluster_id=~\"$cluster_id\"} != `kube-probe` |= `$logfilter` | json"
    }
   ]
  }
 ]
}