{
 "title": "Cilium Metrics",
 "description": "Dashboard for Cilium (https://cilium.io/) metrics",
 "tags": [
  "topic:networking",
  "owner:team-cabbage"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster_id",
    "label": "Cluster",
    "query": {
     "query": "label_values(cilium_version, cluster_id)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(cilium_version{cluster_id=\"$cluster_id\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Errors & Warnings",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_errors_warnings_total{cluster_id=\"$cluster_id\",pod=~\"$pod\"}[$__rate_interval])) by (pod, level) * 60",
     "legendFormat": "{{pod}} ({{level}})"
    }
   ]
  },
  {
   "title": "CPU Usage per node",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "min(irate(cilium_process_cpu_seconds_total{cluster_id=\"$cluster_id\",pod=~\"$pod\"}[$__rate_interval])) by (pod) * 100",
     "legendFormat": "min ({{pod}})"
    },
    {
     "expr": "avg(irate(cilium_process_cpu_seconds_total{cluster_id=\"$cluster_id\",pod=~\"$pod\"}[$__rate_interval])) by (pod) * 100",
     "legendFormat": "avg ({{pod}})"
    },
    {
     "expr": "max(irate(cilium_process_cpu_seconds_total{cluster_id=\"$cluster_id\",pod=~\"$pod\"}[$__rate_interval])) by (pod) * 100",
     "legendFormat": "max ({{pod}})"
    }
   ]
  },
  {
   "title": "Generic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Virtual Memory Bytes",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "min(cilium_process_virtual_memory_bytes{cluster_id=\"$cluster_id\",pod=~\"$pod\"})",
       "legendFormat": "Min Virtual Memory"
      },
      {
       "expr": "avg(cilium_process_virtual_memory_bytes{cluster_id=\"$cluster_id\",pod=~\"$pod\"})",
       "legendFormat": "Average Virtual Memory"
      },
      {
       "expr": "max(cilium_process_virtual_memory_bytes{cluster_id=\"$cluster_id\",pod=~\"$pod\"})",
       "legendFormat": "Max Virtual Memory"
      }
     ]
    },
    {
     "title": "Resident memory status",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(cilium_process_resident_memory_bytes{cluster_id=\"$cluster_id\",pod=~\"$pod\"})",
       "legendFormat": "AVG_resident_memory_bytes"
      },
      {
       "expr": "max(cilium_process_resident_memory_bytes{cluster_id=\"$cluster_id\",pod=~\"$pod\"})",
       "legendFormat": "MAX_resident_memory_bytes_max"
      },
      {
       "expr": "min(cilium_process_resident_memory_bytes{cluster_id=\"$cluster_id\",pod=~\"$pod\"})",
       "legendFormat": "MIN_resident_memory_bytes_min"
      }
     ]
    },
    {
     "title": "Open file descriptors",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(cilium_process_open_fds{cluster_id=\"$cluster_id\",pod=~\"$pod\"})",
       "legendFormat": "all nodes"
      },
      {
       "expr": "min(cilium_process_open_fds{cluster_id=\"$cluster_id\",pod=~\"$pod\"})",
       "legendFormat": "min/node"
      },
      {
       "expr": "avg(cilium_process_open_fds{cluster_id=\"$cluster_id\",pod=~\"$pod\"})",
       "legendFormat": "avg/node"
      },
      {
       "expr": "max(cilium_process_open_fds{cluster_id=\"$cluster_id\",pod=~\"$pod\"})",
       "legendFormat": "max/node"
      }
     ]
    },
    {
     "title": "System-wide BPF memory usage",
     "type": "timeseries",
     "description": "BPF memory usage in the entire system including components not managed by Cilium.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(cilium_bpf_maps_virtual_memory_max_bytes{cluster_id=\"$cluster_id\",pod=~\"$pod\"} + cilium_bpf_progs_virtual_memory_max_bytes{cluster_id=\"$cluster_id\",pod=~\"$pod\"})",
       "legendFormat": "AVG_bpf_memory_bytes_avg"
      },
      {
       "expr": "max(cilium_bpf_maps_virtual_memory_max_bytes{cluster_id=\"$cluster_id\",pod=~\"$pod\"} + cilium_bpf_progs_virtual_memory_max_bytes{cluster_id=\"$cluster_id\",pod=~\"$pod\"})",
       "legendFormat": "MAX_bpf_memory_bytes_max"
      },
      {
       "expr": "min(cilium_bpf_maps_virtual_memory_max_bytes{cluster_id=\"$cluster_id\",pod=~\"$pod\"} + cilium_bpf_progs_virtual_memory_max_bytes{cluster_id=\"$cluster_id\",pod=~\"$pod\"})",
       "legendFormat": "MIN_bpf_memory_bytes_min"
      }
     ]
    },
    {
     "title": "BPF map pressure",
     "type": "timeseries",
     "description": "Fill percentage of BPF maps, tagged by map name",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "cilium_bpf_map_pressure{cluster_id=\"$cluster_id\",pod=~\"$pod\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "API call latency (average node)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(rate(cilium_agent_api_process_time_seconds_sum{cluster_id=\"$cluster_id\",pod=~\"$pod\"}[$__rate_interval])/rate(cilium_agent_api_process_time_seconds_count{cluster_id=\"$cluster_id\",pod=~\"$pod\"}[$__rate_interval])) by (pod, method, path)",
       "legendFormat": "{{method}} {{path}}"
      }
     ]
    },
    {
     "title": "API call latency (max node)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(rate(cilium_agent_api_process_time_seconds_sum{cluster_id=\"$cluster_id\",pod=~\"$pod\"}[$__rate_interval])/rate(cilium_agent_api_process_time_seconds_count{cluster_id=\"$cluster_id\",pod=~\"$pod\"}[$__rate_interval])) by (pod, method, path)",
       "legendFormat": "{{method}} {{path}}"
      }
     ]
    },
    {
     "title": "# API calls (average node)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "avg(rate(cilium_agent_api_process_time_seconds_count{cluster_id=\"$cluster_id\",pod=~\"$pod\"}[$__rate_interval])) by (pod, method, path)",
       "legendFormat": "{{method}} {{path}} "
      }
     ]
    },
    {
     "title": "# API calls (max node)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "max(rate(cilium_agent_api_process_time_seconds_count{cluster_id=\"$cluster_id\",pod=~\"$pod\"}[$__rate_interval])) by (pod, method, path)",
       "legendFormat": "{{method}} {{path}} "
      }
     ]
    },
    {
     "title": "API return codes (average node)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "avg(rate(cilium_agent_api_process_time_seconds_count{cluster_id=\"$cluster_id\",pod=~\"$pod\"}[$__rate_interval])) by (pod, method, path, return_code)",
       "legendFormat": "{{return_code}} ({{method}} {{path}} )"
      }
     ]
    },
    {
     "title": "API return codes (sum all nodes)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(cilium_agent_api_process_time_seconds_count{cluster_id=\"$cluster_id\",pod=~\"$pod\"}[$__rate_interval])) by (pod, method, path, return_code)",
       "legendFormat": "{{return_code}} ({{method}} {{path}} )"
      }
     ]
    }
   ]
  },
  {
   "title": "Cilium",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "BPF",
     "type": "text",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {}
     ]
    },
    {
     "title": "# system calls (average node)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "avg(rate(cilium_bpf_syscall_duration_seconds_count{cluster_id=\"$cluster_id\",pod=~\"$pod\"}[$__rate_interval])) by (pod, operation)",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "# system calls (max node)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "max(rate(cilium_bpf_syscall_duration_seconds_count{cluster_id=\"$cluster_id\",pod=~\"$pod\"}[$__rate_interval])) by (pod, operation)",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "system call latency (avg node)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(rate(cilium_bpf_syscall_duration_seconds_sum{cluster_id=\"$cluster_id\",pod=~\"$pod\"}[$__rate_interval])/ rate(cilium_bpf_syscall_duration_seconds_count{cluster_id=\"$cluster_id\",pod=~\"$pod\"}[$__rate_interval])) by (pod, operation)",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "system call latency (max node)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(rate(cilium_bpf_syscall_duration_seconds_sum{cluster_id=\"$cluster_id\",pod=~\"$pod\"}[$__rate_interval])/ rate(cilium_bpf_syscall_duration_seconds_count{cluster_id=\"$cluster_id\",pod=~\"$pod\"}[$__rate_interval])) by (pod, operation)",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "map ops (average node)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "topk(5, avg(rate(cilium_bpf_map_ops_total{cluster_id=\"$cluster_id\",pod=~\"$pod\"}[$__rate_interval])) by (pod, map_name, operation))",
       "legendFormat": "{{map_name}} {{operation}}"
      }
     ]
    },
    {
     "title": "map ops (max node)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "topk(5, max(rate(cilium_bpf_map_ops_total{cluster_id=\"$cluster_id\",pod=~\"$pod\"}[$__rate_interval])) by (pod, map_name, operation))",
       "legendFormat": "{{map_name}} {{operation}}"
      }
     ]
    },
    {
     "title": "map ops (sum failures)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(cilium_bpf_map_ops_total{cluster_id=\"$cluster_id\",k8s_app=\"cilium\",outcome=\"fail\", pod=~\"$pod\"}[$__rate_interval])) by (pod, map_name, operation)",
       "legendFormat": "{{map_name}} {{operation}}"
      }
     ]
    },
    {
     "title": "kvstore",
     "type": "text",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
     "targets": [
      {}
     ]
    },
    {
     "title": "# operations (sum all nodes)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(kvstore_operations_total{cluster_id=\"$cluster_id\",pod=~\"$pod\"}[$__rate_interval])) by (pod, scope, action)",
       "legendFormat": "{{scope}} {{action}}"
      }
     ]
    },
    {
     "title": "# operations (max node)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "max(rate(kvstore_operations_total{cluster_id=\"$cluster_id\",pod=~\"$pod\"}[$__rate_interval])) by (pod, scope, action)",
       "legendFormat": "{{scope}} {{action}}"
      }
     ]
    },
    {
     "title": "latency (average node)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk(5, avg(rate(cilium_kvstore_operations_duration_seconds_sum{cluster_id=\"$cluster_id\",pod=~\"$pod\"}[$__rate_interval])) by (pod, action, scope) / avg(rate(cilium_kvstore_operations_duration_seconds_count{cluster_id=\"$cluster_id\",pod=~\"$pod\"}[$__rate_interval])) by (pod, action, scope))",
       "legendFormat": "{{action}} {{scope}}"
      }
     ]
    },
    {
     "title": "latency (max node)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk(5, max(rate(cilium_kvstore_operations_duration_seconds_sum{cluster_id=\"$cluster_id\",pod=~\"$pod\"}[$__rate_interval])) by (pod, action, scope) / avg(rate(cilium_kvstore_operations_duration_seconds_count{cluster_id=\"$cluster_id\",pod=~\"$pod\"}[$__rate_interval])) by (pod, action, scope))",
       "legendFormat": "{{action}} {{scope}}"
      }
     ]
    },
    {
     "title": "Events received (average node)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "avg(rate(cilium_kvstore_events_queue_seconds_count{cluster_id=\"$cluster_id\",pod=~\"$pod\"}[$__rate_interval])) by (pod, scope, action)",
       "legendFormat": "{{action}} {{scope}}"
      }
     ]
    },
    {
     "title": "Cilium network information",
     "type": "text",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
     "targets": [
      {}
     ]
    },
    {
     "title": "Forwarded Packets",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(cilium_forward_count_total{cluster_id=\"$cluster_id\",pod=~\"$pod\"}[$__rate_interval])) by (pod, direction)",
       "legendFormat": "{{direction}}"
      }
     ]
    },
    {
     "title": "Forwarded Traffic",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "sum(rate(cilium_forward_bytes_total{cluster_id=\"$cluster_id\",pod=~\"$pod\"}[$__rate_interval])) by (pod, direction) * 8",
       "legendFormat": "{{direction}}"
      }
     ]
    },
    {
     "title": "IPv4 Conntrack TCP",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "min(cilium_datapath_conntrack_gc_entries{cluster_id=\"$cluster_id\", status=\"alive\", family=\"ipv4\", protocol=\"TCP\", pod=~\"$pod\"}) by (family,status)",
       "legendFormat": "min"
      },
      {
       "expr": "avg(cilium_datapath_conntrack_gc_entries{cluster_id=\"$cluster_id\", status=\"alive\", family=\"ipv4\", protocol=\"TCP\", pod=~\"$pod\"}) by (family,status)",
       "legendFormat": "avg"
      },
      {
       "expr": "max(cilium_datapath_conntrack_gc_entries{cluster_id=\"$cluster_id\",status=\"alive\", family=\"ipv4\", protocol=\"TCP\", pod=~\"$pod\"}) by (family,status)",
       "legendFormat": "max"
      },
      {
       "expr": "avg(cilium_datapath_conntrack_gc_entries{cluster_id=\"$cluster_id\", status=\"deleted\", family=\"ipv4\", protocol=\"TCP\", pod=~\"$pod\"}) by (family,status)",
       "legendFormat": "deleted"
      },
      {
       "expr": "max(cilium_datapath_conntrack_gc_entries{cluster_id=\"$cluster_id\", status=\"deleted\", family=\"ipv4\", protocol=\"TCP\", pod=~\"$pod\"}) by (family,status)",
       "legendFormat": "deleted max"
      }
     ]
    },
    {
     "title": "IPv6 Conntrack TCP",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "min(cilium_datapath_conntrack_gc_entries{cluster_id=\"$cluster_id\", status=\"alive\", family=\"ipv6\", protocol=\"TCP\", pod=~\"$pod\"}) by (family,status)",
       "legendFormat": "min"
      },
      {
       "expr": "avg(cilium_datapath_conntrack_gc_entries{cluster_id=\"$cluster_id\", status=\"alive\", family=\"ipv6\", protocol=\"TCP\", pod=~\"$pod\"}) by (family,status)",
       "legendFormat": "avg"
      },
      {
       "expr": "max(cilium_datapath_conntrack_gc_entries{cluster_id=\"$cluster_id\", status=\"alive\", family=\"ipv6\", protocol=\"TCP\", pod=~\"$pod\"}) by (family,status)",
       "legendFormat": "max"
      },
      {
       "expr": "avg(cilium_datapath_conntrack_gc_entries{cluster_id=\"$cluster_id\", status=\"deleted\", family=\"ipv6\", protocol=\"TCP\", pod=~\"$pod\"}) by (family,status)",
       "legendFormat": "deleted"
      },
      {
       "expr": "max(cilium_datapath_conntrack_gc_entries{cluster_id=\"$cluster_id\", status=\"deleted\", family=\"ipv6\", protocol=\"TCP\", pod=~\"$pod\"}) by (family,status)",
       "legendFormat": "deleted max"
      }
     ]
    },
    {
     "title": "IPv4 Conntrack Non-TCP",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "min(cilium_datapath_conntrack_gc_entries{cluster_id=\"$cluster_id\", status=\"alive\", family=\"ipv4\", protocol=\"non-TCP\", pod=~\"$pod\"}) by (family,status)",
       "legendFormat": "min"
      },
      {
       "expr": "avg(cilium_datapath_conntrack_gc_entries{cluster_id=\"$cluster_id\", status=\"alive\", family=\"ipv4\", protocol=\"non-TCP\", pod=~\"$pod\"}) by (family,status)",
       "legendFormat": "avg"
      },
      {
       "expr": "max(cilium_datapath_conntrack_gc_entries{cluster_id=\"$cluster_id\", status=\"alive\", family=\"ipv4\", protocol=\"non-TCP\", pod=~\"$pod\"}) by (family,status)",
       "legendFormat": "max"
      },
      {
       "expr": "avg(cilium_datapath_conntrack_gc_entries{cluster_id=\"$cluster_id\", status=\"deleted\", family=\"ipv4\", protocol=\"non-TCP\", pod=~\"$pod\"}) by (family,status)",
       "legendFormat": "deleted"
      },
      {
       "expr": "max(cilium_datapath_conntrack_gc_entries{cluster_id=\"$cluster_id\", status=\"deleted\", family=\"ipv4\", protocol=\"non-TCP\", pod=~\"$pod\"}) by (family,status)",
       "legendFormat": "deleted max"
      }
     ]
    },
    {
     "title": "IPv6 Conntrack Non-TCP",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "min(cilium_datapath_conntrack_gc_entries{cluster_id=\"$cluster_id\", status=\"alive\", family=\"ipv6\", protocol=\"non-TCP\", pod=~\"$pod\"}) by (family,status)",
       "legendFormat": "min"
      },
      {
       "expr": "avg(cilium_datapath_conntrack_gc_entries{cluster_id=\"$cluster_id\", status=\"alive\", family=\"ipv6\", protocol=\"non-TCP\", pod=~\"$pod\"}) by (family,status)",
       "legendFormat": "avg"
      },
      {
       "expr": "max(cilium_datapath_conntrack_gc_entries{cluster_id=\"$cluster_id\", status=\"alive\", family=\"ipv6\", protocol=\"non-TCP\", pod=~\"$pod\"}) by (family,status)",
       "legendFormat": "max"
      },
      {
       "expr": "avg(cilium_datapath_conntrack_gc_entries{cluster_id=\"$cluster_id\", status=\"deleted\", family=\"ipv6\", protocol=\"non-TCP\", pod=~\"$pod\"}) by (family,status)",
       "legendFormat": "deleted"
      },
      {
       "expr": "max(cilium_datapath_conntrack_gc_entries{cluster_id=\"$cluster_id\", status=\"deleted\", family=\"ipv6\", protocol=\"non-TCP\", pod=~\"$pod\"}) by (family,status)",
       "legendFormat": "deleted max"
      }
     ]
    },
    {
     "title": "Allocated Addresses",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(cilium_ip_addresses{cluster_id=\"$cluster_id\", pod=~\"$pod\"}) by (pod, family)\n",
       "legendFormat": "{{family}}"
      }
     ]
    },
    {
     "title": "Datapath Conntrack Dump Resets",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(cilium_datapath_conntrack_dump_resets_total{cluster_id=\"$cluster_id\", pod=~\"$pod\"}) by (pod, area, family, name)",
       "legendFormat": "{{name}} {{area}} {{family}}"
      }
     ]
    },
    {
     "title": "Service Updates",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "avg(rate(cilium_services_events_total{cluster_id=\"$cluster_id\", pod=~\"$pod\"}[$__rate_interval])) by (pod, action)",
       "legendFormat": "{{action}}"
      }
     ]
    },
    {
     "title": "Connectivity Health",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(cilium_unreachable_nodes{cluster_id=\"$cluster_id\", pod=~\"$pod\"}) by (pod)",
       "legendFormat": "unreachable nodes"
      },
      {
       "expr": "sum(cilium_unreachable_health_endpoints{cluster_id=\"$cluster_id\", pod=~\"$pod\"}) by (pod)",
       "legendFormat": "unreachable health endpoints"
      }
     ]
    },
    {
     "title": "Dropped Egress Packets",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(cilium_drop_count_total{cluster_id=\"$cluster_id\", direction=\"EGRESS\", pod=~\"$pod\"}[$__rate_interval])) by (reason)",
       "legendFormat": "{{reason}}"
      }
     ]
    },
    {
     "title": "Node Events",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "opm" } },
     "targets": [
      {
       "expr": "avg(rate(cilium_nodes_all_events_received_total{cluster_id=\"$cluster_id\", pod=~\"$pod\"}[$__rate_interval])) by (pod, event_type, source) * 60",
       "legendFormat": "{{eventType}} {{source}}"
      }
     ]
    },
    {
     "title": "Dropped Egress Traffic",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "sum(rate(cilium_drop_bytes_total{cluster_id=\"$cluster_id\", direction=\"EGRESS\", pod=~\"$pod\"}[$__rate_interval])) by (reason) * 8",
       "legendFormat": "{{reason}}"
      }
     ]
    },
    {
     "title": "Nodes",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(cilium_nodes_all_num{cluster_id=\"$cluster_id\", pod=~\"$pod\"}) by (pod)",
       "legendFormat": "Average Nodes"
      },
      {
       "expr": "min(cilium_nodes_all_num{cluster_id=\"$cluster_id\", pod=~\"$pod\"}) by (pod)",
       "legendFormat": "Min Nodes"
      },
      {
       "expr": "max(cilium_nodes_all_num{cluster_id=\"$cluster_id\", pod=~\"$pod\"}) by (pod)",
       "legendFormat": "Max Nodes"
      }
     ]
    },
    {
     "title": "Policy",
     "type": "text",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 },
     "targets": [
      {}
     ]
    },
    {
     "title": "L7 forwarded request",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(cilium_policy_l7_denied_total{cluster_id=\"$cluster_id\",pod=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "denied"
      },
      {
       "expr": "sum(rate(cilium_policy_l7_forwarded_total{cluster_id=\"$cluster_id\",pod=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "forwarded"
      },
      {
       "expr": "sum(rate(cilium_policy_l7_received_total{cluster_id=\"$cluster_id\",pod=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "received"
      }
     ]
    },
    {
     "title": "Cilium drops Ingress",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(cilium_drop_count_total{cluster_id=\"$cluster_id\",direction=\"INGRESS\", pod=~\"$pod\"}[$__rate_interval])) by (reason)",
       "legendFormat": "{{reason}}"
      }
     ]
    },
    {
     "title": "Proxy response time (Avg)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(rate(cilium_proxy_upstream_reply_seconds_sum{cluster_id=\"$cluster_id\",pod=~\"$pod\"}[$__rate_interval])) by (pod, scope) / sum(rate(cilium_proxy_upstream_reply_seconds_count{cluster_id=\"$cluster_id\",pod=~\"$pod\"}[$__rate_interval])) by (pod, scope)",
       "legendFormat": "{{scope}}"
      },
      {
       "expr": "avg(cilium_policy_l7_parse_errors_total{cluster_id=\"$cluster_id\",pod=~\"$pod\"}) by (pod)",
       "legendFormat": "parse errors"
      }
     ]
    },
    {
     "title": "Dropped Ingress Traffic",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "sum(rate(cilium_drop_bytes_total{cluster_id=\"$cluster_id\",direction=\"INGRESS\", pod=~\"$pod\"}[$__rate_interval])) by (reason) * 8",
       "legendFormat": "{{reason}}"
      }
     ]
    },
    {
     "title": "Policy Trigger Duration",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "min(rate(cilium_triggers_policy_update_call_duration_seconds_sum{cluster_id=\"$cluster_id\",pod=~\"$pod\"}[$__rate_interval])) by (pod, scope) / sum(rate(cilium_triggers_policy_update_call_duration_seconds_count{cluster_id=\"$cluster_id\",pod=~\"$pod\"}[$__rate_interval])) by (pod, scope)",
       "legendFormat": "min"
      },
      {
       "expr": "avg(rate(cilium_triggers_policy_update_call_duration_seconds_sum{cluster_id=\"$cluster_id\",pod=~\"$pod\"}[$__rate_interval])) by (pod, scope) / sum(rate(cilium_triggers_policy_update_call_duration_seconds_count{cluster_id=\"$cluster_id\",pod=~\"$pod\"}[$__rate_interval])) by (pod, scope)",
       "legendFormat": "avg"
      },
      {
       "expr": "max(rate(cilium_triggers_policy_update_call_duration_seconds_sum{cluster_id=\"$cluster_id\",pod=~\"$pod\"}[$__rate_interval])) by (pod, scope) / sum(rate(cilium_triggers_policy_update_call_duration_seconds_count{cluster_id=\"$cluster_id\",pod=~\"$pod\"}[$__rate_interval])) by (pod, scope)",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Proxy response time (Max)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(rate(cilium_proxy_upstream_reply_seconds_sum{cluster_id=\"$cluster_id\",pod=~\"$pod\"}[$__rate_interval])) by (pod, scope) / sum(rate(cilium_proxy_upstream_reply_seconds_count{cluster_id=\"$cluster_id\",pod=~\"$pod\"}[$__rate_interval])) by (pod, scope)",
       "legendFormat": "Max {{scope}}"
      },
      {
       "expr": "max(rate(cilium_policy_l7_parse_errors_total{cluster_id=\"$cluster_id\",pod=~\"$pod\"}[$__rate_interval])) by (pod)",
       "legendFormat": "parse errors"
      }
     ]
    },
    {
     "title": "Endpoints policy enforcement status",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(cilium_policy_endpoint_enforcement_status{cluster_id=\"$cluster_id\",pod=~\"$pod\"}) by (enforcement)",
       "legendFormat": "{{enforcement}}"
      }
     ]
    },
    {
     "title": "Proxy Redirects",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "min(cilium_proxy_redirects{cluster_id=\"$cluster_id\",pod=~\"$pod\"}) by (pod)",
       "legendFormat": "min"
      },
      {
       "expr": "avg(cilium_proxy_redirects{cluster_id=\"$cluster_id\",pod=~\"$pod\"}) by (pod)",
       "legendFormat": "avg"
      },
      {
       "expr": "max(cilium_proxy_redirects{cluster_id=\"$cluster_id\",pod=~\"$pod\"}) by (pod)",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Policy Trigger Runs",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "opm" } },
     "targets": [
      {
       "expr": "min(rate(cilium_triggers_policy_update_total{cluster_id=\"$cluster_id\",pod=~\"$pod\"}[$__rate_interval])) by (pod) * 60",
       "legendFormat": "min trigger"
      },
      {
       "expr": "avg(rate(cilium_triggers_policy_update_total{cluster_id=\"$cluster_id\",pod=~\"$pod\"}[$__rate_interval])) by (pod) * 60",
       "legendFormat": "average trigger"
      },
      {
       "expr": "max(rate(cilium_triggers_policy_update_total{cluster_id=\"$cluster_id\",pod=~\"$pod\"}[$__rate_interval])) by (pod) * 60",
       "legendFormat": "max trigger"
      },
      {
       "expr": "max(rate(cilium_triggers_policy_update_folds{pod=~\"$pod\"}[$__rate_interval])) by (pod) * 60",
       "legendFormat": "folds"
      }
     ]
    },
    {
     "title": "Policies Per Node",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "min(cilium_policy{cluster_id=\"$cluster_id\",pod=~\"$pod\"}) by(pod)",
       "legendFormat": "min"
      },
      {
       "expr": "avg(cilium_policy{cluster_id=\"$cluster_id\",pod=~\"$pod\"}) by(pod)",
       "legendFormat": "avg"
      },
      {
       "expr": "max(cilium_policy{cluster_id=\"$cluster_id\",pod=~\"$pod\"}) by(pod)",
       "legendFormat": "max"
      },
      {
       "expr": "sum(cilium_policy_import_errors_total{pod=~\"$pod\"}) by (pod)",
       "legendFormat": "policy import errors"
      }
     ]
    },
    {
     "title": "DNS proxy requests",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "avg(rate(cilium_proxy_upstream_reply_seconds_count{cluster_id=\"$cluster_id\",pod=~\"$pod\"}[$__rate_interval])) by (pod, scope)",
       "legendFormat": "{{scope}}"
      }
     ]
    },
    {
     "title": "Policy Revision",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 106 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "min(cilium_policy_max_revision{cluster_id=\"$cluster_id\",pod=~\"$pod\"}) by (pod)",
       "legendFormat": "min"
      },
      {
       "expr": "avg(cilium_policy_max_revision{cluster_id=\"$cluster_id\",pod=~\"$pod\"}) by (pod)",
       "legendFormat": "avg"
      },
      {
       "expr": "max(cilium_policy_max_revision{cluster_id=\"$cluster_id\",pod=~\"$pod\"}) by (pod)",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Endpoints",
     "type": "text",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 111 },
     "targets": [
      {}
     ]
    },
    {
     "title": "Endpoint regeneration time (90th percentile)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 112 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(histogram_quantile(0.90, rate(cilium_endpoint_regeneration_time_stats_seconds_bucket{cluster_id=\"$cluster_id\",scope!=\"total\", pod=~\"$pod\"}[$__rate_interval]))) by (scope)",
       "legendFormat": "{{scope}}"
      }
     ]
    },
    {
     "title": "Endpoint regeneration time (99th percentile)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 112 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(histogram_quantile(0.99, rate(cilium_endpoint_regeneration_time_stats_seconds_bucket{cluster_id=\"$cluster_id\",scope!=\"total\", pod=~\"$pod\"}[$__rate_interval]))) by (scope)",
       "legendFormat": "{{scope}}"
      }
     ]
    },
    {
     "title": "Endpoint regenerations",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 121 },
     "fieldConfig": { "defaults": { "unit": "opm" } },
     "targets": [
      {
       "expr": "sum(rate(cilium_endpoint_regenerations_total{cluster_id=\"$cluster_id\",pod=~\"$pod\"}[$__rate_interval])) by(outcome)",
       "legendFormat": "{{outcome}}"
      }
     ]
    },
    {
     "title": "Cilium endpoint state",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 121 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(cilium_endpoint_state{cluster_id=\"$cluster_id\",pod=~\"$pod\"}) by (endpoint_state)",
       "legendFormat": "{{endpoint_state}}"
      }
     ]
    },
    {
     "title": "Controllers",
     "type": "text",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 126 },
     "targets": [
      {}
     ]
    },
    {
     "title": "Controllers",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 127 },
     "fieldConfig": { "defaults": { "unit": "opm" } },
     "targets": [
      {
       "expr": "sum(rate(cilium_controllers_runs_total{cluster_id=\"$cluster_id\",pod=~\"$pod\"}[$__rate_interval])) by (pod)",
       "legendFormat": "Runs"
      },
      {
       "expr": "sum(cilium_controllers_failing{cluster_id=\"$cluster_id\",pod=~\"$pod\"}) by(pod)",
       "legendFormat": "Failed"
      }
     ]
    },
    {
     "title": "Controller Durations",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 127 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(cilium_controllers_runs_duration_seconds_sum{cluster_id=\"$cluster_id\",pod=~\"$pod\"}[$__rate_interval])) by (pod, status) / sum(rate(cilium_controllers_runs_duration_seconds_count{cluster_id=\"$cluster_id\",pod=~\"$pod\"}[$__rate_interval])) by (pod, status)",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Kubernetes integration",
     "type": "text",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 132 },
     "targets": [
      {}
     ]
    },
    {
     "title": "apiserver latency (average node)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 133 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(rate(cilium_k8s_client_api_latency_time_seconds_sum{cluster_id=\"$cluster_id\",pod=~\"$pod\"}[$__rate_interval])/rate(cilium_k8s_client_api_latency_time_seconds_count{cluster_id=\"$cluster_id\",pod=~\"$pod\"}[$__rate_interval])) by (pod, method, path)",
       "legendFormat": "{{method}} {{path}}"
      }
     ]
    },
    {
     "title": "apiserver latency (max node)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 133 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(rate(cilium_k8s_client_api_latency_time_seconds_sum{cluster_id=\"$cluster_id\",pod=~\"$pod\"}[$__rate_interval])/rate(cilium_k8s_client_api_latency_time_seconds_count{cluster_id=\"$cluster_id\",pod=~\"$pod\"}[$__rate_interval])) by (pod, method, path)",
       "legendFormat": "{{method}} {{path}}"
      }
     ]
    },
    {
     "title": "apiserver #calls (sum all nodes)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 140 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(cilium_k8s_client_api_latency_time_seconds_count{cluster_id=\"$cluster_id\",pod=~\"$pod\"}[$__rate_interval])) by (pod, method, path)",
       "legendFormat": "{{method}} {{path}}"
      }
     ]
    },
    {
     "title": "apiserver calls (sum all nodes)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 140 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(cilium_k8s_client_api_calls_total{cluster_id=\"$cluster_id\",pod=~\"$pod\"}[$__rate_interval])) by (pod, method, return_code)",
       "legendFormat": "{{method}} {{return_code}}"
      }
     ]
    },
    {
     "title": "Valid, Unnecessary K8s Events Received",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 148 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(cilium_kubernetes_events_received_total{cluster_id=\"$cluster_id\",equal=\"true\", valid=\"true\", pod=~\"$pod\"}[$__rate_interval])) by (pod, scope, action)",
       "legendFormat": "{{action}} {{scope}}"
      }
     ]
    },
    {
     "title": "Invalid, Unnecessary K8s Events Received",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 148 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(cilium_kubernetes_events_received_total{cluster_id=\"$cluster_id\",equal=\"true\", valid=\"false\", pod=~\"$pod\"}[$__rate_interval])) by (pod, scope, action)",
       "legendFormat": "{{action}} {{scope}}"
      }
     ]
    },
    {
     "title": "Valid, Necessary K8s Events Received",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 154 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cilium_kubernetes_events_received_total{cluster_id=\"$cluster_id\",equal=\"false\", valid=\"true\", pod=~\"$pod\"}[$__rate_interval])) by (pod, scope, action, valid)",
       "legendFormat": "{{action}} {{scope}}"
      }
     ]
    },
    {
     "title": "Invalid, Necessary K8s Events Received",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 154 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cilium_kubernetes_events_received_total{cluster_id=\"$cluster_id\",equal=\"false\", valid=\"false\", pod=~\"$pod\"}[$__rate_interval])) by (pod, scope, action)",
       "legendFormat": "{{action}} {{scope}}"
      }
     ]
    },
    {
     "title": "CiliumNetworkPolicy Events",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 162 },
     "fieldConfig": { "defaults": { "unit": "opm" } },
     "targets": [
      {
       "expr": "avg(rate(cilium_kubernetes_events_total{cluster_id=\"$cluster_id\",scope=\"CiliumNetworkPolicy\", pod=~\"$pod\"}[$__rate_interval])) by (pod, action) * 60",
       "legendFormat": "{{action}} avg"
      }
     ]
    },
    {
     "title": "NetworkPolicy Events",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 162 },
     "fieldConfig": { "defaults": { "unit": "opm" } },
     "targets": [
      {
       "expr": "avg(rate(cilium_kubernetes_events_total{cluster_id=\"$cluster_id\",scope=\"NetworkPolicy\", pod=~\"$pod\"}[$__rate_interval])) by (pod, action) * 60",
       "legendFormat": "{{action}} avg"
      }
     ]
    },
    {
     "title": "Pod Events",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 169 },
     "fieldConfig": { "defaults": { "unit": "opm" } },
     "targets": [
      {
       "expr": "avg(rate(cilium_kubernetes_events_total{cluster_id=\"$cluster_id\",scope=\"Pod\", pod=~\"$pod\"}[$__rate_interval])) by (pod, action) * 60",
       "legendFormat": "{{action}} avg"
      }
     ]
    },
    {
     "title": "Node Events",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 169 },
     "fieldConfig": { "defaults": { "unit": "opm" } },
     "targets": [
      {
       "expr": "avg(rate(cilium_kubernetes_events_total{cluster_id=\"$cluster_id\",scope=\"Node\", pod=~\"$pod\"}[$__rate_interval])) by (pod, action) * 60",
       "legendFormat": "{{action}} avg"
      }
     ]
    },
    {
     "title": "Service Events",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 176 },
     "fieldConfig": { "defaults": { "unit": "opm" } },
     "targets": [
      {
       "expr": "avg(rate(cilium_kubernetes_events_total{cluster_id=\"$cluster_id\",scope=\"Service\", pod=~\"$pod\"}[$__rate_interval])) by (pod, action) * 60",
       "legendFormat": "{{action}}"
      }
     ]
    },
    {
     "title": "Endpoints Events",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 176 },
     "fieldConfig": { "defaults": { "unit": "opm" } },
     "targets": [
      {
       "expr": "avg(rate(cilium_kubernetes_events_total{cluster_id=\"$cluster_id\",scope=\"Endpoint\", pod=~\"$pod\"}[$__rate_interval])) by (pod, action) * 60",
       "legendFormat": "{{action}}"
      }
     ]
    },
    {
     "title": "Namespace Events",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 183 },
     "fieldConfig": { "defaults": { "unit": "opm" } },
     "targets": [
      {
       "expr": "avg(rate(cilium_kubernetes_events_total{cluster_id=\"$cluster_id\",scope=\"Namespace\", pod=~\"$pod\"}[$__rate_interval])) by (pod, action) * 60",
       "legendFormat": "{{action}}"
      }
     ]
    }
   ]
  },
  {
   "title": "API Rate Limit",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true
  },
  {
   "title": "API Limiter Adjustment Factor",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(cilium_api_limiter_adjustment_factor{cluster_id=\"$cluster_id\",pod=~\"$pod\"}) by (pod, api_call)",
     "legendFormat": "{{api_call}}"
    }
   ]
  },
  {
   "title": "API Limiter Rate Limit",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(cilium_api_limiter_rate_limit{cluster_id=\"$cluster_id\",pod=~\"$pod\"}) by (pod, api_call, value)",
     "legendFormat": "{{api_call}} {{value}}"
    }
   ]
  },
  {
   "title": "API Limiter Processed Total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_api_limiter_processed_requests_total{cluster_id=\"$cluster_id\",pod=~\"$pod\"}[$__rate_interval])) by (pod, api_call, outcome) * 60",
     "legendFormat": "{{api_call}} {{outcome}}"
    }
   ]
  }
 ]
}