{
 "title": "Deprecated container registries in use",
 "tags": [ "owner:team-honeybadger" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "About this dashboard",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "Giant Swarm started an initiative in mid-2025 to consolidate the use of container registries and phaase out some deprecated ones.\n\nThis dashboard informs about all containers in Kubernetes clusters using images from one of the deprecated registries. As these images will be deleted eventually, the goal is to reduce the usage to zero.\n\n[Related GitHub issue](https://github.com/giantswarm/roadmap/issues/3935)\n"
   }
  },
  {
   "title": "Number of containers by image",
   "type": "table",
   "gridPos": { "h": 22, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_info{image=~\"^(quay\\\\.io/giantswarm/|docker\\\\.io/giantswarm/|giantswarm\\\\.azurecr\\\\.io/|giantswarmpublic\\\\.azurecr\\\\.io/).*\"} OR kube_pod_init_container_info{image=~\"^(quay\\\\.io/giantswarm/|docker\\\\.io/giantswarm/|giantswarm\\\\.azurecr\\\\.io/|giantswarmpublic\\\\.azurecr\\\\.io/).*\"}) by (image)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of containers using deprecated registries",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_info{image=~\"^(quay\\\\.io/giantswarm/|docker\\\\.io/giantswarm/|giantswarm\\\\.azurecr\\\\.io/|giantswarmpublic\\\\.azurecr\\\\.io/).*\"} OR kube_pod_init_container_info{image=~\"^(quay\\\\.io/giantswarm/|docker\\\\.io/giantswarm/|giantswarm\\\\.azurecr\\\\.io/|giantswarmpublic\\\\.azurecr\\\\.io/).*\"})",
     "legendFormat": "Containers"
    }
   ]
  },
  {
   "title": "Containers using deprecated registries",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "kube_pod_container_info{image=~\"^(quay\\\\.io/giantswarm/|docker\\\\.io/giantswarm/|giantswarm\\\\.azurecr\\\\.io/|giantswarmpublic\\\\.azurecr\\\\.io/).*\"} OR kube_pod_init_container_info{image=~\"^(quay\\\\.io/giantswarm/|docker\\\\.io/giantswarm/|giantswarm\\\\.azurecr\\\\.io/|giantswarmpublic\\\\.azurecr\\\\.io/).*\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}