{
 "title": "Dex",
 "description": "An overview on the success rate of authentication using SSO via dex.",
 "tags": [
  "owner:team-bigmac",
  "provider:aws",
  "provider:azure",
  "topic:management-cluster",
  "topic:workload-cluster"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "organization",
    "label": "Organization",
    "query": {
     "query": "label_values(http_requests_total{app=\"dex\"}, organization)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(http_requests_total{app=\"dex\", organization=\"$organization\"}, cluster_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "About this dashboard",
   "type": "text",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Dex\n\nThis Dashboard gives an overview on success and error responses returned by our SSO authentication service `dex`. All graph metrics are calculated based on error/success rate within a sliding 5 minute window. The single stats show the average of these metrics within the selected time frame.\n\nTo show metrics for `dex` running on the management cluster, select the installation name from the `cluster` drop down.\nTo show metrics for `dex` running on a workload cluster, select the workload cluster. If you don't see metrics for a cluster, it either means `dex` is not installed or you need to update  it to a version > 1.20.0.\n\n**HTTP Response Codes** [More Info](https://restfulapi.net/http-status-codes/)\n\n`1xx` Info `2xx` Success `3xx` Redirect `4xx` Client error `5xx` Server error\n"
   }
  },
  {
   "title": "Dex Success Response Rate",
   "type": "stat",
   "description": "Percentage of successful responses across all dex requests in the last 5 minutes. Displays the average value in the selected time window.",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (increase(http_requests_total{cluster_id=\"$cluster\",organization=~\"$organization\",app=\"dex\", code=~\"^[1]..$|[2]..$|^[3]..$\"}[5m]))/sum (increase(http_requests_total{cluster_id=\"$cluster\",organization=~\"$organization\",app=\"dex\"}[5m]))"
    }
   ]
  },
  {
   "title": "Dex Success Response Codes",
   "type": "timeseries",
   "description": "Successful dex responses in the last 5 minutes.",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (increase(http_requests_total{cluster_id=\"$cluster\",organization=~\"$organization\",app=\"dex\", code=~\"^[1]..$|[2]..$|^[3]..$\",handler!=\"/healthz\"}[5m]))by (code)",
     "legendFormat": "{{code}}"
    },
    { "expr": "health" }
   ]
  },
  {
   "title": "Dex Errors",
   "type": "stat",
   "description": "Number of dex error responses in the last 5 minutes. Displays the average value in the selected time window.",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (increase(http_requests_total{cluster_id=\"$cluster\",organization=~\"$organization\",app=\"dex\", code=~\"^[4]..$|[5]..$\"}[5m]))"
    }
   ]
  },
  {
   "title": "Dex Error Response Codes",
   "type": "timeseries",
   "description": "Error dex responses in the last 5 minutes.",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (increase(http_requests_total{cluster_id=\"$cluster\",organization=~\"$organization\",app=\"dex\", code=~\"^[4]..$|^[5]..$\"}[5m]))by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "All Dex requests",
   "type": "timeseries",
   "description": "Excluding health checks to /healthz",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{cluster_id=\"$cluster\",organization=~\"$organization\",app=\"dex\",handler!=\"/healthz\"}[2m])) by (handler, method, code)",
     "legendFormat": "{{ method }} {{ handler }} - status {{ code }}"
    }
   ]
  }
 ]
}