{
 "title": "Kong",
 "description": "Dashboard that graphs metrics exported via Prometheus plugin in Kong (http://github.com/kong/kong)",
 "tags": [
  "topic:workload-cluster",
  "kong",
  "owner:team-cabbage"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster_id",
    "label": "Cluster",
    "query": {
     "query": "label_values(kong_http_requests_total,cluster_id)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(kong_http_requests_total{cluster_id=~\"$cluster_id\"},service)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(kong_http_requests_total{cluster_id=~\"$cluster_id\"},instance)"
    }
   },
   {
    "name": "route",
    "query": {
     "query": "label_values(kong_http_requests_total{cluster_id=~\"$cluster_id\"},route)"
    }
   },
   {
    "name": "upstream",
    "query": "label_values(kong_upstream_target_health{cluster_id=~\"$cluster_id\"}, upstream)"
   },
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Request rate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total requests per second (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kong_http_requests_total{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}[1m]))",
     "legendFormat": "Requests/second"
    }
   ]
  },
  {
   "title": "RPS per route/service ($service)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kong_http_requests_total{cluster_id=~\"$cluster_id\", service=~\"$service\", route=~\"$route\", instance=~\"$instance\"}[1m])) by (service)",
     "legendFormat": "service:{{service}}"
    },
    {
     "expr": "sum(rate(kong_http_requests_total{cluster_id=~\"$cluster_id\", service=~\"$service\", route=~\"$route\", instance=~\"$instance\"}[1m])) by (route)",
     "legendFormat": "route:{{route}}"
    }
   ]
  },
  {
   "title": "RPS per route/service by status code",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kong_http_requests_total{cluster_id=~\"$cluster_id\", service=~\"$service\", route=~\"$route\", instance=~\"$instance\"}[1m])) by (service,code)",
     "legendFormat": "service:{{service}}-{{code}}"
    },
    {
     "expr": "sum(rate(kong_http_requests_total{cluster_id=~\"$cluster_id\", service=~\"$service\", route=~\"$route\", instance=~\"$instance\"}[1m])) by (route,code)",
     "legendFormat": "route:{{route}}-{{code}}"
    }
   ]
  },
  {
   "title": "Latencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Kong Proxy Latency across all services",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(kong_kong_latency_ms_bucket{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}[1m])) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(kong_kong_latency_ms_bucket{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}[1m])) by (le))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(kong_kong_latency_ms_bucket{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}[1m])) by (le))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Kong Proxy Latency per Service",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(kong_kong_latency_ms_bucket{cluster_id=~\"$cluster_id\", service=~\"$service\", route=~\"$route\", instance=~\"$instance\"}[1m])) by (service,le))",
       "legendFormat": "p90-{{service}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(kong_kong_latency_ms_bucket{cluster_id=~\"$cluster_id\", service=~\"$service\", route=~\"$route\", instance=~\"$instance\"}[1m])) by (service,le))",
       "legendFormat": "p95-{{service}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(kong_kong_latency_ms_bucket{cluster_id=~\"$cluster_id\", service=~\"$service\", route=~\"$route\", instance=~\"$instance\"}[1m])) by (service,le))",
       "legendFormat": "p99-{{service}}"
      }
     ]
    },
    {
     "title": "Kong Proxy Latency per Route",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(kong_kong_latency_ms_bucket{cluster_id=~\"$cluster_id\", service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (route,le))",
       "legendFormat": "p90-{{route}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(kong_kong_latency_ms_bucket{cluster_id=~\"$cluster_id\", service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (route,le))",
       "legendFormat": "p95-{{route}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(kong_kong_latency_ms_bucket{cluster_id=~\"$cluster_id\", service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (route,le))",
       "legendFormat": "p99-{{route}}"
      }
     ]
    },
    {
     "title": "Request Time across all services",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(kong_request_latency_ms_bucket{}[1m])) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(kong_request_latency_ms_bucket{}[1m])) by (le))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(kong_request_latency_ms_bucket{}[1m])) by (le))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Request Time per service",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(kong_request_latency_ms_bucket{cluster_id=~\"$cluster_id\", service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (service,le))",
       "legendFormat": "p90-{{service}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(kong_request_latency_ms_bucket{cluster_id=~\"$cluster_id\", service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (service,le))",
       "legendFormat": "p95-{{service}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(kong_request_latency_ms_bucket{cluster_id=~\"$cluster_id\", service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (service,le))",
       "legendFormat": "p99-{{service}}"
      }
     ]
    },
    {
     "title": "Request Time per Route",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(kong_request_latency_ms_bucket{cluster_id=~\"$cluster_id\", service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (route,le))",
       "legendFormat": "p90-{{route}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(kong_request_latency_ms_bucket{cluster_id=~\"$cluster_id\", service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (route,le))",
       "legendFormat": "p95-{{route}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(kong_request_latency_ms_bucket{cluster_id=~\"$cluster_id\", service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (route,le))",
       "legendFormat": "p99-{{route}}"
      }
     ]
    },
    {
     "title": "Upstream time across all services",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(kong_upstream_latency_ms_bucket{}[1m])) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(kong_upstream_latency_ms_bucket{}[1m])) by (le))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(kong_upstream_latency_ms_bucket{}[1m])) by (le))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Upstream Time across per service",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(kong_upstream_latency_ms_bucket{cluster_id=~\"$cluster_id\", service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (service,le))",
       "legendFormat": "p90-{{service}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(kong_upstream_latency_ms_bucket{cluster_id=~\"$cluster_id\", service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (service,le))",
       "legendFormat": "p95-{{service}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(kong_upstream_latency_ms_bucket{cluster_id=~\"$cluster_id\", service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (service,le))",
       "legendFormat": "p99-{{service}}"
      }
     ]
    },
    {
     "title": "Upstream Time across per Route",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(kong_upstream_latency_ms_bucket{cluster_id=~\"$cluster_id\", service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (route,le))",
       "legendFormat": "p90-{{route}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(kong_upstream_latency_ms_bucket{cluster_id=~\"$cluster_id\", service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (route,le))",
       "legendFormat": "p95-{{route}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(kong_upstream_latency_ms_bucket{cluster_id=~\"$cluster_id\", service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (route,le))",
       "legendFormat": "p99-{{route}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(kong_bandwidth_bytes{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Egress per service/route",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(kong_bandwidth_bytes{cluster_id=~\"$cluster_id\", direction=\"egress\", service =~\"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (service)",
       "legendFormat": "service:{{service}}"
      },
      {
       "expr": "sum(irate(kong_bandwidth_bytes{cluster_id=~\"$cluster_id\", direction=\"egress\", service =~\"$service\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (route)",
       "legendFormat": "route:{{route}}"
      }
     ]
    },
    {
     "title": "Ingress per service/route",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(kong_bandwidth_bytes{cluster_id=~\"$cluster_id\", direction=\"ingress\", service =~\"$service\"}[1m])) by (service)",
       "legendFormat": "{{service}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Caching",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Kong shared memory usage by Node ($instance)",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 4 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(kong_memory_lua_shared_dict_bytes{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}/kong_memory_lua_shared_dict_total_bytes{cluster_id=~\"$cluster_id\", instance=~\"$instance\"})*100",
       "legendFormat": "{{shared_dict}} ({{kong_subsystem}})"
      }
     ]
    },
    {
     "title": "Kong worker Lua VM usage by Node ($instance)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 40 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "kong_memory_workers_lua_vms_bytes{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}",
       "legendFormat": "PID:{{pid}} ({{kong_subsystem}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Upstream",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Healthy status",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "sum(kong_upstream_target_health{cluster_id=~\"$cluster_id\", state=\"healthy\",upstream=~\"$upstream\"}) by (upstream,target,address) * -1  + sum(kong_upstream_target_health{cluster_id=~\"$cluster_id\", state=~\"(unhealthy|dns_error)\",upstream=~\"$upstream\"}) by (upstream,target,address)",
       "legendFormat": "{{upstream}}:{{target}}"
      }
     ]
    },
    {
     "type": "table-old",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "targets": [
      {
       "expr": "sum(\n# map state to a numeric value\n# since grafana doesn't support value mapping yet\n  label_replace(\n    label_replace(\n      label_replace(\n       kong_upstream_target_health{cluster_id=~\"$cluster_id\", upstream=~\"$upstream\"}\n       # healthy is positive number\n       , \"state_value\", \"1\", \"state\", \"healthy\"\n       # healthchecks_off is 0\n      ), \"state_value\", \"0\", \"state\", \"healthchecks_off\"\n      # unhealthy is negative number\n    ), \"state_value\", \"-1\", \"state\", \"(dns_error|unhealthy)\"\n  )\n)\nby (upstream, target, address, state, state_value) > 0"
      }
     ]
    }
   ]
  },
  {
   "title": "Nginx",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Nginx connection state",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kong_nginx_connections_total{cluster_id=~\"$cluster_id\", state=~\"active|reading|writing|waiting\", instance=~\"$instance\"}) by (state)",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Total Connections",
     "type": "stat",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kong_nginx_connections_total{cluster_id=~\"$cluster_id\", state=\"total\", instance=~\"$instance\"})",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Handled Connections",
     "type": "stat",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kong_nginx_connections_total{cluster_id=~\"$cluster_id\", state=\"handled\", instance=~\"$instance\"})",
       "legendFormat": "Handled"
      }
     ]
    },
    {
     "title": "Accepted Connections",
     "type": "stat",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kong_nginx_connections_total{cluster_id=~\"$cluster_id\", state=\"accepted\", instance=~\"$instance\"})",
       "legendFormat": "Accepted"
      }
     ]
    }
   ]
  }
 ]
}