{
 "title": "Managed Apps",
 "tags": [
  "owner:team-honeybadger",
  "topic:workload-cluster"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "catalog",
    "query": "giantswarm,giantswarm-playground"
   }
  ]
 },
 "panels": [
  { "title": "  ", "type": "macropower-analytics-panel", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of app installations",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (aggregation:giantswarm:app_deployed_workload_cluster_total{catalog=~\"$catalog\"})"
    }
   ]
  },
  {
   "title": "Number of apps with an upgrade available",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (aggregation:giantswarm:app_upgrade_available{catalog=~\"$catalog\"})"
    }
   ]
  },
  {
   "title": "About this dashboard",
   "type": "text",
   "gridPos": { "h": 8, "w": 11, "x": 8, "y": 1 },
   "options": {
    "content": "This dashboard shows installations of managed apps in your workload clusters.\n\nApps are listed by app type and version. Also shown is the upstream chart version. E.g. version 2.2.1 of the Loki app installs version 0.33.0 of Loki\n\nLastly installations of managed apps with an upgrade available are shown.\nPlease check the changelog for the app before upgrading in case there are breaking changes."
   }
  },
  {
   "title": "Installations per app type",
   "type": "table",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(aggregation:giantswarm:app_deployed_workload_cluster_total{catalog=~\"$catalog\"}) by (app)"
    }
   ]
  },
  {
   "title": "Installations per app type and version",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(aggregation:giantswarm:app_deployed_workload_cluster_total{catalog=~\"$catalog\"}) by (app, app_version, catalog, version)"
    }
   ]
  },
  {
   "title": "Installations with an upgrade available",
   "type": "table",
   "description": "If an app is installed in a cluster multiple times this is shown in the app count column.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum by (app, catalog, latest_version, namespace, version) (aggregation:giantswarm:app_upgrade_available{catalog=~\"$catalog\"})"
    }
   ]
  }
 ]
}