{
 "title": "Network Traffic Analysis",
 "tags": [
  "owner:team-atlas",
  "topic:networking"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "cluster_id",
    "label": "cluster_id",
    "query": {
     "query": "label_values(kubernetes_build_info,cluster_id)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_namespace_created{cluster_id=\"$cluster_id\"},namespace)"
    }
   },
   {
    "name": "private_subnets",
    "query": "(10\\..*|100\\.(1[0-9][0-9]|[6-9][0-9]|[1-9])\\..*|172\\.(1[6-9]|2[0-9]|3[01])\\..*|192\\.168\\..*)"
   }
  ]
 },
 "panels": [
  { "title": "Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "# Data availability\n\nThis dashboard relies on optional metrics.\nWe need to enable network monitoring at the installation level and on each cluster for the metrics to be available.\nPlease contact team Atlas for more information."
   }
  },
  { "title": "${cluster_id} cluster traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Private Traffic vs. Public Traffic",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 22 }
   ]
  },
  {
   "title": "Top Private Network Users",
   "type": "table",
   "gridPos": { "h": 10, "w": 7, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sort(\n  sum by (k8s_src_namespace, cluster_id) (\n    rate(\n      beyla_network_flow_bytes_total{\n        dst_address=~\"^$private_subnets\",\n        dst_zone=\"\",\n        direction=\"request\",\n        k8s_src_namespace=~\"$namespace\",\n        cluster_id=\"${cluster_id}\"\n      }[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "{{k8s_src_namespace}}"
    },
    {
     "expr": "sort(\n  sum by (k8s_src_namespace, cluster_id) (\n    rate(\n      beyla_network_flow_bytes_total{\n        dst_address!~\"^$private_subnets\",\n        direction=\"request\",\n        k8s_src_namespace=~\"$namespace\",\n        cluster_id=\"${cluster_id}\"\n      }[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Cross-AZ Network Users",
   "type": "table",
   "gridPos": { "h": 10, "w": 7, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sort(\n  sum by (k8s_src_namespace, cluster_id) (\n    rate(\n      beyla_network_flow_bytes_total{\n        dst_address=~\"^$private_subnets\",\n        direction=\"request\",\n        src_zone!=\"\",\n        dst_zone!=\"\",\n        k8s_src_namespace=~\"$namespace\",\n        cluster_id=\"${cluster_id}\"\n      }[$__rate_interval]\n    )\n    unless on (dst_zone, src_zone)\n      label_replace(beyla_network_flow_bytes_total{src_zone!=\"\", dst_zone!=\"\"},\n        \"dst_zone\", \"$1\", \"src_zone\", \"(.*)\")\n  )\n)",
     "legendFormat": "{{k8s_src_namespace}}"
    },
    {
     "expr": "sort(\n  sum by (k8s_src_namespace, cluster_id) (\n    rate(\n      beyla_network_flow_bytes_total{\n        dst_address=~\"^$private_subnets\",\n        direction=\"request\",\n        src_zone!=\"\",\n        dst_zone!=\"\",\n        k8s_src_namespace=~\"$namespace\",\n        cluster_id=\"${cluster_id}\"\n      }[$__rate_interval]\n    )\n    and on (dst_zone, src_zone)\n      label_replace(beyla_network_flow_bytes_total{src_zone!=\"\", dst_zone!=\"\"},\n        \"dst_zone\", \"$1\", \"src_zone\", \"(.*)\")\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Public Network Users",
   "type": "table",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    { "panelId": 22 }
   ]
  },
  {
   "title": "Cross-AZ vs. In-AZ",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 24 }
   ]
  },
  {
   "title": "Top 10 Private known destination",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (dst_name, cluster_id) (\n  rate(\n    beyla_network_flow_bytes_total{\n      dst_address=~\"^$private_subnets\",\n      dst_zone=\"\",\n      dst_name!=\"\",\n      direction=\"request\",\n      k8s_src_namespace=~\"$namespace\",\n      cluster_id=\"${cluster_id}\"\n    }[$__rate_interval]\n  )\n))",
     "legendFormat": "{{ dst_name }}"
    }
   ]
  },
  {
   "title": "Top 10 Public known destination",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (dst_name, cluster_id) (\n  rate(\n    beyla_network_flow_bytes_total{\n      dst_address!~\"^$private_subnets\",\n      dst_name!=\"\",\n      direction=\"request\",\n      k8s_src_namespace=~\"$namespace\",\n      cluster_id=\"${cluster_id}\"\n    }[$__rate_interval]\n  )\n))",
     "legendFormat": "{{ dst_name }}"
    }
   ]
  },
  {
   "title": "Total Public Traffic",
   "type": "timeseries",
   "description": "Displays the total bytes sent for public traffic.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    { "panelId": 22 }
   ]
  },
  {
   "title": "Total Private Traffic",
   "type": "timeseries",
   "description": "Displays the total bytes sent for public traffic.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    { "panelId": 22 }
   ]
  },
  {
   "title": "Total In-AZ Private Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    { "panelId": 24 }
   ]
  },
  {
   "title": "Total Cross-AZ Private Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    { "panelId": 24 }
   ]
  }
 ]
}