{
 "title": "Network Traffic Analysis - Overview",
 "tags": [
  "topic:networking-traffic-analysis",
  "owner:team-atlas",
  "topic:networking",
  "managed-by: observability-operator"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "cluster_id",
    "label": "cluster_id",
    "query": {
     "query": "label_values(kubernetes_build_info,cluster_id)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_namespace_created{cluster_id=\"$cluster_id\"},namespace)"
    }
   },
   {
    "name": "time_period",
    "label": "Time Period (data transfer only)",
    "query": "10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "# Data availability\n\nThis dashboard relies on optional network metrics.\nNetwork metrics can be enable on a per cluster basis, see our tutorial at https://docs.giantswarm.io/tutorials/observability/network-monitoring/. Please contact team Atlas for more information.\n\n# Information\n\nThis dashboard only visualizes data for network traffic coming from a identified namespace(s) (usually Pods) over a long period of time. Traffic outside namespace is ignored (e.g. Node, AWS resolver, load balancer). For a detailed view use the **Network Traffic Analysis** dashboard. "
   }
  },
  {
   "title": "${cluster_id} network traffic for ${namespace} namespace(s)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }
  },
  {
   "title": "Total Data Transferred Per Day",
   "type": "barchart",
   "description": "Total bytes transferred each day, broken down by source namespace",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (k8s_src_namespace) (network_traffic_analysis:beyla_network_flow_bytes_public:rate5m{cluster_id=~\"$cluster_id\", k8s_src_namespace=~\"$namespace\"}) * $__interval_ms / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Data Transferred Per Day",
   "type": "barchart",
   "description": "Total bytes transferred each day, broken down by source namespace",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (k8s_src_namespace) (network_traffic_analysis:beyla_network_flow_bytes_cross_az:rate5m{cluster_id=~\"$cluster_id\", k8s_src_namespace=~\"$namespace\"}) * $__interval_ms / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Public network traffic",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (k8s_src_namespace, cluster_id) (\n  avg_over_time(\n    network_traffic_analysis:beyla_network_flow_bytes_public:rate5m{\n      k8s_src_namespace=~\"$namespace\",\n      cluster_id=\"$cluster_id\"\n    }[$__interval * 20]\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average  Cross-AZ network traffic",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (k8s_src_namespace, cluster_id) (\n  avg_over_time(\n    network_traffic_analysis:beyla_network_flow_bytes_cross_az:rate5m{\n      k8s_src_namespace=~\"$namespace\",\n      cluster_id=\"${cluster_id}\"\n    }[$__interval * 20]\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Public Traffic",
   "type": "timeseries",
   "description": "Displays the total bytes sent for public traffic.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (k8s_src_namespace, cluster_id) (\n  avg_over_time(\n    network_traffic_analysis:beyla_network_flow_bytes_public:rate5m{\n      k8s_src_namespace=~\"$namespace\",\n      cluster_id=\"$cluster_id\"\n    }[$__interval * 20]\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Cross-AZ Private Traffic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (k8s_src_namespace, cluster_id) (\n  avg_over_time(\n    network_traffic_analysis:beyla_network_flow_bytes_cross_az:rate5m{\n      k8s_src_namespace=~\"$namespace\",\n      cluster_id=\"${cluster_id}\"\n    }[$__interval * 20]\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}