{
 "title": "Pod request vs usage",
 "tags": [
  "owner:team-atlas",
  "topic:resource-usage"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(up{app=\"kube-state-metrics\"}, cluster_id)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{app=\"kube-state-metrics\", cluster_id=\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{cluster_id=\"$cluster\", namespace=~\"$namespace\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Top10 lowest % of used CPU over requests",
   "type": "bargauge",
   "description": "10% means avg usage is 1/10th of reserved resources.\n1000% means avg usage is 10x more than reserved resources.\nShows the 10 lowest ones, to spot wasted resources.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sort(\n    bottomk(10,\n    sum(\n        label_replace(\n            avg_over_time(\n                node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster_id=\"$cluster\", namespace=\"$namespace\", pod=~\"($container).*\"}[$__range]\n                ),\"shortpod\",\"$1\",\"pod\",\"(.*)-.*\"\n            )\n        ) by (shortpod)\n     /\n     max(\n        label_replace(\n            cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{cluster_id=\"$cluster\", namespace=\"$namespace\", pod=~\"($container).*\"}\n            ,\"shortpod\",\"$1\",\"pod\",\"(.*)-.*\"\n        )\n    ) by (shortpod)\n*100)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top10 lowest % of used memory over requests",
   "type": "bargauge",
   "description": "10% means avg usage is 1/10th of reserved resources.\n1000% means avg usage is 10x more than reserved resources.\nShows the 10 lowest ones, to spot wasted resources.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sort(\n    bottomk(10,\n        max(\n            label_replace(\n                avg_over_time(\n                    container_memory_working_set_bytes{app=\"cadvisor\", cluster_id=\"$cluster\", namespace=\"$namespace\",container!=\"\", image!=\"\", pod=~\"($container).*\"}[$__range]\n                ),\"shortpod\",\"$1\",\"pod\",\"(.*)-.*\"\n            )\n        ) by (shortpod)\n        /\n        max(\n            label_replace(\n                cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{cluster_id=\"$cluster\", namespace=\"$namespace\", pod=~\"($container).*\"}\n                ,\"shortpod\",\"$1\",\"pod\",\"(.*)-.*\"\n            )\n        ) by (shortpod)\n    *100)\n)",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "CPU request vs usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(label_replace(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{cluster_id=\"$cluster\", namespace=\"$namespace\", pod=~\"($container).*\"},\"shortpod\",\"$1\",\"pod\",\"(.*)-.*\")) by (shortpod)",
     "legendFormat": "request for {{shortpod}}"
    },
    {
     "expr": "max(label_replace(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster_id=\"$cluster\", namespace=\"$namespace\", pod=~\"($container).*\"},\"shortpod\",\"$1\",\"pod\",\"(.*)-.*\")) by (shortpod)",
     "legendFormat": "usage for {{shortpod}}"
    }
   ]
  },
  {
   "title": "Memory request vs usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(label_replace(cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{cluster_id=\"$cluster\", namespace=\"$namespace\", pod=~\"($container).*\"},\"shortpod\",\"$1\",\"pod\",\"(.*)-.*\")) by (shortpod)",
     "legendFormat": "request for {{shortpod}}"
    },
    {
     "expr": "max(label_replace(container_memory_working_set_bytes{app=\"cadvisor\", cluster_id=\"$cluster\", namespace=\"$namespace\",container!=\"\", image!=\"\", pod=~\"($container).*\"},\"shortpod\",\"$1\",\"pod\",\"(.*)-.*\")) by (shortpod)",
     "legendFormat": "usage for {{shortpod}}"
    }
   ]
  }
 ]
}