{
 "title": "Policy Enforcement (PSS) Status",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster_id",
    "label": "Cluster",
    "query": {
     "query": "label_values(dipstick_policyreport_policy_summary,cluster_id)"
    }
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Note",
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Policy Status Overview\n\nThis dashboard shows aggregate policy status information for the attached workload clusters.\n\nOnly Giant Swarm-managed policies in clusters using managed security tooling are supported.\n\nAdditional information about policy enforcement is available [in our public documentation](https://docs.giantswarm.io/advanced/security/security-policy-enforcement/)."
   }
  },
  {
   "title": "Failing Policies by Cluster",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(dipstick_policyreport_policy_summary{result=\"fail\"}) by (cluster_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failures per Policy",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum(dipstick_policyreport_policy_summary{result=\"fail\"}) by (policy_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Compliance by Cluster",
   "type": "gauge",
   "description": "Percentage of policies with \"pass\" or \"skip\" (exempt) status.",
   "gridPos": { "h": 27, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(dipstick_policyreport_policy_summary{result=~\"pass|skip\"}) by (cluster_id) / sum(dipstick_policyreport_policy_summary{}) by (cluster_id) * 100)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}