{
 "title": "Prometheus / Availability",
 "description": "Availability stats for Prometheus",
 "tags": [
  "owner:team-atlas",
  "topic:observability",
  "component:prometheus"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{container=\"prometheus\",cluster_type=~\"management_cluster\", pod=~\".*prometheus.*\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Pod status readiness", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Prometheus availability over period",
   "type": "bargauge",
   "description": "Prometheus availability\n\nOnly takes into account time when there's data for this pod (either `ready`, `not ready` or `unknown`.",
   "gridPos": { "h": 19, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(kube_pod_status_ready{namespace=~\"(${cluster})-prometheus\", condition=\"true\"}[$__range])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Prometheus availability per hour",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time(kube_pod_status_ready{namespace=~\"(${cluster})-prometheus\", condition=\"true\"}[1h])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Prometheus status",
   "type": "timeseries",
   "description": "When was prometheus ready?",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "expr": "kube_pod_status_ready{namespace=~\"(${cluster})-prometheus\", condition=\"true\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}