{
 "title": "Prometheus / Remote Write",
 "tags": [
  "prometheus-mixin",
  "owner:team-atlas"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "60s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(kube_pod_container_info{image=~\".*prometheus.*\"}, cluster_id)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(prometheus_build_info, instance)"
   },
   {
    "name": "url",
    "label": "URL",
    "query": "label_values(prometheus_remote_storage_shards{cluster_id=~\"$cluster\", instance=~\"$instance\"}, url)"
   }
  ]
 },
 "panels": [
  { "title": "nginx", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ingress traffic and success rate",
   "type": "timeseries",
   "description": "* success %: errors / success rate\n* rps: requests per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{\n    cluster_type=~\"management_cluster\",\n   ingress=~\"prometheus-($cluster)-remote-write\",\n    status!~\"[4-5].*\"}[$__rate_interval]\n)) by (ingress, host, path, method) / \nsum(rate(nginx_ingress_controller_requests{\n    cluster_type=~\"management_cluster\",\n    ingress=~\"prometheus-($cluster)-remote-write\"}[$__rate_interval]\n)) by (ingress, host, path, method)",
     "legendFormat": "success % {{ingress}} - {{status}} for {{method}} {{host}}{{path}}"
    },
    {
     "expr": "sum(irate(nginx_ingress_controller_requests{\n    cluster_type=~\"management_cluster\",\n   ingress=~\"prometheus-($cluster)-remote-write\"}[$__rate_interval]\n)) by (ingress, host, path, method)",
     "legendFormat": "rps {{ingress}} - {{status}} for {{method}} {{host}}{{path}}"
    }
   ]
  },
  {
   "title": "Ingress error codes",
   "type": "timeseries",
   "description": "Status codes different than 2xx",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(nginx_ingress_controller_requests{\n    cluster_type=~\"management_cluster\",\n    ingress=~\"prometheus-($cluster)-remote-write\",\n    status!~\"[2].*\"}[$__rate_interval]\n)) by (ingress, host, path, method, status)",
     "legendFormat": "{{ingress}} - {{status}} for {{method}} {{host}}{{path}}"
    }
   ]
  },
  {
   "title": "Timestamps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Highest Timestamp In vs. Highest Timestamp Sent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(\n  prometheus_remote_storage_highest_timestamp_in_seconds{cluster_id=~\"$cluster\", instance=~\"$instance\"} \n-  \n  ignoring(remote_name, url) group_right(instance) (prometheus_remote_storage_queue_highest_sent_timestamp_seconds{cluster_id=~\"$cluster\", instance=~\"$instance\", url=~\"$url\"} != 0)\n)\n",
     "legendFormat": "{{cluster_id}}:{{instance}} {{remote_name}}:{{url}}"
    }
   ]
  },
  {
   "title": "Rate[5m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "clamp_min(\n  rate(prometheus_remote_storage_highest_timestamp_in_seconds{cluster_id=~\"$cluster\", instance=~\"$instance\"}[5m])  \n- \n  ignoring (remote_name, url) group_right(instance) rate(prometheus_remote_storage_queue_highest_sent_timestamp_seconds{cluster_id=~\"$cluster\", instance=~\"$instance\", url=~\"$url\"}[5m])\n, 0)\n",
     "legendFormat": "{{cluster_id}}:{{instance}} {{remote_name}}:{{url}}"
    }
   ]
  },
  {
   "title": "Samples",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate, in vs. succeeded or dropped [5m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(\n  prometheus_remote_storage_samples_in_total{cluster_id=~\"$cluster\", instance=~\"$instance\"}[5m])\n- \n  ignoring(remote_name, url) group_right(instance) (rate(prometheus_remote_storage_succeeded_samples_total{cluster_id=~\"$cluster\", instance=~\"$instance\", url=~\"$url\"}[5m]) or rate(prometheus_remote_storage_samples_total{cluster_id=~\"$cluster\", instance=~\"$instance\", url=~\"$url\"}[5m]))\n- \n  (rate(prometheus_remote_storage_dropped_samples_total{cluster_id=~\"$cluster\", instance=~\"$instance\", url=~\"$url\"}[5m]) or rate(prometheus_remote_storage_samples_dropped_total{cluster_id=~\"$cluster\", instance=~\"$instance\", url=~\"$url\"}[5m]))\n",
     "legendFormat": "{{cluster_id}}:{{instance}} {{remote_name}}:{{url}}"
    }
   ]
  },
  {
   "title": "Shards",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Current Shards",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_remote_storage_shards{cluster_id=~\"$cluster\", instance=~\"$instance\", url=~\"$url\"}",
     "legendFormat": "{{cluster_id}}:{{instance}} {{remote_name}}:{{url}}"
    }
   ]
  },
  {
   "title": "Max Shards",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_remote_storage_shards_max{cluster_id=~\"$cluster\", instance=~\"$instance\", url=~\"$url\"}",
     "legendFormat": "{{cluster_id}}:{{instance}} {{remote_name}}:{{url}}"
    }
   ]
  },
  {
   "title": "Min Shards",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_remote_storage_shards_min{cluster_id=~\"$cluster\", instance=~\"$instance\", url=~\"$url\"}",
     "legendFormat": "{{cluster_id}}:{{instance}} {{remote_name}}:{{url}}"
    }
   ]
  },
  {
   "title": "Desired Shards",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_remote_storage_shards_desired{cluster_id=~\"$cluster\", instance=~\"$instance\", url=~\"$url\"}",
     "legendFormat": "{{cluster_id}}:{{instance}} {{remote_name}}:{{url}}"
    }
   ]
  },
  {
   "title": "Shard Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Shard Capacity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_remote_storage_shard_capacity{cluster_id=~\"$cluster\", instance=~\"$instance\", url=~\"$url\"}",
     "legendFormat": "{{cluster_id}}:{{instance}} {{remote_name}}:{{url}}"
    }
   ]
  },
  {
   "title": "Pending Samples",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_remote_storage_pending_samples{cluster_id=~\"$cluster\", instance=~\"$instance\", url=~\"$url\"} or prometheus_remote_storage_samples_pending{cluster_id=~\"$cluster\", instance=~\"$instance\", url=~\"$url\"}",
     "legendFormat": "{{cluster_id}}:{{instance}} {{remote_name}}:{{url}}"
    }
   ]
  },
  {
   "title": "Segments",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {}
   ]
  },
  {
   "title": "TSDB Current Segment",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "prometheus_tsdb_wal_segment_current{cluster_id=~\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "{{cluster_id}}:{{instance}}"
    }
   ]
  },
  {
   "title": "Remote Write Current Segment",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "prometheus_wal_watcher_current_segment{cluster_id=~\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "{{cluster_id}}:{{instance}} {{consumer}}"
    }
   ]
  },
  {
   "title": "Misc. Rates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Dropped Samples",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_remote_storage_dropped_samples_total{cluster_id=~\"$cluster\", instance=~\"$instance\"}[5m]) or rate(prometheus_remote_storage_samples_dropped_total{cluster_id=~\"$cluster\", instance=~\"$instance\", url=~\"$url\"}[5m])",
     "legendFormat": "{{cluster_id}}:{{instance}} {{remote_name}}:{{url}}"
    }
   ]
  },
  {
   "title": "Failed Samples",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_remote_storage_failed_samples_total{cluster_id=~\"$cluster\", instance=~\"$instance\", url=~\"$url\"}[5m]) or rate(prometheus_remote_storage_samples_failed_total{cluster_id=~\"$cluster\", instance=~\"$instance\", url=~\"$url\"}[5m])",
     "legendFormat": "{{cluster_id}}:{{instance}} {{remote_name}}:{{url}}"
    }
   ]
  },
  {
   "title": "Retried Samples",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_remote_storage_retried_samples_total{cluster_id=~\"$cluster\", instance=~\"$instance\", url=~\"$url\"}[5m]) or rate(prometheus_remote_storage_samples_retried_total{cluster_id=~\"$cluster\", instance=~\"$instance\", url=~\"$url\"}[5m])",
     "legendFormat": "{{cluster_id}}:{{instance}} {{remote_name}}:{{url}}"
    }
   ]
  },
  {
   "title": "Enqueue Retries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_remote_storage_enqueue_retries_total{cluster_id=~\"$cluster\", instance=~\"$instance\", url=~\"$url\"}[5m])",
     "legendFormat": "{{cluster_id}}:{{instance}} {{remote_name}}:{{url}}"
    }
   ]
  }
 ]
}