{
 "title": "ServiceMonitors Overview",
 "description": "ServiceMonitors Overview: rank servicemonitors by number of metrics, churn...",
 "tags": [
  "topic:observability",
  "owner:team-atlas",
  "component:prometheus-agent",
  "servicemonitor",
  "podmonitor",
  "scraping"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{container=\"prometheus\"},cluster_id)"
    }
   },
   {
    "name": "team",
    "query": {
     "query": "label_values(scrape_samples_scraped{cluster_id=~\"$cluster\"},team)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(scrape_samples_scraped{cluster_id=~\"$cluster\", team=~\"$team\"},job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Help", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Help",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "This dashboard helps you understanding your `servicemonitors` and `podmonitors`.\n\n* Jobs named `xxxxx-prometheus-0/[target]` are scraped by prometheus on the Management Cluster via static targets.\n* The other jobs are scraped by `prometheus-agent` on the Workload Cluster via `servicemonitors` or `podmonitors`."
   }
  },
  { "title": "Agent pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Agent metrics per pod",
   "type": "timeseries",
   "description": "RAM estimation based on the ratio of series / total Prometheus RAM usage",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(prometheus_remote_write_wal_storage_active_series{cluster_id=~\"$cluster\"}) by (cluster_id, pod)",
     "legendFormat": "{{cluster_id}} / {{pod}}"
    },
    {
     "expr": "prometheus_agent_active_series{cluster_id=~\"$cluster\"}",
     "legendFormat": "{{cluster_id}} / {{pod}} (prometheus-agent)"
    }
   ]
  },
  {
   "title": "Agent RAM per pod",
   "type": "timeseries",
   "description": "RAM estimation based on the ratio of series / total Prometheus RAM usage",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (cluster_id,pod) (container_memory_rss{cluster_id=\"$cluster\", pod=~\".*alloy-metrics.*\", container=~\".+\"})",
     "legendFormat": "{{cluster_id}} / {{pod}}"
    },
    {
     "expr": "sum by (cluster_id,pod) (container_memory_rss{cluster_id=\"$cluster\", pod=~\".*prometheus-agent.*\", container=~\".+\"})",
     "legendFormat": "{{cluster_id}} / {{pod}} (prometheus-agent)"
    }
   ]
  },
  {
   "title": "Number of agent pods",
   "type": "timeseries",
   "description": "RAM estimation based on the ratio of series / total Prometheus RAM usage",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(prometheus_remote_write_wal_storage_active_series{cluster_id=~\"$cluster\"}) by (cluster_id)",
     "legendFormat": "{{cluster_id}}"
    },
    {
     "expr": "count(prometheus_remote_write_wal_storage_active_series{cluster_id=~\"$cluster\"}) by (cluster_id)",
     "legendFormat": "{{cluster_id}} (prometheus-agent)"
    }
   ]
  },
  { "title": "Scraping targets metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Samples scraped per servicemonitor",
   "type": "timeseries",
   "description": "The number of samples per target (servicemonitor or podmonitor) remaining after metric relabeling was applied.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(scrape_samples_post_metric_relabeling{cluster_id=~\"$cluster\", job=~\"$job\"}) by (job, cluster_id)",
     "legendFormat": "Job: {{job}} / Cluster: {{cluster_id}}"
    }
   ]
  },
  {
   "title": "Prometheus RAM usage estimation per servicemonitor",
   "type": "timeseries",
   "description": "RAM estimation based on the ratio of series / total Prometheus RAM usage",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "giantswarm:observability:monitoring:resource_usage_estimation:memory_usage_bytes{cluster_id=~\"$cluster\", job=~\"$job\"}",
     "legendFormat": "Job: {{job}} / Cluster: {{cluster_id}}"
    }
   ]
  },
  {
   "title": "Churn per job",
   "type": "timeseries",
   "description": "The approximate number of new series added when scraping.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(max_over_time(scrape_series_added{cluster_id=~\"$cluster\", job=~\"$job\"}[$__interval])) by (cluster_id, job)",
     "legendFormat": "Job: {{job}} / Cluster: {{cluster_id}}"
    }
   ]
  },
  {
   "title": "Samples discarded per servicemonitor",
   "type": "timeseries",
   "description": "The number of samples discarded by relabeling.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(scrape_samples_scraped{cluster_id=~\"$cluster\", job=~\"$job\"} - scrape_samples_post_metric_relabeling{cluster_id=~\"$cluster\", job=~\"$job\"}) by (job, cluster_id)",
     "legendFormat": "Job: {{job}} / Cluster: {{cluster_id}}"
    }
   ]
  },
  {
   "title": "Scrape duration",
   "type": "timeseries",
   "description": "Duration of the scrape. Is the sum of all targets for one job on a cluster.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "sum(scrape_duration_seconds{cluster_id=~\"$cluster\", job=~\"$job\"}) by (cluster_id, job)",
     "legendFormat": "Job: {{job}} / Cluster: {{cluster_id}}"
    }
   ]
  }
 ]
}