{
 "title": "Webhooks Performance",
 "tags": [
  "provider:aws",
  "topic:workload-cluster",
  "owner:team-phoenix"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "organization",
    "label": "Organization",
    "query": {
     "query": "label_values(kubernetes_build_info, organization)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kubernetes_build_info{organization=\"$organization\"}, cluster_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(apiserver_admission_webhook_rejection_count{organization=\"$organization\", cluster_id=\"$cluster\"}[5m])",
     "legendFormat": "{{error_type}} - {{name}}"
    }
   ]
  },
  {
   "title": "Webhook Queries per Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (name, operation) (rate(apiserver_admission_webhook_admission_duration_seconds_count{organization=\"$organization\", cluster_id=\"$cluster\"}[5m]))",
     "legendFormat": "{{operation}} {{name}}"
    }
   ]
  },
  {
   "title": "Admission Duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(apiserver_admission_webhook_admission_duration_seconds_bucket{organization=\"$organization\", cluster_id=\"$cluster\"}[$__rate_interval])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_admission_webhook_admission_duration_seconds_bucket{organization=\"$organization\", cluster_id=\"$cluster\"}[$__rate_interval])) by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(apiserver_admission_webhook_admission_duration_seconds_bucket{organization=\"$organization\", cluster_id=\"$cluster\"}[$__rate_interval])) by (le))",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Admission Duration By Webhook",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum (irate(apiserver_admission_webhook_admission_duration_seconds_bucket{organization=\"$organization\", cluster_id=\"$cluster\"}[15m])) by (name, operation, le))",
     "legendFormat": "P95 {{operation}} {{name}}"
    }
   ]
  }
 ]
}