{
 "title": "Loki / Cost Estimation",
 "tags": [
  "owner:team-atlas",
  "topic:observability",
  "component:loki"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(alloy_build_info,cluster_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Explanation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Explanation",
   "type": "text",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "This dashboard is a tool to estimate the cost of Loki.\n\n`loki` is deployed on the management cluster and `alloy` is deployed on each workload cluster and on the management cluster as well.\n\n`alloy` sends the logs to `loki` and `loki` sends the data on `S3`.\n\nTo evaluate the real cost of `loki`, we need to take in account:\n- CPU and memory used by all loki pods\n- data sent by all alloy on workload clusters to loki\n- data sent on S3\n\n\nOnly the traffic between EC2 instances and Internet has a cost. <br/>\nTo estimate the global cost of the traffic for `loki`, we have to mesure the traffic between `alloy` pods on workload clusters and `loki` on the management cluster.<br/>\nThe traffic between `alloy` pods on the management cluster and `loki` is free.\n\nTotal of bytes stored on S3 is estimated from data sent to S3. Hence, we are not aware of data cleaning.\n\n`cluster` selection allows you to know:\n- how much traffic is transmitted between selected clusters and Loki\n- how many targets are scraped on the selected clusters"
   }
  },
  { "title": "Resource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "description": "request => indicates how much CPU is reserved for Loki\n\nusage => indicates how much CPU is used by Loki",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{container=\"loki\", resource=\"cpu\"})",
     "legendFormat": "request for all pods"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"loki\"}[$__rate_interval]))",
     "legendFormat": "usage for all pods"
    },
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{container=\"loki\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "description": "request => indicates how much memory is reserved for Loki\n\nusage => indicates how much memory is used by Loki",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{container=\"loki\", resource=\"memory\"})",
     "legendFormat": "request for all pods"
    },
    {
     "expr": "sum(rate(container_memory_usage_bytes{container=\"loki\"}[$__rate_interval]))",
     "legendFormat": "usage for all pods"
    },
    {
     "expr": "sum by (pod) (rate(container_memory_usage_bytes{container=\"loki\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Total of bytes sent on S3",
   "type": "stat",
   "description": "Total of bytes sent on S3 over the selected period",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (tenant) (increase(loki_ingester_chunk_stored_bytes_total[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "bytes sent on S3",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (tenant) (increase(loki_ingester_chunk_stored_bytes_total[$__interval]))",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Total of bytes transmitted over the network",
   "type": "stat",
   "description": "Total of bytes transmitted over the network over the selected period.\n\nThe first series displays the total bytes sent by the selected cluster(s) to Loki over the selected period.\n\nThe second series displays the total bytes sent by workload clusters to Loki over the selected period that need to be paid.\n",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(sum by (cluster_id) (increase(loki_write_sent_bytes_total{namespace=\"kube-system\", cluster_id=~\"$cluster\"}[$__interval])))",
     "legendFormat": "Selected cluster(s) traffic"
    },
    {
     "expr": "sum(sum by (cluster_id) (increase(loki_write_sent_bytes_total{namespace=\"kube-system\", cluster_id=~\"$cluster\", cluster_type=\"workload_cluster\"}[$__interval])))",
     "legendFormat": "Cost traffic"
    }
   ]
  },
  {
   "title": "bytes transmitted over the network",
   "type": "timeseries",
   "description": "All the traffic sent by Alloy to Loki in bytes.\n\nThe first series displays the total bytes sent by the selected cluster(s) to Loki.\n\nThe second series displays the total bytes sent by workload clusters to Loki that need to be paid.",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(sum by (cluster_id) (increase(loki_write_sent_bytes_total{namespace=\"kube-system\", cluster_id=~\"$cluster\"}[$__interval])))",
     "legendFormat": "Selected cluster(s) traffic"
    },
    {
     "expr": "sum(sum by (cluster_id) (increase(loki_write_sent_bytes_total{namespace=\"kube-system\", cluster_id=~\"$cluster\", cluster_type=\"workload_cluster\"}[$__interval])))",
     "legendFormat": "Cost traffic"
    }
   ]
  },
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Number of Logs received by Loki over the selected period",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (tenant) (increase(loki_distributor_lines_received_total[$__interval]))",
     "legendFormat": "{{tenant}}"
    }
   ]
  }
 ]
}