{
 "title": "Strimzi Kafka Exporter",
 "description": "Kafka topics and consumer groups",
 "tags": [
  "Kafka",
  "Kafka Exporter",
  "Strimzi",
  "component:strimzi-kafka-exporter",
  "owner:team-atlas",
  "topic:kafka"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "cluster_id", "label": "Cluster", "query": { "query": "label_values(cluster_id)" } },
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "kubernetes_namespace",
    "label": "Namespace",
    "query": "query_result(kafka_broker_info{cluster_id=\"$cluster_id\"})"
   },
   {
    "name": "strimzi_cluster_name",
    "label": "Kafka Cluster",
    "query": "query_result(kafka_broker_info{cluster_id=\"$cluster_id\",namespace=\"$kubernetes_namespace\"})"
   },
   {
    "name": "consumergroup",
    "label": "Consumer Group",
    "query": "label_values(kafka_consumergroup_current_offset{cluster_id=\"$cluster_id\",namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\"}, consumergroup)"
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": "label_values(kafka_topic_partition_current_offset{cluster_id=\"$cluster_id\",namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\"}, topic)"
   }
  ]
 },
 "panels": [
  {
   "title": "Topics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kafka_topic_partitions{cluster_id=\"$cluster_id\",topic=~\"$topic\", namespace=~\"$kubernetes_namespace\"})"
    }
   ]
  },
  {
   "title": "Partitions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_topic_partitions{cluster_id=\"$cluster_id\",topic=~\"$topic\", namespace=~\"$kubernetes_namespace\"})"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_replicas{cluster_id=\"$cluster_id\",topic=~\"$topic\", namespace=\"$kubernetes_namespace\"})"
    }
   ]
  },
  {
   "title": "In Sync Replicas",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_in_sync_replica{cluster_id=\"$cluster_id\",topic=~\"$topic\", namespace=~\"$kubernetes_namespace\"})"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_under_replicated_partition{cluster_id=\"$cluster_id\",topic=~\"$topic\", namespace=~\"$kubernetes_namespace\"})"
    }
   ]
  },
  {
   "title": "Partitions at minimum ISR",
   "type": "stat",
   "description": "Number of partitions which are at their minimum in sync replica count (| ISR | == | min.insync.replicas |)",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_cluster_partition_atminisr{cluster_id=\"$cluster_id\",topic=~\"$topic\", namespace=~\"$kubernetes_namespace\"})"
    }
   ]
  },
  {
   "title": "Partitions under minimum ISR",
   "type": "stat",
   "description": "Number of partitions which are under their minimum in sync replica count (| ISR | < | min.insync.replicas |)",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_cluster_partition_underminisr{cluster_id=\"$cluster_id\",topic=~\"$topic\", namespace=~\"$kubernetes_namespace\"})"
    }
   ]
  },
  {
   "title": "Partitions not on preferred node",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_leader_is_preferred{cluster_id=\"$cluster_id\",topic=~\"$topic\", namespace=~\"$kubernetes_namespace\"} < bool 1)"
    }
   ]
  },
  {
   "title": "Messages in per second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_topic_partition_current_offset{cluster_id=\"$cluster_id\",topic=~\"$topic\", namespace=~\"$kubernetes_namespace\"}[5m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Messages consumed per second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(delta(kafka_consumergroup_current_offset{cluster_id=\"$cluster_id\",consumergroup=~\"$consumergroup\",topic=~\"$topic\", namespace=~\"$kubernetes_namespace\"}[5m])/300) by (consumergroup, topic)",
     "legendFormat": "{{consumergroup}} (topic: {{topic}})"
    }
   ]
  },
  {
   "title": "Lag by  Consumer Group",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{cluster_id=\"$cluster_id\",consumergroup=~\"$consumergroup\",topic=~\"$topic\", namespace=~\"$kubernetes_namespace\"}) by (consumergroup, topic) ",
     "legendFormat": "{{consumergroup}} (topic: {{topic}})"
    }
   ]
  },
  {
   "title": "Consumer Group Offsets",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_current_offset{cluster_id=\"$cluster_id\",consumergroup=~\"$consumergroup\",topic=~\"$topic\", namespace=~\"$kubernetes_namespace\"}) by (consumergroup,partition,topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Consumer Group Lag",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{cluster_id=\"$cluster_id\",consumergroup=~\"$consumergroup\",topic=~\"$topic\", namespace=~\"$kubernetes_namespace\"}) by (consumergroup,partition,topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Number of Partitions",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(kafka_topic_partitions{cluster_id=\"$cluster_id\",topic=~\"$topic\", namespace=~\"$kubernetes_namespace\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Latest Offsets",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 24 },
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_current_offset{cluster_id=\"$cluster_id\",topic=~\"$topic\", namespace=~\"$kubernetes_namespace\"}) by (partition,topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Oldest Offsets",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 24 },
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_oldest_offset{cluster_id=\"$cluster_id\",topic=~\"$topic\", namespace=~\"$kubernetes_namespace\"}) by (partition,topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}