{
 "title": "Team Phoenix - AWS Clusters Overview",
 "tags": [ "owner:team-phoenix" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "provider",
    "label": "Provider",
    "query": {
     "query": "label_values(aggregation:kubernetes:up, provider)"
    }
   },
   {
    "name": "pipeline",
    "label": "Pipeline",
    "query": {
     "query": "label_values(aggregation:kubernetes:up{provider=~\"$provider\"}, pipeline)"
    }
   },
   {
    "name": "customer",
    "label": "Customer",
    "query": {
     "query": "label_values(aggregation:kubernetes:up, customer)"
    }
   },
   {
    "name": "installation",
    "label": "Installation",
    "query": {
     "query": "label_values(aggregation:kubernetes:up{provider=~\"$provider\", customer=~\"$customer\"}, installation)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "TC K8s API Uptime Trend",
   "type": "graph",
   "description": "The graph provides a trend of the combined average uptime across all Workload Clusters Kubernetes APIs we operator across the time range selected for the Grafana Dashboard. Selecting a 7 day time range shows the trend of all Workload Clusters Kubernetes APIs average uptime over the past 7 days.",
   "gridPos": { "h": 11, "w": 20, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(aggregation:kubernetes:up_bool  {cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=~\"$pipeline\",provider=~\"$provider\", installation=~\"$installation\", customer=~\"$customer\"}[30d]) and aggregation:kubernetes:up_bool  {cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=~\"$pipeline\",provider=~\"$provider\", installation=~\"$installation\", customer=~\"$customer\"})/count(avg_over_time(aggregation:kubernetes:up_bool  {cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=~\"$pipeline\",provider=~\"$provider\", installation=~\"$installation\", customer=~\"$customer\"}[30d]) and aggregation:kubernetes:up_bool  {cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=~\"$pipeline\",provider=~\"$provider\", installation=~\"$installation\", customer=~\"$customer\"})*100",
     "legendFormat": "Availability of Kubernetes API"
    }
   ]
  },
  {
   "title": "TC K8s API Uptime Summary",
   "type": "stat",
   "description": "The percentage provides a summary of the combined average uptime across all Workload Clusters Kubernetes APIs we operator across the time range selected for the Grafana Dashboard. Selecting a 7 day time range and having a result of 99% means that all Workload Clusters Kubernetes APIs combined have an average uptime of 99% over the past 7 days.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(aggregation:kubernetes:up_bool  {cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=~\"$pipeline\",provider=~\"$provider\", installation=~\"$installation\", customer=~\"$customer\"}[30d]) and aggregation:kubernetes:up_bool  {cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=~\"$pipeline\",provider=~\"$provider\", installation=~\"$installation\", customer=~\"$customer\"})/count(avg_over_time(aggregation:kubernetes:up_bool  {cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=~\"$pipeline\",provider=~\"$provider\", installation=~\"$installation\", customer=~\"$customer\"}[30d]) and aggregation:kubernetes:up_bool  {cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=~\"$pipeline\",provider=~\"$provider\", installation=~\"$installation\", customer=~\"$customer\"})*100"
    }
   ]
  },
  {
   "title": "Average TC K8s API Uptime by Customer",
   "type": "stat",
   "description": "The graph provides the combined average uptime by customer across all Workload Clusters Kubernetes APIs we operator across the time range selected for the Grafana Dashboard. Selecting a 7 day time range shows the trend of all Workload Clusters Kubernetes APIs average uptime over the past 7 days by Installation.",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(aggregation:kubernetes:up_bool  {cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=~\"$pipeline\",provider=~\"$provider\", installation=~\"$installation\", customer=~\"$customer\"}[30d]) and aggregation:kubernetes:up_bool  {cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=~\"$pipeline\",provider=~\"$provider\", installation=~\"$installation\", customer=~\"$customer\"}) by (customer) /count(avg_over_time(aggregation:kubernetes:up_bool  {cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=~\"$pipeline\",provider=~\"$provider\", installation=~\"$installation\", customer=~\"$customer\"}[30d]) and aggregation:kubernetes:up_bool  {cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=~\"$pipeline\",provider=~\"$provider\", installation=~\"$installation\", customer=~\"$customer\"})by (customer) *100",
     "legendFormat": "{{installation}}"
    }
   ]
  },
  {
   "title": "Average TC K8s API Uptime by Installation",
   "type": "stat",
   "description": "The graph provides the combined average uptime by Installation across all Workload Clusters Kubernetes APIs we operator across the time range selected for the Grafana Dashboard. Selecting a 7 day time range shows the trend of all Workload Clusters Kubernetes APIs average uptime over the past 7 days by Installation.",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(aggregation:kubernetes:up_bool  {cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=~\"$pipeline\",provider=~\"$provider\", installation=~\"$installation\", customer=~\"$customer\"}[30d]) and aggregation:kubernetes:up_bool  {cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=~\"$pipeline\",provider=~\"$provider\", installation=~\"$installation\", customer=~\"$customer\"}) by (installation) /count(avg_over_time(aggregation:kubernetes:up_bool  {cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=~\"$pipeline\",provider=~\"$provider\", installation=~\"$installation\", customer=~\"$customer\"}[30d]) and aggregation:kubernetes:up_bool  {cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=~\"$pipeline\",provider=~\"$provider\", installation=~\"$installation\", customer=~\"$customer\"})by (installation) *100",
     "legendFormat": "{{installation}}"
    }
   ]
  },
  {
   "title": "Completed Cluster Creations",
   "type": "gauge",
   "description": "The graph shows the percentage of cluster transitions which completed in a reasonable time.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(aggregation:giantswarm:cluster_transition_create{pipeline=~\"$pipeline\",provider=~\"$provider\", installation=~\"$installation\", customer=~\"$customer\"}!=999999999999)/count(aggregation:giantswarm:cluster_transition_create{pipeline=~\"$pipeline\",provider=~\"$provider\", installation=~\"$installation\", customer=~\"$customer\"})*100"
    }
   ]
  },
  {
   "title": "Completed Cluster Updates",
   "type": "gauge",
   "description": "The graph shows the percentage of cluster transitions which completed in a reasonable time.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count(aggregation:giantswarm:cluster_transition_update{pipeline=~\"$pipeline\",provider=~\"$provider\", installation=~\"$installation\", customer=~\"$customer\"}!=999999999999)/count(aggregation:giantswarm:cluster_transition_update{pipeline=~\"$pipeline\",provider=~\"$provider\", installation=~\"$installation\", customer=~\"$customer\"})*100)"
    }
   ]
  },
  {
   "title": "TC K8s API Uptime Trend by Cluster",
   "type": "graph",
   "description": "The graph provides a trend of the combined average uptime across all Workload Clusters Kubernetes APIs we operator across the time range selected for the Grafana Dashboard. Selecting a 7 day time range shows the trend of all Workload Clusters Kubernetes APIs average uptime over the past 7 days.",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(aggregation:kubernetes:up_bool  {cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=~\"$pipeline\",provider=~\"$provider\", installation=~\"$installation\", customer=~\"$customer\"}[30d]) and aggregation:kubernetes:up_bool  {cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=~\"$pipeline\",provider=~\"$provider\", installation=~\"$installation\", customer=~\"$customer\"}) by (cluster_id, installation) /count(avg_over_time(aggregation:kubernetes:up_bool  {cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=~\"$pipeline\",provider=~\"$provider\", installation=~\"$installation\", customer=~\"$customer\"}[30d]) and aggregation:kubernetes:up_bool  {cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=~\"$pipeline\",provider=~\"$provider\", installation=~\"$installation\", customer=~\"$customer\"})by (cluster_id, installation) *100",
     "legendFormat": "{{installation}}/{{cluster_id}}"
    }
   ]
  },
  {
   "title": "Mean Cluster Creation Time",
   "type": "gauge",
   "description": "The graph shows the average time for cluster transitions which completed in a reasonable time.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(aggregation:giantswarm:cluster_transition_create{pipeline=~\"$pipeline\",provider=~\"$provider\", installation=~\"$installation\", customer=~\"$customer\"}<=1800)"
    }
   ]
  },
  {
   "title": "Mean Cluster Update Time",
   "type": "gauge",
   "description": "The graph shows the average time for cluster transitions which completed in a reasonable time.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(aggregation:giantswarm:cluster_transition_update{pipeline=~\"$pipeline\",provider=~\"$provider\", installation=~\"$installation\", customer=~\"$customer\"}<=7200)"
    }
   ]
  },
  {
   "title": "Release Version Distribution",
   "type": "graph",
   "description": "The stacked graph shows how the distribution of release versions are over our Workload Clusterss",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(aggregation:giantswarm:cluster_release_version{provider=~\"$provider\",installation=~\"$installation\",pipeline=~\"$pipeline\", customer=~\"$customer\", release_version=~\"12.*\"})",
     "legendFormat": "Release Version 12.x.x"
    },
    {
     "expr": "sum(aggregation:giantswarm:cluster_release_version{provider=~\"$provider\",installation=~\"$installation\",pipeline=~\"$pipeline\", customer=~\"$customer\", release_version=~\"13.*\"})",
     "legendFormat": "Release Versions 13.X.X"
    },
    {
     "expr": "sum(aggregation:giantswarm:cluster_release_version{provider=~\"$provider\",installation=~\"$installation\",pipeline=~\"$pipeline\", customer=~\"$customer\", release_version=~\"14.*\"})",
     "legendFormat": "Release Versions 14.X.X"
    },
    {
     "expr": "sum(aggregation:giantswarm:cluster_release_version{provider=~\"$provider\",installation=~\"$installation\",pipeline=~\"$pipeline\", customer=~\"$customer\", release_version=~\"15.*\"})",
     "legendFormat": "Release Versions 15.X.X"
    },
    {
     "expr": "sum(aggregation:giantswarm:cluster_release_version{provider=~\"$provider\",installation=~\"$installation\",pipeline=~\"$pipeline\", customer=~\"$customer\", release_version=~\"16.*\"})",
     "legendFormat": "Release Versions 16.X.X"
    },
    {
     "expr": "sum(aggregation:giantswarm:cluster_release_version{provider=~\"$provider\",installation=~\"$installation\",pipeline=~\"$pipeline\", customer=~\"$customer\", release_version=~\"17.*\"})",
     "legendFormat": "Release Version 17.x.x"
    }
   ]
  },
  {
   "title": "Cluster Creations with Problems",
   "type": "gauge",
   "description": "The graph shows the percentage of cluster transitions which completed in a reasonable time.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100-(count(aggregation:giantswarm:cluster_transition_create{pipeline=~\"$pipeline\",provider=~\"$provider\", installation=~\"$installation\", customer=~\"$customer\"}<=1800)/count(aggregation:giantswarm:cluster_transition_create{pipeline=~\"$pipeline\",provider=~\"$provider\", installation=~\"$installation\", customer=~\"$customer\"})*100)"
    }
   ]
  },
  {
   "title": "Cluster Updates with Problems",
   "type": "gauge",
   "description": "The graph shows the percentage of cluster transitions which completed in a reasonable time.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100-(count(aggregation:giantswarm:cluster_transition_update{pipeline=~\"$pipeline\",provider=~\"$provider\", installation=~\"$installation\", customer=~\"$customer\"}<=72000)/count(aggregation:giantswarm:cluster_transition_update{pipeline=~\"$pipeline\",provider=~\"$provider\", installation=~\"$installation\", customer=~\"$customer\"})*100)"
    }
   ]
  },
  { "title": "HA vs. single master clusters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Info",
   "type": "text",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 31 },
   "options": {
    "content": "High availability Kubernetes masters (HA masters) has been introduced with AWS release v11.4.0. It is the default when creating new clusters as of that release."
   }
  },
  {
   "title": "Workload Clusterss with release v11.4.0 or newer",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 3, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(aggregation:giantswarm:cluster_release_version{provider=~\"$provider\", installation=~\"$installation\", pipeline=~\"$pipeline\", customer=~\"$customer\", release_version!~\"8.*\", release_version!~\"9.*\", release_version!~\"10.*\", release_version!~\"11.1.*\", release_version!~\"11.2.*\", release_version!~\"11.3.*\"})",
     "legendFormat": "Single"
    }
   ]
  },
  {
   "title": "Workload Clusterss with Single vs. HA masters",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 7, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(sum(aggregation:kubernetes:node_total{cluster_type=~\"tenant_cluster|workload_cluster\", installation=~\"$installation\",provider=~\"$provider\",pipeline=~\"$pipeline\", role=\"master\", customer=~\"$customer\"}) by (cluster_id) == 1)",
     "legendFormat": "Single"
    },
    {
     "expr": "count(sum(aggregation:kubernetes:node_total{cluster_type=~\"tenant_cluster|workload_cluster\", installation=~\"$installation\",provider=~\"$provider\",pipeline=~\"$pipeline\", role=\"master\", customer=~\"$customer\"}) by (cluster_id) == 3)",
     "legendFormat": "HA"
    }
   ]
  },
  {
   "title": "Clusters that would support HA masters",
   "type": "bargauge",
   "description": "Clusters with release >= v11.4.0",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(sum(aggregation:kubernetes:node_total{cluster_type=~\"tenant_cluster|workload_cluster\", installation=~\"$installation\",provider=~\"$provider\",pipeline=~\"$pipeline\", role=\"master\", customer=~\"$customer\"}) by (cluster_id) == 1) / count(sum(aggregation:kubernetes:node_total{cluster_type=~\"tenant_cluster|workload_cluster\", installation=~\"$installation\",provider=~\"$provider\",pipeline=~\"$pipeline\", role=\"master\", customer=~\"$customer\"}) by (cluster_id))",
     "legendFormat": "Single"
    },
    {
     "expr": "count(sum(aggregation:kubernetes:node_total{cluster_type=~\"tenant_cluster|workload_cluster\", installation=~\"$installation\",provider=~\"$provider\",pipeline=~\"$pipeline\", role=\"master\", customer=~\"$customer\"}) by (cluster_id) == 3) / count(sum(aggregation:kubernetes:node_total{cluster_type=~\"tenant_cluster|workload_cluster\", installation=~\"$installation\",provider=~\"$provider\",pipeline=~\"$pipeline\", role=\"master\", customer=~\"$customer\"}) by (cluster_id))",
     "legendFormat": "HA"
    }
   ]
  },
  {
   "title": "Single vs Multi Master Ratio",
   "type": "graph",
   "description": "The stacked graph shows how many of our Workload Clusterss are configured as Single or Multi Master setups. ",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 31 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "count(sum(aggregation:kubernetes:node_total{cluster_type=~\"tenant_cluster|workload_cluster\", installation=~\"$installation\",provider=~\"$provider\",pipeline=~\"$pipeline\", role=\"master\", customer=~\"$customer\"}) by (cluster_id) == 1) / count(sum(aggregation:kubernetes:node_total{cluster_type=~\"tenant_cluster|workload_cluster\", installation=~\"$installation\",provider=~\"$provider\",pipeline=~\"$pipeline\", role=\"master\", customer=~\"$customer\"}) by (cluster_id))",
     "legendFormat": "Single Master"
    },
    {
     "expr": "count(sum(aggregation:kubernetes:node_total{cluster_type=~\"tenant_cluster|workload_cluster\", installation=~\"$installation\",provider=~\"$provider\",pipeline=~\"$pipeline\", role=\"master\", customer=~\"$customer\"}) by (cluster_id) == 3) / count(sum(aggregation:kubernetes:node_total{cluster_type=~\"tenant_cluster|workload_cluster\", installation=~\"$installation\",provider=~\"$provider\",pipeline=~\"$pipeline\", role=\"master\", customer=~\"$customer\"}) by (cluster_id))",
     "legendFormat": "Multi Master"
    }
   ]
  }
 ]
}