{
 "title": "Clusters",
 "tags": [ "owner:team-turtles" ],
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  { "title": "Latest figures", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Installations",
   "type": "stat",
   "description": "Note that this number always represents the latest data and is not influenced by the time selector.",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(group(aggregation:giantswarm:cluster_release_version{pipeline=\"stable\"}) by (installation))",
     "legendFormat": "{{installation}}"
    }
   ]
  },
  {
   "title": "Clusters",
   "type": "stat",
   "description": "Note that this number always represents the latest data and is not influenced by the time selector.",
   "gridPos": { "h": 7, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(aggregation:giantswarm:cluster_release_version{pipeline=\"stable\"})",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Kubelets",
   "type": "stat",
   "description": "Note that this number always represents the latest data and is not influenced by the time selector.",
   "gridPos": { "h": 7, "w": 6, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:kubelet:version{cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"stable\"})",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Clusters Per Region",
   "type": "bargauge",
   "description": "Note that this chart always represents the latest data and is not influenced by the time selector.",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(aggregation:giantswarm:cluster_release_version{region=~\"eu-.*|.*europe|germany.*|sweden.*|uk.*|france.*|italy.*|poland.*|spain.*|switzerland.*\",pipeline=\"stable\"})",
     "legendFormat": "Europe"
    },
    {
     "expr": "count(aggregation:giantswarm:cluster_release_version{region=~\"us-.*|.*us|.*us2|.*us3\",pipeline=\"stable\"})",
     "legendFormat": "America"
    },
    {
     "expr": "count(aggregation:giantswarm:cluster_release_version{region=~\"ap-.*|australia.*|.*asia|.*india.*|japan.*|korea.*\",pipeline=\"stable\"})",
     "legendFormat": "Asia / Pacific"
    },
    {
     "expr": "count(aggregation:giantswarm:cluster_release_version{region=~\"af-.*|.*africa.*\",pipeline=\"stable\"})",
     "legendFormat": "Africa"
    },
    {
     "expr": "count(aggregation:giantswarm:cluster_release_version{region=~\"ca-.*|canada.*\",pipeline=\"stable\"})",
     "legendFormat": "Canada"
    },
    {
     "expr": "count(aggregation:giantswarm:cluster_release_version{region=~\"cn-.*\",pipeline=\"stable\"})",
     "legendFormat": "China"
    },
    {
     "expr": "count(aggregation:giantswarm:cluster_release_version{region=~\"onprem\",pipeline=\"stable\"})",
     "legendFormat": "OnPrem"
    },
    {
     "expr": "count(aggregation:giantswarm:cluster_release_version{region!~\"eu-.*|.*europe|germany.*|sweden.*|uk.*|france.*|italy.*|poland.*|spain.*|switzerland.*|us-.*|.*us|.*us2|.*us3|ap-.*|australia.*|.*asia|.*india.*|japan.*|korea.*|af-.*|.*africa.*|ca-.*|canada.*|cn-.*|onprem\",pipeline=\"stable\"})",
     "legendFormat": "Unknown Region"
    }
   ]
  },
  {
   "title": "Clusters per customer",
   "type": "bargauge",
   "description": "The latest number of cluster each customer has. Note: This graph is not affected by the time selection for this dashboard.",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(aggregation:giantswarm:cluster_release_version{pipeline=\"stable\"}) by (customer)",
     "legendFormat": "{{ customer }}"
    }
   ]
  },
  {
   "title": "Clusters per Provider",
   "type": "bargauge",
   "description": "Note: This chart is not influenced by the time selector.",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(aggregation:giantswarm:cluster_release_version{pipeline=\"stable\"}) by (provider)",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Kubelets per customer",
   "type": "bargauge",
   "description": "The latest number of kubelets each customer has running. Note: This graph is not affected by the time selection for this dashboard.",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:kubelet:version{cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"stable\"}) by (customer)",
     "legendFormat": "{{ customer }}"
    }
   ]
  },
  {
   "title": "Clusters by Kubernetes version",
   "type": "bargauge",
   "description": "The numberof clusters currently running by their Kubernetes version. Note: This chart is not influenced by the time selector.",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(group(aggregation:kubernetes:version{cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"stable\"}) by (cluster_id, git_version)) by (git_version)",
     "legendFormat": "{{git_version}}"
    }
   ]
  },
  {
   "title": "AWS Clusters Per Release Version",
   "type": "barchart",
   "description": "Current number of clusters per release in AWS. Note that this chart is not influenced by the time selector.",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "label_replace(count(aggregation:giantswarm:cluster_release_version{provider=~\"aws|capa\",pipeline=\"stable\"}) by (release_version), \"release_version\", \"unknown\", \"release_version\", \"\")",
     "legendFormat": "{{release_version}}"
    }
   ]
  },
  {
   "title": "Azure Clusters per Release Version",
   "type": "barchart",
   "description": "Current number of clusters per release in Azure. Note that this chart is not influenced by the time selector.",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 23 },
   "targets": [
    {
     "expr": "label_replace(count(aggregation:giantswarm:cluster_release_version{provider=~\"azure|capz\",pipeline=\"stable\"}) by (release_version), \"release_version\", \"unknown\", \"release_version\", \"\")",
     "legendFormat": "{{release_version}}"
    }
   ]
  },
  {
   "title": "VSphere Clusters per Release Version",
   "type": "barchart",
   "description": "Current number of clusters per release on KVM. Note that this chart is not influenced by the time selector.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(count(aggregation:giantswarm:cluster_release_version{provider=~\"vsphere|capv\",pipeline=\"stable\"}) by (release_version), \"release_version\", \"unknown\", \"release_version\", \"\")",
     "legendFormat": "{{release_version}}"
    }
   ]
  },
  {
   "title": "Cloud-Director Clusters per Release Version",
   "type": "barchart",
   "description": "Current number of clusters per release on KVM. Note that this chart is not influenced by the time selector.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(count(aggregation:giantswarm:cluster_release_version{provider=~\"cloud-director|capvcd\",pipeline=\"stable\"}) by (release_version), \"release_version\", \"unknown\", \"release_version\", \"\")",
     "legendFormat": "{{release_version}}"
    }
   ]
  },
  {
   "title": "KVM Clusters per Release Version",
   "type": "barchart",
   "description": "Current number of clusters per release on KVM. Note that this chart is not influenced by the time selector.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(aggregation:giantswarm:cluster_release_version{provider=\"kvm\",pipeline=\"stable\"}) by (release_version)",
     "legendFormat": "{{release_version}}"
    }
   ]
  },
  {
   "title": "Percentage API Servers Per Kubernetes Version",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count(aggregation:kubernetes:version{pipeline=\"stable\"}) by (git_version) / scalar(count(aggregation:kubernetes:version{pipeline=\"stable\"}))) * 100",
     "legendFormat": "{{git_version}}"
    }
   ]
  },
  {
   "title": "Percentage Kubelets Per Kubernetes Version",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(aggregation:kubelet:version{pipeline=\"stable\"}) by (git_version) / scalar(sum(aggregation:kubelet:version{pipeline=\"stable\"}))) * 100",
     "legendFormat": "{{gitVersion}}"
    }
   ]
  },
  { "title": "Development over time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Clusters ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(aggregation:giantswarm:cluster_release_version{pipeline=\"stable\"})",
     "legendFormat": "Clusters"
    }
   ]
  },
  {
   "title": "Kubelets",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(aggregation:kubelet:version{cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"stable\"})",
     "legendFormat": "Kubelets"
    }
   ]
  },
  {
   "title": "Clusters Per Customer",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(aggregation:giantswarm:cluster_release_version{pipeline=\"stable\"}) by (customer)",
     "legendFormat": "{{customer}}"
    }
   ]
  },
  {
   "title": "Kubelets Per Customer",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(aggregation:kubelet:version{cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"stable\"}) by (customer)",
     "legendFormat": "{{customer}}"
    }
   ]
  },
  {
   "title": "Clusters Per Installation",
   "type": "timeseries",
   "description": "Excludes the MC itself",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(aggregation:giantswarm:cluster_release_version{pipeline=\"stable\"}) by (installation) - 1",
     "legendFormat": "{{installation}}"
    }
   ]
  },
  {
   "title": "Kubelets Per Installation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(aggregation:kubelet:version{cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"stable\"}) by (installation)",
     "legendFormat": "{{installation}}"
    }
   ]
  },
  {
   "title": "Clusters Per Provider",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(aggregation:giantswarm:cluster_release_version{pipeline=\"stable\"}) by (provider)",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Kubelets Per Provider",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(aggregation:kubelet:version{cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"stable\"}) by (provider)",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Clusters Per Region",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(aggregation:giantswarm:cluster_release_version{region=~\"eu-.*|.*europe|germany.*|sweden.*|uk.*|france.*|italy.*|poland.*|spain.*|switzerland.*\",pipeline=\"stable\"})",
     "legendFormat": "Europe"
    },
    {
     "expr": "sum(aggregation:giantswarm:cluster_release_version{region=~\"us-.*|.*us|.*us2|.*us3\",pipeline=\"stable\"})",
     "legendFormat": "America"
    },
    {
     "expr": "sum(aggregation:giantswarm:cluster_release_version{region=~\"ap-.*|australia.*|.*asia|.*india.*|japan.*|korea.*\",pipeline=\"stable\"})",
     "legendFormat": "Asia / Pacific"
    },
    {
     "expr": "sum(aggregation:giantswarm:cluster_release_version{region=~\"cn-.*\",pipeline=\"stable\"})",
     "legendFormat": "China"
    },
    {
     "expr": "sum(aggregation:giantswarm:cluster_release_version{region=~\"af-.*|.*africa.*\",pipeline=\"stable\"})",
     "legendFormat": "Africa"
    },
    {
     "expr": "sum(aggregation:giantswarm:cluster_release_version{region=~\"ca-.*|canada.*\",pipeline=\"stable\"})",
     "legendFormat": "Canada"
    },
    {
     "expr": "sum(aggregation:giantswarm:cluster_release_version{region=~\"onprem\",pipeline=\"stable\"})",
     "legendFormat": "OnPrem"
    },
    {
     "expr": "sum(aggregation:giantswarm:cluster_release_version{region!~\"eu-.*|.*europe|germany.*|sweden.*|uk.*|france.*|italy.*|poland.*|spain.*|switzerland.*|us-.*|.*us|.*us2|.*us3|ap-.*|australia.*|.*asia|.*india.*|japan.*|korea.*|af-.*|.*africa.*|ca-.*|canada.*|cn-.*|onprem\",pipeline=\"stable\"})",
     "legendFormat": "Unknown"
    }
   ]
  },
  {
   "title": "Kubelets Per Region",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(aggregation:kubelet:version{region=~\"eu-.*|.*europe|germany.*|sweden.*|uk.*|france.*|italy.*|poland.*|spain.*|switzerland.*\"})",
     "legendFormat": "Europe"
    },
    {
     "expr": "sum(aggregation:kubelet:version{region=~\"us-.*|.*us|.*us2|.*us3\"})",
     "legendFormat": "America"
    },
    {
     "expr": "sum(aggregation:kubelet:version{region=~\"ap-.*|australia.*|.*asia|.*india.*|japan.*|korea.*\"})",
     "legendFormat": "Asia / Pacific"
    },
    {
     "expr": "sum(aggregation:kubelet:version{region=~\"cn-.*\"})",
     "legendFormat": "China"
    },
    {
     "expr": "sum(aggregation:kubelet:version{region=~\"af-.*|.*africa.*\"})",
     "legendFormat": "Africa"
    },
    {
     "expr": "sum(aggregation:kubelet:version{region=~\"ca-.*|canada.*\"})",
     "legendFormat": "Canada"
    },
    {
     "expr": "sum(aggregation:kubelet:version{region=~\"onprem\"})",
     "legendFormat": "OnPrem"
    },
    {
     "expr": "sum(aggregation:kubelet:version{region!~\"eu-.*|.*europe|germany.*|sweden.*|uk.*|france.*|italy.*|poland.*|spain.*|switzerland.*|us-.*|.*us|.*us2|.*us3|ap-.*|australia.*|.*asia|.*india.*|japan.*|korea.*|af-.*|.*africa.*|ca-.*|canada.*|cn-.*|onprem\"})",
     "legendFormat": "Unknown"
    }
   ]
  },
  {
   "title": "API Servers Per Kubernetes Version",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(aggregation:kubernetes:version{cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"stable\"}) by (git_version)",
     "legendFormat": "{{gitVersion}}"
    }
   ]
  },
  {
   "title": "Kubelets Per Kubernetes Version",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(aggregation:kubelet:version{cluster_type=~\"tenant_cluster|workload_cluster\",pipeline=\"stable\"}) by (git_version)",
     "legendFormat": "{{gitVersion}}"
    }
   ]
  },
  { "title": "Provider Specifics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "AWS Clusters Per Release Version",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(aggregation:giantswarm:cluster_release_version{provider=~\"aws|capa\",pipeline=\"stable\"}) by (release_version)",
     "legendFormat": "{{release_version}}"
    }
   ]
  },
  {
   "title": "AWS Percentage Clusters By Release Version",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count(aggregation:kubernetes:version{pipeline=\"stable\", provider=~\"aws|capa\"}) by (git_version) / scalar(count(aggregation:kubernetes:version{pipeline=\"stable\", provider=~\"aws|capa\"}))) * 100",
     "legendFormat": "{{release_version}}"
    }
   ]
  },
  {
   "title": "Azure Clusters Per Release Version",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(aggregation:giantswarm:cluster_release_version{provider=~\"azure|capz\",pipeline=\"stable\"}) by (release_version)",
     "legendFormat": "{{release_version}}"
    }
   ]
  },
  {
   "title": "Azure Percentage Clusters By Release Version",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count(aggregation:kubernetes:version{pipeline=\"stable\", provider=~\"azure|capz\"}) by (git_version) / scalar(count(aggregation:kubernetes:version{pipeline=\"stable\", provider=~\"azure|capz\"}))) * 100",
     "legendFormat": "{{release_version}}"
    }
   ]
  },
  {
   "title": "VSphere Clusters Per Release Version",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(aggregation:kubernetes:version{provider=~\"vsphere|capv\",pipeline=\"stable\"}) by (release_version)",
     "legendFormat": "{{release_version}}"
    }
   ]
  },
  {
   "title": "VSphere Percentage Clusters By Release Version",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count(aggregation:kubernetes:version{pipeline=\"stable\", provider=~\"vsphere|capv\"}) by (git_version) / scalar(count(aggregation:kubernetes:version{pipeline=\"stable\", provider=~\"vsphere|capv\"}))) * 100",
     "legendFormat": "{{release_version}}"
    }
   ]
  },
  {
   "title": "Cloud-Director Clusters Per Release Version",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(aggregation:giantswarm:cluster_release_version{provider=~\"cloud-director|capvcd\",pipeline=\"stable\"}) by (release_version)",
     "legendFormat": "{{release_version}}"
    }
   ]
  },
  {
   "title": "Cloud-Director Percentage Clusters By Release Version",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count(aggregation:kubernetes:version{pipeline=\"stable\", provider=~\"cloud-director|capvcd\"}) by (git_version) / scalar(count(aggregation:kubernetes:version{pipeline=\"stable\", provider=~\"cloud-director|capvcd\"}))) * 100",
     "legendFormat": "{{release_version}}"
    }
   ]
  },
  {
   "title": "KVM Clusters Per Release Version",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(aggregation:giantswarm:cluster_release_version{provider=~\"kvm\",pipeline=\"stable\"}) by (release_version)",
     "legendFormat": "{{release_version}}"
    }
   ]
  },
  {
   "title": "KVM Percentage Clusters By Release Version",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count(aggregation:kubernetes:version{pipeline=\"stable\", provider=~\"kvm\"}) by (git_version) / scalar(count(aggregation:kubernetes:version{pipeline=\"stable\", provider=~\"kvm\"}))) * 100",
     "legendFormat": "{{release_version}}"
    }
   ]
  }
 ]
}