{
 "title": "Managed Apps (Joe Remix) (Gerald Remix)",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "customer",
    "label": "Customer",
    "query": {
     "query": "label_values(prometheus_tsdb_head_series,customer)"
    }
   },
   {
    "name": "management_cluster",
    "label": "Management Cluster",
    "query": {
     "query": "label_values(prometheus_tsdb_head_series{customer=~\"$customer\"}, installation)"
    }
   },
   {
    "name": "app",
    "label": "App",
    "query": {
     "query": "label_values(aggregation:giantswarm:app_deployed_workload_cluster_total{catalog=\"default\", customer=~\"$customer\", installation=~\"$management_cluster\"}, app)"
    }
   },
   {
    "name": "app_version",
    "label": "App Version",
    "query": {
     "query": "label_values(aggregation:giantswarm:app_deployed_workload_cluster_total{catalog=\"default\", customer=~\"$customer\", installation=~\"$management_cluster\", app=~\"$app\"}, app_version)"
    }
   },
   {
    "name": "version",
    "label": "Version",
    "query": {
     "query": "label_values(aggregation:giantswarm:app_deployed_workload_cluster_total{catalog=\"default\", customer=~\"$customer\", installation=~\"$management_cluster\", app=~\"$app\", app_version=~\"$app_version\"}, version)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Apps Used",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:giantswarm:app_deployed_workload_cluster_total{catalog=\"default\", customer=~\"$customer\", installation=~\"$management_cluster\", app=~\"$app\", app_version=~\"$app_version\", version=~\"$version\"}) by (app)",
     "legendFormat": "{{app}} "
    }
   ]
  },
  {
   "title": "Apps Used By Customer(s)",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:giantswarm:app_deployed_workload_cluster_total{catalog=\"default\", customer=~\"$customer\", installation=~\"$management_cluster\", app=~\"$app\", app_version=~\"$app_version\", version=~\"$version\"}) by (customer, app)",
     "legendFormat": "{{customer}} / {{app}} "
    }
   ]
  },
  {
   "title": "Apps Used By Versions",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:giantswarm:app_deployed_workload_cluster_total{catalog=\"default\", customer=~\"$customer\", installation=~\"$management_cluster\", app=~\"$app\", app_version=~\"$app_version\", version=~\"$version\"}) by (app, app_version, version)",
     "legendFormat": "{{app}} ({{version}}, {{app_version}})"
    }
   ]
  },
  {
   "title": "Apps Used By Customer(s) And Versions",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:giantswarm:app_deployed_workload_cluster_total{catalog=\"default\", customer=~\"$customer\", installation=~\"$management_cluster\", app=~\"$app\", app_version=~\"$app_version\", version=~\"$version\"}) by (customer, app, app_version, version)",
     "legendFormat": "{{customer}} - {{app}} ({{version}}, {{app_version}})"
    }
   ]
  },
  {
   "title": "Apps Used By Customer(s) And Versions And Management Clusters",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:giantswarm:app_deployed_workload_cluster_total{catalog=\"default\", customer=~\"$customer\", installation=~\"$management_cluster\", app=~\"$app\", app_version=~\"$app_version\", version=~\"$version\"}) by (customer, installation, app, app_version, version)",
     "legendFormat": "{{customer}} / {{installation}} - {{app}} ({{version}}, {{app_version}})"
    }
   ]
  },
  {
   "title": "Number Of Versions In Use",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "count(sum(aggregation:giantswarm:app_deployed_workload_cluster_total{catalog=\"default\", customer=~\"$customer\", installation=~\"$management_cluster\", app=~\"$app\", app_version=~\"$app_version\", version=~\"$version\"}) by (version))"
    }
   ]
  }
 ]
}