{
 "title": "WG Successful Upgrades",
 "description": "Show in detail where which AWS releases are in use",
 "tags": [ "owner:team-turtles" ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 0 },
   "options": {
    "content": "Customers by provider in one of the latest patch version of the two supported major releases"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "AWS",
   "type": "stat",
   "description": "Note that this number always represents the latest data and is not influenced by the time selector.",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(aggregation:giantswarm:cluster_release_version{pipeline=\"stable\", provider=\"aws\", release_version=~\"19.3.1|19.2.0\"}) / count(aggregation:giantswarm:cluster_release_version{pipeline=\"stable\", provider=\"aws\"}) * 100",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Azure",
   "type": "stat",
   "description": "Note that this number always represents the latest data and is not influenced by the time selector.",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(aggregation:giantswarm:cluster_release_version{pipeline=\"stable\", provider=\"azure\", release_version=~\"19.0.1|19.1.0\"}) / count(aggregation:giantswarm:cluster_release_version{pipeline=\"stable\", provider=\"azure\"}) * 100",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "KVM",
   "type": "stat",
   "description": "Note that this number always represents the latest data and is not influenced by the time selector.",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(aggregation:giantswarm:cluster_release_version{pipeline=\"stable\", provider=\"kvm\", release_version=~\"16.2.0|16.2.1\"}) / count(aggregation:giantswarm:cluster_release_version{pipeline=\"stable\", provider=\"kvm\"}) * 100",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Azure Clusters Per Release Version Over Time",
   "type": "graph",
   "description": "Current number of clusters per release in AWS. Note that this chart is not influenced by the time selector.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aggregation:giantswarm:cluster_release_version{provider=\"azure\",pipeline=\"stable\"}) by (release_version)",
     "legendFormat": "{{release_version}}"
    }
   ]
  },
  {
   "title": "Azure Clusters Per Release Version Over Time by Percentage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(aggregation:giantswarm:cluster_release_version{provider=\"azure\", pipeline=\"stable\"}, \"release_version\", \"$1\", \"release_version\", \"([0-9]*\\\\.[0-9]*).*\")) by (provider, release_version)",
     "legendFormat": "{{release_version}}"
    }
   ]
  },
  {
   "title": "AWS Clusters Per Release Version Over Time",
   "type": "graph",
   "description": "Current number of clusters per release in AWS. Note that this chart is not influenced by the time selector.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aggregation:giantswarm:cluster_release_version{provider=\"aws\",pipeline=\"stable\"}) by (release_version)",
     "legendFormat": "{{release_version}}"
    }
   ]
  },
  {
   "title": "AWS Clusters Per Release Version Over Time by Percentage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(aggregation:giantswarm:cluster_release_version{provider=\"aws\", pipeline=\"stable\"}, \"release_version\", \"$1\", \"release_version\", \"([0-9]*\\\\.[0-9]*).*\")) by (provider, release_version)",
     "legendFormat": "{{release_version}}"
    }
   ]
  },
  {
   "title": "KVM Clusters Per Release Version Over Time",
   "type": "graph",
   "description": "Current number of clusters per release in AWS. Note that this chart is not influenced by the time selector.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aggregation:giantswarm:cluster_release_version{provider=\"kvm\",pipeline=\"stable\"}) by (release_version)",
     "legendFormat": "{{release_version}}"
    }
   ]
  },
  {
   "title": "KVM Clusters Per Release Version Over Time by Percentage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(aggregation:giantswarm:cluster_release_version{provider=\"kvm\", pipeline=\"stable\"}, \"release_version\", \"$1\", \"release_version\", \"([0-9]*\\\\.[0-9]*).*\")) by (provider, release_version)",
     "legendFormat": "{{release_version}}"
    }
   ]
  },
  {
   "title": "Azure Clusters Per Release Version",
   "type": "graph",
   "description": "Current number of clusters per release in AWS. Note that this chart is not influenced by the time selector.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aggregation:giantswarm:cluster_release_version{provider=\"azure\",pipeline=\"stable\"}) by (release_version)",
     "legendFormat": "{{release_version}}"
    }
   ]
  },
  {
   "title": "Azure clusters in latest version",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:giantswarm:cluster_release_version{provider=\"azure\", release_version=~\"14.1.5|13.1.1\"}) by (customer) / sum(aggregation:giantswarm:cluster_release_version{provider=\"azure\"}) by (customer) * 100",
     "legendFormat": "{{ customer }}"
    }
   ]
  },
  {
   "title": "AWS Clusters Per Release Version",
   "type": "graph",
   "description": "Current number of clusters per release in AWS. Note that this chart is not influenced by the time selector.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(aggregation:giantswarm:cluster_release_version{provider=\"aws\",customer=\"vodafone\",pipeline=\"stable\"}) by (release_version)",
     "legendFormat": "{{release_version}}"
    }
   ]
  },
  {
   "title": "AWS clusters in latest version",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:giantswarm:cluster_release_version{provider=\"aws\", release_version=~\"19.2.1|19.2.0\"}) by (customer) / sum(aggregation:giantswarm:cluster_release_version{provider=\"aws\"}) by (customer) * 100",
     "legendFormat": "{{ customer }}"
    }
   ]
  },
  {
   "title": "KVM Clusters Per Release Version",
   "type": "graph",
   "description": "Current number of clusters per release in AWS. Note that this chart is not influenced by the time selector.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aggregation:giantswarm:cluster_release_version{provider=\"kvm\",pipeline=\"stable\"}) by (release_version)",
     "legendFormat": "{{release_version}}"
    }
   ]
  },
  {
   "title": "KVM clusters in latest version",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(aggregation:giantswarm:cluster_release_version{provider=\"kvm\", release_version=~\"14.0.0|13.1.0\"}) by (customer) / count(aggregation:giantswarm:cluster_release_version{provider=\"kvm\"}) by (customer) * 100",
     "legendFormat": "{{ customer }}"
    }
   ]
  }
 ]
}