{
 "title": "Honeybadger Registry Migration Progress",
 "description": "Specifically created for the December 2023 project to move away from Docker Hub and then other regisitries.",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster_id", "query": { "query": "label_values(cluster_id)" } }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Container count by registry - latest relative shares",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:container:images{image=~\"gsoci.azurecr.io.*\", cluster_id=~\"$cluster_id\"})",
     "legendFormat": "gsoci Public"
    },
    {
     "expr": "sum(aggregation:container:images{image=~\"docker.io/.*\", cluster_id=~\"$cluster_id\"})",
     "legendFormat": "Docker Hub"
    },
    {
     "expr": "sum(aggregation:container:images{image=~\"quay.io/.*\", cluster_id=~\"$cluster_id\"})",
     "legendFormat": "Quay"
    },
    {
     "expr": "sum(aggregation:container:images{image=~\".*aliyuncs.com.*\", cluster_id=~\"$cluster_id\"})",
     "legendFormat": "Aliyun"
    },
    {
     "expr": "sum(aggregation:container:images{image!~\".*aliyuncs.com.*\",image!~\"docker.io/.*\",image!~\"quay.io/.*\",image!~\"gsoci.azurecr.io/.*\", cluster_id=~\"$cluster_id\"})",
     "legendFormat": "Others"
    },
    {
     "expr": "sum(aggregation:container:images{image=~\"gsociprivate.azurecr.io.*\", cluster_id=~\"$cluster_id\"})",
     "legendFormat": "gsoci Private"
    }
   ]
  },
  {
   "title": "Container share by registry",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(aggregation:container:images{image=~\"gsoci.azurecr.io.*\", cluster_id=~\"$cluster_id\"}) / sum(aggregation:container:images{cluster_id=~\"$cluster_id\"})",
     "legendFormat": "gsoci Public"
    },
    {
     "expr": "sum(aggregation:container:images{image=~\"docker.io/.*\",cluster_id=~\"$cluster_id\"}) / sum(aggregation:container:images{cluster_id=~\"$cluster_id\"})",
     "legendFormat": "Docker Hub"
    },
    {
     "expr": "sum(aggregation:container:images{image=~\"quay.io/.*\",cluster_id=~\"$cluster_id\"}) / sum(aggregation:container:images{cluster_id=~\"$cluster_id\"})",
     "legendFormat": "Quay"
    },
    {
     "expr": "sum(aggregation:container:images{image=~\".*aliyuncs.com.*\",cluster_id=~\"$cluster_id\"}) / sum(aggregation:container:images{cluster_id=~\"$cluster_id\"})",
     "legendFormat": "Aliyun"
    },
    {
     "expr": "sum(aggregation:container:images{image!~\".*aliyuncs.com.*\",image!~\"docker.io/.*\",image!~\"quay.io/.*\",image!~\"gsoci.azurecr.io/.*\",cluster_id=~\"$cluster_id\"}) / sum(aggregation:container:images{cluster_id=~\"$cluster_id\"})",
     "legendFormat": "Others"
    },
    {
     "expr": "sum(aggregation:container:images{image=~\"gsociprivate.azurecr.io.*\", cluster_id=~\"$cluster_id\"}) / sum(aggregation:container:images{cluster_id=~\"$cluster_id\"})",
     "legendFormat": "gsoci Private"
    }
   ]
  },
  {
   "title": "Container count by registry",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 6, "y": 11 },
   "targets": [
    {
     "expr": "sum(aggregation:container:images{image=~\"gsoci.azurecr.io.*\", cluster_id=~\"$cluster_id\"})",
     "legendFormat": "gsoci Public"
    },
    {
     "expr": "sum(aggregation:container:images{image=~\"docker.io/.*\",cluster_id=~\"$cluster_id\"})",
     "legendFormat": "Docker Hub"
    },
    {
     "expr": "sum(aggregation:container:images{image=~\"quay.io/.*\",cluster_id=~\"$cluster_id\"})",
     "legendFormat": "Quay"
    },
    {
     "expr": "sum(aggregation:container:images{image=~\".*aliyuncs.com.*\",cluster_id=~\"$cluster_id\"})",
     "legendFormat": "Aliyun"
    },
    {
     "expr": "sum(aggregation:container:images{image!~\".*aliyuncs.com.*\",image!~\"docker.io/.*\",image!~\"quay.io/.*\",image!~\"gsoci.azurecr.io/.*\",cluster_id=~\"$cluster_id\"})",
     "legendFormat": "Others"
    },
    {
     "expr": "sum(aggregation:container:images{image=~\"gsociprivate.azurecr.io.*\", cluster_id=~\"$cluster_id\"})",
     "legendFormat": "gsoci Private"
    }
   ]
  },
  { "title": "Container details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Containers in use from gsoci public",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum(aggregation:container:images{image=~\"gsoci.azurecr.io.*\",cluster_id=~\"$cluster_id\"}) by (installation, cluster_id, image)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Containers in use from gsoci private",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum(aggregation:container:images{image=~\"gsociprivate.azurecr.io.*\",cluster_id=~\"$cluster_id\"}) by (installation, cluster_id, image)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}