{
 "title": "Docker Actions",
 "tags": [ "owner:team-honeybadger" ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "customer",
    "label": "Customer",
    "query": "label_values(prometheus_tsdb_head_series, customer)"
   },
   {
    "name": "management_cluster",
    "label": "Management Cluster",
    "query": "label_values(prometheus_tsdb_head_series{customer=~\"$customer\"}, installation)"
   }
  ]
 },
 "panels": [
  {
   "title": "Number of Docker Pulls (Total)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aggregation:docker:action_count{customer=~\"$customer\", installation=~\"$management_cluster\", action=\"pull\"})",
     "legendFormat": "Pulls"
    }
   ]
  },
  {
   "title": "Rate of Docker Pulls (Total)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(aggregation:docker:action_count{customer=~\"$customer\", installation=~\"$management_cluster\", action=\"pull\"}[24h]))",
     "legendFormat": "Pulls"
    }
   ]
  },
  {
   "title": "Number of Docker Pulls Per Customer",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aggregation:docker:action_count{customer=~\"$customer\", installation=~\"$management_cluster\", action=\"pull\"}) by (customer)",
     "legendFormat": "{{customer}}"
    }
   ]
  },
  {
   "title": "Number of Docker Pulls Per Installation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aggregation:docker:action_count{customer=~\"$customer\", installation=~\"$management_cluster\", action=\"pull\"}) by (installation)",
     "legendFormat": "{{installation}}"
    }
   ]
  },
  {
   "title": "Number of Docker Pulls Per Cluster",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aggregation:docker:action_count{customer=~\"$customer\", installation=~\"$management_cluster\", action=\"pull\"}",
     "legendFormat": "{{installation}} - {{cluster_id}}"
    }
   ]
  },
  {
   "title": "Average Number of Docker Pulls Per Node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aggregation:docker:action_count{customer=~\"$customer\", installation=~\"$management_cluster\", action=\"pull\"}) by (installation, cluster_id) / sum(aggregation:kubernetes:node_total{customer=~\"$customer\", installation=~\"$management_cluster\"}) by (installation, cluster_id)",
     "legendFormat": "{{installation}} - {{cluster_id}}"
    }
   ]
  },
  {
   "title": "Average Rate of Docker Pulls Per Node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(aggregation:docker:action_count{customer=~\"$customer\", installation=~\"$management_cluster\", action=\"pull\"}[24h])) by (installation, cluster_id) / sum(aggregation:kubernetes:node_total{customer=~\"$customer\", installation=~\"$management_cluster\"}) by (installation, cluster_id)",
     "legendFormat": "{{installation}} - {{cluster_id}}"
    }
   ]
  }
 ]
}