{
 "title": "Prometheus and Mimir resource usage",
 "description": "The goal of this dashboard is to compare resource usage before and after migration to mimir, especially for RAM usage.",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "installation",
    "query": {
     "query": "label_values(aggregation:giantswarm:cluster_info,installation)"
    }
   },
   {
    "name": "customer",
    "label": "Customer",
    "query": {
     "query": "label_values(aggregation:mimir:memory_usage,customer)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "RAM usage total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(aggregation:prometheus:memory_usage{installation=~\"$installation\",customer=~\"$customer\"})",
     "legendFormat": "Prometheus RAM"
    },
    {
     "expr": "sum(aggregation:mimir:memory_usage{installation=~\"$installation\",customer=~\"$customer\"})",
     "legendFormat": "Mimir RAM"
    }
   ]
  },
  {
   "title": "RAM usage by installation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(aggregation:prometheus:memory_usage{installation=~\"$installation\",customer=~\"$customer\"}) by (installation)",
     "legendFormat": "Prometheus RAM for {{installation}}"
    },
    {
     "expr": "sum(aggregation:mimir:memory_usage{installation=~\"$installation\",customer=~\"$customer\"}) by (installation)",
     "legendFormat": "Mimir RAM for {{installation}}"
    }
   ]
  },
  {
   "title": "Scraped series",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_head_series{installation=~\"$installation\"}) by (installation)",
     "legendFormat": "Prometheus scraped samples for {{installation}}"
    },
    {
     "expr": "sum(aggregation:mimir:scrape_samples_post_metric_relabeling{installation=~\"$installation\"}) by (installation)",
     "legendFormat": "Mimir scraped samples for {{installation}}"
    }
   ]
  },
  {
   "title": "New series",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum(irate(prometheus_tsdb_head_samples_appended_total{installation=~\"$installation\"}[$__rate_interval])) by (installation)",
     "legendFormat": "Prometheus new series for {{installation}}"
    },
    {
     "expr": "sum(aggregation:mimir:scrape_series_added{installation=~\"$installation\"}) by (installation)",
     "legendFormat": "Mimir new series for {{installation}}"
    }
   ]
  }
 ]
}