{
 "title": "CIS Compliance Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "CAPA CIS Compliance Failed checks",
   "type": "stat",
   "description": "The amount of CIS Compliancy checks that fail on the CAPA provider. \nWe don't take check in account that fail in workload categories (5.*)",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(last_over_time(aggregation:cluster_compliance_info{title=\"CIS Kubernetes Benchmarks v1.23\", status=\"Fail\", compliance_id!~\"5.*\",provider=\"capa\"}[1d])) by (compliance_id))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CAPZ CIS Compliance Failed checks",
   "type": "stat",
   "description": "The amount of CIS Compliancy checks that fail on the CAPZ provider. \nWe don't take check in account that fail in workload categories (5.*)",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(last_over_time(aggregation:cluster_compliance_info{title=\"CIS Kubernetes Benchmarks v1.23\", status=\"Fail\", compliance_id!~\"5.*\",provider=\"capz\"}[1d])) by (compliance_id))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VSphere CIS Compliance Failed checks",
   "type": "stat",
   "description": "The amount of CIS Compliancy checks that fail on the Vsphere provider. \nWe don't take check in account that fail in workload categories (5.*)",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(last_over_time(aggregation:cluster_compliance_info{title=\"CIS Kubernetes Benchmarks v1.23\", status=\"Fail\", compliance_id!~\"5.*\",provider=\"vsphere\"}[1d])) by (compliance_id))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CAPVCD CIS Compliance Failed checks",
   "type": "stat",
   "description": "The amount of CIS Compliancy checks that fail on the CAPVCD (Cloud-Director) provider. \nWe don't take check in account that fail in workload categories (5.*)",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(last_over_time(aggregation:cluster_compliance_info{title=\"CIS Kubernetes Benchmarks v1.23\", status=\"Fail\", compliance_id!~\"5.*\",provider=\"cloud-director\"}[1d])) by (compliance_id))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Percentage of failing checks severity.",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(last_over_time(aggregation:cluster_compliance_info{title=\"CIS Kubernetes Benchmarks v1.23\", status=\"Fail\", compliance_id!~\"5.*\", severity=\"CRITICAL\"}[1d])) by (compliance_id))",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(count(last_over_time(aggregation:cluster_compliance_info{title=\"CIS Kubernetes Benchmarks v1.23\", status=\"Fail\", compliance_id!~\"5.*\", severity=\"HIGH\"}[1d])) by (compliance_id))",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(count(last_over_time(aggregation:cluster_compliance_info{title=\"CIS Kubernetes Benchmarks v1.23\", status=\"Fail\", compliance_id!~\"5.*\", severity=\"MEDIUM\"}[1d])) by (compliance_id))",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(count(last_over_time(aggregation:cluster_compliance_info{title=\"CIS Kubernetes Benchmarks v1.23\", status=\"Fail\", compliance_id!~\"5.*\", severity=\"LOW\"}[1d])) by (compliance_id))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CIS Compliance check status per cluster",
   "type": "table",
   "gridPos": { "h": 43, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "avg(aggregation:cluster_compliance_info{title=\"CIS Kubernetes Benchmarks v1.23\",compliance_id!~\"5.*\"}) by (cluster_id,compliance_id,status)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}