{
 "title": "Failing service and pod monitors",
 "tags": [ "owner:team-atlas" ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster_type",
    "label": "Cluster Type",
    "query": {
     "query": "label_values(aggregation:giantswarm:cluster_info,cluster_type)"
    }
   },
   {
    "name": "installation",
    "label": "Installation",
    "query": {
     "query": "label_values(aggregation:giantswarm:cluster_info{cluster_type=~\"$cluster_type\"},installation)"
    }
   },
   {
    "name": "cluster_id",
    "label": "Cluster",
    "query": {
     "query": "label_values(aggregation:giantswarm:cluster_info{cluster_type=~\"$cluster_type\", installation=~\"$installation\"},cluster_id)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(aggregation:giantswarm:jobscrapingfailures{cluster_type=~\"$cluster_type\", installation=~\"$installation\", cluster_id=~\"$cluster_id\"},job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total failing jobs",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(aggregation:giantswarm:jobscrapingfailures{cluster_type=~\"$cluster_type\", installation=~\"$installation\", cluster_id=~\"$cluster_id\", job=~\"$job\"}) by (job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failing jobs per installation",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(aggregation:giantswarm:jobscrapingfailures{cluster_type=~\"$cluster_type\", installation=~\"$installation\", cluster_id=~\"$cluster_id\", job=~\"$job\"}) by (installation)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total failing jobs over time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(aggregation:giantswarm:jobscrapingfailures{cluster_type=~\"$cluster_type\", installation=~\"$installation\", cluster_id=~\"$cluster_id\", job=~\"$job\"}) by (job, cluster_id, installation)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}