{
 "title": "AWS releases and workload clusters",
 "description": "Show in detail where which AWS releases are in use",
 "tags": [ "owner:team-phoenix" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "installation",
    "query": {
     "query": "label_values(aggregation:giantswarm:cluster_release_version{provider=~\"$provider\"},installation)"
    }
   },
   {
    "name": "release_version",
    "label": "Release",
    "query": {
     "query": "label_values(aggregation:giantswarm:cluster_release_version{provider=~\"aws|capa\", pipeline=\"stable\"},release_version)"
    }
   },
   { "name": "provider", "label": "provider", "query": { "query": "label_values(provider)" } }
  ]
 },
 "panels": [
  {
   "title": "Releases in use",
   "type": "stat",
   "description": "Number of releases in use in tenant clusters",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(sum(aggregation:giantswarm:cluster_release_version{provider=~\"aws|capa\",pipeline=\"stable\", installation=~\"$installation\"}) by (release_version))"
    }
   ]
  },
  {
   "title": "Each release version",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Installations using release $release_version",
     "type": "timeseries",
     "description": "Show which installations have cluster with the given version",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 6 },
     "repeat": "release_version",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count(aggregation:giantswarm:cluster_release_version{provider=\"$provider\", release_version=~\"$release_version\", installation=~\"$installation\"}) by (installation)",
       "legendFormat": "{{ installation }}"
      }
     ]
    }
   ]
  },
  { "title": "Each installation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Releases used in installation - $installation",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "repeat": "installation",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(aggregation:giantswarm:cluster_release_version{provider=~\"aws|capa\", installation=~\"$installation\"}) by (release_version)",
     "legendFormat": "{{ release_version }}"
    }
   ]
  }
 ]
}