{
 "title": "Operational Load",
 "time": { "from": "now-80d", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Postmortems",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "operations_github_issue_total{type=\"postmortem\", state=\"open\", team!=\"\"}",
     "legendFormat": "{{team}}"
    }
   ]
  },
  {
   "title": "Clusters",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "count(count(aggregation:giantswarm:cluster_info{cluster_type=\"management_cluster\"}) by (installation))",
     "legendFormat": "Management Clusters"
    },
    {
     "expr": "count(aggregation:giantswarm:cluster_info{cluster_type=\"workload_cluster\"})",
     "legendFormat": "Workload Clusters"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(aggregation:node:cpu_cores_total)",
     "legendFormat": "Cores"
    },
    {
     "expr": "sum(aggregation:node:memory_memtotal_bytes_total)",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Business Hours Opsgenie Pages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "round(increase(operations_opsgenie_alert_total{type=\"business_hours\"}[24h]))",
     "legendFormat": "{{team}}"
    }
   ]
  },
  {
   "title": "Business Hours Opsgenie Pages per week",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "round(increase(operations_opsgenie_alert_total{type=\"business_hours\"}[7d]))",
     "legendFormat": "{{team}}"
    }
   ]
  },
  {
   "title": "Rate of Business Hours Opsgenie Pages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "rate(operations_opsgenie_alert_total{type=\"business_hours\"}[24h]) * 60 * 60 * 24",
     "legendFormat": "{{team}}"
    }
   ]
  },
  {
   "title": "Out of Business Hours Opsgenie Pages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "round(increase(operations_opsgenie_alert_total{type=\"out_of_business_hours\"}[24h]))",
     "legendFormat": "{{team}}"
    }
   ]
  },
  {
   "title": "Out of Business Hours Opsgenie Pages per week",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "round(increase(operations_opsgenie_alert_total{type=\"out_of_business_hours\"}[7d]))",
     "legendFormat": "{{team}}"
    }
   ]
  },
  {
   "title": "Rate of out of Business Hours Opsgenie Pages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "expr": "rate(operations_opsgenie_alert_total{type=\"out_of_business_hours\"}[24h]) * 60 * 60 * 24",
     "legendFormat": "{{team}}"
    }
   ]
  },
  {
   "title": "Urgent Emails",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "round(increase(operations_opsgenie_alert_total{name=\"urgent_email\"}[24h]))",
     "legendFormat": "Urgent Emails"
    }
   ]
  },
  {
   "title": "Urgent Emails per week",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "round(increase(operations_opsgenie_alert_total{name=\"urgent_email\"}[7d]))",
     "legendFormat": "Urgent Emails"
    }
   ]
  },
  {
   "title": "Rate of Urgent Emails",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "targets": [
    {
     "expr": "rate(operations_opsgenie_alert_total{name=\"urgent_email\"}[24h]) * 60 * 60 * 24",
     "legendFormat": "Urgent Emails"
    }
   ]
  },
  {
   "title": "Incidents",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "round(increase(operations_incident_io_incident_total{team!=\"\"}[24h]))",
     "legendFormat": "{{team}}"
    }
   ]
  },
  {
   "title": "Incidents per week",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "targets": [
    {
     "expr": "round(increase(operations_incident_io_incident_total{team!=\"\"}[7d]))",
     "legendFormat": "{{team}}"
    }
   ]
  },
  {
   "title": "Rate of Incidents",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "targets": [
    {
     "expr": "rate(operations_incident_io_incident_total{team!=\"\"}[24h]) * 60 * 60 * 24",
     "legendFormat": "{{team}}"
    }
   ]
  }
 ]
}