{
 "title": "Images from deprecated registries",
 "tags": [ "owner:team-honeybadger" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "customer",
    "label": "Customer",
    "query": {
     "query": "label_values({__name__=~ \"aggregation:docker:containers_from_deprecated_registries:(dockerhub|quay)\"}, customer)"
    }
   },
   { "name": "image_filter", "label": "Image name" },
   { "name": "pod_filter", "label": "Pod name" }
  ]
 },
 "panels": [
  {
   "title": "About this dashboard",
   "type": "text",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "# Containers from deprecated registries\n\nOur goal is to phase out the use of `quay.io/giantswarm/` and `docker.io/giantswarm` for container images. This dashboards shows aggregated data about containers created through images from deprecated registries.\n\nNote the filter options above. The **Image** filter allows to enter a substring of an image identifier, to narrow down the dashboard data to a particular image.\n\nFor more information about the individual images and containers, you can also follow the links on the installation names to jump into a dashboard for that installation.\n\n[Related GitHub issue](https://github.com/giantswarm/roadmap/issues/3935)"
   }
  },
  {
   "title": "Total containers",
   "type": "timeseries",
   "description": "Total containers still running using images from deprecated registries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(aggregation:docker:containers_from_deprecated_registries:dockerhub{customer=~\"$customer\",image=~\".*$image_filter.*\",pod=~\".*$pod_filter.*\"} or aggregation:docker:containers_from_deprecated_registries:quay{customer=~\"$customer\",image=~\".*$image_filter.*\",pod=~\".*$pod_filter.*\"})",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Customers",
   "type": "stat",
   "description": "Number of customers running containers from deprecated registries (current snapshot)",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(aggregation:docker:containers_from_deprecated_registries:dockerhub{customer=~\"$customer\",image=~\".*$image_filter.*\",pod=~\".*$pod_filter.*\"} OR aggregation:docker:containers_from_deprecated_registries:quay{customer=~\"$customer\",image=~\".*$image_filter.*\",pod=~\".*$pod_filter.*\"}) by (customer))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Installations",
   "type": "stat",
   "description": "Number of installations running containers from deprecated registries (current snapshot)",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(aggregation:docker:containers_from_deprecated_registries:dockerhub{customer=~\"$customer\",image=~\".*$image_filter.*\",pod=~\".*$pod_filter.*\"} OR aggregation:docker:containers_from_deprecated_registries:quay{customer=~\"$customer\",image=~\".*$image_filter.*\",pod=~\".*$pod_filter.*\"}) by (installation))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Clusters",
   "type": "stat",
   "description": "Number of clusters running containers from deprecated registries (current snapshot)",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(aggregation:docker:containers_from_deprecated_registries:dockerhub{customer=~\"$customer\",image=~\".*$image_filter.*\",pod=~\".*$pod_filter.*\"} OR aggregation:docker:containers_from_deprecated_registries:quay{customer=~\"$customer\",image=~\".*$image_filter.*\",pod=~\".*$pod_filter.*\"}) by (cluster_id))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Images",
   "type": "stat",
   "description": "Number of distinct images from deprecated registries used in running containers",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(aggregation:docker:containers_from_deprecated_registries:dockerhub{customer=~\"$customer\",image=~\".*$image_filter.*\",pod=~\".*$pod_filter.*\"} OR aggregation:docker:containers_from_deprecated_registries:quay{customer=~\"$customer\",image=~\".*$image_filter.*\",pod=~\".*$pod_filter.*\"}) by (image))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "stat",
   "description": "Number of containers from deprecated registries running",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:docker:containers_from_deprecated_registries:dockerhub{customer=~\"$customer\",image=~\".*$image_filter.*\",pod=~\".*$pod_filter.*\"} OR aggregation:docker:containers_from_deprecated_registries:quay{customer=~\"$customer\",image=~\".*$image_filter.*\",pod=~\".*$pod_filter.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "List by customer",
   "type": "table",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(aggregation:docker:containers_from_deprecated_registries:dockerhub{customer=~\"$customer\",image=~\".*$image_filter.*\",pod=~\".*$pod_filter.*\"}) by (customer)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(aggregation:docker:containers_from_deprecated_registries:quay{customer=~\"$customer\",image=~\".*$image_filter.*\",pod=~\".*$pod_filter.*\"}) by (customer)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "List by installation",
   "type": "table",
   "description": "Links lead to detailed dashboard in the MC",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 13 },
   "targets": [
    {
     "expr": "sum(aggregation:docker:containers_from_deprecated_registries:dockerhub{customer=~\"$customer\",image=~\".*$image_filter.*\",pod=~\".*$pod_filter.*\"}) by (installation)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(aggregation:docker:containers_from_deprecated_registries:quay{customer=~\"$customer\",image=~\".*$image_filter.*\",pod=~\".*$pod_filter.*\"}) by (installation)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "List by provider",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
   "targets": [
    {
     "expr": "sum(aggregation:docker:containers_from_deprecated_registries:dockerhub{customer=~\"$customer\",image=~\".*$image_filter.*\",pod=~\".*$pod_filter.*\"}) by (provider)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(aggregation:docker:containers_from_deprecated_registries:quay{customer=~\"$customer\",image=~\".*$image_filter.*\",pod=~\".*$pod_filter.*\"}) by (provider)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "List by cluster type",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 20 },
   "targets": [
    {
     "expr": "sum(aggregation:docker:containers_from_deprecated_registries:dockerhub{customer=~\"$customer\",image=~\".*$image_filter.*\",pod=~\".*$pod_filter.*\"}) by (cluster_type)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(aggregation:docker:containers_from_deprecated_registries:quay{customer=~\"$customer\",image=~\".*$image_filter.*\",pod=~\".*$pod_filter.*\"}) by (cluster_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Images by registry",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Dockerhub",
     "type": "table",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 73 },
     "targets": [
      {
       "expr": "sum(aggregation:docker:containers_from_deprecated_registries:dockerhub{customer=~\"$customer\",image=~\".*$image_filter.*\",pod=~\".*$pod_filter.*\"}) by (image)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Quay",
     "type": "table",
     "gridPos": { "h": 15, "w": 12, "x": 12, "y": 73 },
     "targets": [
      {
       "expr": "sum(aggregation:docker:containers_from_deprecated_registries:quay{customer=~\"$customer\",image=~\".*$image_filter.*\",pod=~\".*$pod_filter.*\"}) by (image)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Full list", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Full list",
   "type": "table",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "aggregation:docker:containers_from_deprecated_registries:dockerhub{customer=~\"$customer\",image=~\".*$image_filter.*\",pod=~\".*$pod_filter.*\"} or aggregation:docker:containers_from_deprecated_registries:quay{customer=~\"$customer\",image=~\".*$image_filter.*\",pod=~\".*$pod_filter.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Progress over time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Dockerhub",
     "type": "timeseries",
     "description": "Number of containers using images from docker.io/giantswarm",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 92 },
     "targets": [
      {
       "expr": "sum(aggregation:docker:containers_from_deprecated_registries:dockerhub{customer=~\"$customer\",image=~\".*$image_filter.*\",pod=~\".*$pod_filter.*\"}) by (installation)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Quay",
     "type": "timeseries",
     "description": "Number of containers using images from quay.io/giantswarm",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 102 },
     "targets": [
      {
       "expr": "sum(aggregation:docker:containers_from_deprecated_registries:quay{customer=~\"$customer\",image=~\".*$image_filter.*\",pod=~\".*$pod_filter.*\"}) by (installation)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "giantswarm(public).azurecr.io",
     "type": "timeseries",
     "description": "Number of containers using images from giantswarm.azurecr.io and giantswarmpublic.azurecr.io",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 112 },
     "targets": [
      {
       "expr": "sum(aggregation:docker:containers_from_deprecated_registries:giantswarmacr{customer=~\"$customer\",image=~\".*$image_filter.*\",pod=~\".*$pod_filter.*\"})",
       "legendFormat": "giantswarm.azurecr.io"
      },
      {
       "expr": "sum(aggregation:docker:containers_from_deprecated_registries:giantswarmpublicacr{customer=~\"$customer\",image=~\".*$image_filter.*\",pod=~\".*$pod_filter.*\"})",
       "legendFormat": "giantswarmpublic.azurecr.io"
      }
     ]
    }
   ]
  }
 ]
}