{
 "title": "OpenSSF Scorecard Security Overview",
 "tags": [
  "security",
  "openssf",
  "owner:team-shield"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "customer",
    "label": "Customer",
    "query": {
     "query": "label_values(aggregation:openssf_scorecard_overall_score, customer)"
    }
   },
   {
    "name": "installation",
    "label": "Installation",
    "query": {
     "query": "label_values(aggregation:openssf_scorecard_overall_score{customer=~\"$customer\"}, installation)"
    }
   },
   {
    "name": "organization",
    "label": "Organization",
    "query": {
     "query": "label_values(aggregation:openssf_scorecard_overall_score{customer=~\"$customer\", installation=~\"$installation\"}, organization)"
    }
   },
   {
    "name": "repository",
    "label": "Repository",
    "query": {
     "query": "label_values(aggregation:openssf_scorecard_overall_score{customer=~\"$customer\", installation=~\"$installation\", organization=~\"$organization\"}, repository)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": {
    "content": "# Need more info?\n\nThis data includes only public, non-archived, non-fork repositories.\n\nPer-repository detailed data is available in the [gazelle Grafana instance](https://grafana.gazelle.awsprod.gigantic.io)."
   }
  },
  {
   "title": "Average Score (Whole Organization)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "avg(aggregation:openssf_scorecard_overall_score >= 0) by (config)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "High Level Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Total Repositories",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(aggregation:openssf_scorecard_overall_score{customer=~\"$customer\", installation=~\"$installation\", organization=~\"$organization\"})"
    }
   ]
  },
  {
   "title": "Average Overall Score",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(aggregation:openssf_scorecard_overall_score{customer=~\"$customer\", installation=~\"$installation\", organization=~\"$organization\"} > -1)"
    }
   ]
  },
  {
   "title": "Repos with Score < 5",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(aggregation:openssf_scorecard_overall_score{customer=~\"$customer\", installation=~\"$installation\", organization=~\"$organization\"} < 5 and aggregation:openssf_scorecard_overall_score >= 0)"
    }
   ]
  },
  {
   "title": "Repos with No Data",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(aggregation:openssf_scorecard_overall_score{customer=~\"$customer\", installation=~\"$installation\", organization=~\"$organization\"} == -1)"
    }
   ]
  },
  { "title": "Repository Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Repositories Scorecard Overview",
   "type": "table",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "aggregation:openssf_scorecard_overall_score{customer=~\"$customer\", installation=~\"$installation\", organization=~\"$organization\", repository=~\"$repository\"} > -1"
    }
   ]
  },
  {
   "title": "Bottom 10 Repositories",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(aggregation:openssf_scorecard_overall_score{customer=~\"$customer\", installation=~\"$installation\", organization=~\"$organization\", repository=~\"$repository\"} > -1)",
     "legendFormat": "{{repository}}"
    }
   ]
  },
  { "title": "Security Check Analysis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 21 },
   "options": {
    "content": "Detailed Check information is availabe at <https://scorecard.dev/#the-checks>."
   }
  },
  {
   "title": "Average Score per Check Type",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sort_desc(avg by (check) (aggregation:openssf_scorecard_check_score{customer=~\"$customer\", installation=~\"$installation\", organization=~\"$organization\", repository=~\"$repository\"} > -1))",
     "legendFormat": "{{check}}"
    }
   ]
  },
  {
   "title": "Individual Check Scores Heatmap (Table View)",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "aggregation:openssf_scorecard_check_score{customer=~\"$customer\", installation=~\"$installation\", organization=~\"$organization\", repository=~\"$repository\"} > -1"
    }
   ]
  },
  { "title": "Repositories Without Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Repositories Missing Scorecard Analysis",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "aggregation:openssf_scorecard_overall_score{customer=~\"$customer\", installation=~\"$installation\", organization=~\"$organization\"} == -1"
    }
   ]
  }
 ]
}