{
 "title": "Management cluster utilization (request vs actual usage)",
 "description": "This dashboards shows the current resources requested (as in request/limits) vs total amount of resource allocatable by kubernetes.",
 "tags": [ "owner:team-bigmac" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "installation",
    "label": "Installation",
    "query": {
     "query": "label_values(aggregation:kubernetes:pod_resource_requests_cpu_cores, installation)"
    }
   },
   {
    "name": "app",
    "label": "App",
    "query": {
     "query": "label_values(aggregation:kubernetes:pod_resource_requests_cpu_cores{installation=~\"$installation\"}, container)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Available Cores",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:kubernetes:node_allocatable_cpu_cores_total{installation=~\"$installation\", cluster_type=\"management_cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "App Cores",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:kubernetes:pod_resource_requests_cpu_cores{installation=~\"$installation\", container=~\"$app\", container!=\"\", cluster_type=\"management_cluster\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(aggregation:kubernetes:pod_resource_limits_cpu_cores{installation=~\"$installation\", container=~\"$app\", container!=\"\", cluster_type=\"management_cluster\"})",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(aggregation:container:cpu_usage_cores{installation=~\"$installation\", container!=\"\", container=~\"$app\"})",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "App Cores (%)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:kubernetes:pod_resource_requests_cpu_cores{installation=~\"$installation\", container!=\"\", container=~\"$app\", cluster_type=\"management_cluster\"}) / sum(aggregation:kubernetes:node_allocatable_cpu_cores_total{installation=~\"$installation\", cluster_type=\"management_cluster\"}) * 100",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(aggregation:kubernetes:pod_resource_limits_cpu_cores{installation=~\"$installation\", container!=\"\", container=~\"$app\", cluster_type=\"management_cluster\"}) / sum(aggregation:kubernetes:node_allocatable_cpu_cores_total{installation=~\"$installation\", cluster_type=\"management_cluster\"}) * 100",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(aggregation:container:cpu_usage_cores{installation=~\"$installation\", container!=\"\", container=~\"$app\"}) / sum(aggregation:kubernetes:node_allocatable_cpu_cores_total{installation=~\"$installation\", cluster_type=\"management_cluster\"}) * 100",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:kubernetes:node_allocatable_memory_bytes{installation=~\"$installation\", cluster_type=\"management_cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "App Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:kubernetes:pod_resource_requests_memory_bytes{installation=~\"$installation\", container!=\"\", container=~\"$app\", cluster_type=\"management_cluster\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(aggregation:kubernetes:pod_resource_limits_memory_bytes{installation=~\"$installation\", container!=\"\", container=~\"$app\", cluster_type=\"management_cluster\"})",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(aggregation:container:memory_usage_bytes{installation=~\"$installation\", container!=\"\", container=~\"$app\"})",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "App Memory (%)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:kubernetes:pod_resource_requests_memory_bytes{installation=~\"$installation\", container!=\"\", container=~\"$app\", cluster_type=\"management_cluster\"}) / sum(aggregation:kubernetes:node_allocatable_memory_bytes{installation=~\"$installation\", cluster_type=\"management_cluster\"}) * 100",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(aggregation:kubernetes:pod_resource_limits_memory_bytes{installation=~\"$installation\", container!=\"\", container=~\"$app\", cluster_type=\"management_cluster\"}) / sum(aggregation:kubernetes:node_allocatable_memory_bytes{installation=~\"$installation\", cluster_type=\"management_cluster\"}) * 100",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(aggregation:container:memory_usage_bytes{installation=~\"$installation\", container!=\"\", container=~\"$app\"}) / sum(aggregation:kubernetes:node_allocatable_memory_bytes{installation=~\"$installation\", cluster_type=\"management_cluster\"}) * 100",
     "legendFormat": "Usage"
    }
   ]
  },
  { "title": "Apps", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Apps",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(aggregation:kubernetes:pod_resource_requests_cpu_cores{installation=~\"$installation\", container=~\"$app\", cluster_type=\"management_cluster\", container!=\"\"}) by (container)",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "sum(aggregation:kubernetes:pod_resource_limits_cpu_cores{installation=~\"$installation\", container=~\"$app\", container!=\"\", cluster_type=\"management_cluster\"}) by (container)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(avg_over_time(aggregation:container:cpu_usage_cores{installation=~\"$installation\", container!=\"\", container=~\"$app\"}[1d])) by (container)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(aggregation:kubernetes:pod_resource_requests_memory_bytes{installation=~\"$installation\", container!=\"\", container=~\"$app\", cluster_type=\"management_cluster\"}) by (container)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(aggregation:kubernetes:pod_resource_limits_memory_bytes{installation=~\"$installation\", container!=\"\", container=~\"$app\", cluster_type=\"management_cluster\"}) by (container)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(avg_over_time(aggregation:container:memory_usage_bytes{installation=~\"$installation\", container!=\"\", container=~\"$app\"}[1d])) by (container)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(avg_over_time(aggregation:kubernetes:pod_resource_requests_cpu_cores{installation=~\"$installation\", container=~\"$app\", cluster_type=\"management_cluster\", container!=\"\"}[1d])) by (container) - sum(avg_over_time(aggregation:container:cpu_usage_cores{installation=~\"$installation\", container=~\"$app\", cluster_type=\"management_cluster\", container!=\"\"}[1d])) by (container)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(avg_over_time(aggregation:kubernetes:pod_resource_requests_memory_bytes{installation=~\"$installation\", container=~\"$app\", cluster_type=\"management_cluster\", container!=\"\"}[1d])) by (container) - sum(avg_over_time(aggregation:container:memory_usage_bytes{installation=~\"$installation\", container=~\"$app\", cluster_type=\"management_cluster\", container!=\"\"}[1d])) by (container)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Installations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Apps per Installation",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(label_join(aggregation:kubernetes:pod_resource_requests_cpu_cores{installation=~\"$installation\", container=~\"$app\", cluster_type=\"management_cluster\", container!=\"\"}, \"combined\", \"_\", \"installation\", \"container\")) by (combined, installation, container)",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "sum(label_join(aggregation:kubernetes:pod_resource_limits_cpu_cores{installation=~\"$installation\", container=~\"$app\", container!=\"\", cluster_type=\"management_cluster\"}, \"combined\", \"_\", \"installation\", \"container\")) by (combined, installation, container)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(label_join(avg_over_time(aggregation:container:cpu_usage_cores{installation=~\"$installation\", container!=\"\", container=~\"$app\"}[1d]), \"combined\", \"_\", \"installation\", \"container\")) by (combined, installation, container)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(label_join(aggregation:kubernetes:pod_resource_requests_memory_bytes{installation=~\"$installation\", container!=\"\", container=~\"$app\", cluster_type=\"management_cluster\"}, \"combined\", \"_\", \"installation\", \"container\")) by (combined, installation, container)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(label_join(aggregation:kubernetes:pod_resource_limits_memory_bytes{installation=~\"$installation\", container!=\"\", container=~\"$app\", cluster_type=\"management_cluster\"}, \"combined\", \"_\", \"installation\", \"container\")) by (combined, installation, container)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(label_join(avg_over_time(aggregation:container:memory_usage_bytes{installation=~\"$installation\", container!=\"\", container=~\"$app\"}[1d]), \"combined\", \"_\", \"installation\", \"container\")) by (combined, installation, container)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(label_join(avg_over_time(aggregation:kubernetes:pod_resource_requests_cpu_cores{installation=~\"$installation\", container=~\"$app\", cluster_type=\"management_cluster\", container!=\"\"}[1d]), \"combined\", \"_\", \"installation\", \"container\")) by (combined, installation, container) - sum(label_join(avg_over_time(aggregation:container:cpu_usage_cores{installation=~\"$installation\", container=~\"$app\", cluster_type=\"management_cluster\", container!=\"\"}[1d]), \"combined\", \"_\", \"installation\", \"container\")) by (combined, installation, container)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(label_join(avg_over_time(aggregation:kubernetes:pod_resource_requests_memory_bytes{installation=~\"$installation\", container=~\"$app\", cluster_type=\"management_cluster\", container!=\"\"}[1d]), \"combined\", \"_\", \"installation\", \"container\")) by (combined, installation, container) - sum(label_join(avg_over_time(aggregation:container:memory_usage_bytes{installation=~\"$installation\", container=~\"$app\", cluster_type=\"management_cluster\", container!=\"\"}[1d]), \"combined\", \"_\", \"installation\", \"container\")) by (combined, installation, container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Installations",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum(aggregation:kubernetes:pod_resource_requests_cpu_cores{installation=~\"$installation\", cluster_type=\"management_cluster\", container!=\"\"}) by (installation)",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "sum(aggregation:kubernetes:pod_resource_limits_cpu_cores{installation=~\"$installation\", container!=\"\", cluster_type=\"management_cluster\"}) by (installation)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(avg_over_time(aggregation:container:cpu_usage_cores{installation=~\"$installation\", container!=\"\", container=~\"$app\"}[1d])) by (installation)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(aggregation:kubernetes:pod_resource_requests_memory_bytes{installation=~\"$installation\", container!=\"\", cluster_type=\"management_cluster\"}) by (installation)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(aggregation:kubernetes:pod_resource_limits_memory_bytes{installation=~\"$installation\", container!=\"\", cluster_type=\"management_cluster\"}) by (installation)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(avg_over_time(aggregation:container:memory_usage_bytes{installation=~\"$installation\", container!=\"\"}[1d])) by (installation)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(avg_over_time(aggregation:kubernetes:pod_resource_requests_cpu_cores{installation=~\"$installation\", cluster_type=\"management_cluster\", container!=\"\"}[1d])) by (installation) - sum(avg_over_time(aggregation:container:cpu_usage_cores{installation=~\"$installation\", cluster_type=\"management_cluster\", container!=\"\"}[1d])) by (installation)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(avg_over_time(aggregation:kubernetes:pod_resource_requests_memory_bytes{installation=~\"$installation\", cluster_type=\"management_cluster\", container!=\"\"}[1d])) by (installation) - sum(avg_over_time(aggregation:container:memory_usage_bytes{installation=~\"$installation\", cluster_type=\"management_cluster\", container!=\"\"}[1d])) by (installation)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}