{
 "title": "AWS EC2 Spot Instance Usage",
 "description": "This dashboard shows how AWS spot instances are distributed in our clusters",
 "tags": [ "owner:team-phoenix" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pipeline",
    "label": "Pipeline",
    "query": {
     "query": "label_values(aggregation:aws:instance_lifecycle, pipeline)"
    }
   },
   {
    "name": "customer",
    "label": "Customer",
    "query": {
     "query": "label_values(aggregation:aws:instance_lifecycle, customer)"
    }
   },
   {
    "name": "installation",
    "label": "Installation",
    "query": {
     "query": "label_values(aggregation:aws:instance_lifecycle{customer=~\"$customer\"}, installation)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Number of Spot Instances",
   "type": "graph",
   "description": "Which percentage of instances on our Installations are Spot",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aggregation:aws:instance_lifecycle{lifecycle=\"spot\", pipeline=~\"$pipeline\", customer=~\"$customer\", installation=~\"$installation\"})"
    }
   ]
  },
  {
   "title": "EC2 Instances by lifecycle",
   "type": "bargauge",
   "description": "Which lifecycle (spot vs scheduled) is used for EC2 Instances and how much",
   "gridPos": { "h": 9, "w": 5, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:aws:instance_lifecycle{pipeline=~\"$pipeline\", customer=~\"$customer\", installation=~\"$installation\"}) by (lifecycle)",
     "legendFormat": "{{ lifecycle }}"
    }
   ]
  },
  {
   "title": "Spot percentage",
   "type": "stat",
   "description": "Spot instances devided by all instances",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:aws:instance_lifecycle{lifecycle=\"spot\",pipeline=~\"$pipeline\",customer=~\"$customer\",installation=~\"$installation\"}) / sum(aggregation:aws:instance_lifecycle{lifecycle!=\"spot\",pipeline=~\"$pipeline\",customer=~\"$customer\",installation=~\"$installation\"})"
    }
   ]
  },
  {
   "title": "Percent of Spot Instances by Installation",
   "type": "graph",
   "description": "Which percentage of instances on our Installations are Spot",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(aggregation:aws:instance_lifecycle{lifecycle=\"spot\", pipeline=~\"$pipeline\", customer=~\"$customer\"}) by (installation) / sum(aggregation:aws:instance_types) by (installation) *100",
     "legendFormat": "{{ installation }}"
    }
   ]
  },
  {
   "title": "Percent of Spot Instances by Customer",
   "type": "graph",
   "description": "Which percentage of instances for our customers are Spot",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(aggregation:aws:instance_lifecycle{lifecycle=\"spot\", pipeline=~\"$pipeline\"}) by (customer) / sum(aggregation:aws:instance_types) by (customer) *100",
     "legendFormat": "{{ installation }}"
    }
   ]
  },
  {
   "title": "Spot Instances by Installation",
   "type": "graph",
   "description": "How many spot instances are there per installation?",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(aggregation:aws:instance_lifecycle{lifecycle=\"spot\", pipeline=~\"$pipeline\", customer=~\"$customer\"}) by (installation)",
     "legendFormat": "{{ installation }}"
    }
   ]
  },
  {
   "title": "Spot Instances by Customer",
   "type": "graph",
   "description": "How many spot instances are there per customer?",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(aggregation:aws:instance_lifecycle{lifecycle=\"spot\", pipeline=~\"$pipeline\"}) by (customer)",
     "legendFormat": "{{ installation }}"
    }
   ]
  }
 ]
}