{
 "title": "Service Level",
 "tags": [ "owner:team-atlas" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "pipeline",
    "label": "Pipeline",
    "query": "label_values(slo_requests, pipeline)"
   },
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(slo_requests{pipeline=~\"$pipeline\"}, service)"
   },
   {
    "name": "customer",
    "label": "Customer",
    "query": "label_values(slo_requests{pipeline=~\"$pipeline\"}, customer)"
   },
   {
    "name": "installation",
    "label": "Installation",
    "query": "label_values(slo_requests{pipeline=~\"$pipeline\", customer=~\"$customer\"}, installation)"
   },
   {
    "name": "cluster_id",
    "label": "Cluster ID",
    "query": "label_values(slo_requests{pipeline=~\"$pipeline\", installation=~\"$installation\", customer=~\"$customer\"}, cluster_id)"
   }
  ]
 },
 "panels": [
  {
   "title": "Currently Alerting Services",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(\n        slo_errors_per_request:ratio_rate1h{pipeline=~\"$pipeline\", service=~\"$service\", customer=~\"$customer\", installation=~\"$installation\", cluster_id=~\"$cluster_id\"} > on (service, cluster_id, installation, label_application_giantswarm_io_team) group_left (cluster_type, class) slo_threshold_high\n        and\n        slo_errors_per_request:ratio_rate5m{pipeline=~\"$pipeline\", service=~\"$service\", customer=~\"$customer\", installation=~\"$installation\", cluster_id=~\"$cluster_id\"} > on (service, cluster_id, installation, label_application_giantswarm_io_team) group_left (cluster_type, class) slo_threshold_high\n        or\n        slo_errors_per_request:ratio_rate6h{pipeline=~\"$pipeline\", service=~\"$service\", customer=~\"$customer\", installation=~\"$installation\", cluster_id=~\"$cluster_id\"} > on (service, cluster_id, installation, label_application_giantswarm_io_team) group_left (cluster_type, class) slo_threshold_low\n        and\n        slo_errors_per_request:ratio_rate30m{pipeline=~\"$pipeline\", service=~\"$service\", customer=~\"$customer\", installation=~\"$installation\", cluster_id=~\"$cluster_id\"} > on (service, cluster_id, installation, label_application_giantswarm_io_team) group_left (cluster_type, class) slo_threshold_low\n      ) by (service, customer, installation, cluster_id)"
    }
   ]
  },
  {
   "title": "Alert",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(\n      slo_errors_per_request:ratio_rate1h{pipeline=~\"$pipeline\", service=~\"$service\", customer=~\"$customer\", installation=~\"$installation\", cluster_id=~\"$cluster_id\"} > on (service, cluster_id, installation, label_application_giantswarm_io_team) group_left (cluster_type, class) slo_threshold_high\n      and\n      slo_errors_per_request:ratio_rate5m{pipeline=~\"$pipeline\", service=~\"$service\", customer=~\"$customer\", installation=~\"$installation\", cluster_id=~\"$cluster_id\"} > on (service, cluster_id, installation, label_application_giantswarm_io_team) group_left (cluster_type, class) slo_threshold_high\n      or\n      slo_errors_per_request:ratio_rate6h{pipeline=~\"$pipeline\", service=~\"$service\", customer=~\"$customer\", installation=~\"$installation\", cluster_id=~\"$cluster_id\"} > on (service, cluster_id, installation, label_application_giantswarm_io_team) group_left (cluster_type, class) slo_threshold_low\n      and\n      slo_errors_per_request:ratio_rate30m{pipeline=~\"$pipeline\", service=~\"$service\", customer=~\"$customer\", installation=~\"$installation\", cluster_id=~\"$cluster_id\"} > on (service, cluster_id, installation, label_application_giantswarm_io_team) group_left (cluster_type, class) slo_threshold_low\n    ) by (service, customer, installation, cluster_id)",
     "legendFormat": "{{service}} / {{installation}} / {{cluster_id}}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "slo_requests{pipeline=~\"$pipeline\", service=~\"$service\", customer=~\"$customer\", installation=~\"$installation\", cluster_id=~\"$cluster_id\"}",
     "legendFormat": "{{service}} / {{installation}} / {{cluster_id}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "slo_errors{pipeline=~\"$pipeline\", service=~\"$service\", customer=~\"$customer\", installation=~\"$installation\", cluster_id=~\"$cluster_id\"}",
     "legendFormat": "{{service}} / {{installation}} / {{cluster_id}}"
    }
   ]
  },
  {
   "title": "High Burn Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "slo_errors_per_request:ratio_rate5m{pipeline=~\"$pipeline\", service=~\"$service\", customer=~\"$customer\", installation=~\"$installation\", cluster_id=~\"$cluster_id\"}",
     "legendFormat": "{{service}} / {{installation}} / {{cluster_id}} (5m)"
    },
    {
     "expr": "slo_errors_per_request:ratio_rate1h{pipeline=~\"$pipeline\", service=~\"$service\", customer=~\"$customer\", installation=~\"$installation\", cluster_id=~\"$cluster_id\"}",
     "legendFormat": "{{service}} / {{installation}} / {{cluster_id}} (1h)"
    },
    {
     "expr": "min(slo_threshold_high{service=~\"$service\", installation=~\"$installation\", cluster_id=~\"$cluster_id\"}) by (service)",
     "legendFormat": "SLO High Threshold - {{service}}"
    }
   ]
  },
  {
   "title": "Low Burn Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "slo_errors_per_request:ratio_rate30m{pipeline=~\"$pipeline\", service=~\"$service\", customer=~\"$customer\", installation=~\"$installation\", cluster_id=~\"$cluster_id\"}",
     "legendFormat": "{{service}} / {{installation}} / {{cluster_id}} (30m)"
    },
    {
     "expr": "slo_errors_per_request:ratio_rate6h{pipeline=~\"$pipeline\", service=~\"$service\", customer=~\"$customer\", installation=~\"$installation\", cluster_id=~\"$cluster_id\"}",
     "legendFormat": "{{service}} / {{installation}} / {{cluster_id}} (6h)"
    },
    {
     "expr": "min(slo_threshold_low{service=~\"$service\", installation=~\"$installation\", cluster_id=~\"$cluster_id\"}) by (service)",
     "legendFormat": "SLO Low Threshold - {{service}}"
    }
   ]
  },
  {
   "title": "SLO targets",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1- min(slo_target{pipeline=~\"$pipeline\", service=~\"$service\", customer=~\"$customer\", installation=~\"$installation\", cluster_id=~\"$cluster_id\"}) by (service)"
    }
   ]
  }
 ]
}