{
 "title": "SLO / Detail",
 "description": "https://sloth.dev",
 "tags": [
  "service levels",
  "sli",
  "slo",
  "sloth"
 ],
 "time": { "from": "now-90d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "installation",
    "query": {
     "query": "label_values(aggregation:slo:objective:ratio,installation)"
    }
   },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(aggregation:slo:current_burn_rate:ratio{installation=\"$installation\"},cluster_id)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(aggregation:slo:objective:ratio{installation=\"$installation\"},service)"
    }
   },
   {
    "name": "slo",
    "query": {
     "query": "label_values(aggregation:slo:objective:ratio{installation=\"$installation\", service=\"$service\"},slo)"
    }
   },
   { "name": "min_burning_rate", "label": "Min Burning rate", "query": "1" }
  ]
 },
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Exceeded burning rate SLOs ",
     "type": "table",
     "description": "The SLOs that currently are burning more error budget that then available",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "aggregation:slo:current_burn_rate:ratio{installation=\"${installation}\", cluster_id=~\"${cluster}\", service=\"${service}\", slo=~\"${slo}\"} > ${min_burning_rate}"
      }
     ]
    },
    {
     "title": "All burning rate (Filtered >${min_burning_rate}x)",
     "type": "timeseries",
     "description": "The burning rate of the all the Service SLOs",
     "gridPos": { "h": 12, "w": 16, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "aggregation:slo:current_burn_rate:ratio{installation=\"${installation}\", cluster_id=~\"${cluster}\", service=\"${service}\", slo=~\"${slo}\"}",
       "legendFormat": "{{sloth_id}}"
      }
     ]
    }
   ]
  },
  { "title": "${service}/${slo}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }, "repeat": "slo" },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aggregation:slo:objective:ratio{installation=\"${installation}\",service=\"${service}\", slo=\"${slo}\"}",
     "legendFormat": "{{slo}}"
    }
   ]
  },
  {
   "title": "SLI",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (max(aggregation:slo:sli_error:ratio_rate5m{installation=\"${installation}\", cluster_id=~\"${cluster}\", service=\"${service}\", slo=~\"${slo}\"}) OR on() vector(0))",
     "legendFormat": "SLI"
    },
    {
     "expr": "aggregation:slo:objective:ratio{installation=\"${installation}\", service=\"${service}\", slo=\"${slo}\"}",
     "legendFormat": "Objective"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aggregation:slo:objective:ratio{installation=\"${installation}\", service=\"${service}\", slo=\"${slo}\"}",
     "legendFormat": "Objective"
    }
   ]
  },
  {
   "type": "stat",
   "description": "This month remaining error budget, starts the 1st of the month and ends  28th-31st (not rolling window)",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1-(\n  sum_over_time(\n    (\n       aggregation:slo:sli_error:ratio_rate5m{installation=\"${installation}\", cluster_id=~\"${cluster}\", service=\"${service}\", slo=\"${slo}\"}\n       * on() group_left() (\n         month() == bool vector(${__to:date:M})\n       )\n    )[32d:1h]\n  )\n  / on(slo)\n  (\n    aggregation:slo:error_budget:ratio{installation=\"${installation}\", cluster_id=~\"${cluster}\", service=\"${service}\", slo=\"${slo}\"} *on() group_left() (12 * 24 * days_in_month())\n  )\n)",
     "legendFormat": "Remaining error budget (month)"
    }
   ]
  },
  {
   "type": "stat",
   "description": "This moment burning % of the budget.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 8 },
   "repeat": "cluster",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aggregation:slo:current_burn_rate:ratio{installation=\"${installation}\", cluster_id=\"${cluster}\", service=\"${service}\", slo=\"${slo}\"}",
     "legendFormat": "{{cluster_id }} - Current burning budget %"
    }
   ]
  },
  {
   "type": "stat",
   "description": "A rolling window of the total period (30d) error budget remaining.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 8 },
   "repeat": "cluster",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - aggregation:slo:period_burn_rate:ratio{installation=\"${installation}\", cluster_id=~\"$cluster\", service=\"${service}\", slo=\"${slo}\"}) or on() vector(1)",
     "legendFormat": "{{ cluster_id}} - Remaining error budget (30d window)"
    }
   ]
  },
  {
   "title": "Month error budget burn chart",
   "type": "timeseries",
   "description": "This graph shows the month error budget burn down chart (starts the 1st until the end of the month)",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1-(\n  sum_over_time(\n    (\n       aggregation:slo:sli_error:ratio_rate5m{installation=\"${installation}\", cluster_id=~\"${cluster}\", service=\"${service}\", slo=\"${slo}\"}\n       * on() group_left() (\n         month() == bool vector(${__to:date:M})\n       )\n    )[32d:5m]\n  )\n  / on(service, slo)\n  (\n    aggregation:slo:error_budget:ratio{installation=\"${installation}\", service=\"${service}\",slo=\"${slo}\"} *on() group_left() (12 * 24 * days_in_month())\n  )\n)",
     "legendFormat": "{{ cluster_id }} - Remaining error budget"
    },
    {
     "expr": "1 - sum_over_time(\n  (\n    (1 / (days_in_month() * 24)) *\n    (month() == bool vector(${__to:date:M}))\n  )[32d:5m]\n)",
     "legendFormat": "Ideal constant consumption"
    }
   ]
  },
  {
   "title": "Burn rate (speed) magnitude",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 11 },
   "targets": [
    {
     "expr": "aggregation:slo:current_burn_rate:ratio{installation=\"${installation}\", cluster_id=~\"${cluster}\", service=\"${service}\", slo=\"${slo}\"} > 0",
     "legendFormat": "{{ cluster_id }} - Burn rate"
    }
   ]
  }
 ]
}