{
 "title": "Organization monitoring",
 "description": "This dashboard serves as a way to monitor grafana organizations across all installations.",
 "tags": [ "owner:team-atlas" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "customer", "query": { "query": "label_values(customer)" } },
   { "name": "installation", "query": { "query": "label_values(installation)" } }
  ]
 },
 "panels": [
  { "title": "Organizations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total active organizations per customer",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(aggregation:observability:organization:organization_info{status=\"active\"}) by (customer)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "list of organizations",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(aggregation:observability:organization:organization_info{customer=~\"$customer\", installation=~\"$installation\", status=\"active\"}) by (customer, installation, display_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "tenants", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Total number of tenants per customer",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(aggregation:observability:organization:organization_tenants) by (customer)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "List of tenants per organization",
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 12 },
   "options": {
    "content": "To view the list of tenants below, you need to select a customer and an installation"
   }
  },
  {
   "title": "List of tenants per organization",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "(sum(aggregation:observability:organization:organization_tenants{customer=~\"$customer\", installation=~\"$installation\"}) by (customer, installation, name, org_id)) * on (org_id) group_left(display_name) aggregation:observability:organization:organization_info{customer=~\"$customer\", installation=~\"$installation\", status=\"active\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}