{
 "title": "Pods",
 "tags": [ "owner:team-turtles" ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:kubelet:running_pod_total{cluster_type=~\"control_plane|management_cluster\"})",
     "legendFormat": "Management Clusters"
    },
    {
     "expr": "sum(aggregation:kubelet:running_pod_total{cluster_type=~\"tenant_cluster|workload_cluster\"})",
     "legendFormat": "Workload Clusters"
    }
   ]
  },
  {
   "title": "Pods managed by",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:kubelet:running_pod_total{cluster_type=~\"control_plane|management_cluster\"}) + sum(aggregation:kubernetes:pod_total{cluster_type=~\"tenant_cluster|workload_cluster\"})",
     "legendFormat": "Giant Swarm"
    },
    {
     "expr": "sum(aggregation:kubelet:running_pod_total{cluster_type=~\"tenant_cluster|workload_cluster\"}) - sum(aggregation:kubernetes:pod_total{cluster_type=~\"tenant_cluster|workload_cluster\"})",
     "legendFormat": "Customers"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:kubelet:running_container_total{cluster_type=~\"control_plane|management_cluster\"})",
     "legendFormat": "Management Clusters"
    },
    {
     "expr": "sum(aggregation:kubelet:running_container_total{cluster_type=~\"tenant_cluster|workload_cluster\"})",
     "legendFormat": "Workload Clusters"
    }
   ]
  },
  {
   "title": "Pod Memory Usage in Workload Clusters",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:kubernetes:pod_resource_requests_memory_bytes{cluster_type=~\"tenant_cluster|workload_cluster\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(aggregation:kubernetes:pod_resource_limits_memory_bytes{cluster_type=~\"tenant_cluster|workload_cluster\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Pod CPU Usage in Workload Clusters",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:kubernetes:pod_resource_requests_cpu_cores{cluster_type=~\"tenant_cluster|workload_cluster\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(aggregation:kubernetes:pod_resource_limits_cpu_cores{cluster_type=~\"tenant_cluster|workload_cluster\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Pods ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(aggregation:kubelet:running_pod_total)",
     "legendFormat": "Pods"
    }
   ]
  },
  {
   "title": "Pods Per Customer",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(aggregation:kubelet:running_pod_total{customer!=\"\"}) by (customer)",
     "legendFormat": "{{customer}}"
    }
   ]
  },
  {
   "title": "Pods Per Installation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(aggregation:kubelet:running_pod_total) by (installation)",
     "legendFormat": "{{installation}}"
    }
   ]
  },
  {
   "title": "Pods Per Provider",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(aggregation:kubelet:running_pod_total{provider!=\"\"}) by (provider)",
     "legendFormat": "{{provider}}"
    }
   ]
  }
 ]
}