{
 "title": "Does my app fit ?",
 "description": "Give cpu and memory, computes the amount of resources for 1 app / workload clusters",
 "tags": [ "owner:team-atlas" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cpu", "label": "cpu (in milli)", "query": "0" },
   { "name": "memory", "query": "150" },
   {
    "name": "memory_unit",
    "label": "memory unit (B, Ki, Mi, Gi, Ti)",
    "query": "1,1024,1048576,1073741824,1099511627776"
   }
  ]
 },
 "panels": [
  {
   "title": "Does my app fit cpu ?",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(aggregation:kubernetes:node_allocatable_cpu_cores_total{cluster_type=~\"control_plane|management_cluster\"})by(cluster_id)-sum(aggregation:kubernetes:pod_resource_requests_cpu_cores{cluster_type=~\"control_plane|management_cluster\"})by(cluster_id) - on(cluster_id) ($cpu/1000*label_replace(sum(aggregation:kubernetes:version{cluster_type=~\"tenant_cluster|workload_cluster\"}) by (installation),\"cluster_id\",\"$1\",\"installation\",\"(.*)\")) OR sum(aggregation:kubernetes:node_allocatable_cpu_cores_total{cluster_type=~\"control_plane|management_cluster\"})by(cluster_id)-sum(aggregation:kubernetes:pod_resource_requests_cpu_cores{cluster_type=~\"control_plane|management_cluster\"})by(cluster_id)",
     "legendFormat": "{{ cluster_id }}"
    }
   ]
  },
  {
   "title": "Does my app fit memory ?",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(aggregation:kubernetes:node_allocatable_memory_bytes{cluster_type=~\"control_plane|management_cluster\"})by(cluster_id)-sum(aggregation:kubernetes:pod_resource_requests_memory_bytes{cluster_type=~\"control_plane|management_cluster\"})by(cluster_id) - on(cluster_id) ($memory*$memory_unit*label_replace(sum(aggregation:kubernetes:version{cluster_type=~\"tenant_cluster|workload_cluster\"}) by (installation),\"cluster_id\",\"$1\",\"installation\",\"(.*)\")) OR sum(aggregation:kubernetes:node_allocatable_memory_bytes{cluster_type=~\"control_plane|management_cluster\"})by(cluster_id)-sum(aggregation:kubernetes:pod_resource_requests_memory_bytes{cluster_type=~\"control_plane|management_cluster\"})by(cluster_id)",
     "legendFormat": "{{ cluster_id }}"
    }
   ]
  },
  {
   "title": "CPU left",
   "type": "bargauge",
   "gridPos": { "h": 19, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:kubernetes:node_allocatable_cpu_cores_total{cluster_type=~\"control_plane|management_cluster\"})by(cluster_id)-sum(aggregation:kubernetes:pod_resource_requests_cpu_cores{cluster_type=~\"control_plane|management_cluster\"})by(cluster_id)",
     "legendFormat": "{{ cluster_id }}"
    }
   ]
  },
  {
   "title": "Memory left",
   "type": "bargauge",
   "gridPos": { "h": 19, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:kubernetes:node_allocatable_memory_bytes{cluster_type=~\"control_plane|management_cluster\"})by(cluster_id)-sum(aggregation:kubernetes:pod_resource_requests_memory_bytes{cluster_type=~\"control_plane|management_cluster\"})by(cluster_id)",
     "legendFormat": "{{ cluster_id }}"
    }
   ]
  },
  {
   "title": "n° workload clusters",
   "type": "bargauge",
   "gridPos": { "h": 19, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(aggregation:kubernetes:version{cluster_type=~\"tenant_cluster|workload_cluster\"}) by (installation)",
     "legendFormat": "{{ installation }}"
    }
   ]
  }
 ]
}