{
 "title": "Security: Overview",
 "tags": [ "owner:team-shield" ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "team",
    "label": "Team",
    "query": {
     "query": "label_values(aggregation:kyverno_policy_status_team, team)"
    }
   },
   {
    "name": "app",
    "label": "App",
    "query": {
     "query": "label_values(aggregation:kyverno_policy_status_team, app)"
    }
   },
   {
    "name": "deployment",
    "label": "Deployment",
    "query": {
     "query": "label_values(aggregation:kyverno_policy_status_team, deployment)"
    }
   },
   {
    "name": "policy",
    "label": "Policy",
    "query": {
     "query": "label_values(aggregation:dipstick_policy_results,policy_name)"
    }
   },
   {
    "name": "customer",
    "label": "Customer",
    "query": {
     "query": "label_values(aggregation:dipstick_policy_results,customer)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Workload Cluster Policies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "PSS Policy Failures by Customer",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(avg_over_time(aggregation:dipstick_policy_results{result=\"fail\", customer=~\"$customer\", policy_name=~\"$policy\"}[1d])) by (customer)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PSS Policy Failures by Cluster",
   "type": "timeseries",
   "gridPos": { "h": 35, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "(sum(aggregation:giantswarm:cluster_release_version{}) by (cluster_id, release_version) == 1)\n* on(cluster_id) group_left(customer)\nsum(avg_over_time(aggregation:dipstick_policy_results{result=\"fail\", customer=~\"$customer\", policy_name=~\"$policy\"}[1d])) by (customer, cluster_id)",
     "legendFormat": "{{customer}} / {{cluster_id}} ({{release_version}})"
    }
   ]
  },
  {
   "title": "Percent Failure per Cluster Version",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "100 * \n# 1 day average count of failed policies\nsum((sum(aggregation:giantswarm:cluster_release_version{}) by (cluster_id, release_version) == 1)\n* on(cluster_id) group_left(customer)\nsum(avg_over_time(aggregation:dipstick_policy_results{result=\"fail\", customer=~\"$customer\", policy_name=~\"$policy\"}[1d])) by (customer, cluster_id)) by (release_version)\n/\n# 1 day average total policy count \nsum((sum(aggregation:giantswarm:cluster_release_version{}) by (cluster_id, release_version) == 1)\n* on(cluster_id) group_left(customer)\nsum(avg_over_time(aggregation:dipstick_policy_results{customer=~\"$customer\", policy_name=~\"$policy\"}[1d])) by (customer, cluster_id)) by (release_version)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PSS Policy Failures by Release Version",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum((sum(aggregation:giantswarm:cluster_release_version{}) by (cluster_id, release_version) == 1)\n* on(cluster_id) group_left(customer)\nsum(avg_over_time(aggregation:dipstick_policy_results{result=\"fail\", customer=~\"$customer\", policy_name=~\"$policy\"}[1d])) by (customer, cluster_id)) by (release_version)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Anomaly Detection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "New Falco Events per Day",
   "type": "stat",
   "description": "Observed on the stable pipeline, per 10 minutes. Logarithmic scale.",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(increase(aggregation:falco_events{pipeline=\"stable\",rule!=\"Falco internal: syscall event drop\"}[1d])) by (rule)",
     "legendFormat": "{{rule}}"
    }
   ]
  },
  {
   "title": "P1, P2, P3 Falco Events per Rule",
   "type": "timeseries",
   "description": "Observed on the stable pipeline, per 10 minutes. Logarithmic scale.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "sum(rate(aggregation:falco_events{pipeline=\"stable\",rule!=\"Falco internal: syscall event drop\",priority=~\"1|2|3\"}[10m])) by (rule)",
     "legendFormat": "{{rule}}"
    }
   ]
  },
  {
   "title": "Falco Events per Rule",
   "type": "timeseries",
   "description": "Observed on the stable pipeline, per 10 minutes. Logarithmic scale.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "sum(rate(aggregation:falco_events{pipeline=\"stable\",rule!=\"Falco internal: syscall event drop\"}[10m])) by (rule)",
     "legendFormat": "{{rule}}"
    }
   ]
  },
  { "title": "Vulnerability Mangement", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Average Vulnerabilities by Severity (C,H,M)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "avg by (severity) (avg_over_time(aggregation:starboard_unique_vulnerability_count{severity=~\"CRITICAL|HIGH|MEDIUM\"}[1h]))",
     "legendFormat": "{{ severity }}"
    }
   ]
  },
  {
   "title": "# of Critical/High Vulnerabilities by Installation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "targets": [
    {
     "expr": "sum(aggregation:starboard_unique_vulnerability_count{severity=~\"CRITICAL|HIGH\"}) by (installation)",
     "legendFormat": "{{ installation }}"
    }
   ]
  },
  {
   "title": "Average Critical/High Vulnerabilities by Pipeline",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "avg by (pipeline) (avg_over_time(aggregation:starboard_unique_vulnerability_count{severity=~\"CRITICAL|HIGH\"}[1h]))",
     "legendFormat": "{{ pipeline }}"
    }
   ]
  },
  {
   "title": "Average Critical/High Vulnerabilities by Customer",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 80 },
   "targets": [
    {
     "expr": "avg by (customer) (avg_over_time(aggregation:starboard_unique_vulnerability_count{severity=~\"CRITICAL|HIGH\"}[1h]))",
     "legendFormat": "{{ customer }}"
    }
   ]
  },
  {
   "title": "Kyverno Policies and Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 }
  },
  {
   "title": "Cluster AdmissionReport Counts",
   "type": "timeseries",
   "description": "Clusters with > 2000 Kyverno AdmissionReports. Logarithmic scale.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 90 },
   "targets": [
    {
     "expr": "aggregation:kyverno_resource_counts{kind=\"admissionreports.kyverno.io\"} > 2000",
     "legendFormat": "{{installation}}/{{cluster_id}}"
    }
   ]
  },
  {
   "title": "Failing Kyverno Policies per Day",
   "type": "stat",
   "description": "Rate of Kyverno policy failures in stable pipeline clusters, per day.\nNot shown: deprecated APIs and strict capabilities, due to noise",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 98 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(increase(aggregation:kyverno_policy_failures{policy_name!~\"check-deprecated-apis|capo-policy\", pipeline=\"stable\"}[1d])) by (policy_name)",
     "legendFormat": "{{ policy_name }}"
    }
   ]
  }
 ]
}