{
 "title": "Control Plane Apps",
 "tags": [ "owner:team-honeybadger" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "customer", "label": "Customer", "query": { "query": "label_values(customer)" } },
   { "name": "provider", "label": "Provider", "query": { "query": "label_values(provider)" } }
  ]
 },
 "panels": [
  {
   "title": "Managed Apps",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(aggregation:kubernetes:version{customer=~\"$customer\",provider=~\"$provider\",pipeline=\"stable\"})",
     "legendFormat": "Control Planes"
    },
    {
     "expr": "sum(aggregation:giantswarm:app_deployed_management_cluster_total{customer=~\"$customer\",provider=~\"$provider\",pipeline=\"stable\"})",
     "legendFormat": "Apps"
    }
   ]
  },
  {
   "title": "Managed Apps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(aggregation:giantswarm:app_deployed_management_cluster_total{customer=~\"$customer\",provider=~\"$provider\",pipeline=\"stable\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Versions of cluster-operator",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(aggregation:giantswarm:app_deployed_management_cluster_total{customer=~\"$customer\",provider=~\"$provider\",name=~\"cluster-operator.*\",pipeline=\"stable\"}) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Versions of aws-operator",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(aggregation:giantswarm:app_deployed_management_cluster_total{customer=~\"$customer\",provider=~\"$provider\",name=~\"aws-operator.*\",pipeline=\"stable\"}) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Versions of azure-operator",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(aggregation:giantswarm:app_deployed_management_cluster_total{customer=~\"$customer\",provider=~\"$provider\",name=~\"azure-operator.*\",pipeline=\"stable\"}) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Versions of kvm-operator",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(aggregation:giantswarm:app_deployed_management_cluster_total{customer=~\"$customer\",provider=~\"$provider\",name=~\"kvm-operator.*\",pipeline=\"stable\"}) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Versions of app-operator",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(aggregation:giantswarm:app_deployed_management_cluster_total{customer=~\"$customer\",provider=~\"$provider\",name=~\"app-operator.*\",pipeline=\"stable\"}) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Versions of release-operator",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(aggregation:giantswarm:app_deployed_management_cluster_total{customer=~\"$customer\",provider=~\"$provider\",name=~\"release-operator.*\",pipeline=\"stable\"}) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Versions of GS Apps",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(aggregation:giantswarm:app_deployed_management_cluster_total{customer=~\"$customer\",provider=~\"$provider\",name=~\"g8s-.*\",pipeline=\"stable\"}) by (name,version)",
     "legendFormat": "{{name}} {{version}}"
    }
   ]
  }
 ]
}