{
 "title": "Cilium performance",
 "tags": [ "owner:team-cabbage" ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster_id",
    "query": {
     "query": "label_values(cilium_version,cluster_id)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(cilium_version{cluster_id=\"$cluster_id\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Info",
   "type": "text",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "Please conslut https://intranet.giantswarm.io/docs/dev-and-releng/cilium/cilium-performance-issues/ intranet page for learn more about this dashboard."
   }
  },
  { "title": "Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Number of pods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "count(kube_pod_created{cluster_id=\"$cluster_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Endpoints", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Endpoint state",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(cilium_endpoint_state{cluster_id=\"$cluster_id\", pod=~\"$pod\"}) by (endpoint_state)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Endpoints",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum(cilium_endpoint{cluster_id=\"$cluster_id\", pod=~\"$pod\"})",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "Endpoint regeneration rate [2m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 14 },
   "targets": [
    {
     "expr": "sum(rate(cilium_endpoint_regenerations_total{cluster_id=\"$cluster_id\",pod=~\"$pod\"}[2m])) by(outcome)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Identities", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Identities",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum(cilium_identity{cluster_id=\"$cluster_id\", pod=~\"$pod\"}) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Cilium process CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "min(irate(cilium_process_cpu_seconds_total{cluster_id=\"$cluster_id\",pod=~\"$pod\"}[5m])) by (pod) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "FailedCreatePodSandBox events rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "sum(rate(etcd_kubernetes_events_count{cluster_id=\"$cluster_id\",reason=\"FailedCreatePodSandBox\"}[5m])) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  { "title": "API performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "API process time [seconds] > 50s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "avg(rate(cilium_agent_api_process_time_seconds_sum{cluster_id=\"$cluster_id\",pod=~\"$pod\"}[5m])/rate(cilium_agent_api_process_time_seconds_count{cluster_id=\"$cluster_id\",pod=~\"$pod\"}[5m]) > 50) by (pod, method, path)",
     "legendFormat": "{{pod}} {{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Endpoint regeneration rate 99th percentile [5m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.99, rate(cilium_endpoint_regeneration_time_stats_seconds_bucket{cluster_id=\"$cluster_id\",scope!=\"total\", pod=~\"$pod\"}[5m]))) by (scope)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "BPF", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "BPF map pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "cilium_bpf_map_pressure{cluster_id=\"$cluster_id\",pod=~\"$pod\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}