name: pre-commit

on:
  pull_request:
    branches:
      - main
    paths:
      - 'helm/dashboards/**' # helm chart directory

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Cache pre-commit hooks
      uses: actions/cache@v2
      with:
        path: ~/.cache/pre-commit
        key: ${{ runner.os }}-precommit-${{ hashFiles('.pre-commit-config.yaml') }}
    - name: Install pre-commit
      run: pip install pre-commit
    - name: Run pre-commit on changed files
      run: pre-commit run --show-diff-on-failure --color=always --all-files
