name: update-monitoring-mixins

on:
  pull_request:
  workflow_dispatch:

jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Sync dashboards 
      run: ./scripts/update-monitoring-mixin-dashboards.sh

    - name: Set up git identity
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
    - name: Commit update
      run: |
        git add ./helm/dashboards
        git commit -m "Update Monitoring mixins dashboards"
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        title: Update Monitoring mixins dashboards
        branch: update-mixins-dashboard
