name: update-monitoring-mixins

on:
  pull_request:
  workflow_dispatch:

jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Sync dashboards 
      run: ./scripts/update-monitoring-mixin-dashboards.sh

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4.2.3
      with:
        title: Update Monitoring mixins dashboards
        branch: update-mixins-dashboard
        base: alertmanager-dashboard
        body: |
          Update Monitoring mixins dashboards
