name: update-monitoring-mixins

on:
  schedule:
    - cron:  '0 11 1 * *'
  workflow_dispatch:

jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Sync dashboards 
      run: ./scripts/update-monitoring-mixin-dashboards.sh

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4.2.3
      with:
        title: "[AUTO] Update Monitoring mixins dashboards"
        branch: update-mixins-dashboard
        base: alertmanager-dashboard
        body: |
          Update Monitoring mixins dashboards

          Hint: reviewing dashboards is cumbersome, you'd better deploy them on a test cluster.
